### ISSUE TITLE
why this. can complete static field and method

### ISSUE THREAD

**Issue by wsdjeg** [artur-shaik/vim-javacomplete2#104]
maybe `this.` shuould equals `(new ClassName()).`
![2015-10-07 12-48-59](https://cloud.githubusercontent.com/assets/13142418/10329306/1934e388-6cf2-11e5-8801-c9a7e3467d3a.png)

**Comment by wsdjeg** [comment]
static variable should be qualified by type name

**Comment by wsdjeg** [comment]
thank you

**Comment by wsdjeg** [comment]
hi @artur-shaik 
it does not work for me 
![2015-11-02 21-59-58](https://cloud.githubusercontent.com/assets/13142418/10883588/ec79e5f2-81ad-11e5-81b9-6b44b3565110.png)
![2015-11-02 22-05-16](https://cloud.githubusercontent.com/assets/13142418/10883590/ece25d76-81ad-11e5-8981-ec4a7dd3647c.png)

**Comment by artur-shaik** [comment]
Does it give you completion variants with static? I don't see it on screenshots... And can you enable logs if so, please.

**Comment by wsdjeg** [comment]
yes it give the static fields
![2015-11-02 22-17-24](https://cloud.githubusercontent.com/assets/13142418/10883836/86e20362-81af-11e5-860d-60a50b48fbf2.png)
```
this.                                                        
F1. "this.|"                                                                    
DoGetClassInfo: this           
A0. this                          
DoGetClassInfo: Service                         
finish completion  0.154182s 
```

**Comment by artur-shaik** [comment]
My fault, fixed.

**Comment by wsdjeg** [comment]
hi @artur-shaik 
i find when the issue appear!
if a class extends an abstract class which has static fields,
then this.==> will complete static fileds;


![2015-11-02 23-14-25](https://cloud.githubusercontent.com/assets/13142418/10885278/7c786878-81b7-11e5-9949-fb297b3e1e51.png)
![2015-11-02 23-14-09](https://cloud.githubusercontent.com/assets/13142418/10885389/f7caa310-81b7-11e5-9765-f0fa6194ea74.png)

**Comment by wsdjeg** [comment]
it works well thank you
