### ISSUE TITLE
Variable and constant name completion/suggestion.

### ISSUE THREAD

**Issue by wsdjeg** [artur-shaik/vim-javacomplete2#105]
![2015-10-07 13-22-36](https://cloud.githubusercontent.com/assets/13142418/10329771/074aaecc-6cf8-11e5-8385-f72f0281f3be.png)
![2015-10-07 13-23-07](https://cloud.githubusercontent.com/assets/13142418/10329855/1365a4fe-6cf9-11e5-9577-37220a5af9ea.png)

**Comment by artur-shaik** [comment]
What you mean? What constant? Where it is defined?

**Comment by wsdjeg** [comment]
i will show you a small example

**Comment by wsdjeg** [comment]
i this these two pic will show the issue clear
![2015-11-02 22-22-18](https://cloud.githubusercontent.com/assets/13142418/10883963/58db8da2-81b0-11e5-91b6-230b5e88394f.png)
![2015-11-02 22-22-57](https://cloud.githubusercontent.com/assets/13142418/10883962/58daf6da-81b0-11e5-9a39-196eb4c823d2.png)

**Comment by artur-shaik** [comment]
You mean completion of variable names? For me, usually, it done by YCM. But of cause YCM can't complete variables or constants from extended classes. Is this an issue?

**Comment by wsdjeg** [comment]
yes it also same for me , i am using ycm,so if the variable is contains in the current file,i just need to type tab,but it can not complete variables from the extended classes

**Comment by wsdjeg** [comment]
some time ,i need to use `this.`

**Comment by wsdjeg** [comment]
YCM also can not complete the unfinished classes name from classpath,then we can type c-x c-o to show the completions,so i think we can add this variables's completion as same as classname

**Comment by artur-shaik** [comment]
Looks like #119 related to the same.
Will look, what we can do.

**Comment by wsdjeg** [comment]
sorry for my pool english,Fortunately you can Understand what i mean

**Comment by wsdjeg** [comment]
hi @artur-shaik I think the plugin can complete variable and constant,for example:
```java
class A {
    public String aaaaaaa;
}
class B extends A{
     aaaa|===> c-x c-o will get the variable
}
```
but if the variable or method begin with a Capital，it will not work,for example

```java
class A {
    public String AAAAAAAA;
}
class B extends A{
     AAAA|===> c-x c-o will get the variable
}
```

**Comment by wsdjeg** [comment]
here is my test result
![2015-11-21 14-17-06](https://cloud.githubusercontent.com/assets/13142418/11317092/5f28b41e-905b-11e5-96fa-a656065dcb80.png)

after change test3() to Test3()
![2015-11-21 14-20-19](https://cloud.githubusercontent.com/assets/13142418/11317093/5f3cb72a-905b-11e5-9cff-64e4efc2ba3c.png)
![2015-11-21 14-20-32](https://cloud.githubusercontent.com/assets/13142418/11317094/5f5710d4-905b-11e5-9786-44a6020af21a.png)

**Comment by artur-shaik** [comment]
Can you try again?

**Comment by wsdjeg** [comment]
great, it works ,let me show you two pics;
![2015-11-23 19-57-50](https://cloud.githubusercontent.com/assets/13142418/11336015/a60d64c0-921c-11e5-888e-094262f76242.png)
![2015-11-23 19-58-12](https://cloud.githubusercontent.com/assets/13142418/11336018/af2bc33a-921c-11e5-8ec6-4b467ab6ce2c.png)
but if the field or method is current class's,it does not work;
for example ,
```java
class A {
    public String AAAAAAAA;
    AAA|===>
}
```
maybe it can be complete by ycm's tag functions,if it is hart to implements,let's close this issue.

**Comment by wsdjeg** [comment]
![2015-11-23 20-08-34](https://cloud.githubusercontent.com/assets/13142418/11336177/0dc0a270-921e-11e5-8ac9-8fe5c6c47497.png)
![2015-11-23 20-08-51](https://cloud.githubusercontent.com/assets/13142418/11336178/0e0720f6-921e-11e5-86c7-b4bfaf5080b3.png)

**Comment by artur-shaik** [comment]
Seems like this completion doesn't have any sence, that's why internal vim java parser can't parse it.
And I don't see why we need complete field name out of method body.

**Comment by wsdjeg** [comment]
sorry it is my fault,i do not really want to complete out of mentod body,just see this pic
![2015-11-23 21-03-18](https://cloud.githubusercontent.com/assets/13142418/11337162/ba98d90c-9225-11e5-8c47-ce589425798b.png)

**Comment by wsdjeg** [comment]
i ment it works well in sub class but not work in parent class

**Comment by artur-shaik** [comment]
Yeah, you right. Here we have issue...

**Comment by artur-shaik** [comment]
@wsdjeg, Try again, please.

**Comment by wsdjeg** [comment]
great work  it works will !thank you very much
