### ISSUE TITLE
NeoVim migration

### ISSUE THREAD

**Issue by tepf** [artur-shaik/vim-javacomplete2#106]
You probably know but neovim is quite stable now and the plugin api has a [java wrapper](https://github.com/fdinoff/neovim-java-client), although WIP. As far as I know this would eliminate the need of VimL and maybe make development easier.

What are your thoughts on this?

**Comment by wsdjeg** [comment]
i think viml will not be eliminated ,neovim will not replace vim ,because it still is a text editor

**Comment by artur-shaik** [comment]
Looks like it's not official wrapper. Anyway now we need VimL java-parser because `javaparser` java library still cannot parse unfinished classes, that's why for now we depend on VimL parser.

**Comment by tepf** [comment]
> i think viml will not be eliminated ,neovim will not replace vim ,because it still is a text editor

I don't quite understand what you want to say. But I definitely think neovim is a replacement or successor. Maybe not in the sense that vim ceizes to exist, but in the sense that it is an improvement. Next version if you want.

> Looks like it's not official wrapper. Anyway now we need VimL `java-parser` because javaparser java library still cannot parse unfinished classes, that's why for now we depend on VimL parser.

Well.. it is mentioned in the [related projects](https://github.com/neovim/neovim/wiki/Related-projects) of neovim.

But why do you actually need to parse unfinished classes?

**Comment by artur-shaik** [comment]
@tepf because when completion is executed we should know, what class, variable, is related to. We should find variable declaration, classname import and etc... 

And by the way, plugin should work in neovim, too. May be when we change parser engine later, we can move in that direction.

**Comment by tepf** [comment]
So you mean the `java-parser` can't build an AST when there are unfinished lines like `LinkedLi`? Anyway doesn't matter. I just wanted to see if you know about the java wrapper.

Yes it does work in neovim. I just thought development would be easier that way..

**Comment by wsdjeg** [comment]
if the JC2's will change it's tools,i think JDT  is better choice,as the YCM's author says

**Comment by artur-shaik** [comment]
Anyway, thank you for mention. I'll keep it on mind. Close for now.
