### ISSUE TITLE
Static imports

### ISSUE THREAD

**Issue by artur-shaik** [artur-shaik/vim-javacomplete2#111]
```
import static org.junit.Assert.assertEquals;
```
still doesn't work.

**Comment by artur-shaik** [comment]
Made some support for static imports.

Tested this on `spark` framework.

```java
import static spark.Spark.*;

public class App 
{
    public static void main( String[] args )
    {
        get("/hello", (req, res) -> {
            req.| // has Request's completion
        });

        modelAndView().| // ModelAndView's completion
    }
}
```

Doesn't do static methods suggestion without class scope.

**Comment by mattn** [comment]
![](http://go-gyazo.appspot.com/16389d5d9d53c03f.png)

:+1:

**Comment by mattn** [comment]
Hmm, seems not work correctly.

**Comment by artur-shaik** [comment]
Hm, can you try on minimal example. And show logs for that.

**Comment by artur-shaik** [comment]
And, by the way, can you try the same without static import, like `Spark.get("/api" ....`.

**Comment by mattn** [comment]
![](http://go-gyazo.appspot.com/51e5b4e522ebfa2a.png)

```java
Spark.get("/foo", (req, res) -> {
  req.
});
```
This doesn't.

**Comment by mattn** [comment]
And more simple case.

```
─src
  └─main
      └─java
          ├─bar Bar.java
          └─foo Foo.java
```

**Foo.java**
```java
package foo;

import static bar.Bar.*;

public class Foo {
	public static void main(String[] args) {
		// HERE
	}
}
```

**Bar.java**
```java
package bar;

public class Bar {
	public final static void get() {
		
	}
}
```
This also doesn't.

**Comment by artur-shaik** [comment]
Do `Collections` also not work?

**Comment by mattn** [comment]
Seems to be completing members of spark.* instead of Collections.

![](http://go-gyazo.appspot.com/9df201bd95b3fa54.png)

**Comment by artur-shaik** [comment]
Yeah, there is some mess in completion. Should look more, but strange that you have not completions for Request.

**Comment by mattn** [comment]
If you want to reproduce, you can get my project from https://github.com/mattn/spark-sandbox

**Comment by artur-shaik** [comment]
Ok, thanks for that...

**Comment by artur-shaik** [comment]
Strange, for me, it just worked...

![2015-11-02-150132_568x320_scrot](https://cloud.githubusercontent.com/assets/4862907/10877704/af631336-8172-11e5-841d-b4289d060332.png)

**Comment by mattn** [comment]
Ah, sorry. I forgot `mvn compile`. Works fine.

**Comment by artur-shaik** [comment]
Last commit should fix unrelated completions. Like `Collection` above...

**Comment by mattn** [comment]
When no-candidates, seems to be unrelated completion.
![](http://go-gyazo.appspot.com/14c56543ea78f602.png)

**Comment by artur-shaik** [comment]
Yeah, this is old issue. It shows package name of class. Will fix it
later.

**Comment by wsdjeg** [comment]
import clollection will show the methods

**Comment by wsdjeg** [comment]
![2015-11-02 20-07-12](https://cloud.githubusercontent.com/assets/13142418/10881461/c221f386-819d-11e5-9da4-f53fcb989a5e.png)
great work

**Comment by wsdjeg** [comment]
can not import inner class ,but when use import static it will show me the inner class ,but i think static import should not contains inner class
![2015-11-03 21-52-55](https://cloud.githubusercontent.com/assets/13142418/10909637/82863c72-8275-11e5-8231-4312a38c54e8.png)

**Comment by wsdjeg** [comment]
![2015-11-03 21-52-33](https://cloud.githubusercontent.com/assets/13142418/10910081/40d9b382-8278-11e5-8a23-6f9b44cfbf48.png)

**Comment by wsdjeg** [comment]
it is my fault there is no wrong `import static android.view.View.OnClickListener;` has no errors, we just can delete the `static` from this statement
![2015-11-03 22-33-10](https://cloud.githubusercontent.com/assets/13142418/10910542/e440833c-827a-11e5-9fe3-b644699cd0ae.png)

**Comment by mattn** [comment]
Hmm, it seems latest can't complete spark/get candidates.

**Comment by mattn** [comment]
Also simple jsp doesn't 
![](http://go-gyazo.appspot.com/54985b5483493742.png)

**Comment by artur-shaik** [comment]
Strange, work for me in jsp. Didn't checked `spark` yet.

**Comment by mattn** [comment]
![](http://go-gyazo.appspot.com/50e686c281a67d9c.png)
but works with full namespace.

**Comment by wsdjeg** [comment]
strang it also works well for me 
![2015-11-12 20-40-48](https://cloud.githubusercontent.com/assets/13142418/11118560/bcdc0fe6-897d-11e5-8fdc-bc6a391d54d1.png)

**Comment by artur-shaik** [comment]
Seems like you're right about `spark` and etc...

**Comment by mattn** [comment]
@artur-shaik thanks.
