### ISSUE TITLE
Can't add project files to completion engine

### ISSUE THREAD

**Issue by tepf** [artur-shaik/vim-javacomplete2#115]
I would like to have my files to show up in the completion as well. What needs to be in the `.vimrc` to have `.class` files in the current folder (and subfolders) imported by default? Or for example the `build/classes` you generally have in Gradle.

I know you can use `g:JavaComplete_LibsPath` but it doesn't work for me or I just don't know how to use it.

**Comment by mattn** [comment]
currently, javacomplete2 handle root directory with maven pom.xml.

**Comment by tepf** [comment]
How did you set vim up to be able to quickly edit java files? I don't want to create a pom.xml everytime I edit a `.java`. I only use this plugin for little projects or single file editing.

**Comment by mattn** [comment]
If we can parse gradle files, it will be possible.

**Comment by mattn** [comment]
or if gradle can generate CLASSPATH.

**Comment by tepf** [comment]
So it is not possible to just create a folder with 2 `.java` files and have them connected? I absolutely need maven to have completion for more than 1 file?

**Comment by mattn** [comment]
If you don't use external library, you should be possible to complete. AFAIK.

**Comment by mattn** [comment]
At the first, please show me your directory structure.

**Comment by tepf** [comment]
It depends.. sometimes just `.java` and `.class` all in one folder if it's a very small project. And other times it's the common maven/gradle structure

    src/
    |-  main/
    |   |-  Main.java
    |   |-  OtherClass.java
    |-  test/
    build/
    |-  classes/
    |   |-  main/
    |   |   |-  Main.class
    |   |   |-  OtherClass.class
    |   |-  test/

**Comment by DonnieWest** [comment]
Obviously, for generic java projects without a build tool, you'll need to supply the jars you want to complete with. You might try:


1. Setting the g:JavaComplete_LibsPath to what you want. You do this by running 

```let g:JavaComplete_LibsPath = "/path/to/jar:/path/to/other/jar"```

To get this to work, you might have to run 

```
JCcacheClear
JCserverTerminate
let g:JavaComplete_LibsPath = "/path/to/jars"
JCserverStart
```

To get Javacomplete to recognize the new classpaths.

2. Setting the $CLASSPATH variable to the locations of the jars you want before starting Javacomplete
3. Placing the jars in the libs/ directory (I think?)

If you're looking for something that supports Gradle, check out either my fork of Vim Grand [that supports generic Gradle projects ](https://github.com/DonnieWest/vim-grand/tree/develop) or my [my Neovim plugin](https://github.com/DonnieWest/VimStudio) that does it a bit more elegantly.

**Comment by wsdjeg** [comment]
@DonnieWest will the plugin auto generate R.java

**Comment by tepf** [comment]
@DonnieWest I will check your VimStudio plugin. 

Does this mean you have to generate a .jar just to have autocompletion? It's not enough to point javacomplete where the `.class` are?

**Comment by DonnieWest** [comment]
@wsdjeg Gradle generates the R.java automatically, which VimStudio relies on. 

@tepf I don't know about how Javacomplete handles class files. I would try generating a jar file and see what happens?

**Comment by wsdjeg** [comment]
sorry i am using maven to create android app

**Comment by wsdjeg** [comment]
@mattn
hi mattn now i use this plugin to complete android app.but can not complete many class and method and can not import my R.java
here is my android code https://github.com/wsdjeg/learnandroidthehardway

i use maven to genarate R.java. it will created by maven android plugin into target/generate resource/R.java also will be compiled into target/classes/R.class

**Comment by mattn** [comment]
Could you please make more small example to reproduce? Android SDK contains 1.1GB files.

**Comment by wsdjeg** [comment]
ok  i will show it later

**Comment by wsdjeg** [comment]
hi @mattn 
i have only create one class ,and alse i have add the android dependency,but has no method names onCreate(
![2015-10-20 19-57-18](https://cloud.githubusercontent.com/assets/13142418/10606407/32973b14-7765-11e5-87d1-614b069f633c.png)
![2015-10-20 19-59-53](https://cloud.githubusercontent.com/assets/13142418/10606408/329d521a-7765-11e5-80f5-881fe2c29082.png)

**Comment by wsdjeg** [comment]
i have fixed it by change it to 
![2015-10-20 20-07-20](https://cloud.githubusercontent.com/assets/13142418/10606542/30ff4fe8-7766-11e5-8470-3ceebce40b81.png)
![2015-10-20 20-07-40](https://cloud.githubusercontent.com/assets/13142418/10606557/3d9e8d36-7766-11e5-9bda-2ee2d8472ab2.png)

**Comment by artur-shaik** [comment]
Any progress with this issue? Any suggestions?

**Comment by liujoey** [comment]
for gradle, if you include `eclipse plugin` in your build.gradle file, and then run `gradle eclipse` then it will generate `.project` and `.classpath` file for root project and all sub projects. These files can then be imported into Eclipse. I think javacomplete2 should at least read `.classpath` file, because this file includes all the jar files your project depends on. It's better than a `pom.xml` because in `.classpath` file all the underlining dependencies are already solved, so if your project depends on jar A, and jar A itself depends on jar B, then jar B will also been included in `.classpath` file.

**Comment by artur-shaik** [comment]
> I think javacomplete2 should at least read .classpath file

@mattn haven't you done that?

**Comment by wsdjeg** [comment]
i have test .classpath it works well

**Comment by mattn** [comment]
yes, i did. but not make sure it works on latest.

**Comment by artur-shaik** [comment]
@liujoey can you please a manual, how to add eclipse plugin to gradle? I will add it to README. Or you can make PR.

**Comment by wsdjeg** [comment]
hi @artur-shaik @tepf  google 's android studio,is really different from eclipse,lt works based on gradle.the config file of gradle is named `build.gradle`. gradle works like maven.the `build.gradle` contains the info of classpath outputdirectory and so on. and i think @DonnieWest 's vimstudio is helpful.

**Comment by wsdjeg** [comment]
here is my config ,whit the help of [syntastic](https://github.com/scrooloose/syntastic),i can auto compile and auto complete  the java code.here is part of my confic ,hope this will help you.

![2015-11-06 19-28-57](https://cloud.githubusercontent.com/assets/13142418/10996064/a6ff2db8-84bc-11e5-8fd4-2efaab9dbc2b.png)
in the above pic, i do not add lib directory.
now the JavaComplete2 does not support gradle,if you really want to use this , you can add maven support for you project,here is an example which i just giving a PR.
https://github.com/liaohuqiu/android-RavenServer/blob/master/pom.xml

**Comment by liujoey** [comment]
@artur-shaik 
Gradle uses build.gradle file to manage builds. Here are first few lines in my build.gradle file

```groovy
allprojects {
    apply plugin: 'eclipse'
}
```

And then in command line, run:
```
gradle eclipse
```

This command will download all dependencies and generate `.classpath` files.

**Comment by wsdjeg** [comment]
maybe it is better to use maven,because if you use vim to finished you java or andorid,you need maven-android-plugin ,and  the vim checker syntastic is using pom.xml,also the complete plugin is using pom.xml

**Comment by artur-shaik** [comment]
@liujoey, ok, thank you. I've updated readme. @tepf can you try this setup?

**Comment by mattn** [comment]
Could you please try below's vim script on root directory of the project which have build.gradle?

```vim
function! s:detectClasspath()
  if !filereadable('build.gradle')
    echohl ErrorMsg | echo "build.gradle not exists" | echohl None
    return
  endif
  try
    let f = tempname()
    call writefile(readfile('build.gradle') + ["println 'CLASSPATH:' + sourceSets['main']['compileClasspath'].collect { n -> n.absolutePath }.join(File.pathSeparator)"], f)
    let ret = system('gradle -q -b ' . shellescape(f))
    if v:shell_error
      return
    endif
	echo filter(split(ret, "\n"), 'v:val =~ "^CLASSPATH:"')[0][10:]
  finally
    call delete(f)
  endtry
endfunction

call s:detectClasspath()
```

**Comment by tepf** [comment]
@mattn I tried your script it recognizes the build.gradle in the root dir.
@liujoey It does indeed create a classpath file, but I get no completion from other classes. Are there any settings I have to do in `.vimrc`?

**Comment by mattn** [comment]
@tepf if you are okay, I'll make pull-request to recognize CLASSPATH on vim-javacomplete2.

**Comment by tepf** [comment]
@mattn That would be great if Vim could recognize it and add them to the completion engine!

**Comment by wsdjeg** [comment]
if you the plugin can not load you config file,you can set you classpath manually.
add you jar to `g:JavaComplete_LibsPath`
add you src dir to `g:JavaComplete_SourcesPath`
also you should add outputdirectory to `g:JavaComplete_LibsPath`
add ./gen to g:JavaComplete_SourcesPath(./gen contains the R.java)

**Comment by liujoey** [comment]
@wsdjeg it only works for small or experimental projects, imaging a java project uses ~100 of 3rd party packages and ~10 of sub-projects. Definitely you want to go the CLASSPATH route.

@mattn That will be great. I'm not sure how the plugin uses build.gradle file, because it doesn't tell you the absolute path of the jar file, it doesn't tell you the transitive dependencies, only after gradle generates .classpath file, it should have all jar files downloaded and been put in user's home folder, that's why I recommend the plugin should directly use the .classpath file.

**Comment by mattn** [comment]
#127 Could you try latest commit?

**Comment by liujoey** [comment]
@mattn now it hangs my neovim. Need to kill the neovim process from activity monitor.

Running Mac OS X El Capitan
Neovim 0.1

**Comment by mattn** [comment]
```
:call system("gradle")
```
also hang?

**Comment by liujoey** [comment]
call system("gradle") doesn't hang. As soon as I trigger the completion with `C-X C-O`, it hangs.

**Comment by mattn** [comment]
at the first time, javacomplete2 call gradle command to detect CLASSPATH. But it should be cached.

**Comment by liujoey** [comment]
in my case, I've already ran `gradle eclipse` command to generate the `.classpath` file. I need this file for eclipse anyway. And my project is pretty large, ran `gradle` command could spend few minutes to do the full build. So I don't recommend you to invoke the gradle command in the plugin.

**Comment by DonnieWest** [comment]
@mattn I agree with @liujoey Is there a way we can put this behind a feature flag of some sort?

This is conflicting with my existing plugins and causes my vim to freeze when opening a project. Unfortunately, it also ignores the existence of the Gradle wrapper that is commonly used in the projects I deal with on a daily basis (a local gradle binary instead of the system gradle)

**Comment by artur-shaik** [comment]
Is there any big open source java projects using `gradle`, that would be nice for testing?

**Comment by DonnieWest** [comment]
I can't immediately think of anything non-android.

https://github.com/nickbutcher/plaid

This project is a pretty new one though released by a member of the Android team at Google. I'll keep my eyes out for anything non Androiid

**Comment by DonnieWest** [comment]
Netflix has a few - https://github.com/Netflix/Hystrix

**Comment by wsdjeg** [comment]
hi @DonnieWest @artur-shaik now the neovim has a lot of bugs,and many plugins I needed can not works well in neovim,so i can not use vimstudio ,also i think JavaComplete2 should has itself analyzer for classpath insteaded of based on any other plugin.
