### ISSUE TITLE
android complete error!

### ISSUE THREAD

**Issue by wsdjeg** [artur-shaik/vim-javacomplete2#116]
i use maven create my android app;
here is my dir tree
```
-src/main/java/com/wsdjeg/MainActivity.java
-res/
- AndroidManifest.xml
-pom.xml
```

the mvn android plugin will crate R.java into target/generated-sources/r/com/wsdjeg/R.java

and all the java file will be compile into target/classes

i can not import R.java,it only can import android.R,which is not what i want:

when i add import com.wsdjeg.R; into my file or do not add syntastic will not show error,also build app success;

but when i try to complete the Internal class in R.java 

the JC2 show me like this 
![2015-10-20 22-46-38](https://cloud.githubusercontent.com/assets/13142418/10611014/d88d9092-777c-11e5-9758-7884456646ad.png)

when i want to complete method of internal class
![2015-10-20 22-38-17](https://cloud.githubusercontent.com/assets/13142418/10611066/0bffb842-777d-11e5-9e40-57d54b63f0ad.png)

**Comment by wsdjeg** [comment]
@mattn 
i have fix the import R.java by add this to my vimrc
```vim
if filereadable("AndroidManifest.xml")
      set tags+=/home/wsdjeg/others/android-sources-6.0r1/tags
      let g:JavaComplete_SourcesPath = "target/generated-sources/r"
endif
```

**Comment by wsdjeg** [comment]
#45

**Comment by mattn** [comment]
Could you please show me AondroidManifest.xml and your directory structure in target/generated-sources.

**Comment by wsdjeg** [comment]
https://github.com/wsdjeg/learnandroidthehardway/blob/master/AndroidManifest.xml

**Comment by wsdjeg** [comment]
![2015-10-21 23-46-27](https://cloud.githubusercontent.com/assets/13142418/10641928/fc8a0094-784d-11e5-8004-518b4fe4164d.png)
![2015-10-21 23-46-31](https://cloud.githubusercontent.com/assets/13142418/10641927/fc86c06e-784d-11e5-8bec-31de3bd67fb8.png)

**Comment by wsdjeg** [comment]
in ide ,the as or eclipse will auto generate R.java in gen/

but i use maven, i have no gen dir,the mvn android:generate-resours command will auto create R.java into target

**Comment by mattn** [comment]
It sesms android-maven-plugin generate R.java into target/generated-resource. But plugin can't know whether the plugin is used, where the file is generated at. So I'm thinking your settings:
```vim
if filereadable("AndroidManifest.xml")
      set tags+=/home/wsdjeg/others/android-sources-6.0r1/tags
      let g:JavaComplete_SourcesPath = "target/generated-sources/r"
endif
```

This is best solution. And I'm thinking this should be written in README or doc.

**Comment by wsdjeg** [comment]
yes ,i think so!
now the remaining question is complete the methed and field  of inner class ,and import inner class

**Comment by mattn** [comment]
@artur-shaik please add this FAQ into README or docs?

**Comment by artur-shaik** [comment]
Can you, please, make a PR? Currently, I have not enough time.

**Comment by wsdjeg** [comment]
ok i will make

**Comment by wsdjeg** [comment]
@mattn @artur-shaik 
something error with this config
```vim
let g:JavaComplete_SourcesPath = "target/generated-sources/r"
```
it will miss Clsss import in src

**Comment by wsdjeg** [comment]
i think "target/generated-sources/r" should be add to g:JavaComplete_SourcesPath instead of 
```vim
let g:JavaComplete_SourcesPath = "target/generated-sources/r"
```

**Comment by wsdjeg** [comment]
@artur-shaik  i have fixed it .and create an PR
