### ISSUE TITLE
unnecessary import and miss completetion from inner class and the class like android.app.Activity

### ISSUE THREAD

**Issue by wsdjeg** [artur-shaik/vim-javacomplete2#120]
hi artur-shaik, now i am use this plugin for my android code completion,as you know,android project contains a lot of inner class ,now i can not import it and can not complete the method field of a inner class, my latest PR make the plugin support import user's R.java.i have test for a long time ,it works well.
before use, we just meed to use this command to generate R.java `mvn android:generate-sources`

**Comment by artur-shaik** [comment]
Honestly, I'm more enterprise developer, so I don't really know what
contains android project. So now I can only finally implement static
imports. And we can see what we will have.

**Comment by wsdjeg** [comment]
thank you very much

**Comment by wsdjeg** [comment]
it is really strange,
```java
import android.app.Activity;
class Foo extends Activity{
void test(){
super.|
}
}
```
after dot i can only can complet 95%method,for example i cannot conplet onDestroy

**Comment by DonnieWest** [comment]
@wsdjeg Android doesn't implement onDestroy as an inner class - it's a protected method on the Activity class. I'm not currently sure why it's giving this behavior, but your best bet for getting this fixed is to create a minimal example project that we can see that doesn't require the entire Android SDK

**Comment by wsdjeg** [comment]
you can have a look at my test branch https://github.com/wsdjeg/learnandroidthehardway/tree/test

which centains only one activiy ,and the pom.xml is simple ,just add the adnroid.jar into the javacompletelib.

or you can add g:JavaComplete_LibsPath='/path/to/android.jar' into vimrc

**Comment by DonnieWest** [comment]
@wsdjeg can you replicate this same issue outside of Android? Maybe this happens when there is a class with a *ton* of methods like the Activity class?

If you can narrow this down it'll help a lot with getting it fixed.

**Comment by wsdjeg** [comment]
i have never got the same issues befre,when i use this plugin for javaee project, some class also contains  a ton of methods,but will not miss any one.i have test it by create an BaseActivity extendes Activity, and override onDestory,
then the another class extends BaseActivity will not miss super.onDestory.

maybe these test will help to find the error:

```java
import android.app.Activity;
class Foo extends Activity{
Activity a = new Activity();
a.|==>
this.|===>

}
```

**Comment by wsdjeg** [comment]
maybe it is also related issue

**Comment by wsdjeg** [comment]
```java
import android.app.Activity;
class Foo extends Activity{
Activity a = new Activity();
a.|==>
this.|===>

}
```
i have test all of this ,has no ondestroy, here is my log

![2015-10-27 19-17-48](https://cloud.githubusercontent.com/assets/13142418/10756503/71cfd47e-7cdf-11e5-8696-4a1a7b6938f6.png)

**Comment by wsdjeg** [comment]
![2015-10-27 21-17-19](https://cloud.githubusercontent.com/assets/13142418/10759062/32aae322-7cf0-11e5-90fc-75a08b22a5e6.png)
here is a log for complete after an inner class

**Comment by wsdjeg** [comment]
i hava test create an empty dir;
then use this command:
```
vim test.java
let g:JavaComplete_LibsPath="/home/wsdjeg/.m2/repository/android/android/6.0_r1/android-6.0_r1.jar"
```
![2015-10-28 16-10-21](https://cloud.githubusercontent.com/assets/13142418/10782857/aa200916-7d8e-11e5-8339-88ca73e636c1.png)
still has no ondestory

**Comment by wsdjeg** [comment]
JCimprotminssing give me unecessary Class.
![2015-10-28 20-02-23](https://cloud.githubusercontent.com/assets/13142418/10787902/f2875d7e-7dae-11e5-913d-771385968e19.png)
in this picture,i have import android.app.AlertDialog
so there is no need import the inner class ,(now the plugin can not import innerclass)
AlertDialog.Builder dialogBuilder = new AlertDialog.Builder(context);
but when use this command JCimportaddming,will show me these,when i type esc  the unnecessary class also be added to my file!

I found a good advantage of JCimportaddmings ,will not import the class with the same package as the current class!it's very good

**Comment by artur-shaik** [comment]
Ok, I see issue for unnecessary import. Are there any more issues?

**Comment by wsdjeg** [comment]
when the cursor is on the package name 
imporm com. | wsdjeg.Example;
                       ^
then i type <F4> (JCimpportAdd  or JCimportAddI)
will show me many unnecessary packageName;
![2015-10-09 20-52-35](https://cloud.githubusercontent.com/assets/13142418/10883796/4d6ece6c-81af-11e5-9216-bf107535bede.png)
![2015-10-09 20-52-41](https://cloud.githubusercontent.com/assets/13142418/10883797/4d8182dc-81af-11e5-8d56-b0018b20980c.png)

**Comment by artur-shaik** [comment]
For this there is issue already.

**Comment by wsdjeg** [comment]
i see , thank you ,i will browse all the issues !

**Comment by wsdjeg** [comment]
i find there are more than three issues here,should we split them

**Comment by artur-shaik** [comment]
Yeah, of cause...
