### ISSUE TITLE
can not complete static method and fileds of a static nested class(help wanted)

### ISSUE THREAD

**Issue by wsdjeg** [artur-shaik/vim-javacomplete2#123]
i hope thes func  :
1.  complete method and fileds of inner class
2.  import inner class by <Plug>(JavaComplete-Imports-Add) and <Plug>(JavaComplete-Imports-AddMissing)
> now the plugin can complete class name and the methods or fileds in the import statement,but can not use command
maybe just let the inner class complete as same as generally class

**Comment by artur-shaik** [comment]
> 1. complete method and fileds of inner class
Doesn't it work?
> 2. import inner class by (JavaComplete-Imports-Add) and (JavaComplete-Imports-AddMissing)
This going to be hard, because we should scan and parse every class, to know where to search inner classes. In addition, this is bad approach to use static imports, more readable and better to use it with parent class name.

**Comment by wsdjeg** [comment]
i think meybe static import is not for inner class,even if `import static android.view.View.OnClickListener`will not show error,as inner class will not be embellished by static,and `import android.view.View.OnClickListener`is most used in the android app src！import static is most used by import a static method of parent class.

and i think maybe there is no need to scan every Class .because the inner class has beeb compiled into different file

**Comment by wsdjeg** [comment]
maybe it is better let @mattn discuss together

**Comment by wsdjeg** [comment]
it is my fault, i will try with different case in IDE.
```java
package com.wsdjeg.test;
public class TestJC {
    public static class TestJC2{
       public static void testM(){                                                                                                              

       }   
    }   
}
```

**Comment by wsdjeg** [comment]
here is my test class 
```java
package com.wsdjeg.testjc;

public class OuterClass {
	public  static class NestedStaticClass{
		public void printMessage(){
			
		}
		public static void printMessage2(){
			
		}
	}
	public class InnerClass{
		public void printMessage(){
			
		}
	}
	public static interface Iface{} 
	public  interface Iface2{}
	public abstract class Aclass{}
	public static abstract class Aclass2{}
}
```

and the result is here 
![2015-11-05 20 53 52](https://cloud.githubusercontent.com/assets/13142418/10968871/67027386-83ff-11e5-90fd-5722e50973fd.png)

**Comment by wsdjeg** [comment]
hi @artur-shaik @mattn  i have finished my testing,here is the status of IDE.
as the pic above ,alfter the `import static` statement we can use `alt + /` to complete these :
1. static nested class (not non-static nested class which is called inner class), both static and non-static nested interfate,static abstract nested class (not non-static abstract nested class)
2. static method or fields of both outer class and static nested class

in the eclipse IDE <C-S-o> is the hotkey for autoimport,it just can import outer class,interface and static nested class,can not import non-static nested class which is called inner class,also it can not **autoimport** static method or fields.

**Comment by wsdjeg** [comment]
and here is the result of Javacomplete2.
![2015-11-05 21-21-21](https://cloud.githubusercontent.com/assets/13142418/10969474/8303efd4-8403-11e5-8d1e-8f88cfe98fe1.png)
in the first pic `com.wsdjeg.test.OuterClass.InnerClass` and `com.wsdjeg.test.OuterClass.Aclass` should be delete.
![2015-11-05 21-23-38](https://cloud.githubusercontent.com/assets/13142418/10969480/8d7046f2-8403-11e5-9339-0321b42ae07c.png)
in this pic can not complete the static method of static nested class

**Comment by DonnieWest** [comment]
@artur-shaik do you know how one might go about fixing this? I'd like to help if at all possible

After the latest changes, we can complete the R.java file but it's filled with static inner classes that don't show up under completion.

**Comment by wsdjeg** [comment]
ohahaha,same issue ,android project contans a ton of inner class and static nestest class

**Comment by wsdjeg** [comment]
@DonnieWest
here is diff between inner class and static nested class
http://www.geeksforgeeks.org/static-class-in-java/

**Comment by artur-shaik** [comment]
I think it can be easily done for compiled classes, but for sources it requires more effort.
Do inner source classes require for this?

**Comment by wsdjeg** [comment]
I think we can change the title to Intelligent Output of completion !i have taken a long time test with eclipse,i think i can finish the detail!but it need time

**Comment by wsdjeg** [comment]
I WILL finish it tonight

**Comment by DonnieWest** [comment]
@artur-shaik the files I'm having trouble with are accessible as compiled or source. Anything would be a huge help :-)

**Comment by wsdjeg** [comment]
R.java will be autocompiled when generated

**Comment by artur-shaik** [comment]
Ok, will work this days on compiled nested classes.

**Comment by DonnieWest** [comment]
Thanks @artur-shaik

**Comment by artur-shaik** [comment]
Ok, have made some implementation. Can you test it.

**Comment by wsdjeg** [comment]
thank you @artur-shaik ,
now i have test the latest version,it can complete some method,but still very strange,let's open an new issue discuss about the completion ,as you know , the feature of javacomplete2 becomes more complex ,I think a discussion of basic framework is needed before add some function!

**Comment by DonnieWest** [comment]
@artur-shaik I'll check it out tonight :-)

**Comment by wsdjeg** [comment]
fied
#144
