### ISSUE TITLE
miss completetion from class like android.app.Activity

### ISSUE THREAD

**Issue by wsdjeg** [artur-shaik/vim-javacomplete2#124]
i hava test create an empty dir;
then use this command:
```
vim test.java
let g:JavaComplete_LibsPath="/home/wsdjeg/.m2/repository/android/android/6.0_r1/android-6.0_r1.jar"
```
![2015-10-28 16-10-21](https://cloud.githubusercontent.com/assets/13142418/10782857/aa200916-7d8e-11e5-8339-88ca73e636c1.png)
still has no ondestory

**Comment by mattn** [comment]
maybe, onDestroy is protected member.

http://developer.android.com/reference/android/app/Activity.html#onDestroy()

but to override onDestroy should be appeard in candidates.

**Comment by wsdjeg** [comment]
my class extends Activity,even if it is protected ,i should be able to use this.onDestroy(),as you say,if i override the method,i also can use it

**Comment by wsdjeg** [comment]
if i override the method,it will appeard in candidates.

**Comment by wsdjeg** [comment]
@mattn
greate maybe it really due to `protected`

**Comment by wsdjeg** [comment]
@mattn
greate maybe it really due to `protected`

**Comment by wsdjeg** [comment]
https://github.com/wsdjeg/platform_frameworks_base/blob/master/core/java/android/app/Activity.java

**Comment by artur-shaik** [comment]
Could you give link for `android-6.0_r1.jar`, please?

**Comment by wsdjeg** [comment]
i will mail it to you , tonight,
i am using https://github.com/simpligility/maven-android-sdk-deployer  this project help me install my sdk into ~/.m2

**Comment by wsdjeg** [comment]
sorry i have try with other protected method ,it works well

**Comment by wsdjeg** [comment]
hi @artur-shaik @mattn  let me give you an example!
the TestJC is packaged in com.wsdjeg.test,and the TestJC2 is packaged in com.wsdjeg.math;
```java
package com.wsdjeg.test;
public class TestJC {
    protected void testM() {
    }   
} 
```
```java
package com.wsdjeg.math;
import com.wsdjeg.test.TestJC;
public class TestJC2 {
    private void method() {
         TestJC d = new TestJC();
          d.==>//here only show me the method of Object,i think there is no error!
    }   
} 
```
```java
package com.wsdjeg.math;
import com.wsdjeg.test.TestJC;
public class TestJC2 extends TestJC2{
    private void method() {
          this.===>//here show me both testM() and the method of Object, alse has no error,so i think it is not diu to protected!
    }   
} 
```

**Comment by wsdjeg** [comment]
here is the jar file 
http://share.weiyun.com/bb8d08272ca9423b028abd74f507b250
if you can not download ,please have a look at my repo,
https://github.com/wsdjeg/JavaTutorial
named (android-6.0_r1.jar)

**Comment by wsdjeg** [comment]
hi @mattn  @artur-shaik 
i have find where the error is !!!

when the class is in the jar files ,will miss it's protected method 
here is my test
i create an new java porject 
only one Hello.java which contains an protected method testM()

and use mvn install to install it into my ~/.m2

then in another project use the dependency of this jar

the new class  TestHello
```
public class TestHello extends Hello {
    this. ===> only method of Object
}

**Comment by artur-shaik** [comment]
Know that, can confirm. Patch almost ready.

**Comment by wsdjeg** [comment]
Glad to hear it ,thank you very much

**Comment by artur-shaik** [comment]
Javavi should be recompiled.

**Comment by wsdjeg** [comment]
greate,it works very well,thank you !
