### ISSUE TITLE
no such group or event: TextChangedI

### ISSUE THREAD

**Issue by lrusnac** [artur-shaik/vim-javacomplete2#125]
Hi, I got these errors every time I open a java file.

I'm on mac, vim version 7.3, jdk 1.8.0_45.

I cloned the repository in my bundle folder and added `autocmd FileType java set omnifunc=javacomplete#Complete` to my .vimrc

![schermata 2015-11-04 alle 12 51 15](https://cloud.githubusercontent.com/assets/1005173/10937389/cf0870f6-82f2-11e5-90b1-2b9dd893f3c4.png)

**Comment by artur-shaik** [comment]
Please, can you try with last commit.

**Comment by lrusnac** [comment]
great, it works, thanks
