### ISSUE TITLE
make "mvn dependency:build-classpath" work under mingw/msys.

### ISSUE THREAD

**Issue by richox** [artur-shaik/vim-javacomplete2#126]
msys uses unix-like path, for example "/C/mydir/aaa.jar" but maven produces windows path, that makes javacomplete2 not work with maven under msys.
here is my patch:
diff --git a/autoload/javacomplete.vim b/autoload/javacomplete.vim
index 75d8470..eaeae3e 100644
--- a/autoload/javacomplete.vim
+++ b/autoload/javacomplete.vim
@@ -160,7 +160,16 @@ function! s:GenerateClassPath(path, pom) abort
   let lines = split(system('mvn --file ' . a:pom . ' dependency:build-classpath -DincludeScope=test'), "\n")
   for i in range(len(lines))
     if lines[i] =~ 'Dependencies classpath:'
-      let cp = lines[i+1] . g:PATH_SEP . join([fnamemodify(a:pom, ':h'), 'target', 'classes'], g:FILE_SEP)
+      let cpline = lines[i+1]
+      if has('unix') && tolower(system('uname')) =~ 'mingw'
+        " convert windows path to unix-like path under mingw/msys
+        let items = split(cpline, ';')
+        let items = map(items, 'substitute(v:val, "\\", "/", "g")')
+        let items = map(items, 'substitute(v:val, "^\\([A-Z]\\):", "\\=submatch(1)", "")')
+        let items = map(items, 'substitute(v:val, "^", "/", "")')
+        let cpline = join(items, g:PATH_SEP)
+      endif
+      let cp = cpline . g:PATH_SEP . join([fnamemodify(a:pom, ':h'), 'target', 'classes'], g:FILE_SEP)
       call writefile([cp], a:path)
       return cp
     endif

**Comment by richox** [comment]
markdown sucks:(, here is my patch:

    diff --git a/autoload/javacomplete.vim b/autoload/javacomplete.vim
    index 75d8470..eaeae3e 100644
    --- a/autoload/javacomplete.vim
    +++ b/autoload/javacomplete.vim
    @@ -160,7 +160,16 @@ function! s:GenerateClassPath(path, pom) abort
       let lines = split(system('mvn --file ' . a:pom . ' dependency:build-classpath -DincludeScope=test'), "\n")
       for i in range(len(lines))
         if lines[i] =~ 'Dependencies classpath:'
    -      let cp = lines[i+1] . g:PATH_SEP . join([fnamemodify(a:pom, ':h'), 'target', 'classes'], g:FILE_SEP)
    +      let cpline = lines[i+1]
    +      if has('unix') && tolower(system('uname')) =~ 'mingw'
    +        " convert windows path to unix-like path under mingw/msys
    +        let items = split(cpline, ';')
    +        let items = map(items, 'substitute(v:val, "\\", "/", "g")')
    +        let items = map(items, 'substitute(v:val, "^\\([A-Z]\\):", "\\=submatch(1)", "")')
    +        let items = map(items, 'substitute(v:val, "^", "/", "")')
    +        let cpline = join(items, g:PATH_SEP)
    +      endif
    +      let cp = cpline . g:PATH_SEP . join([fnamemodify(a:pom, ':h'), 'target', 'classes'], g:FILE_SEP)
           call writefile([cp], a:path)
           return cp
         endif

**Comment by mattn** [comment]
msys2 can handle `c:/path/to`. it is enough to convert backslash to slash i think.

**Comment by richox** [comment]
msys2 can handle c:/path/to. it is enough to convert backslash to slash i think.

it's not enough, javacomplete2 uses ":" as path separator under msys. so we need to convert "C:/" to "/C/".

**Comment by mattn** [comment]
do you mean $PATH? afaik no need to do for CLASSPATH.

On 11/8/15, Zhang Li <notifications@github.com> wrote:
>     msys2 can handle c:/path/to. it is enough to convert backslash to slash
> i think.
>
> it's not enough, javacomplete2 uses ":" as path separator under msys. so we
> need to convert "C:/" to "/C/".
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/artur-shaik/vim-javacomplete2/issues/126#issuecomment-154776787


-- 
- Yasuhiro Matsumoto

**Comment by wsdjeg** [comment]
any update about this issue? @richox

**Comment by artur-shaik** [comment]
@richox can you test this again? There was plenty of modifications in this area.
