### ISSUE TITLE
how do you start complet after @Override

### ISSUE THREAD

**Issue by wsdjeg** [artur-shaik/vim-javacomplete2#128]
i find you have add this map to you vimrc
let g:UltiSnipsExpandTrigger="\<C-x>"
 let g:UltiSnipsJumpForwardTrigger="\<c-b>"
 let g:UltiSnipsJumpBackwardTrigger="\<c-z>"

so after @Override how do you start omnifunc

**Comment by artur-shaik** [comment]
There is nothing special about after `@Override` completion, just `<C-x><C-o>` after `@Override` keyword, or `<C-Space>` default completion trigger of YCM. UltiSnips configs I have set long time ago.

**Comment by wsdjeg** [comment]
oh  i know i will chang my Ultisnips maps, <c-space> has been used by pinyin input method,you know i am a chinese.
