### ISSUE TITLE
i can use  `./gradlew`  to build the project ,but can not use gradle eclipse ,also can not use JC2

### ISSUE THREAD

**Issue by wsdjeg** [artur-shaik/vim-javacomplete2#133]
![2015-11-17 19-14-27](https://cloud.githubusercontent.com/assets/13142418/11209927/70d5863c-8d5f-11e5-8cf6-6fa3df2018f1.png)

**Comment by mattn** [comment]
is it an issue of javacomplete2?

**Comment by wsdjeg** [comment]
yes ,now i have genarate .classpath,but javacomplet2 does not load it

**Comment by wsdjeg** [comment]
here is the repo of the android project
https://github.com/wsdjeg/AndroidSwipeLayout

**Comment by DonnieWest** [comment]
The Eclipse plugin doesn't work for Android projects. If you check your .classpath file, it won't have the files you need for completion. 

I would delete the Eclipse plugin and delete the .classpath file and use the latest commit. It should work for you

**Comment by wsdjeg** [comment]
thank you @DonnieWest  i have just used your plugin ,but the command do not work

**Comment by wsdjeg** [comment]
there are same issue
