### ISSUE TITLE
New Gradle support doesn't complete R.java

### ISSUE THREAD

**Issue by DonnieWest** [artur-shaik/vim-javacomplete2#135]
This is just a public spot to think about how to fix this and where.

Current Gradle support doesn't include R.java for Android projects. I'm considering one of the following solutions:

1. Have Gradle output the locations of the R.java files into the classpath for JavaComplete2
2. Modify JavaComplete2 to use build.gradle source paths, including the locations of the R.java files
3. Handle this in my external plugin VimStudio. Don't modify this project at all

What do you guys think? @artur-shaik @mattn ?

**Comment by wsdjeg** [comment]
you plugin need neovim,but most people just use vim

**Comment by artur-shaik** [comment]
I still haven't enough time to play more with `gradle`. But it seems that first option is more like how `maven`'s classpath generation works now. It would be great if we implement the same method for `gradle`, I think.

**Comment by DonnieWest** [comment]
@artur-shaik I'm having difficulty getting this to work. I can output the location of every R.java file in the project and load it into g:JavaComplete_LibsPath and it doesn't seem to complete. I haven't had enough time to determine where the issue is occurring.

I'm guessing though that g:JavaComplete_LibsPath is not expecting a .java file but rather a jar, right?

**Comment by wsdjeg** [comment]
@DonnieWest  please use `let g:JavaComplete_SourcesPath = "target/generated-sources/r"`for me the R.java autocreated into `target/generated-sources/r/com/wsdjeg/R.java`,my packagename is com.wsdjeg,it works ok for me

**Comment by wsdjeg** [comment]
g:JavaComplete_LibsPath expanding *.jar and path for classpath

**Comment by artur-shaik** [comment]
@DonnieWest yeah, for `*.java` we use `g:JavaComplete_SourcesPath`.

**Comment by DonnieWest** [comment]
@wsdjeg that doesn't work for gradle and it doesn't account for multi-module projects or for aar libraries included with Android.

@artur-shaik will that variable take a path to a java file (/example/project/R.java) or does it just take a directory containing *.java files (/example/project/src)

**Comment by wsdjeg** [comment]
really strange ,it works well for me,can you try with create an example R.java manualy,and add it to g:JavaComplete_SourcesPath ,now this plugin maybe can not use arr package!

**Comment by wsdjeg** [comment]
so i think maven also is more easy to work with this plugin!

**Comment by wsdjeg** [comment]
@DonnieWest @artur-shaik does this plugin now need to install gradle same as maven ,i think if so ,we shoudle add something to readme!
