### ISSUE TITLE
after update to the latest version ,when i open gradle android project,the vim stop here!

### ISSUE THREAD

**Issue by wsdjeg** [artur-shaik/vim-javacomplete2#136]
i have test with just only one javacomplete2  plugin
![2015-11-18 21-13-09](https://cloud.githubusercontent.com/assets/13142418/11241884/4c41424a-8e39-11e5-9179-ed3b5660cfdd.png)
![2015-11-18 21-11-03](https://cloud.githubusercontent.com/assets/13142418/11241889/607ac1c8-8e39-11e5-901c-39cbcdffde7f.png)

**Comment by wsdjeg** [comment]
can you try with this repo
https://github.com/gitskarios/Materialize

**Comment by wsdjeg** [comment]
i will show you the profile log

https://github.com/wsdjeg/DotFiles/blob/develop/vim-javacomplete2.log

i find the plugin take a long time

**Comment by wsdjeg** [comment]
issue maybe is here
![2015-11-19 20-20-17](https://cloud.githubusercontent.com/assets/13142418/11270567/0d9cd4ce-8efb-11e5-90b8-8b8ac3812485.png)

**Comment by wsdjeg** [comment]
@artur-shaik hi here is an plugin for gradle,i have try with it ,it can get the classpath

**Comment by wsdjeg** [comment]
close this now,i will just use maven,gradle is very ```````````

**Comment by DonnieWest** [comment]
Just figured this out. I had a typo in my gradle support. Pushing update shortly

**Comment by wsdjeg** [comment]
still does not work i clone this project and can build success,but can not complete,just can complete the class in src directory
![2015-11-24 20-32-31](https://cloud.githubusercontent.com/assets/13142418/11366836/c005399c-92ea-11e5-9268-10117e1bb9b6.png)

**Comment by wsdjeg** [comment]
here is my fork can you try?
https://github.com/wsdjeg/AndroidSwipeLayout
