### ISSUE TITLE
Can't complete static method

### ISSUE THREAD

**Issue by mattn** [artur-shaik/vim-javacomplete2#138]
```
System.out::pri
```
println should be in candidates. but not.

![](https://gyazo.com/1ea0326879f8b071574eacd113abce56.png)

**Comment by artur-shaik** [comment]
Hm, have completion been executed? With the same code I have all `print`
completion suggestions.

**Comment by mattn** [comment]
@artur-shaik yeah, I can complete members like String.valueOf, IntStream.range. But System.out::println is not.

**Comment by artur-shaik** [comment]
Ou, now I can see your use case. For me, if comletion called after `::`
it works fine, but if after `out::pri|` I have the same issue.

Will see what we can do...

**Comment by mattn** [comment]
thanks.
