### ISSUE TITLE
Which CLASSPATH is required?

### ISSUE THREAD

**Issue by mattn** [artur-shaik/vim-javacomplete2#14]
Currently, $CLASSPATH is too long. On my environment, it's over limit of length of CLASSPATH.
`~/.m2/repository` is needed? `$JAVA_HOME/lib` is needed?
I'm thinking it is enough to add jars which is depended on current `project`. i mean `project` is `WEB-INF/lib` or `lib` or `src/java/classes` or etc.
How do you think?

**Comment by artur-shaik** [comment]
Yes, I currently think that maven repos shoud be optional. But I want to keep JRE libraries, that will give ability to complete class names from standart library, that is always needed.

**Comment by mattn** [comment]
However, my `~/.m2/repository` has 850 jars.

**Comment by mattn** [comment]
my `/usr/lib/jvm/java/lib` has 700 over jars.

**Comment by mattn** [comment]
I'm thinking it's better to glob `$JRE/lib/*.jar` not `$JRE/lib/**/*.jar`.

**Comment by artur-shaik** [comment]
Hm, my jre lib dir has only 22 jars (that is appended), but jdk lib has over 600 jars. You sure you have counted jre lib jars?

**Comment by artur-shaik** [comment]
But if you set explicitly CLASSPATH to jdk, that yeah, that will be appended.

**Comment by mattn** [comment]
```
$ find $JRE/lib -name "*.jar" | wc
25

$ find $JDK/lib -name "*.jar" | wc
678
```

**Comment by mattn** [comment]
But `java.home` seems to be detected as JDK.

**Comment by artur-shaik** [comment]
That's for me:
`java.home = /usr/lib64/java/jdk1.8.0_40/jre`

**Comment by mattn** [comment]
Just moving m2 as optional, it may be some fixes.

**Comment by artur-shaik** [comment]
Should we check and append `jre` path if it is not found in path? Would it be acceptable?

**Comment by mattn** [comment]
Sorry, on my windows, java.home are JRE

```
java.home = C:\Program Files\Java\jre1.8.0_45
```

**Comment by artur-shaik** [comment]
So does it append jdk libs?

**Comment by mattn** [comment]
on my linux box (at home), $JRE/lib has 600 over file when i looked at yesterday. i don't do anything about $CLASSPATH.

**Comment by artur-shaik** [comment]
Hm, may be any `$JRE` variable issue, can you show content of it when you will at home? And if it `jre/lib`, can you show what extra directories it has?

**Comment by mattn** [comment]
I use $JRE $JDK just for explaining. not set.

**Comment by mattn** [comment]
I'll look into it on my PC at home in later.

**Comment by mattn** [comment]
It works fine with `let g:JavaComplete_MavenRepositoryDisable = 1`
