### ISSUE TITLE
Intelligent Output of completion

### ISSUE THREAD

**Issue by wsdjeg** [artur-shaik/vim-javacomplete2#144]
#### completion after `import static`,end of this statement must be static!
here is my example class which has been compiled with no error! in this class there are two error line has been annotated.

![2015-11-25 20-17-58](https://cloud.githubusercontent.com/assets/13142418/11397116/e9d375fa-93b1-11e5-9160-7ebe3cfde497.png)

in another class these should be complete:
* static nested class, if end with outer class or non-static nested class ,it will get compile error!
    * end with outer class
![end_with_outer_class](https://cloud.githubusercontent.com/assets/13142418/11396873/df9aa808-93af-11e5-8d1d-7983955e416f.png)
    * end with inner class (which is also called non-static nested class)
![2015-11-25 20-11-26](https://cloud.githubusercontent.com/assets/13142418/11396975/d3758100-93b0-11e5-8775-ce5a96554d08.png)

* static methods add fields of both outer class and static nested class(non-static nested class has no static method!)
 **conclusion** Inner class shoud be delete from import static,also static members of static nesed class should be add to import static!

### completion after import ,end of this statement must be a class or interface!
same example as above:
after import these should be complete:
* outer class interface and so on
* Innerclass and static nested class nested interface
because this will be compiled,and has no error!

**conclusion**  `import`statement should be able use `auto import` these is diff from `import static`

**Comment by wsdjeg** [comment]
hi @artur-shaik @DonnieWest @mattn i think i have finshed the completion frame after import and import static,what do you think,anything need to be added?

**Comment by wsdjeg** [comment]
when and where do add all classes in classpath to a list ,i am reading the src of the plugin,is the list named g:JavaComplete_Cache?

**Comment by artur-shaik** [comment]
Made some changes, can you play with it?

**Comment by wsdjeg** [comment]
thank you ,i just get home ,let me have a try!

**Comment by wsdjeg** [comment]
![2015-11-26 16-50-48](https://cloud.githubusercontent.com/assets/13142418/11418759/efef11cc-945d-11e5-8a7c-d36d02d365d9.png)
the third one should be Testi instead of nestedclass itself

**Comment by artur-shaik** [comment]
What is `Testi`? Can you show your `Test` class content?

**Comment by wsdjeg** [comment]
![2015-11-26 18-02-15](https://cloud.githubusercontent.com/assets/13142418/11420245/d941a502-9467-11e5-8052-1c779048329b.png)

**Comment by artur-shaik** [comment]
Ok, can you play with it, one more time?

**Comment by wsdjeg** [comment]
great man!!! let me have a test

**Comment by wsdjeg** [comment]
greate it works well!

**Comment by wsdjeg** [comment]
after import static in works well,but after import some thing diff

**Comment by wsdjeg** [comment]
![2015-11-26 21-33-51](https://cloud.githubusercontent.com/assets/13142418/11424126/6dbe7b34-9485-11e5-8080-60ccf7c742d7.png)
here only hava nostatic innerclass,pleass add static class

**Comment by wsdjeg** [comment]
i have find Testi can be auto add ,thank you

**Comment by artur-shaik** [comment]
Aaand here is it :smile:

**Comment by wsdjeg** [comment]
how fast! let me try

**Comment by wsdjeg** [comment]
wow ,great!!!!works well

**Comment by wsdjeg** [comment]
the input will be remember，please clean it after import 

![2015-11-26 21-53-14](https://cloud.githubusercontent.com/assets/13142418/11424478/7957b926-9488-11e5-8f5f-b8b19e43f26e.png)

**Comment by artur-shaik** [comment]
@wsdjeg yeah, this is another one issue.

**Comment by wsdjeg** [comment]
if the very strange,i can complete in import static,but can not complete in method!
here is test R.java
![2015-11-26 22-04-19](https://cloud.githubusercontent.com/assets/13142418/11424626/aa534850-9489-11e5-989f-35ec05bbabcc.png)
![2015-11-26 22-02-06](https://cloud.githubusercontent.com/assets/13142418/11424645/cc83c260-9489-11e5-9221-b6e9bcfcb3b3.png)

![2015-11-26 22-02-32](https://cloud.githubusercontent.com/assets/13142418/11424654/dc6ced6e-9489-11e5-86c8-2f56d169041d.png)

**Comment by artur-shaik** [comment]
Can you try, again?

**Comment by wsdjeg** [comment]
thank you very much greate it works very well with R.java.i think is must be known by @DonnieWest 
![2015-11-26 22-54-16](https://cloud.githubusercontent.com/assets/13142418/11425646/4ce3b81e-9491-11e5-8e2b-9f1bd2e0e569.png)
![2015-11-26 22-59-27](https://cloud.githubusercontent.com/assets/13142418/11425653/5e820062-9491-11e5-9ba6-4f0c458fdfe3.png)

**Comment by DonnieWest** [comment]
Having some issues here unfortunately - @wsdjeg how are you adding the R.java file to javacomplete?

I've tried a few things and it's not properly completing the file, but I'm guessing it's with my configuration

**Comment by wsdjeg** [comment]
no need to set anything,it is jc2 feature ,auto add maven output dir into classpath,it contains com.wsdjeg.helloworld.R.class.i do not add R.java.because R.java and R.class were created at same time,and will not be edite mannuly.
for example
my maven outputdir is /path/to/project/target/classes
R.class is here path/to/project/target/classes/com/wsdjeg/helloworld/R.class
my

**Comment by wsdjeg** [comment]
also you can add it to g:JavaComplete_LibsPath,it also works

**Comment by wsdjeg** [comment]
there is no need care about R.java. just R.class willbe ok

**Comment by wsdjeg** [comment]
you can have a look at my last PR for pom

**Comment by DonnieWest** [comment]
Odd - on Gradle it's not completing even when R.class is added to the g:JavaComplete_LibsPath

I'll have to play around with it some more.

**Comment by wsdjeg** [comment]
strange why?just add to classpath use complete path ,do not just use  relative path

**Comment by wsdjeg** [comment]
can use show me the out put of echo g:JavaComplete_LibsPath when you open a java file

**Comment by wsdjeg** [comment]
in maven project aar package works well.because maven will unpackage it and auto add to classpath

**Comment by wsdjeg** [comment]
https://github.com/artur-shaik/vim-javacomplete2/pull/146

**Comment by wsdjeg** [comment]
for example test.aar.classes.jar wilk be unpackage into target/generate-unpckaged/test.jar and add to buildclasspath

**Comment by artur-shaik** [comment]
@DonnieWest, didn't you forget to recompile javavi lib?

**Comment by wsdjeg** [comment]
hi @DonnieWest i think i have find why does not work ,i will give an PR!
![2015-11-27 18-44-21](https://cloud.githubusercontent.com/assets/13142418/11439518/e744ef7c-9536-11e5-85c5-eb5dfaa81acc.png)

open java file and echo g:JavaComplete_LibsPath show this 

![2015-11-27 18-42-56](https://cloud.githubusercontent.com/assets/13142418/11439505/cf06d718-9536-11e5-9851-4914e99fb531.png)

**Comment by wsdjeg** [comment]
now it works well @DonnieWest 
example
https://github.com/wsdjeg/AndroidSwipeLayout
![2015-11-27 19-02-49](https://cloud.githubusercontent.com/assets/13142418/11440015/1979fb06-953a-11e5-846b-8c7defea3114.png)

**Comment by wsdjeg** [comment]
@mattn please see here if g:JavaComplete_LibsPath != null,
the classpath will like this, '.' is not the begin of the class path
![2015-11-27 19-32-14](https://cloud.githubusercontent.com/assets/13142418/11440479/ab9b21a6-953d-11e5-8082-09f50f112ccb.png)

**Comment by mattn** [comment]
Sorry, I can't understand what you mean.

**Comment by wsdjeg** [comment]
maybe it is my fault, i means classpath should be `.:/path/libspath:/path/test.jar:/path/classes` instead of `/path/libspath:/path/test.jar:.:/path/classes`

**Comment by wsdjeg** [comment]
now in gradle project if i set g:JavaComplete_LibsPath = 'path/to/packageName/R.class'
i can complet R.===> but can not use import and completion of others classes

**Comment by wsdjeg** [comment]
sorry it my fault, i have reset my fork

**Comment by wsdjeg** [comment]
strange completion 
![2015-11-27 21-10-36](https://cloud.githubusercontent.com/assets/13142418/11441901/7614b318-954b-11e5-9ded-47151663df03.png)
![2015-11-27 21-10-46](https://cloud.githubusercontent.com/assets/13142418/11441902/763348a0-954b-11e5-92fa-215cd95ef630.png)

**Comment by artur-shaik** [comment]
@wsdjeg you mean `class`?

**Comment by wsdjeg** [comment]
no after `id` should be compete `edite`
![2015-11-26 22-04-19](https://cloud.githubusercontent.com/assets/13142418/11424626/aa534850-9489-11e5-989f-35ec05bbabcc.png)

**Comment by wsdjeg** [comment]
there is no error in import statement and import static

**Comment by wsdjeg** [comment]
![2015-11-27 22-07-27](https://cloud.githubusercontent.com/assets/13142418/11442820/53496222-9553-11e5-8d3b-67e881d87d8a.png)
![2015-11-27 22-07-37](https://cloud.githubusercontent.com/assets/13142418/11442822/5391d462-9553-11e5-917a-3252c8043749.png)
![2015-11-27 22-07-47](https://cloud.githubusercontent.com/assets/13142418/11442823/5393bdd6-9553-11e5-867c-2fc5d146bdb2.png)
![2015-11-27 22-08-27](https://cloud.githubusercontent.com/assets/13142418/11442839/721ee960-9553-11e5-8904-c47c4817f417.png)
![Uploading 2015-11-27 22-08-27屏幕截图.png…]()

**Comment by artur-shaik** [comment]
Now should work right.

**Comment by wsdjeg** [comment]
wow  ^_^ works well,need wo close this issue? it is too long

**Comment by artur-shaik** [comment]
You decide, you are the tester. :smile:

**Comment by wsdjeg** [comment]
thank you,i will do some test,and report it!

**Comment by wsdjeg** [comment]
* should not complete class name after package statement;
![2015-11-27 22-53-38](https://cloud.githubusercontent.com/assets/13142418/11443693/181ef4c6-955a-11e5-92b8-f075dd4a1b01.png)
* it is better to use auto import for auto import static nested class ,it is not vert important ,but when check exists imports should contains import static.
![2015-11-27 23-00-29](https://cloud.githubusercontent.com/assets/13142418/11443772/b8b4c140-955a-11e5-91f1-674d24f58e7e.png)

* the input should be Clear up
![2015-11-26 21-53-14](https://cloud.githubusercontent.com/assets/13142418/11443806/1657aa24-955b-11e5-9855-f1aac44ffb6e.png)

**Comment by wsdjeg** [comment]
just same as innerclass
![2015-11-27 23-08-48](https://cloud.githubusercontent.com/assets/13142418/11443885/dd25b84e-955b-11e5-9074-04a45d18e0d6.png)

**Comment by artur-shaik** [comment]
Can you create separate issues, please?
And this can be closed as I see.

**Comment by wsdjeg** [comment]
ok i will open an new issue
