### ISSUE TITLE
No javavi library classes found, it means that we couldn't compile it. Do you have JDK7+ installed?

### ISSUE THREAD

**Issue by zhaochenyou** [artur-shaik/vim-javacomplete2#154]
This appear in my Windows 7 with JDK8. I didn't install my JDK in the default path, but another place.
This is my jdk configure:

JAVA_HOME = C:\bin\Java\jdk1.8.0_66
CLASSPATH = .;%JAVA_HOME%\lib\dt.jar;%JAVA_HOME%\lib\tools.jar;
PATH = C:\ProgramData\Oracle\Java\javapath;%JAVA_HOME%\bin;%JAVA_HOME%\jre\bin;C:\bin\Vim74\vim74\;

Please help me a little.

**Comment by wsdjeg** [comment]
new version jdk has no need to set classpath,
and what is the output of java -version in cmd?

**Comment by wsdjeg** [comment]
it is better to install maven,and javacomplete2 support maven better.

**Comment by zhaochenyou** [comment]
java -version say:
java version "1.8.0_66"
Java(TM) SE Runtime Environment(build 1.8.0_66-b18)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b18, mixed mode)

I have installed and used javacomplete2 in Fedora22 with vim. It works very good.
I find there is a folder which name is "javavi",
it's  ~/.vim/bundle/vim-javacomplete2/libs/javavi.
And inside this folder, there's "src" and "target" folder.
There's lots of java source code in "src", But there's nothing in "target".
I think that's why the plugin cannot find the javavi classes.
But how can I fix this ?

**Comment by wsdjeg** [comment]
delete target then open an java file with vim,just waitting do not stop it,

**Comment by wsdjeg** [comment]
javac -d ~/.vim/bundle/vim-javacomplete2/libs/javavi/target/classes -classpath ~/.vim/bundle/vim-javacomplete2/libs/javavi/target/classes:~/.vim/bundle/vim-javacomplete2/libs/javaparser.jar -sourcepath ~/.vim/bundle/vim-javacomplete2/libs/javavi/src/main/java -g -nowarn -target 1.8 -source 1.8 -encoding UTF-8 ~/.vim/bundle/vim-javacomplete2/libs/javavi/src/main/java/kg/ash/javavi/Javavi.java

**Comment by zhaochenyou** [comment]
Thanks a lot, but the command output lots of java building errors.
cannot find java classes, I find these codes in the src folder.
Finnally I think the real reason of building error is the Windows Command,
It use '\' as a path seperator, not '/' in Linux/Unix.
I have meet an error when I use "PluginInstall" with Vundle.
It download all the plugins to another path, Not my C:/Users/zhaochenyou/.vim/bundle .
It's also because the windows command use '\' but not '/'.
Anyway thanks a lot.

**Comment by artur-shaik** [comment]
@zhaochenyou can you show, what errors it prints you?

**Comment by zhaochenyou** [comment]
C:\Windows\system32\cmd.exe /c (javac -d C:/Users/zhaochenyou/.vim/bundle/vim-javacomplete
2/libs/javavi/target/classes -classpath C:/Users/zhaochenyou/.vim/bundle/vim-javacomplete2
/libs/javavi/target/classes:C:/Users/zhaochenyou/.vim/bundle/vim-javacomplete2/libs/javapa
rser.jar; -sourcepath C:/Users/zhaochenyou/.vim/bundle/vim-javacomplete2/libs/javavi/src/m
ain/java: -g -nowarn -target 1.8 -source 1.8 -encoding UTF-8 C:/Users/zhaochenyou/.vim/bun
dle/vim-javacomplete2/libs/javavi/src/main/java/kg/ash/javavi/Javavi.java)
C:\Users\zhaochenyou\.vim\bundle\vim-javacomplete2\libs\javavi\src\main\java\kg\ash\javavi
\Javavi.java:5: error: package kg.ash.javavi.actions does not exist
import kg.ash.javavi.actions.Action;
                            ^
C:\Users\zhaochenyou\.vim\bundle\vim-javacomplete2\libs\javavi\src\main\java\kg\ash\javavi
\Javavi.java:6: error: package kg.ash.javavi.actions does not exist
import kg.ash.javavi.actions.ActionFactory;
                            ^
C:\Users\zhaochenyou\.vim\bundle\vim-javacomplete2\libs\javavi\src\main\java\kg\ash\javavi
\Javavi.java:7: error: package kg.ash.javavi.clazz does not exist
import kg.ash.javavi.clazz.SourceClass;
                          ^
C:\Users\zhaochenyou\.vim\bundle\vim-javacomplete2\libs\javavi\src\main\java\kg\ash\javavi
\Javavi.java:8: error: package kg.ash.javavi.searchers does not exist
import kg.ash.javavi.searchers.ClassMap;
                              ^
C:\Users\zhaochenyou\.vim\bundle\vim-javacomplete2\libs\javavi\src\main\java\kg\ash\javavi
\Javavi.java:16: error: cannot find symbol
    public static HashMap<String,SourceClass> cachedClasses = new HashMap<>();
                                 ^
  symbol:   class SourceClass
  location: class Javavi
C:\Users\zhaochenyou\.vim\bundle\vim-javacomplete2\libs\javavi\src\main\java\kg\ash\javavi
\Javavi.java:18: error: cannot find symbol
    public static HashMap<String,ClassMap> cachedClassPackages = new HashMap<>();
                                 ^
  symbol:   class ClassMap
  location: class Javavi
C:\Users\zhaochenyou\.vim\bundle\vim-javacomplete2\libs\javavi\src\main\java\kg\ash\javavi
\Javavi.java:49: error: cannot find symbol
    public static Daemon daemon = null;
                  ^
  symbol:   class Daemon
  location: class Javavi
C:\Users\zhaochenyou\.vim\bundle\vim-javacomplete2\libs\javavi\src\main\java\kg\ash\javavi
\Javavi.java:60: error: cannot find symbol
        Action action = null;
        ^
  symbol:   class Action
  location: class Javavi
C:\Users\zhaochenyou\.vim\bundle\vim-javacomplete2\libs\javavi\src\main\java\kg\ash\javavi
\Javavi.java:82: error: cannot find symbol
                        action = ActionFactory.get(arg);
                                 ^
  symbol:   variable ActionFactory
  location: class Javavi
9 errors
shell returned 1
Hit any key to close this window...

**Comment by wsdjeg** [comment]
if you do not know how to compile maven project ,i think you should read maven doc,and it is not JC2's issue

**Comment by artur-shaik** [comment]
@zhaochenyou from wich directory you run this command?

**Comment by wsdjeg** [comment]
why do not use mvn -f path/to/pom.xml compile,it is easy and do not care about your current directory

**Comment by zhaochenyou** [comment]
I just gvim Test.java.
Then the windows command output this.
I will learn how to use maven now.

**Comment by wsdjeg** [comment]
can you show me the out put  of mvn -v in command line
if you can use mvn in cammand ,it is easy to auto compile javavi

**Comment by artur-shaik** [comment]
Seems something broken with windows support...

**Comment by wsdjeg** [comment]
change all / to \ ,it is easy
![2015-12-08 20-44-03](https://cloud.githubusercontent.com/assets/13142418/11655918/77c00e66-9dec-11e5-9285-f18c75bc4ae1.png)

**Comment by wsdjeg** [comment]
sorry @artur-shaik i have read the code,i find it will be a long time  work to support win

**Comment by wsdjeg** [comment]
and i have test it in windows os ,same issue as @zhaochenyou

**Comment by wsdjeg** [comment]
@artur-shaik i will try to fix it tonight

**Comment by wsdjeg** [comment]
https://github.com/artur-shaik/vim-javacomplete2/pull/158

**Comment by wsdjeg** [comment]
i am checking line by line ,i think it will be ok

**Comment by artur-shaik** [comment]
@zhaochenyou, can you try again with last commits?
