### ISSUE TITLE
I find this script generate classpath faster than JC2's

### ISSUE THREAD

**Issue by wsdjeg** [artur-shaik/vim-javacomplete2#156]
hi @DonnieWest 
I have tried this script ,
https://github.com/meonlol/vim-grand/blob/master/grand.gradle
it is faster,can you test is ,if possible ，we can use it in javacomplete2

**Comment by DonnieWest** [comment]
The script we use is based on that, but his is Android specific. By using gradle to get all project information we ensure we stay compatible with all projects. His isn't and gas issues with multimodule projects

**Comment by wsdjeg** [comment]
i know thank ,please add the outputdir debug **or** release into the classpath,now javacomplete2 works well with reflection

**Comment by wsdjeg** [comment]
I have tried use vim ,but it just works for minority project
https://github.com/artur-shaik/vim-javacomplete2/pull/152
is this should be merged? 
and i think should not use .classpath and pom.xml or gradle together

**Comment by DonnieWest** [comment]
I'm a bit confused here - is this still open because we're waiting on a reply from me? Is it still relevant in light of recent commits?

**Comment by wsdjeg** [comment]
nothing changed but change '/' to g:FILE_SEP
this issue is about classpath of gradle project,can you add each classes output dir into classpath by change classpath.gradle

**Comment by DonnieWest** [comment]
We already have the generated sources, are we wanting to include the resulting class files as well?

**Comment by wsdjeg** [comment]
yes,because jc2,now need run reflaction from class file,and if it is possble provide a list or v which can be used by 'javac -d '，it will be better let scrooloose/syntastic works well

**Comment by wsdjeg** [comment]
if  there are more than one  type dir .such as release and debug，only one should be used

**Comment by DonnieWest** [comment]
Syntastic support isn't JavaComplete2's job. You're welcome to take g:JavaComplete_LibsPath and g:JavaComplete_SourcesPath and do it yourself though

I'll check out adding the resulting class files to the Libs path and if I can get things to work properly

**Comment by wsdjeg** [comment]
ok,i know ,but as you konw detect output dir need time,i think this shoule not be done twice,so if it is possible.please provide plubic variable

**Comment by DonnieWest** [comment]
So, fiddling with this, I'm still not getting R completions when I add them to my LibsPath

https://asciinema.org/a/4varjgavqx1tkuvidcv9adtja

Sorry for the amount of stuff in my LibsPath - this is the only OSS project for Android I knew of. This also fails on various closed source projects I have that are much smaller in size. The only modifications to JavaComplete2 is right here on the classpath.gradle file:

https://gist.github.com/DonnieWest/8a7868015d68b40c7883#file-classpath-gradle-L17-L25

Any clues?

**Comment by wsdjeg** [comment]
def rjava = proj.getBuildDir().absolutePath + File.separator + "intermediates" + File.separator + "classes" + File.separator + "debug"
    def rFiles = new File(rjava)
    if (rFiles.exists()) {
      rFiles.eachFileRecurse(){ file ->
        if (file.name.endsWith("R.class")){
          classpathFiles += file //no need add every file in to class path, just add the debug dir or release dir,
        }
      }
    }


and the latest version javacomplete2 support gradle well, let me hava a try ,

**Comment by DonnieWest** [comment]
Is there something you changed in the above? I'm not sure I understand

**Comment by wsdjeg** [comment]
you chould not add path to R.class into class path,
you just need add debug dir into it
for example 
`/test/build/implete/classes/debug/`
instead of `/test/build/implete/classes/debug/com/test/R.class`

**Comment by DonnieWest** [comment]
You're not doing that in your pull request. You're simply adding EVERY file that happens to end with "class"

Also. I do NOT appreciate slight modifications of MY code and submitted as YOUR pull request.

**Comment by wsdjeg** [comment]
sorry ,i closing it ,but it works well,and has no repeat path

**Comment by wsdjeg** [comment]
@DonnieWest  really sorry,i just want give it to you for checking

**Comment by DonnieWest** [comment]
@wsdjeg it's fine, probably my misunderstanding.

Can you please post a sample R.java file that works for you? I poked around a few other projects and I've found one that works for me. Apparently there's something not being parsed correctly and I'd like to see if we can root out what it is. I'll go ahead and shoot up a PR since we can both confirm it works

**Comment by wsdjeg** [comment]
here is my fork project,after gradle build,and download all jars
everything is ok,
i can complete the nested class of R which has same package name with current javafile without import,
if i have import R, will complete  nested class of the R which  I hava import,and the mambers or func of R's nested class,
i do not know why i can not add pic now ,do you have mail ,i will mail you

**Comment by wsdjeg** [comment]
https://github.com/wsdjeg/AndroidSwipeLayout

**Comment by DonnieWest** [comment]
Just create a gist with your generated R.java file please - I'd like a few to compare to see what is working and what isn't when Javacomplete2 parses the resulting R.class file

**Comment by wsdjeg** [comment]
https://gist.github.com/wsdjeg/e1d8b8fcc04e169f4ad8

**Comment by DonnieWest** [comment]
Awesome! Thanks!

**Comment by wsdjeg** [comment]
after you PR there is something wrong,can you show me 
echo g:JavaComplete_LibsPath

**Comment by DonnieWest** [comment]
@wsdjeg what's wrong? R.class files are in my g:JavaComplete_LibsPath

**Comment by DonnieWest** [comment]
![2015-12-13-012101_3200x1800_scrot](https://cloud.githubusercontent.com/assets/1453484/11765993/29b45dc2-a138-11e5-8aad-43a4b14b6474.png)

**Comment by wsdjeg** [comment]
you should only add the outputdir into class path,which also used by `javac -d outputdir`
that means the class file are in the subdir of outputdir,and the subdir is package name
and the R.class and Main.class has same outputdir
after add outputdir,every nested class in java file write by yourself will be complete well

**Comment by DonnieWest** [comment]
It's completing just fine for me with only adding the R.java file

As far as javac  -d - that's only where javac puts the resulting classfiles and that shouldn't impact completions and I'm unsure what you're trying to say there

**Comment by wsdjeg** [comment]
maybe @artur-shaik knows,i meads we should add outputdirectory into class path  rather than the path of class file,

**Comment by wsdjeg** [comment]
/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/MyActivity$7.class:/home/wsdjeg/fork/AndroidSwipeLayout/library/build/intermediates/exploded-aar/com.android.support/recyclerview-v7/21.0.0/classes.jar:/home/wsdjeg/fork/AndroidSwipeLayout/library/build/intermediates/classes/debug/com/daimajia/swipe/adapters/BaseSwipeAdapter.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/jp/wasabeef/recyclerview/R$id.class:/home/wsdjeg/fork/AndroidSwipeLayout/library/build/intermediates/classes/debug/com/daimajia/swipe/adapters/SimpleCursorSwipeAdapter.class:/home/wsdjeg/.gradle/caches/modules-2/files-2.1/org.jacoco/org.jacoco.report/0.7.1.201405082137/ce9a5584b7d79828535891b2d7733c639f97e8dd/org.jacoco.report-0.7.1.201405082137.jar:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/jp/wasabeef/recyclerview/R$anim.class:/home/wsdjeg/fork/AndroidSwipeLayout/library/build/intermediates/classes/debug/com/daimajia/swipe/implments/SwipeItemMangerImpl.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/adapter/RecyclerViewAdapter$SimpleViewHolder.class:/home/wsdjeg/.gradle/caches/modules-2/files-2.1/org.jacoco/org.jacoco.agent/0.7.1.201405082137/e1b1c97041a0a92f87ab265b6b977c7d409ead40/org.jacoco.agent-0.7.1.201405082137.jar:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/GridViewExample$1.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/adapter/util/RecyclerItemClickListener$1.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/ListViewExample$3.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/easing/R$style.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/androidanimations/library/R$string.class:/home/wsdjeg/fork/AndroidSwipeLayout/library/build/intermediates/classes/debug/com/daimajia/swipe/implments/SwipeItemMangerImpl$ValueBox.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/R$layout.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/RecyclerViewExample$1.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/MyActivity$10.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/jp/wasabeef/recyclerview/R$attr.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/jp/wasabeef/recyclerview/R$dimen.class:/home/wsdjeg/fork/AndroidSwipeLayout/library/build/intermediates/classes/debug/com/daimajia/swipe/SwipeLayout.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/MyActivity$1.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipe/R.class:/home/wsdjeg/fork/AndroidSwipeLayout/library/build/intermediates/classes/debug/com/daimajia/swipe/adapters/CursorSwipeAdapter.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/adapter/ListViewAdapter$3.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/easing/R$styleable.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/MyActivity$13.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/easing/R$bool.class:/home/wsdjeg/fork/AndroidSwipeLayout/library/build/intermediates/classes/debug/com/daimajia/swipe/SwipeLayout$DragEdge.class:/home/wsdjeg/fork/AndroidSwipeLayout/library/build/intermediates/classes/debug/com/daimajia/swipe/SwipeLayout$Status.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/easing/R$string.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/jp/wasabeef/recyclerview/R$bool.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/BuildConfig.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipe/R$id.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipe/R$attr.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/easing/R$anim.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/MyActivity$4.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/exploded-aar/com.daimajia.androidanimations/library/1.1.2/classes.jar:/home/wsdjeg/fork/AndroidSwipeLayout/library/build/intermediates/classes/debug/com/daimajia/swipe/SwipeLayout$3.class:/home/wsdjeg/.gradle/caches/modules-2/files-2.1/org.jacoco/org.jacoco.ant/0.7.1.201405082137/fa7d7352cf2847db16efb1d2fc4eefa36e897690/org.jacoco.ant-0.7.1.201405082137.jar:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/exploded-aar/com.android.support/recyclerview-v7/21.0.0/classes.jar:/home/wsdjeg/fork/AndroidSwipeLayout/library/build/intermediates/classes/debug/com/daimajia/swipe/implments/SwipeItemMangerImpl$SwipeMemory.class:/home/wsdjeg/fork/AndroidSwipeLayout/library/build/intermediates/classes/debug/com/daimajia/swipe/R.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/adapter/GridViewAdapter.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/R$style.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/MyActivity$11.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/adapter/RecyclerViewAdapter$SimpleViewHolder$1.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/easing/R$layout.class:/home/wsdjeg/fork/AndroidSwipeLayout/library/build/intermediates/classes/debug/com/daimajia/swipe/SwipeLayout$ShowMode.class:/home/wsdjeg/fork/AndroidSwipeLayout/library/build/intermediates/classes/debug/com/daimajia/swipe/SwipeLayout$SwipeDetector.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/adapter/util/DividerItemDecoration.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/NestedExample.class:/home/wsdjeg/fork/AndroidSwipeLayout/library/build/intermediates/classes/debug/com/daimajia/swipe/SwipeLayout$SwipeDenier.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/R$color.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/R$string.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/jp/wasabeef/recyclerview/R$layout.class:/home/wsdjeg/.gradle/caches/modules-2/files-2.1/org.jacoco/org.jacoco.core/0.7.1.201405082137/4e8449045f1ac3b845ad5947f87c96e31c88c4eb/org.jacoco.core-0.7.1.201405082137.jar:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/MyActivity$5.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/GridViewExample$3.class:/home/wsdjeg/fork/AndroidSwipeLayout/library/build/intermediates/classes/debug/com/daimajia/swipe/SwipeLayout$OnRevealListener.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/R$menu.class:/home/wsdjeg/fork/AndroidSwipeLayout/library/build/intermediates/classes/debug/com/daimajia/swipe/interfaces/SwipeItemMangerInterface.class:/home/wsdjeg/tools/android-sdk-linux/extras/android/m2repository/com/android/support/support-annotations/22.1.1/support-annotations-22.1.1.jar:/home/wsdjeg/fork/AndroidSwipeLayout/library/build/intermediates/classes/debug/com/daimajia/swipe/R$id.class:/home/wsdjeg/fork/AndroidSwipeLayout/library/build/intermediates/classes/debug/com/daimajia/swipe/interfaces/SwipeAdapterInterface.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/MyActivity$6.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/MyActivity$12.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/exploded-aar/com.android.support/support-v4/22.1.1/classes.jar:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/easing/R$color.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/adapter/ArraySwipeAdapterSample.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/ListViewExample$2.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/jp/wasabeef/recyclerview/R$color.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/GridViewExample$2.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/androidanimations/library/R.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/exploded-aar/com.daimajia.easing/library/1.0.0/classes.jar:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/exploded-aar/jp.wasabeef/recyclerview-animators/1.0.3/classes.jar:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/adapter/ListViewAdapter$2.class:/home/wsdjeg/fork/AndroidSwipeLayout/library/build/intermediates/exploded-aar/com.android.support/support-v4/22.1.1/classes.jar:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/jp/wasabeef/recyclerview/R$style.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/jp/wasabeef/recyclerview/R.class:/home/wsdjeg/fork/AndroidSwipeLayout/library/build/intermediates/classes/debug/com/daimajia/swipe/SwipeLayout$4.class:/home/wsdjeg/fork/AndroidSwipeLayout/library/build/intermediates/classes/debug/com/daimajia/swipe/SwipeLayout$OnLayout.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/easing/R$id.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/jp/wasabeef/recyclerview/R$string.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/ListViewExample$4.class:/home/wsdjeg/fork/AndroidSwipeLayout/library/build/intermediates/classes/debug/com/daimajia/swipe/adapters/ArraySwipeAdapter.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/MyActivity$3.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/R$styleable.class:/home/wsdjeg/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-debug-all/5.0.1/f69b5f7d96cec0d448acf1c1a266584170c9643b/asm-debug-all-5.0.1.jar:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/adapter/RecyclerViewAdapter$3.class:/home/wsdjeg/fork/AndroidSwipeLayout/library/build/intermediates/classes/debug/com/daimajia/swipe/SimpleSwipeListener.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/jp/wasabeef/recyclerview/R$integer.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/adapter/util/RecyclerItemClickListener$OnItemClickListener.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/easing/R$drawable.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/ListViewExample$1.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/ListViewExample.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/NestedExample$1.class:/home/wsdjeg/fork/AndroidSwipeLayout/library/build/intermediates/classes/debug/com/daimajia/swipe/adapters/RecyclerSwipeAdapter.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/MyActivity.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/easing/R$dimen.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/R.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/adapter/RecyclerViewAdapter.class:/home/wsdjeg/fork/AndroidSwipeLayout/library/build/intermediates/classes/debug/com/daimajia/swipe/implments/SwipeItemMangerImpl$OnLayoutListener.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/easing/R.class:/home/wsdjeg/fork/AndroidSwipeLayout/library/build/intermediates/classes/debug/com/daimajia/swipe/SwipeLayout$DoubleClickListener.class:/home/wsdjeg/.gradle/caches/modules-2/files-2.1/com.nineoldandroids/library/2.4.0/e9b63380f3a242dbdbf103a2355ad7e43bad17cb/library-2.4.0.jar:/home/wsdjeg/fork/AndroidSwipeLayout/library/build/intermediates/classes/debug/com/daimajia/swipe/R$attr.class:/home/wsdjeg/fork/AndroidSwipeLayout/library/build/intermediates/classes/debug/com/daimajia/swipe/SwipeLayout$2.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/adapter/RecyclerViewAdapter$1.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/R$attr.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/MyActivity$2.class:/home/wsdjeg/tools/android-sdk-linux/platforms/android-21/android.jar:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/R$id.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipe/R$styleable.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/MyActivity$8.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/MyActivity$14.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/androidanimations/library/R$drawable.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/adapter/ListViewAdapter$1.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/NestedExample$2.class:/home/wsdjeg/fork/AndroidSwipeLayout/library/build/intermediates/classes/debug/com/daimajia/swipe/util/Attributes.class:/home/wsdjeg/fork/AndroidSwipeLayout/library/build/intermediates/classes/debug/com/daimajia/swipe/util/Attributes$Mode.class:/home/wsdjeg/fork/AndroidSwipeLayout/library/build/intermediates/classes/debug/com/daimajia/swipe/SwipeLayout$SwipeListener.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/easing/R$attr.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/jp/wasabeef/recyclerview/R$drawable.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/easing/R$integer.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/jp/wasabeef/recyclerview/R$styleable.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/MyActivity$15.class:/home/wsdjeg/fork/AndroidSwipeLayout/library/build/intermediates/classes/debug/com/daimajia/swipe/R$styleable.class:/home/wsdjeg/fork/AndroidSwipeLayout/library/build/intermediates/classes/debug/com/daimajia/swipe/SwipeLayout$1.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/adapter/ListViewAdapter.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/exploded-aar/AndroidSwipeLayout/library/unspecified/classes.jar:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/MyActivity$9.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/adapter/RecyclerViewAdapter$2.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/R$dimen.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/GridViewExample.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/ListViewExample$5.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/R$drawable.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/RecyclerViewExample.class:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug/com/daimajia/swipedemo/adapter/util/RecyclerItemClickListener.class:/home/wsdjeg/fork/AndroidSwipeLayout/library/build/intermediates/classes/debug/com/daimajia/swipe/BuildConfig.class

**Comment by wsdjeg** [comment]
you see it is after you PR,all classes in classptah rather than output directory

**Comment by DonnieWest** [comment]
I did just miss that I made a typo when putting that up :)

However, are you noticing anything /wrong/ with the completions you are getting? The more class files we add, the worse the performance from JavaComplete2 which should already be getting completions from source files, not compiled class files

This R.class thing is a workaround until we can properly parse R.java files with numerous inner classes

**Comment by wsdjeg** [comment]
if we add a directory into classpath, the jdk auto detect the files in this path,if the file's subpath is com/wsdjeg/Test.class,and it's package name is com.wsdjeg; it will be auto reflection

**Comment by wsdjeg** [comment]
maybe you misunderstand what is classpath,it is derectory,not class's whole path

**Comment by DonnieWest** [comment]
I understand the purpose of the classpath, but the more files in it the slower JavaComplete2 functions. We need to avoid adding ALL classes for what is /just/ a workaround. Do you have a practical example of  something not working correctly

**Comment by wsdjeg** [comment]
sorry ,it is my fauly,i understander what you mean,you just want add R.class,rather than all the classes,but should we add the nested class of R.class in to it

**Comment by wsdjeg** [comment]
may be we should add R.class add R$**.class

**Comment by DonnieWest** [comment]
@wsdjeg I'd be more than happy to add anything else if we encounter some other issue, just let me know :-) 

@artur-shaik do you happen to see why my original R.java wasn't working? Anything I can provide to help figure it out

**Comment by wsdjeg** [comment]
i have test it but can not complete the R if we do not import it,as you know if the R,class has same package name with current file ,we can do not import it

**Comment by wsdjeg** [comment]
same as other class

**Comment by wsdjeg** [comment]
can you test my fork?

**Comment by DonnieWest** [comment]
So, just adding the output directory allows completion without importing it? Do you know of any other way?

**Comment by wsdjeg** [comment]
https://github.com/wsdjeg/vim-javacomplete2

**Comment by wsdjeg** [comment]
yes , if we add the output dir, we can complete other class which has the same package name without import it,not only R

**Comment by DonnieWest** [comment]
I'm not able to test immediately, but you're just looking for every class file and adding it to the classpath individually

**Comment by wsdjeg** [comment]
no,i def the outputdir,and detect if it is empty,if not add it into classpath ,mybe the code can be shorter

**Comment by wsdjeg** [comment]
```
def rjava = proj.getBuildDir().absolutePath + File.separator + "intermediates" + File.separator + "classes" + File.separator + "debug"
    def rFiles = new File(rjava)
    if (rFiles.exists()) {
        rFiles.eachFileRecurse(){ file ->
            if (file.name.endsWith("class")){
                classpathFiles += rjava
            }
        }
    }
```
 you see i am adding rjava rather than file

**Comment by wsdjeg** [comment]
/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/exploded-aar/jp.wasabeef/recyclerview-animators/1.0.3/classes.jar:/home/wsdjeg/.gradle/ca
ches/modules-2/files-2.1/org.jacoco/org.jacoco.ant/0.7.1.201405082137/fa7d7352cf2847db16efb1d2fc4eefa36e897690/org.jacoco.ant-0.7.1.201405082137.jar:/h
ome/wsdjeg/fork/AndroidSwipeLayout/library/build/intermediates/exploded-aar/com.android.support/recyclerview-v7/21.0.0/classes.jar:/home/wsdjeg/fork/An
droidSwipeLayout/demo/build/intermediates/exploded-aar/com.android.support/recyclerview-v7/21.0.0/classes.jar:/home/wsdjeg/fork/AndroidSwipeLayout/libr
ary/build/intermediates/classes/debug:/home/wsdjeg/fork/AndroidSwipeLayout/library/build/intermediates/exploded-aar/com.android.support/support-v4/22.1
.1/classes.jar:/home/wsdjeg/tools/android-sdk-linux/extras/android/m2repository/com/android/support/support-annotations/22.1.1/support-annotations-22.1
.1.jar:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/classes/debug:/home/wsdjeg/.gradle/caches/modules-2/files-2.1/org.jacoco/org.jacoc
o.report/0.7.1.201405082137/ce9a5584b7d79828535891b2d7733c639f97e8dd/org.jacoco.report-0.7.1.201405082137.jar:/home/wsdjeg/tools/android-sdk-linux/plat
forms/android-21/android.jar:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/exploded-aar/AndroidSwipeLayout/library/unspecified/classes.
jar:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/exploded-aar/com.android.support/support-v4/22.1.1/classes.jar:/home/wsdjeg/.gradle/c
aches/modules-2/files-2.1/org.jacoco/org.jacoco.agent/0.7.1.201405082137/e1b1c97041a0a92f87ab265b6b977c7d409ead40/org.jacoco.agent-0.7.1.201405082137.j
ar:/home/wsdjeg/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-debug-all/5.0.1/f69b5f7d96cec0d448acf1c1a266584170c9643b/asm-debug-all-5.0.1.jar:/ho
me/wsdjeg/.gradle/caches/modules-2/files-2.1/org.jacoco/org.jacoco.core/0.7.1.201405082137/4e8449045f1ac3b845ad5947f87c96e31c88c4eb/org.jacoco.core-0.7
.1.201405082137.jar:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/exploded-aar/com.daimajia.androidanimations/library/1.1.2/classes.jar
:/home/wsdjeg/fork/AndroidSwipeLayout/demo/build/intermediates/exploded-aar/com.daimajia.easing/library/1.0.0/classes.jar:/home/wsdjeg/.gradle/caches/m
odules-2/files-2.1/com.nineoldandroids/library/2.4.0/e9b63380f3a242dbdbf103a2355ad7e43bad17cb/library-2.4.0.jar



you see it after my pr what the classpath is only has two `classes/debug` one is lib's proj the other is demo's

**Comment by DonnieWest** [comment]
Oh! Sorry I missed that! Yeah, I agree it can probably be made shorter. Can you think if anything that doesn't require adding all the class files to the classpath?

If not, go ahead and make the pull request I stupidly griped about. I'll close mine.

**Comment by wsdjeg** [comment]
after the latest version of JC2,there is no need care about numbers of classes,now the JC2 works faster than before.

**Comment by wsdjeg** [comment]
you PR is very nice,but just need to change a litter i will note it on code

**Comment by DonnieWest** [comment]
I won't be near my laptop to push it up for a few hours, if you have the opportunity feel free to push it up. If not then I'll do it much later

**Comment by wsdjeg** [comment]
it is not urgent ,just waitting for you

**Comment by wsdjeg** [comment]
this issue too long close it, and we can talk about the classpath of gradle in https://github.com/artur-shaik/vim-javacomplete2/pull/161
