### ISSUE TITLE
Idea: Lookup documentation on completion candidate 

### ISSUE THREAD

**Issue by brcolow** [artur-shaik/vim-javacomplete2#157]
I had an idea, and was wondering if it would be feasible.

I will use IntelliJ IDEA as illustration. We type "String." and completion menu comes up. Then we can select a completion candidate:

![compl](https://cloud.githubusercontent.com/assets/6589866/11610287/256fc0ae-9b5b-11e5-9b77-bc3f4d12ef06.png)

Then (depending on key bindings, for me it is Ctrl+Q), we can query the locally installed JDK Javadocs about this method:

![compl1](https://cloud.githubusercontent.com/assets/6589866/11610292/48671710-9b5b-11e5-961e-e3bdb88854e7.png)

Now I am not suggesting to copy the user interface itself, but the _functionality_. For example, if one pressed Ctrl+Q on the candidate, maybe it could popup in a browser, or a tab split, or something else.

What do you guys think?

**Comment by artur-shaik** [comment]
Yeah, something like this already in todo list, under `javadoc` entry. I
think this can work like c++, python doc in YCM, with popup buffer.

Need more investigation about this...

**Comment by artur-shaik** [comment]
Consider switch to [jc.nvim](https://github.com/artur-shaik/jc.nvim)
