### ISSUE TITLE
some error with completion of '{'and '}' with neocomplet

### ISSUE THREAD

**Issue by wsdjeg** [artur-shaik/vim-javacomplete2#159]
I think it is better do not complete '{'and '}' ,and i think it is completion engine‘s work ,not JC2,jc2 just need to check the context,and provide a list of completion.
if you complet '{'
why do not complet < ( or [
also why do not complet ) after a mothed,
so i think if do so ,it will beyond the intention of javacomplete2

and as i know many plugin supprt completion of ( [ { and <

**Comment by wsdjeg** [comment]
neocomplete support auto complete ( [ { < after complete done
also you can set by yourself
by let g:neopairs#pairs = { '[': ']', '<': '>', '(': ')', '{': '}' }
in the neopairs.vim has this script
```vim
let g:neopairs#_pairs =
      \ get(g:, 'neopairs#_pairs',
      \     { '[': ']', '<': '>', '(': ')', '{': '}' })
```

**Comment by Shougo** [comment]
> neocomplete support auto complete ( [ { < after complete done

It is not neocomplete feature.  It is neopairs.vim feature.

**Comment by wsdjeg** [comment]
yes ,but what do you think of this issue,i think it will be better omnifun just check context,and provide list,the complete engine could use this list as source,maybe ycm also work like this ,but i do not know more about ycm,
also i just open an issue about auto jump out pairs after autocomplete pairs 
https://github.com/Shougo/neopairs.vim/issues/1

**Comment by artur-shaik** [comment]
jc2 doesn't complete `{`. jc2 complete only `@Override` methods with `}`. Do you have some extra `}` on `@Override` completion?

**Comment by wsdjeg** [comment]
yes , i use neocomplete together with neopairs,after complete will get
@Override
public void test() {
      _//cursor
}}

**Comment by wsdjeg** [comment]
with help of neopairs,
if i complete `this.test2().test2().test3();`
i just need to type this dot  tab right dot  tab right `;`

**Comment by artur-shaik** [comment]
Hm. I think we can do this close brace optional, for those who use neopairs or something else.

**Comment by wsdjeg** [comment]
yes，that good idea.maybe it is better provide an option to set this func on or off

**Comment by wsdjeg** [comment]
thanks i have just @ you, in neopairs repo,the pic show a perfect completion together with deoplete,will you have a try? as you konw YCM does not add vim omni into it's core complete engine

**Comment by artur-shaik** [comment]
Yeah, thank you for info. Some day I will try neo plugins :smile:

**Comment by wsdjeg** [comment]
but the neosnippet can not parser the completion word after @override,but i think after @override ,i will use JC2's auto close and disable neosnippets, it is easy for me to create a toggle function between them。
here is my omni autocomplete input_patterns
```vim
 let g:deoplete#omni#input_patterns.java = [
                        \'[^. \t0-9]\.\w*',
                        \'[^. \t0-9]\->\w*',
                        \'[^. \t0-9]\::\w*',
                        \'\s[A-Z][a-z]',
                        \'^\s*@[A-Z][a-z]'
                        \]
```
in YCM you only can set `.` `->` `::`

**Comment by wsdjeg** [comment]
https://github.com/wsdjeg/DotFiles/commit/88c3bb9c899ef3efc0a06c8385444532c28930f8
my this commit fix the conflict between JC2 and neosnippet, and it works very well
