### ISSUE TITLE
JCimportsRemoveUnused is removing wrong imports

### ISSUE THREAD

**Issue by richox** [artur-shaik/vim-javacomplete2#166]
java code:

    import java.util.List;
    import java.util.Map;
    import java.util.Set;

    public class Main {
        public static void main(String[] args) {
            List<Map> mylist;
            Set<Map.Entry> myset;
        }
    }

JCimportsRemoveUnused will remove `import java.util.Set;`, which should not be removed.

**Comment by wsdjeg** [comment]
it is due to the dot  `Map.Entry`  ,if change to `MapEntry` ,the import works well ,same as JCimportsAddMissing,I will try to fix it

**Comment by wsdjeg** [comment]
I am not sure if it is due to javaparser , i have read the the src of javacomplete2 ,but only can find this.
```
return JavaParser.parse(new StringReader(content), true);
```

**Comment by artur-shaik** [comment]
Thanks. Need more unit tests...
