### ISSUE TITLE
Neovim support/migration

### ISSUE THREAD

**Issue by brcolow** [artur-shaik/vim-javacomplete2#17]
Hello,

Thanks for the awesome work so far - I am really enjoying this plugin. I was wondering if you have considered supporting [Neovim](https://github.com/neovim/neovim)? Currently when I try and use the plugin in Neovim I get some Could not find function provider#python#call errors. It would be awesome if the plugin was Neovim-capable, especially because it could then be coupled with Shougo's new asynchronous completion plugin [deoplete](https://github.com/Shougo/deoplete.nvim) (which is also in development). This combination could be very powerful and very awesome.

Thanks for your consideration.

**Comment by artur-shaik** [comment]
Hello,
Thanks for using it :smile: 
I tried Neovim, and it works for me, without any issue, can you what version of Neovim are you using?

**Comment by brcolow** [comment]
NVIM 0.0.0-alpha+201506170758 (compiled Jun 18 2015 16:55:46)

**Comment by artur-shaik** [comment]
Looks like neovim python issue.
Can you do this:
```
pip2 install --upgrade neovim
pip3 install --upgrade neovim
```

**Comment by brcolow** [comment]
Still the same =(.

**Comment by artur-shaik** [comment]
When I compiled most recent neovim, I had the same error, but for all python plugins. Running this commands fixed this.

Do you have any other python plugins worked?

**Comment by brcolow** [comment]
Yes, [deoplete](https://github.com/Shougo/deoplete.nvim)

**Comment by Shougo** [comment]
deoplete is for python3 plugin.
It is not python plugin.

You can check other python plugin behavior like UltiSnips.

**Comment by Shougo** [comment]
You can check the python behavior `:py print(2)`.

**Comment by brcolow** [comment]
@Shougo good call! Executing `py print(2)` in Neovim fails with error:

E117: Unknown function: provider#python#Call

Looks like the error is in my Neovim configuration/setup/install.

**Comment by Shougo** [comment]
You should check `provider#python#Prog()` and `provider#python#Error()` result.
I think the pip python path and neovim using python path is different.

**Comment by brcolow** [comment]
Might as well close this issue - it is my problem nothing to do with javacomplete2!
