### ISSUE TITLE
Custom directory

### ISSUE THREAD

**Issue by adelarsq** [artur-shaik/vim-javacomplete2#174]
I want to change the `C:\Users\User1\.javacomplete2` to something like `C:\Users\User1\.vim\javacomplete2`. Is it possible?

**Comment by artur-shaik** [comment]
I think we should add option for this.

**Comment by wsdjeg** [comment]
if your are busy now ,I will do it tonight

**Comment by artur-shaik** [comment]
@wsdjeg, yeah, of cause you can do it.

**Comment by artur-shaik** [comment]
You can use `let g:JavaComplete_BaseDir = path` command to set cache directory.

**Comment by adelarsq** [comment]
Thanks. I'm using like this now:
```
let g:JavaComplete_BaseDir='~/.vim/cache'
```
