### ISSUE TITLE
<esc> on import window

### ISSUE THREAD

**Issue by adelarsq** [artur-shaik/vim-javacomplete2#175]
`<ESC>` on import window (`<Plug>JavaComplete-Imports-Add`) chooses the first option instead of canceling the operation.

**Comment by wsdjeg** [comment]
not issue,you should read the output info,the default selection is 0

**Comment by wsdjeg** [comment]
and  maybe we can provide a g:var to disable this feature,but by default it is 0,because @artur-shaik want add the feature about most used suggestion

**Comment by adelarsq** [comment]
Better an option to disable, since not always the list is updated and in this case we wish to cancel.

**Comment by wsdjeg** [comment]
@adelarsq In the new PR, if you want disable the auto selection of import ,you just need to add this option to you vimrc.
```vim
let g:JavaComplete_Import_Default = -1
```

**Comment by adelarsq** [comment]
Cool! Thanks @wsdjeg. I have added the basedir config also:
```viml
let g:JavaComplete_BaseDir='~/.vim/javacomplete2'
```

**Comment by wsdjeg** [comment]
I think it is better set 
```vim
let g:JavaComplete_BaseDir='~/.cache/javacomplete2'
```
because `.vim` is vim's default user root dir,rather than cache dir
but It does not work now ,because the PR has not been merged

**Comment by adelarsq** [comment]
Yeap. But this is because I prefer all plugin related stuff in ~/.vim directory. I did get your pull request into my branch, so its working for me already. :+1:

**Comment by wsdjeg** [comment]
> I prefer all plugin related stuff in ~/.vim

maybe  you can use ~/.vim/cache/javacomplete2,because many plugin will generate cache file ,not only javacomplete2,use cache directort,will make ~/.vim tidy

**Comment by adelarsq** [comment]
It's better. I already use like this for anothers plugins (ctrlp, undo, etc), but didn't remember. It's working.

**Comment by artur-shaik** [comment]
`let g:JavaComplete_ImportDefault = -1` - should work.
