### ISSUE TITLE
Unable to fetch classes from jar file.

### ISSUE THREAD

**Issue by zabell** [artur-shaik/vim-javacomplete2#177]
Hello, I use javacomplete2 for my android projects, and have done so for a while.
I'm unable to omnicomplete after a recent update, I have a clean install with JDK8.
I've set the following without success.
autocmd FileType java setlocal omnifunc=javacomplete#Complete
let g:JavaComplete_LibsPath = "/opt/android/platforms/android-23/android.jar"

Also I used to have an .vimrc that is run for each project including classpaths.
let $CLASSPATH="/opt/android/platforms/android-23/android.jar:......"

Am i doing something wrong? Worked fine for me for months in 2015.

**Comment by wsdjeg** [comment]
why do not use maven or gradle manager your android project? also can you show me you vimrc and structure of you project?

**Comment by zabell** [comment]
Hey I do use gradle for my projects, but i want the ability to just open anyfile, type import android. <c-x><c-o> and get the list. It has worked for me all of last year. It should just fetch the classes contained in the jar file, but it seams that it doesn't.

**Comment by wsdjeg** [comment]
> anyfile, type import android

any filetype? now the plugin only support java and jsp

**Comment by zabell** [comment]
Sorry, any java file. Only java files should set the omnifunc.
autocmd FileType java setlocal omnifunc=javacomplete#Complete

**Comment by wsdjeg** [comment]
ok;
can you try with this step
open a java file
then 
```
:echo g:JavaComplete_LibsPath
```
show me the output
then 
```
:JCdebugEnableLogs
```
try to complete `import android.`


then show me the out put of 
```
:JCdebugGetLogContent
```

**Comment by wsdjeg** [comment]
by the way ,if your using gradle ,I recommend you do not set g:JavaComplete_LibsPath and $CLASSPATH in your vimrc, just let `./gradlew `manager you classpath

**Comment by zabell** [comment]
```
:echo g:JavaComplete_LibsPath
/opt/android/platforms/android-23/android.jar:.
```

```
import android.
Context: 3
DotExpr: android.
Communicate: -E "android" [s:GetMembers for static]

Communicate: -p "android" [s:DoGetInfoByReflection]
{}
```

**Comment by wsdjeg** [comment]
how about delete `~/.javacomplete2`

**Comment by zabell** [comment]
That solved my problem, was it that the cache is not updated?

**Comment by wsdjeg** [comment]
yes , the cache updateed by the last update time of pom.xml or build.gradle,the plugin will compare it with the time of the cache file

**Comment by wsdjeg** [comment]
https://github.com/artur-shaik/vim-javacomplete2/blob/master/autoload/javacomplete.vim#L170
https://github.com/artur-shaik/vim-javacomplete2/blob/master/autoload/javacomplete.vim#L184
