### ISSUE TITLE
Not all methods are shown

### ISSUE THREAD

**Issue by SageEx** [artur-shaik/vim-javacomplete2#194]
Hi, first of all thanks for this amazing plugin.
I noticed that not all associated methods are shown on `.` trigger.
Specifically, I was using `Socket` class form `java.net` and its `getInputStream()` method was not displayed in the completion menu. I am using deoplete.
Is this a bug or I need some config option ?
![2016-02-06-234510_529x300_scrot](https://cloud.githubusercontent.com/assets/7141867/12868389/b0ab316a-cd2b-11e5-9646-9242f630d649.png)

**Comment by wsdjeg** [comment]
I also using deoplete,never encount this issue,I will test for it after ther new year holiday

**Comment by artur-shaik** [comment]
So, @wsdjeg , could you reproduce it?

**Comment by wsdjeg** [comment]
I will test it tonight,just finish my holiday

**Comment by wsdjeg** [comment]
everthing works well 
![2016-02-13 20-29-53](https://cloud.githubusercontent.com/assets/13142418/13027616/911fef06-d290-11e5-8055-a8d42e2b1d81.png)

**Comment by SageEx** [comment]
@wsdjeg, yea, it seems to work now for me too.
@artur-shaik any idea why it was not working then ? perhaps the completion was too slow ?

**Comment by artur-shaik** [comment]
@SageEx not really sure why you had this issue. I have not played enough with deoplete, but I didn't have this issue when I enable deoplete first time.

**Comment by wsdjeg** [comment]
Q: Is deoplete faster than neocomplete?

A: No.  Deoplete is asynchronous completion plugin.  But it does not
mean that it is faster than neocomplete.  **It can skip the completion if you**
**input the characters too fast.**  I think it is great than the speed.  You
should use faster machine for deoplete.

**Comment by SageEx** [comment]
@wsdjeg @artur-shaik That must be it. Thanks a lot.
