### ISSUE TITLE
[Question] Does this plugin work with Groovy?

### ISSUE THREAD

**Issue by EPadronU** [artur-shaik/vim-javacomplete2#196]
I was testing the plugin with Groovy but it doesn't look to work. I got the following error when I tried to import a Groovy class:

    continuing in function javacomplete#imports#Add
                                                   Error detected while processing function javacomplete#imports#Add..javacomplete#server#Start..<SNR>92_Poll:
    line    2:
    E492: Not an editor command: JavacompletePy << EOPC
    line    3:
    E488: Trailing characters: try:
    Executing QuickFixCmdPre Auto commands for "*vimgrep*"
    autocommand let s:locked = 1

    poll())
    "poll())" [New File]
    Reading ShaDa file "/home/nodxine/.local/share/nvim/shada/main.shada" marks
    Executing BufNewFile Auto commands for "*"
    autocommand call s:SelectJavascript()

    Executing BufNewFile Auto commands for "*"
    autocommand if !did_filetype() && expand("<amatch>") !~ g:ft_ignore_pat | runtime! scripts.vim | endif

    Searching for "scripts.vim" in "/home/nodxine/.config/nvim,/home/nodxine/.config/nvim/plugged/vim-groovy/,/home/nodxine/.config/nvim/plugged/ultisnips/,/home/nodxine/.config/nvim/plugged/YouCompleteMe/,/home/nodxine/.config/nvim/plugged/vim-rooter/,/home/nodxine/.config/nvim/plugged/vim-colors-solarized/,/home/nodxine/.config/nvim/plugged/vim-javacomplete2/,/home/nodxine/.config/nvim/plugged/matchit.zip/,/home/nodxine/.config/nvim/plugged/ctrlp.vim/,/home/nodxine/.config/nvim/plugged/vim-snippets/,/home/nodxine/.config/nvim/plugged/auto-pairs/,/home/nodxine/.config/nvim/plugged/nerdcommenter/,/home/nodxine/.config/nvim/plugged/vim-mundo/,/home/nodxine/.config/nvim/plugged/vim-fugitive/,/home/nodxine/.config/nvim/plugged/vim-git/,/home/nodxine/.config/nvim/plugged/vim-repeat/,/home/nodxine/.config/nvim/plugged/vim-surround/,/home/nodxine/.config/nvim/plugged/vim-airline/,/home/nodxine/.config/nvim/plugged/vim-airline-themes/,/home/nodxine/.config/nvim/plugged/groovyindent/,/home/nodxine/.config/nvim/plugged/re
    Searching for "/home/nodxine/.config/nvim/scripts.vim"
    Searching for "/home/nodxine/.config/nvim/plugged/vim-groovy/scripts.vim"
    Searching for "/home/nodxine/.config/nvim/plugged/ultisnips/scripts.vim"
    Searching for "/home/nodxine/.config/nvim/plugged/YouCompleteMe/scripts.vim"
    Searching for "/home/nodxine/.config/nvim/plugged/vim-rooter/scripts.vim"
    Searching for "/home/nodxine/.config/nvim/plugged/vim-colors-solarized/scripts.vim"
    Searching for "/home/nodxine/.config/nvim/plugged/vim-javacomplete2/scripts.vim"
    Searching for "/home/nodxine/.config/nvim/plugged/matchit.zip/scripts.vim"
    Searching for "/home/nodxine/.config/nvim/plugged/ctrlp.vim/scripts.vim"
    Searching for "/home/nodxine/.config/nvim/plugged/vim-snippets/scripts.vim"
    Searching for "/home/nodxine/.config/nvim/plugged/auto-pairs/scripts.vim"
    Searching for "/home/nodxine/.config/nvim/plugged/nerdcommenter/scripts.vim"
    Searching for "/home/nodxine/.config/nvim/plugged/vim-mundo/scripts.vim"
    Searching for "/home/nodxine/.config/nvim/plugged/vim-fugitive/scripts.vim"
    Searching for "/home/nodxine/.config/nvim/plugged/vim-git/scripts.vim"
    Searching for "/home/nodxine/.config/nvim/plugged/vim-repeat/scripts.vim"
    Searching for "/home/nodxine/.config/nvim/plugged/vim-surround/scripts.vim"
    Searching for "/home/nodxine/.config/nvim/plugged/vim-airline/scripts.vim"
    Searching for "/home/nodxine/.config/nvim/plugged/vim-airline-themes/scripts.vim"
    Searching for "/home/nodxine/.config/nvim/plugged/groovyindent/scripts.vim"
    Searching for "/home/nodxine/.config/nvim/plugged/restore_view.vim/scripts.vim"
    Searching for "/etc/xdg/nvim/scripts.vim"
    Searching for "/home/nodxine/.local/share/nvim/site/scripts.vim"
    Searching for "/usr/local/share/nvim/site/scripts.vim"
    Searching for "/usr/share/nvim/site/scripts.vim"
    Searching for "/usr/share/nvim/runtime/scripts.vim"
    chdir(/home/nodxine/InProgress/playground)
    chdir(/usr/share/nvim/runtime)
    chdir(/home/nodxine/InProgress/playground)
    line 0: sourcing "/usr/share/nvim/runtime/scripts.vim"
    finished sourcing /usr/share/nvim/runtime/scripts.vim
    continuing in BufNewFile Auto commands for "*"
    Searching for "/usr/share/nvim/site/after/scripts.vim"
    Searching for "/usr/local/share/nvim/site/after/scripts.vim"
    Searching for "/home/nodxine/.local/share/nvim/site/after/scripts.vim"
    Searching for "/etc/xdg/nvim/after/scripts.vim"
    Searching for "/home/nodxine/.config/nvim/plugged/ultisnips/after/scripts.vim"
    Searching for "/home/nodxine/.config/nvim/after/scripts.vim"
    Executing BufNewFile Auto commands for "*"
    autocommand if getline(1) =~ '^\(commit\|tree\|object\) \x\{40\}\>\|^tag \S\+$' |   set ft=git | endif

    autocommand if getline(1) =~ '^From \x\{40\} Mon Sep 17 00:00:00 2001$' |   set filetype=gitsendemail | endif

    autocommand if !did_filetype() && expand("<amatch>") !~ g:ft_ignore_pat    && (getline(1) =~ '^#' || getline(2) =~ '^#' || getline(3) =~ '^#'^I|| getline(4) =~ '^#' || getline(5) =~ '^#') |   setf conf | endif

    Executing BufNewFile Auto commands for "*"
    autocommand call fugitive#detect(expand('%:p'))

    Executing BufNewFile Auto commands for "*"
    autocommand if has_key(s:temp_files,s:cpath(expand('<afile>:p'))) |   let b:git_dir = s:temp_files[s:cpath(expand('<afile>:p'))].dir |   let b:git_type = 'temp' |   let b:git_args = s:temp_files[s:cpath(expand('<afile>:p'))].args |   call fugitive#detect(expand('<afile>:p')) |   setlocal bufhidden=delete nobuflisted |   nnoremap <buffer> <silent> q    :<C-U>bdelete<CR>| endif

    Cannot open file "poll())"
    Executing QuickFixCmdPost Auto commands for "*vimgrep*"
    autocommand let s:locked = 0

    line    4:
    E480: No match: command("let value = '%d'" % bridgeState
    line    5:
    E492: Not an editor command: except:
    line    6:
    E488: Trailing characters:   # we'll get here if the bridgeState variable was not defined or if it's None.
    line    7:
    E488: Trailing characters:   # In this case we stop the processing and return the default 0 value.
    line    8:
    E492: Not an editor command:   pass
    line    9:
    E492: Not an editor command: EOPC

My `g:JavaComplete_LibsPath`:

    let g:JavaComplete_LibsPath = '/home/nodxine/.sdkman/candidates/groovy/current/lib/groovy-swing-2.4.5.jar:/home/nodxine/.sdkman/candidates/groovy/current/lib/jsp-api-2.0.jar:/home/nodxine/.sdkman/candidates/groovy/current/lib/commons-cli-1.2.jar:/home/nodxine/.sdkman/candidates/groovy/current/lib/groovy-bsf-2.4.5.jar:/home/nodxine/.sdkman/candidates/groovy/current/lib/ant-antlr-1.9.4.jar:/home/nodxine/.sdkman/candidates/groovy/current/lib/groovy-xml-2.4.5.jar:/home/nodxine/.sdkman/candidates/groovy/current/lib/ant-launcher-1.9.4.jar:/home/nodxine/.sdkman/candidates/groovy/current/lib/groovy-templates-2.4.5.jar:/home/nodxine/.sdkman/candidates/groovy/current/lib/groovy-json-2.4.5.jar:/home/nodxine/.sdkman/candidates/groovy/current/lib/bsf-2.4.0.jar:/home/nodxine/.sdkman/candidates/groovy/current/lib/gpars-1.2.1.jar:/home/nodxine/.sdkman/candidates/groovy/current/lib/groovy-ant-2.4.5.jar:/home/nodxine/.sdkman/candidates/groovy/current/lib/groovy-jmx-2.4.5.jar:/home/nodxine/.sdkman/candidates/groovy/current/lib/multiverse-core-0.7.0.jar:/home/nodxine/.sdkman/candidates/groovy/current/lib/junit-4.12.jar:/home/nodxine/.sdkman/candidates/groovy/current/lib/jsr166y-1.7.0.jar:/home/nodxine/.sdkman/candidates/groovy/current/lib/ant-junit-1.9.4.jar:/home/nodxine/.sdkman/candidates/groovy/current/lib/groovy-test-2.4.5.jar:/home/nodxine/.sdkman/candidates/groovy/current/lib/groovy-testng-2.4.5.jar:/home/nodxine/.sdkman/candidates/groovy/current/lib/jansi-1.11.jar:/home/nodxine/.sdkman/candidates/groovy/current/lib/xstream-1.4.7.jar:/home/nodxine/.sdkman/candidates/groovy/current/lib/groovy-console-2.4.5.jar:/home/nodxine/.sdkman/candidates/groovy/current/lib/ivy-2.4.0.jar:/home/nodxine/.sdkman/candidates/groovy/current/lib/hamcrest-core-1.3.jar:/home/nodxine/.sdkman/candidates/groovy/current/lib/groovy-servlet-2.4.5.jar:/home/nodxine/.sdkman/candidates/groovy/current/lib/servlet-api-2.4.jar:/home/nodxine/.sdkman/candidates/groovy/current/lib/jline-2.12.jar:/home/nodxine/.sdkman/candidates/groovy/current/lib/ant-1.9.4.jar:/home/nodxine/.sdkman/candidates/groovy/current/lib/groovy-groovysh-2.4.5.jar:/home/nodxine/.sdkman/candidates/groovy/current/lib/testng-6.8.13.jar:/home/nodxine/.sdkman/candidates/groovy/current/lib/groovy-jsr223-2.4.5.jar:/home/nodxine/.sdkman/candidates/groovy/current/lib/groovy-2.4.5.jar:/home/nodxine/.sdkman/candidates/groovy/current/lib/groovy-docgenerator-2.4.5.jar:/home/nodxine/.sdkman/candidates/groovy/current/lib/xmlpull-1.1.3.1.jar:/home/nodxine/.sdkman/candidates/groovy/current/lib/groovy-nio-2.4.5.jar:/home/nodxine/.sdkman/candidates/groovy/current/lib/jcommander-1.47.jar:/home/nodxine/.sdkman/candidates/groovy/current/lib/commons-logging-1.2.jar:/home/nodxine/.sdkman/candidates/groovy/current/lib/groovy-sql-2.4.5.jar:/home/nodxine/.sdkman/candidates/groovy/current/lib/groovy-groovydoc-2.4.5.jar:/home/nodxine/.sdkman/candidates/groovy/current/lib/qdox-1.12.1.jar'

**Comment by DonnieWest** [comment]
It doesn't work, this is for Java only

**Comment by EPadronU** [comment]
Thank you, @DonnieWest. I was curious about the possibility. Cheers.
