### ISSUE TITLE
other jvm-based language completion?

### ISSUE THREAD

**Issue by richox** [artur-shaik/vim-javacomplete2#197]
there is no scala completion for vim yet, it would be a great improvement for vim if there was a scala completion plugin.
I'm not familiar with vim-scripts, but I think javavi can be a common backend for all jvm-based languages.

**Comment by EPadronU** [comment]
+1

**Comment by adelarsq** [comment]
@artur-shaik what about put javavi on his own repository? So we can improve and anothers projects can use the library.

**Comment by artur-shaik** [comment]
@adelarsq I'm not really disposed to break project, because javavi still contains java source parser, and viml code still can be used for another languages.
But, still we need more investigation on it.

By the way, can we compose list of existing parsers of other languages?

**Comment by wsdjeg** [comment]
I do not think split javavi is a good idea.because javavi also need javaparser.and I do not think people who use vim like `git submodel`.that is why I do not use ycm,too many third_part lib

**Comment by adelarsq** [comment]
@wsdjeg Good point. I was thinking about use submodules.

**Comment by adelarsq** [comment]
@artur-shaik Actually I don't know about parsers for anothers languages. For now what languages will be desired between Scala, Groovy, Clojure, Kotlin, Ceylon, Xtend, Fantom and X10 (or anothers)?

**Comment by adelarsq** [comment]
@artur-shaik what about use [ANTLR](https://github.com/antlr/antlr4) and [grammars-v4](https://github.com/antlr/grammars-v4) for the parsing?

**Comment by artur-shaik** [comment]
@adelarsq thank you for information, may be it really make sence to use this tools, just need more investigation on it.

**Comment by mattn** [comment]
If you use clojure, I suggest to use [neoclojure](https://github.com/ujihisa/neoclojure.vim)

**Comment by johnzeng** [comment]
If it's only grammar parsing , maybe we can try something like compiler plugin. [writing scala compiler plugin](http://www.scala-lang.org/old/node/140) , this can gives you a compiler based completion just like clang.

**Comment by Misfit-John** [comment]
I am writing a scala compiler plugin that may help to do completion.

https://github.com/Misfit-John/Scala-completion-Base

but I don't know how to integrate it with vim.... anyway, this is still a base , it can only print out members in a very tricky way.

**Comment by richox** [comment]
@Misfit-John can you get completion from source code which contains syntax errors?

**Comment by Misfit-John** [comment]
@richox What do you mean by syntax error? Almost all of the compiler base completion tools don't allow syntax error so the compiler can make you a right completion. If you are saying that you are using some special scala syntax, you can make a plugin to tell compiler what does them means so compiler can understand your code and give you right completion.

**Comment by DonnieWest** [comment]
@Misfit-John most completion tools feature a "loose parser" that is forgiving of errors so you still get completions when some of your code is wrong. Ecj is an example and vim-javacomplete2 here has a strict parser combined with a Vimscript loose parser to gather completions for in progress code

**Comment by Misfit-John** [comment]
@DonnieWest I can understand that, but this plugin is based on a scala compiler, it's kind of hacking, so you can't expect it to be a loose parser because I am not rewriting a parser. I can understand that when you are typing codes, your file will be syntex error so my first step is just to make sure that when you type a "." after a symbol, you can get the member list of this symbol.  Basically your file is syntax correct before you type the dot and so you can get the member list, this will be enough at current stage.

**Comment by artur-shaik** [comment]
With LSP introduction I think this is not relevant anymore.
