### ISSUE TITLE
#193 not fixed:(

### ISSUE THREAD

**Issue by richox** [artur-shaik/vim-javacomplete2#198]
#193 not fixed:(

**Comment by wsdjeg** [comment]
please do not open issue like this,if the #193 is not been fixed, I think @artur-shaik will reopen it.

**Comment by richox** [comment]
@wsdjeg sorry but i'm not sure he can get notified

**Comment by wsdjeg** [comment]
you can use `@`

**Comment by artur-shaik** [comment]
Yeah, @wsdjeg is right. I have notification for every message.
