### ISSUE TITLE
Error on javacomplete#StartServer

### ISSUE THREAD

**Issue by PatrickHail** [artur-shaik/vim-javacomplete2#20]
EDIT: I'm using vim 7.4, and globpath has the signature: globpath({path}, {expr} [, {flag}])

Is there a version of vim where globpath has 4 args?

EDIT2: I checked vim --version and I had 7.4, but it was compiled in 2013. Compiled from source and this works now.

Starting vim with vim-android. :call javacomplete#StartServer() results in the following error messages:

```
Error detected while processing function javacomplete#StartServer..<SNR>90_GetClassPath..<SNR>90_GetExtraPath..<SNR
>90_ExpandPathToJars:
line    6:
E118: Too many arguments for function: globpath
E15: Invalid expression: globpath(a:path, "*", 1, 1)
line    7:
E121: Undefined variable: files
E15: Invalid expression: files
Error detected while processing function javacomplete#StartServer..<SNR>90_GetClassPath..<SNR>90_GetJavaviClassPath
:
line    6:
E118: Too many arguments for function: globpath
E116: Invalid arguments for function empty(globpath(javaviDir. 'target/classes', '**/*.class', 1, 1))
E15: Invalid expression: !empty(globpath(javaviDir. 'target/classes', '**/*.class', 1, 1))
```

Output of :call javacomplete#GetLogContent()
```
JavaComplete_Home: /home/patrick/.vim/bundle/vim-javacomplete2
Default sources: 
Restart server
Classpath: 0:/home/patrick/.vim/bundle/vim-javacomplete2/libs/javaparser.jar::/home/patrick/android-sdks/platforms/android-22/android.jar:/home/patrick/android-sdks/platforms/android-22/android.jar:0
Restart server
Classpath: 0:/home/patrick/.vim/bundle/vim-javacomplete2/libs/javaparser.jar::/home/patrick/android-sdks/platforms/android-22/android.jar:/home/patrick/android-sdks/platforms/android-22/android.jar:0
Restart server
Classpath: 0:/home/patrick/.vim/bundle/vim-javacomplete2/libs/javaparser.jar::/home/patrick/android-sdks/platforms/android-22/android.jar:/home/patrick/android-sdks/platforms/android-22/android.jar:0
```

**Comment by artur-shaik** [comment]
Looks like we should write exact version of Vim in requirements.

**Comment by artur-shaik** [comment]
Strange, but I have 7.4 (2013 Aug 10) and I have `globpath` with 4 arguments.
Now checked some old systems, there is Vim 7.3 (2010 Aug 15). This version has `globpath` with  3 arguments.
Are you sure that you had 7.4 before compilation?

**Comment by Shougo** [comment]
Yes, @PatrickHail 's Vim is very old.
The globpath 4th arguments is added in Vim 7.4.

**Comment by mattn** [comment]
FYI, it's easy to do behave using `split(globpath(x,y,z), "\n")` for both. the lines given probably will not be longer enough to worry about. However, I don't mean that we should support legacies.

**Comment by tokuhirom** [comment]
4 argument globpath is introduced at 7.4.279.
https://groups.google.com/forum/#!searchin/vim_dev/globpath$204/vim_dev/r3zuf8emme0/fA75zp6vbXQJ

CentOS 7 bundled 7.4.160. So, latest operation system versions are bundled vim, that doesn't have 4 arguments globpath.

**Comment by artur-shaik** [comment]
@tokuhirom thank you for research. I added workaround that @mattn suggested.

@tokuhirom can you check it?

**Comment by tokuhirom** [comment]
Thanks! It works fine. But I got another error...
```
Error detected while processing function javacomplete#Complete..javacomplete#Start
Server..<SNR>156_GetClassPath:
line   27:
E117: Unknown function: exepath
```

exepath function was introduced at vim 7.4.235.

**Comment by mattn** [comment]
It's possible to implement exepath on vim script.

https://github.com/vim-jp/vital.vim/blob/386a15ed7784c718220c23be6c78498463d9b2a6/autoload/vital/__latest__/System/Filepath.vim#L59-L88

but I suggest to just  remove this line.
```
call s:Info(exepath(java))
```
https://github.com/artur-shaik/vim-javacomplete2/blob/master/autoload/javacomplete.vim#L2136

**Comment by artur-shaik** [comment]
Done.

**Comment by tokuhirom** [comment]
orz.
```
Error detected while processing function javacomplete#Complete..javacomplete#Start
Server..<SNR>157_ExpandAllPaths:
line    2:
E117: Unknown function: uniq
```

**Comment by mattn** [comment]
https://gist.github.com/mattn/641c151b4a8875592eca

**Comment by artur-shaik** [comment]
@mattn thank you.
@tokuhirom please, try again.

**Comment by tokuhirom** [comment]
Thanks! it works!
