### ISSUE TITLE
completion for inner class not work

### ISSUE THREAD

**Issue by richox** [artur-shaik/vim-javacomplete2#200]
compress for `org.apache.hadoop.mapreduce.Mapper.Context` OK when using `Mapper$Context` as type name:
http://pan.baidu.com/s/1i4hl29f

but not work when using `Context` as type name:
http://pan.baidu.com/s/1i4weIf7

**Comment by artur-shaik** [comment]
Hm, may be for completion to work here, you need to add static import of `org.apache.hadoop.mapreduce.Mapper.Context`?

**Comment by richox** [comment]
@artur-shaik we are using `Context` inside `Mapper` class so we don't need to import it. the second case can be successfully compiled.

**Comment by artur-shaik** [comment]
Yeah, sorry... Here you are right. Will see what I can do...

**Comment by wsdjeg** [comment]
@richox `github.com` support upload `*.png` file,so you can just upload your files here ,it will be easy for us to read the issue.also you can write you example code here.

**Comment by wsdjeg** [comment]
and if you have import `Mapper`,I think completion after `Mapper.Context` works well

**Comment by richox** [comment]
@artur-shaik uploading image to github is banned in China:(

**Comment by wsdjeg** [comment]
I am in China,I can use this feature
![qq 20160112133605](https://cloud.githubusercontent.com/assets/13142418/13167232/3a069faa-d70c-11e5-875d-13f83328a088.png)

**Comment by wsdjeg** [comment]
@richox can you show me some example whe text,please do not use image.

**Comment by artur-shaik** [comment]
Can you try again with latest commit, please...
