### ISSUE TITLE
Avoid conflict of configuration file.

### ISSUE THREAD

**Issue by wsdjeg** [artur-shaik/vim-javacomplete2#202]
@artur-shaik 
now the plugin support eclipse's .classpath maven's pom.xml and gralde's build.gradle.if a project has more than one configuration file.we should provid a g:var which can  control the priority order  of loadding the files.
for example by default it is g:JavaComplete_ClassPathLoaddingOrder = ['eclipse','maven','gradle']
and for gradle, there should be a g:var for disable build script `./gradlew` and let user just use `gradle` instead of `./gradlew` or `.\gradlew.bat`.
I'd like to open a PR for this feature.
and as @Shougo says the plugin freeze his vim/neovim when he open his android project, I think maybe it is due to the conflict of `gradle` and the build script. I will try to fix it.

**Comment by artur-shaik** [comment]
Sounds reasonable.

On 02-21 (19:40), Wang Shidong wrote:
>    [1]@artur-shaik
>    now the plugin support eclipse's .classpath maven's pom.xml and gralde's
>    build.gradle.if a project has more than one configuration file.we should
>    provid a g:var which can control the priority order of loadding the files.
>    for example by default it is g:JavaComplete_ClassPathLoaddingOrder =
>    ['eclipse','maven','gradle']
>    and for gradle, there should be a g:var for disable build script ./gradlew
>    and let user just use gradle instead of ./gradlew or .\gradlew.bat.
>    I'd like to open a PR for this feature.
>    and as [2]@Shougo says the plugin freeze his vim/neovim when he open his
>    android project, I think maybe it is due to the conflict of gradle and the
>    build script. I will try to fix it.
> 
>    —
>    Reply to this email directly or [3]view it on GitHub.
> 
>    Reverse link: [4]unknown
> 
> References
> 
>    Visible links
>    1. https://github.com/artur-shaik
>    2. https://github.com/Shougo
>    3. https://github.com/artur-shaik/vim-javacomplete2/issues/202
>    4. https://github.com/artur-shaik/vim-javacomplete2/issues/202

-- 
Best regards,
Artur Shaikhullin

**Comment by wsdjeg** [comment]
here is how I will do for this PR,
```vim
fu! s:eclipse()
    echo 'Use_eclipse'
endf

fu! s:maven()
    echo 'Use_maven'
endf

fu! s:gradle()
    echo 'Use_gradle'
endf

fu! s:test()
for key in [ 'gradle' ,'aa','eclipse', 'maven']
    try
        exec "call s:".key."()"
    catch
    endtry
endfor
endf

call s:test()
```

the out put is
```
Use_gradle                                                                                                                                             
Use_eclipse                                                                                                                                            
Use_maven
```
I just let the functions be called in order
