### ISSUE TITLE
completion for class name sort in alphabetic order?

### ISSUE THREAD

**Issue by richox** [artur-shaik/vim-javacomplete2#205]
OutputSimilar.sort now sorts with length of class name, which (i think) is ugly:(

**Comment by wsdjeg** [comment]
I think the sortting feature has not been implemented,but if you use deoplete,it will remanber last one you seletct.for JC2 now this feature is in TODO list.

**Comment by artur-shaik** [comment]
Ok, made it alphabetically ordered for now. Looks better I think, too.
