### ISSUE TITLE
Order of imports should be preserved, or follow Eclipse/NetBeans

### ISSUE THREAD

**Issue by andrewbenton** [artur-shaik/vim-javacomplete2#207]
At the moment, all spacing in the import statement section will be removed and they are lumped together and sorted alphabetically without looking at the first token of the import.  This results in the statements being arranged in odd ways.

**Comment by wsdjeg** [comment]
are you means split them with space,and put class from same jar together?

**Comment by andrewbenton** [comment]
If possible, then putting classes with the same jar together would be fantastic.  I was more referring to this:

Say that you have some imports organized as such:

java```
package A;

import java.util.List;

import com.google.gson.JsonObject;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
```

This will currently be reorganized to show:

java```
package A;

import com.google.gson.JsonObject
import java.util.List;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
```

However, Eclipse, Netbeans, and most FOSS that I've seen will organize sections into java, javax, com, org, and then other imports, and sort based on their names, like in the first example.  

I personally also like keeping imports separated by the Jar that they are from as well, but I haven't seen that as much.

**Comment by wsdjeg** [comment]
we could provide a way like this:
1. begin with `java.`
2. begin with `javax.`
3. begin with `com.`
4. begin with `org.`
5. begin with `other`
and in each one,we separated them by same jars, and put space between 1 - 5

**Comment by brcolow** [comment]
It would also be nice to have a list option where we can set the order, something like:

`let g:JavaCompleteImportOrder = ['java.', 'javax.', 'com.', 'org.', '.net']`

for customization of import order. Not sure if this would encompass all possible use-cases, though.

**Comment by wsdjeg** [comment]
yeal ,just same as `g:JavaComplete_ClasspathGenerationOrder`

**Comment by wsdjeg** [comment]
@andrewbenton @brcolow I have implement this feature ,can you have a try?

**Comment by artur-shaik** [comment]
Ok, now we have option to switch ordering by package names, or by jar files.

**Comment by wsdjeg** [comment]
great work,thanks

**Comment by artur-shaik** [comment]
@wsdjeg yeah, and those java code still requires huge refactoring. :scream:

**Comment by wsdjeg** [comment]
yeah,it is an hard work.by the way ,do you use irc?

**Comment by artur-shaik** [comment]
@wsdjeg yes, sometimes.

**Comment by wsdjeg** [comment]
now I am using irssi in neovim'terminal buffer,it look really great,and support vim plugin.

**Comment by artur-shaik** [comment]
Cool... )
On 03-11 (05:11), Wang Shidong wrote:
>    now I am using irssi in neovim'terminal buffer,it look really great,and
>    support vim plugin.
> 
>    —
>    Reply to this email directly or [1]view it on GitHub.
> 
>    Reverse link: [2]unknown
> 
> References
> 
>    Visible links
>    1. https://github.com/artur-shaik/vim-javacomplete2/issues/207#issuecomment-195357265
>    2. https://github.com/artur-shaik/vim-javacomplete2/issues/207#issuecomment-195357265

-- 
Best regards,
Artur Shaikhullin
