### ISSUE TITLE
Do not ask to import already fulfilled types

### ISSUE THREAD

**Issue by andrewbenton** [artur-shaik/vim-javacomplete2#210]
As an example, if you have:

```java
package a;

public class Main {
    public static void main(String[] args) {
        StringBuilder sb = new StringBuilder();
    }
}
```

Then when you run JCimportAddMissing, you will still be prompted to choose between importing `java.lang.StringBuilder` or `com.sun.xml.internal.ws.client.sei.ResponseBuilder$StringBuilder` or `com.sun.xml.internal.ws.server.sei.EndpointArgumentsBuilder$StringBuilder`.  These implicitly imported objects shouldn't need to be checked each time.

**Comment by wsdjeg** [comment]
I do not know about that two classes ,but I think if it is static inner class ,it should not be remove;
wu should not miss any possible class

**Comment by andrewbenton** [comment]
I just saw the issue that you filed.  Perhaps we can add an option to avoid asking about classes that seem to already be imported?  I find having to reaffirm my use of java.lang.* to be a nuisance more often than a help.

**Comment by wsdjeg** [comment]
no,it is not a good idea,because if you has wrong imports in your file,you will not get any suggestion,for example
you hava `import java.util.Date;`  but you want `java.sql.Date`,if you add this option ,you will not get suggestion,and `java.lang.*` is hidden  import ,you do not need add to your file,

**Comment by wsdjeg** [comment]
for example
```
class A {
  String a ;
}
```
if you add this option ,you will not get other class named String,but if I want `com.wsdjeg.String` how do I get it?

**Comment by andrewbenton** [comment]
I understand what you are saying, but for most people most times, they will want to avoid that behavior.  Having an option, even if it isn't the default, that allows you to opt out of that behavior would be useful.  It would not modify the default behavior.

**Comment by wsdjeg** [comment]
ok but I think another command is need,
`JCimportsAddMissing` do this case,
`JCimportsRegenerate` do just like what `JCimportsAddMissing` do now

**Comment by wsdjeg** [comment]
and maybe it not good to change `JCimportsAddMissing` behavior,just add an option or new command

**Comment by artur-shaik** [comment]
I think, we can create editable global variable with some popular `java.lang` classes, that will work like exceptions for import (include them automatically).

**Comment by wsdjeg** [comment]
@artur-shaik do you mean a global dict?such as
{
 'String':'java.lang.String',
 'Object':'java.lang.Object'
}
if the class name is in the keys of such dict,just use the value of the key as the full class name.

**Comment by artur-shaik** [comment]
Yeah, something like this...
On 03-02 (23:32), Wang Shidong wrote:
>    [1]@artur-shaik do you mean a global dict?such as
>    {
>    'String':'java.lang.String',
>    'Object':'java.lang.Object'
>    }
>    if the class name is in the keys of such dict,just use the value of the
>    key as the full class name.
> 
>    —
>    Reply to this email directly or [2]view it on GitHub.
> 
>    Reverse link: [3]unknown
> 
> References
> 
>    Visible links
>    1. https://github.com/artur-shaik
>    2. https://github.com/artur-shaik/vim-javacomplete2/issues/210#issuecomment-191630335
>    3. https://github.com/artur-shaik/vim-javacomplete2/issues/210#issuecomment-191630335

-- 
Best regards,
Artur Shaikhullin

**Comment by wsdjeg** [comment]
I think I can implement it ,but by default,it should be empty dict,what do you think?

**Comment by artur-shaik** [comment]
I think, at least `String` and `Object` should be there by default. May
be some body will give some more suggestions.

On 03-02 (23:59), Wang Shidong wrote:
>    I think I can implement it ,but by default,it should be empty dict,what do
>    you think?
> 
>    —
>    Reply to this email directly or [1]view it on GitHub.
> 
>    Reverse link: [2]unknown
> 
> References
> 
>    Visible links
>    1. https://github.com/artur-shaik/vim-javacomplete2/issues/210#issuecomment-191642518
>    2. https://github.com/artur-shaik/vim-javacomplete2/issues/210#issuecomment-191642518

-- 
Best regards,
Artur Shaikhullin

**Comment by wsdjeg** [comment]
I have another idea about this feature,for example `let g:JavaComplete_test=['java.lang.']`,if the class can be found in such package,just use this as the full name.it will be more faster than filter

**Comment by artur-shaik** [comment]
Yeah, I think list is better for this.

On 03-03 (00:09), Wang Shidong wrote:
>    I have another idea about this feature,for example let
>    g:JavaComplete_test=['java.lang.'],if the class can be found in such
>    package,just use this as the full name.it will be more faster than filter
> 
>    —
>    Reply to this email directly or [1]view it on GitHub.
> 
>    Reverse link: [2]unknown
> 
> References
> 
>    Visible links
>    1. https://github.com/artur-shaik/vim-javacomplete2/issues/210#issuecomment-191644579
>    2. https://github.com/artur-shaik/vim-javacomplete2/issues/210#issuecomment-191644579

-- 
Best regards,
Artur Shaikhullin

**Comment by wsdjeg** [comment]
@artur-shaik I have implement this feature,anyone want to skip `String` when he use addimports function,he just need to add `java.lang.String` to `g:JavaComplete_RegularClasses`.now only `JCimportAdd` add `JCimportAddI` works well, I will do more for `JCimportsAddMissing`.

**Comment by wsdjeg** [comment]
I have implement `JCimportsAddMissing` skipping classes ,anyone can test it?

**Comment by artur-shaik** [comment]
@wsdjeg working nice. I just made population `s:RegularClassesDict` with choosed option. This give us ability not to ask for candidats next time we adding import for the same class name.

So, now we need find way to make it persistent, and have ability to clear dictionary if we made mistake.

**Comment by artur-shaik** [comment]
Ok, added new command that will use known options.

If you need to change option just use old command.

Now we need to permanently save this list for project.

**Comment by wsdjeg** [comment]
>This give us ability not to ask for candidats next time we adding import for the same class name.

that is just what i thinked tonight

**Comment by wsdjeg** [comment]
>Ok, added new command that will use known options.If you need to change option just use old command.Now we need to permanently save this list for project.

I found we usually have same idea ~_~

**Comment by artur-shaik** [comment]
@wsdjeg that's great :smile:

**Comment by wsdjeg** [comment]
I just got off the plane, about three days of travel.But I took the computer with me.

**Comment by artur-shaik** [comment]
Good, have a nice trip. And turn off your computer, enjoy your travel :smile:

**Comment by wsdjeg** [comment]
@artur-shaik 
I think meybe here we should use smartAdd
https://github.com/artur-shaik/vim-javacomplete2/blob/fbea3577745eb865d91bc5fb53944e5de9eb0cbb/autoload/javacomplete.vim#L142
 `call javacomplete#imports#Add(1)`

**Comment by wsdjeg** [comment]
I have a little confused on this logic at begin,but after after a little thought.
```vim
  if a:0 == 0 || !a:1 || index(keys(s:RegularClassesDict), classname) < 0
    let response = javacomplete#server#Communicate("-class-packages", classname, 'Filter packages to add import')
    if response =~ '^['
      let result = eval(response)
      let import = s:ChooseImportOption(result, classname)

      if !empty(import)
        call s:AddImport(import)
        call s:SortImports()
      endif
    endif
  else
    call s:AddImport(s:RegularClassesDict[classname])
    call s:SortImports()
  endif
```
This means if we want to use the dict,we need `a:0 == 0 && !a:1 && index(keys(s:RegularClassesDict), classname) < 0`

so the above code is same as
```vim
  if  a:1 && index(keys(s:RegularClassesDict), classname)>= 0
     call s:AddImport(s:RegularClassesDict[classname])
     call s:SortImports()
  else
    let response = javacomplete#server#Communicate("-class-packages", classname, 'Filter packages to add import')
    if response =~ '^['
      let result = eval(response)
      let import = s:ChooseImportOption(result, classname)

      if !empty(import)
        call s:AddImport(import)
        call s:SortImports()
      endif
    endif
  endif

```

**Comment by artur-shaik** [comment]
@wsdjeg , yes, you're right...
