### ISSUE TITLE
Choosing between imports provides no escape

### ISSUE THREAD

**Issue by andrewbenton** [artur-shaik/vim-javacomplete2#211]
While 90% of the time when importing you are going to want to choose one of the available options, there should also be an escape available so that none of the provided options are chosen for an import.

**Comment by wsdjeg** [comment]
can you show me an example,I can not understand.

**Comment by andrewbenton** [comment]
When you are given the list of imports to choose from, whether you are using importAdd or importAddMissing, you are forced to make a choice for one import.  There should be a way to skip an import if you don't want to take any of the choices.   

You can actually do this by entering invalid input such as `-1`, which I only found after playing around with it.

**Comment by wsdjeg** [comment]
> You can actually do this by entering invalid input such as -1,

this feature has been implemented ,please see readme

**Comment by wsdjeg** [comment]
let g:JavaComplete_ImportDefault = 0 - the default selection of import options. By default it is 0, which means automatically select first one. To make nothing on default set -1.

**Comment by wsdjeg** [comment]
@andrewbenton I have implement this feature,you can use `g:JavaComplete_RegularClasses` set some classes that you already know its full name
