### ISSUE TITLE
Sort import suggestions by likelyhood of use.

### ISSUE THREAD

**Issue by andrewbenton** [artur-shaik/vim-javacomplete2#212]
There's no empirical way to do this, however the import order could probably be improved by sorting first based on non-static over static, then on java libraries vs others, then alphabetically.  Not really necessary, but certainly a 'nice to have'.

**Comment by wsdjeg** [comment]
@andrewbenton do you mean put the most use imports at beginning,if so,you can see TODO list,it will be implement,but need time.
@artur-shaik 
   to implement this feature,we need `Cross session cache` to remamber what is the most used imports, and an backup command is needed
   for example
   `JCsaveImportsOrderCache ~/path/to/your_back_up_dir`

ordercache:
```
{'projectA':{
         'String':['most select class full name','second most select class full name'],
         'Date':[]
    },
  'projectB':{
   }
}
```
for maven project the projectA key could be the pom_path

**Comment by andrewbenton** [comment]
I'm not referring to putting the most used imports at the beginning, though I'm looking forward to that.  As nice as a frequency based sort would be, I'm suggesting that the sort could be based on some loose model of what the typical Java programmer uses.

**Comment by wsdjeg** [comment]
I am sorry ,I am not very family with different type java programe,so what is the `based on some loose model of what the typical Java programmer uses` rally mean?

**Comment by artur-shaik** [comment]
Made some changes. What do you think? Order based on `JavaComplete_ImportOrder` list. Static moved to the end. Still without 'most used', but eliminates those mess we have now.

![screen7](https://cloud.githubusercontent.com/assets/4862907/13529976/24330090-e249-11e5-82a7-e2c47770849e.jpeg)

**Comment by wsdjeg** [comment]
nice!!
