### ISSUE TITLE
Change vim-plug example to load only on java files

### ISSUE THREAD

**Issue by malteneuss** [artur-shaik/vim-javacomplete2#215]
Would it be a problem to change the vim-plug installation example from
`Plug 'artur-shaik/vim-javacomplete2`
to
`Plug 'artur-shaik/vim-javacomplete2, { 'for': 'java' }`
so that this java-plugin is really only loaded when opening a java file?

**Comment by adelarsq** [comment]
Works. But I don't see any benefits to do this.

**Comment by wsdjeg** [comment]
no need lazy load.because this plugin do not autoload anything when vim startup.

**Comment by malteneuss** [comment]
I see. Then i consider this issue closed.
