### ISSUE TITLE
Kill javac process on vim exit

### ISSUE THREAD

**Issue by malteneuss** [artur-shaik/vim-javacomplete2#217]
When opening a java file in neovim, a javac compiler process is created to generate autocompletion information, which apparantly takes quite a long time to complete on a bigger java project.
I noticed a java compiler process started at each vim opening but not terminated when vim is closed. When i close and reopen neovim several times in a short time period, e.g. to test some vim configuration, this quickly fills my entire system's RAM memory.

![javacomplete2](https://cloud.githubusercontent.com/assets/5301202/13547337/3f88d582-e2cf-11e5-9b72-45e795677414.png)

**Comment by wsdjeg** [comment]
never encounter this issue,can you test with mini vimrc?and with the info you show me,I can not test for this issue.
you shoud show me such info
1. your os
2. javac version
3. can you use `mvn compile` build project successfully
4. minivimrc
5. vim/neovim version

**Comment by wsdjeg** [comment]
and can you show me the command line ,in the first pic,only half of the command line i can see

**Comment by artur-shaik** [comment]
@malteneuss can you try to set `g:JavaComplete_ServerAutoShutdownTime` variable (in seconds). The daemon will kill itself if there will no request during this time.

Normally daemon should be terminated on vim exit, but sometimes this happen, that's why we added timeout killer.

**Comment by artur-shaik** [comment]
@malteneuss any progress with it?

**Comment by adelarsq** [comment]
I think that this issue can be closed, since the config solves the problem.
