### ISSUE TITLE
Optional usage of fqn

### ISSUE THREAD

**Issue by andiderp** [artur-shaik/vim-javacomplete2#22]
I would be great if it were possible to specify that you only want to see the classnames and not the full path of the class. Then it would be easier to read. 
Instead of boolean containsAll(java.util.Collection)  
it would only show boolean containsAll(Collection).

**Comment by artur-shaik** [comment]
I think this should be optional. I will add it to my TODO list.

**Comment by artur-shaik** [comment]
Commit 95226d9fa9989b69977573f2ecbddb8fb4e05811 adds this option.
