### ISSUE TITLE
No Javavi library classes found, it means that we couldn't compile it. Do you have JDK8+ installed?

### ISSUE THREAD

**Issue by rajat-explorer** [artur-shaik/vim-javacomplete2#220]
Using JDK 8
java-version output
`java -version
openjdk version "1.8.0_72-internal"
OpenJDK Runtime Environment (build 1.8.0_72-internal-b15)
OpenJDK 64-Bit Server VM (build 25.72-b15, mixed mode)
`
Vim Version 
`VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Feb 29 2016 04:33:06)
Included patches: 1-1459
Modified by pi-rho
`

**Comment by wsdjeg** [comment]
what is your reproduce step?
and can you show me  minivimrc?

**Comment by rajat-explorer** [comment]
cat .vimrc output
`execute pathogen#infect()
syntax on
filetype plugin indent on
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
autocmd FileType java setlocal omnifunc=javacomplete#Complete
nmap <F4> <Plug>(JavaComplete-Imports-Add)
imap <F4> <Plug>(JavaComplete-Imports-Add)
nmap <F5> <Plug>(JavaComplete-Imports-AddMissing)
imap <F5> <Plug>(JavaComplete-Imports-AddMissing)
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:clang_c_options = '-std=gnu11'
let g:clang_cpp_options = '-std=c++11 -stdlib=libc++'
set rtp+=$HOME/.local/lib/python2.7/site-packages/powerline/bindings/vim/

" Always show statusline
set laststatus=2

" Use 256 colours (Use this setting only if your terminal supports 256 colours)
set t_Co=256
syntax on
set number 
filetype on`

`And iget this every time i open a java file in vim`

**Comment by rajat-explorer** [comment]
@wsdjeg  updated the title to include exact error msg.

**Comment by wsdjeg** [comment]
I know,the message,but how do you install this plugn?via Vundle or dein?

**Comment by rajat-explorer** [comment]
i did it via pathogen as mentioned on the readme

**Comment by wsdjeg** [comment]
here is my minivimrc
```vim
set runtimepath^=~/path/to/vim-javacomplete2/
autocmd FileType java setlocal omnifunc=javacomplete#Complete
filetype plugin indent on
syntax on
```
you need delete the `/vim-javacomplete2/libs/javavi/targets`
then open a new java file ,just wait for the vim auto compile this javavi lib.

**Comment by wsdjeg** [comment]
how about `call javacomplete#server#Compile()`,and wait ,do you have `mvn` in your path?

**Comment by rajat-explorer** [comment]
@wsdjeg  rebuilding the lib solved the problem
Thanks!

**Comment by wsdjeg** [comment]
welcome

**Comment by Nefari0uss** [comment]
Sorry to open a closed issue but I'm having the same error. Win10, Vim7.4. I use vim-plugged as my plugin manager. Tried deleting the targets folder as well as the call javacomplete#server#compile fix.

**Comment by artur-shaik** [comment]
@Nefari0uss can you check if lib were compiled. Are there classes files in `/vimfolder/bundles/vim-javacomplete2/libs/javavi/target` ?

**Comment by Nefari0uss** [comment]
I created a new file with ```$vim test.java``` then ran ``` call javacomplete#server#compile```. Running ```$ ls ~/.vim/plugged/vim-javacomplete2/libs/javavi/target``` shows that there's a classes folder but nothing inside of it. Java version is 1.8.0.74 (64 bit).

**Comment by artur-shaik** [comment]
You can set `let g:JavaComplete_ShowExternalCommandsOutput = 1` than run compilation, and look in `:messages` how compilation were done.

Or you can install maven and try to compile manually with maven.

**Comment by Nefari0uss** [comment]
All I get with trying the first option is ```Messages maintainer: Brad Moolenaar <Brad@vim.org>```. Let me start downloading maven and try that. What command would I have to use with Maven to compile?

**Comment by artur-shaik** [comment]
Hm... ok.

For maven, you need to have it in run path. Then in command line, you need to go to `vimdir/bundles/vim-javacomplete2/libs/javavi/` and run `mvn compile`.

**Comment by Nefari0uss** [comment]
OK, that seems to fix the error upon startup.
