### ISSUE TITLE
Add License file please

### ISSUE THREAD

**Issue by not-napoleon** [artur-shaik/vim-javacomplete2#224]
Hello,

First off, thank you for your work on this project.  As a java developer frustrated with eclim, this is exactly what I was looking for.  That said, I am hesitant to use it, much less modify it, without knowing what terms you are distributing it under.  Please add a license file so folks can know exactly what your intentions are.

You can read more about why open source projects on github need licenses here: https://help.github.com/articles/open-source-licensing/

This site provides some advice on choosing a license: http://choosealicense.com/ and the OSI provides a good list of open source licenses and answers some questions: https://opensource.org/licenses

Thanks for your time.

**Comment by DonnieWest** [comment]
It looks as though there's a License header on [java_parser.vim](https://github.com/artur-shaik/vim-javacomplete2/blob/master/autoload/java_parser.vim) so I would assume the _intent_ is to put it all under the same license as VIM itself. A LICENSE file would be greatly helpful though

**Comment by artur-shaik** [comment]
Hi, thank you for intent of using this plugin.

What about licensing. I really want to add something like this: https://github.com/scrooloose/syntastic/blob/master/LICENCE, but as @DonnieWest said, original plugin was licensed under VIM license, so I think I will add it as you ask. Not really like those 'defaut copyright laws', hope somewhen it will be changed. 

So, thank you for advice.
