### ISSUE TITLE
No longer completes classes on Android

### ISSUE THREAD

**Issue by DonnieWest** [artur-shaik/vim-javacomplete2#225]
## Actual behavior (Required!)
When attempting to complete an import in an Android project, Javacomplete says "packages still empty, try later. indexing..." even on non-android imports

Also related behavior, when completing within a class that extends an Android component there are missing completions when completing ```this``` or ```super```

## Expected behavior (Required!)
Should give imports and complete android related classes

## The steps to reproduce actual behavior (Required!)
 1. Create a basic Android Studio project or use [Plaid](https://github.com/nickbutcher/plaid)
 2. Open the MainActivity.java or other file that extends an Activity
 3. Attempt to complete an android import
 4. ```:messages``` will show that the app is indexing, even after several minutes
 5. Move to class body and attempt completing ```this``` or ```super``` and receive no results or ones that are missing

## Environment (Required!)
 * OS: Archlinux
 * Neovim version: Neovim 1.3.0-68-gd19af41

## Q&A
- [x] Yes, I tried minimal .vimrc configuration.
- [x] Yes, I have enabled logs with `JCdebugEnableLogs` and can put here content of `JCdebugGetLogContent` command, if you need.
- [x] Even, if you wish, I can set `g:JavaComplete_JavaviDebug` to `1`, than set `g:JavaComplete_JavaviLogfileDirectory`, and put here server logs, too.
- For clarification my minimal vim was simply setting runtimepath to the location of vim-javacomplete2 and setting the omnifunc

## Additional information

I'm opening this issue to solicit insight from others and begin tracking down what exactly is causing this. I'm happy to provide additional information, and I suspect that this is not Android specific but I'm only getting these issues within Android projects right now

**Comment by artur-shaik** [comment]
Please, can you provide `JavaviDebug` logs?

**Comment by wsdjeg** [comment]
@DonnieWest 
`./gradlew build` show me 
```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/wsdjeg/forks/plaid/app/build.gradle' line: 17

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.application']
   > Gradle version 2.10 is required. Current version is 2.8. If using the gradle wrapper, try editing the distributionUrl in /home/wsdjeg/forks/plaid/gradle/wrapper/gradle-wrapper.properties to gradle-2.10-all.zip

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.036 secs
```

**Comment by DonnieWest** [comment]
@wsdjeg must be a sad bug on their end - try editing the distributionUrl in /home/wsdjeg/forks/plaid/gradle/wrapper/gradle-wrapper.properties to gradle-2.10-all.zip

@artur-shaik I'll get those logs to you tonight

**Comment by DonnieWest** [comment]
http://pastebin.com/kfJ4nyzY - javavi debug

http://pastebin.com/XP2Y6qrL - cache file

You can see in the Javavi Debug log that it has a "file not found" exception, but my cache file (it's the very first entry, so you don't have to go find it in all the jars being included) correctly lists the location without the "." in front of the path

**Comment by artur-shaik** [comment]
Hm, look like we missed `:`...

**Comment by artur-shaik** [comment]
Can you try again with 1dd7b6b30df544f6b6520946d580b5a43b4ca171 ?

**Comment by DonnieWest** [comment]
Thank you! That fixes the import statements, but it does not fix completions on ```this``` and ```super```

**Comment by artur-shaik** [comment]
@DonnieWest nice. Can you show class declaration, just want try to reproduce it.

**Comment by DonnieWest** [comment]
I went ahead and created a the smallest sample application that I can get to trigger this: the class declaration in question can be found [here](https://github.com/DonnieWest/Sample-Project-for-Javacomplete-225/blob/master/app/src/main/java/com/donniewest/sample/MainActivity.java)

Unfortunately, it's still an Android project so I know it would be most helpful to whittle down exactly what is causing issues with JavaComplete2. It's something I'll experiment with

**Comment by wsdjeg** [comment]
I will try it tonight .

**Comment by artur-shaik** [comment]
Strange behavoir, when we try to find class in class path we have this exception:

```
Search class: android.support.v7.app.AppCompatActivity
java.lang.NoClassDefFoundError: android/support/v4/app/ActivityCompatApi23$RequestPermissionsRequestCodeValidator
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at kg.ash.javavi.readers.Reflection.exist(Reflection.java:45)
 ```
Somebody know what is `android.support.v4.app.ActivityCompatApi23$RequestPermissionsRequestCodeValidator` ? Where is it, and how it refers to `android.support.v7.app.AppCompatActivity` ?

**Comment by wsdjeg** [comment]
test with your test project
./gradlew build shows
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find com.android.support:appcompat-v7:23.2.1.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/support/appcompat-v7/23.2.1/appcompat-v7-23.2.1.pom
         https://jcenter.bintray.com/com/android/support/appcompat-v7/23.2.1/appcompat-v7-23.2.1.jar
     Required by:
         Sample-Project-for-Javacomplete-225:app:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 7.942 secs
``` 
but I have installed the support lib in sdk
![2016-03-18 21-02-06](https://cloud.githubusercontent.com/assets/13142418/13878479/ba30c75e-ed4c-11e5-907d-c36288c94cf9.png)

**Comment by wsdjeg** [comment]
@DonnieWest I think maybe it is not the issue with javacomplete2,because with the latest SDK,I can not see v7 jars,in the support lib directory,but I can see V4 V13 ,in V7 directory,only `src` directory
```
wsdjeg@wsdjeg-K43SJ:~$ cd tools/android-sdk-linux/extras/android/support/
wsdjeg@wsdjeg-K43SJ:~/tools/android-sdk-linux/extras/android/support$ tree -L 2
.
├── annotations
│   └── android-support-annotations.jar
├── customtabs
│   ├── AndroidManifest.xml
│   └── libs
├── design
│   ├── AndroidManifest.xml
│   ├── libs
│   ├── res
│   ├── res-public
│   └── src
├── graphics
│   └── drawable
├── multidex
│   ├── instrumentation
│   └── library
├── NOTICE.txt
├── package.xml
├── percent
│   ├── AndroidManifest.xml
│   ├── libs
│   ├── res
│   └── src
├── README.txt
├── recommendation
│   ├── AndroidManifest.xml
│   └── libs
├── samples
│   ├── Support13Demos
│   ├── Support4Demos
│   ├── Support7Demos
│   └── SupportAppNavigation
├── source.properties
├── v13
│   ├── android-support-v13.jar
│   └── src
├── v14
│   └── preference
├── v17
│   ├── leanback
│   └── preference-leanback
├── v4
│   ├── android-support-v4.jar
│   └── src
└── v7
    ├── appcompat
    ├── cardview
    ├── gridlayout
    ├── mediarouter
    ├── palette
    ├── preference
    └── recyclerview

41 directories, 11 files
wsdjeg@wsdjeg-K43SJ:~/tools/android-sdk-linux/extras/android/support$ 
```

**Comment by DonnieWest** [comment]
@artur-shaik I can dig deeper when I get home, but that class is referenced through AppCompat.java [here](https://android.googlesource.com/platform/frameworks/support/+/refs/heads/master/v7/appcompat/src/android/support/v7/app/AppCompatActivity.java#25)

Which is [here](https://android.googlesource.com/platform/frameworks/support/+/refs/heads/master/v4/java/android/support/v4/app/ActivityCompat.java#316)

and finally defined [here](https://chromium.googlesource.com/android_tools/+/master/sdk/extras/android/support/v4/src/java/android/support/v4/app/ActivityCompat.java)

@wsdjeg I can find the file by running ```find . -name "*appcompat.jar"``` in mine. Your ```tree``` command is only going a depth of 2 and so you won't find the jar. Mine is found ```$ANDROID_HOME/extras/android/support/v7/appcompat/libs/android-support-v7-appcompat.jar```

When I get home tonight, if you're still having problems, I can help you get configured and this working

**Comment by wsdjeg** [comment]
opps,
```
✔ wsdjeg:DotFiles [ master | ✚ 1 ] ➭ ls $ANDROID_HOME/extras/android/support/v7/appcompat/libs/
android-support-v4.jar  android-support-v7-appcompat.jar
✔ wsdjeg:DotFiles [ master | ✚ 1 ] ➭ 
```
but I do not know why `./gradlew build can not work`

**Comment by artur-shaik** [comment]
Ok, so, if I add this to vimrc:
```
let g:JavaComplete_LibsPath = '/androidproject/app/build/intermediates/exploded-aar/com.android.support/support-v4/23.1.1/jars/libs/internal_impl-23.1.1.jar'
```
completion works.
Now we need understand, why path to this `jar` doesn't exist in gradle results.

**Comment by wsdjeg** [comment]
can you us ./gradlew build to build the app?

**Comment by artur-shaik** [comment]
@wsdjeg I used another android project, I found on my PC.

But for this test project, I have the same results as you.

**Comment by DonnieWest** [comment]
@artur-shaik @wsdjeg I forgot that I have the experimental repositories enabled on my Android SDK - sorry guys! 

That does fix the issue! I'll write up a fix and submit a pull request shortly

**Comment by wsdjeg** [comment]
@DonnieWest but how to fix `./gradlew build` for the test project you shown above?

**Comment by DonnieWest** [comment]
@wsdjeg You probably need to open the Android sdk and install the latest preview channel tools. My Sample project, however, is just a project created by Android Studio with a single blank activity

**Comment by wsdjeg** [comment]
so you means you can use `./gradlew build` sucessfully in the command line?

**Comment by DonnieWest** [comment]
I can on my machine. I'm running Archlinux with Java 8 and the latest Android SDK Preview Channel Tools enabled and insalled

**Comment by wsdjeg** [comment]
:sob: How to enable latest sdk preview channel?

**Comment by wsdjeg** [comment]
I am sorry,maybe it is due to I can not visite `dl.google.com`,I will try more about it.

**Comment by DonnieWest** [comment]
@wsdjeg https://sites.google.com/a/android.com/tools/preview-channel maybe this will help you?

**Comment by wsdjeg** [comment]
yes,that is what I need.

**Comment by wsdjeg** [comment]
`./gradlew build` still can not work,I have install all needed jars in the sdk

**Comment by wsdjeg** [comment]
> test with your test project
> ./gradlew build shows
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring project ':app'.
> > Could not resolve all dependencies for configuration ':app:_debugCompile'.
>    > Could not find com.android.support:appcompat-v7:23.2.1.
>      Searched in the following locations:
>          https://jcenter.bintray.com/com/android/support/appcompat-v7/23.2.1/appcompat-v7-23.2.1.pom
>          https://jcenter.bintray.com/com/android/support/appcompat-v7/23.2.1/appcompat-v7-23.2.1.jar
>      Required by:
>          Sample-Project-for-Javacomplete-225:app:unspecified
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED
> 
> Total time: 7.942 secs
> 
> but I have installed the support lib in sdk

this issue has been fixed by install 
![2016-03-20 00-41-28](https://cloud.githubusercontent.com/assets/13142418/13899917/834cb250-ee34-11e5-80f9-870535951cfc.png)
not the issue about proview channal.

**Comment by wsdjeg** [comment]
and after that,when I built this project I get this error
`Cannot run program "/usr/local/android-sdk-linux/build-tools/19.0.3/aapt": error=2, No such file or directory`
also fixed by `sudo apt-get install lib32stdc++6 lib32z1`
