### ISSUE TITLE
Can't complete "".getBytes().length

### ISSUE THREAD

**Issue by mattn** [artur-shaik/vim-javacomplete2#229]
## Actual behavior
No candidates

## Expected behavior
At least, `length` should be appeared.

## The steps to reproduce actual behavior
 1. `<C-X><C-O>` after `"".get`. Then select getBytes(). This works fine.
 2. After 1, type `.<C-X><C-O>`

## Environment
 * OS: Windows
 * Vim version: 7.4.1583

**Comment by wsdjeg** [comment]
can confirm also happened in linux.
example
```java
public class Foo{
    public void run(){
    "".getBytes()._  // cursor is her
    }
}
```

**Comment by artur-shaik** [comment]
Should be working now. Thanks for issue.

**Comment by mattn** [comment]
Seems still bad. Fixed `"".getBytes()._` but `"".get_` doesn't work.

**Comment by artur-shaik** [comment]
Ok, should work now.

**Comment by mattn** [comment]
Hmm, still not. The first case doesn't work.

**Comment by artur-shaik** [comment]
Yeah, sorry. My fault. Now should work.

On 03-20 (04:30), mattn wrote:
>    Hmm, still not. The first case doesn't work.
> 
>    —
>    You are receiving this because you modified the open/close state.
>    Reply to this email directly or [1]view it on GitHub
> 
>    Reverse link: [2]unknown
> 
> References
> 
>    Visible links
>    1. https://github.com/artur-shaik/vim-javacomplete2/issues/229#issuecomment-198908837
>    2. https://github.com/artur-shaik/vim-javacomplete2/issues/229#issuecomment-198908837

-- 
Best regards,
Artur Shaikhullin

**Comment by mattn** [comment]
:+1:  Thanks!
