### ISSUE TITLE
Lambdas

### ISSUE THREAD

**Issue by artur-shaik** [artur-shaik/vim-javacomplete2#23]
So, I have sorted out some internal parsing techniques and implement basic lambda completions.

Fow now we have such constructions work:

```java
        JButton test = new JButton("Button");
        test.addActionListener( (e) -> {
            e.<completion>;
        });
```

```java
        List<Integer> list = new ArrayList<>();
        list.stream().map(t -> {
            t.<completion>;
        });
```

```java
        Predicate<Integer> pred = p -> p.<completion>;
```

Named arguments also works:
```java
        somevar.method((String s, Long l) -> {
            s.<completion>;
            l.<completion>;
        })
```

Return value parsing in such construction:
```java
        public Predicate<Integer> getCondition() {
            return p -> p.intValue == 0;
        }
```

Method references like this:
```java
        System.out::println
        HashMap::new
```

So, now would be nice if somebody start using this methods. And write about bugs, that occurred. For this switch to `lambda` branch, and recompile javavi lib.

**Comment by mattn** [comment]
Currently, lambda completion is working?

**Comment by artur-shaik** [comment]
It should. Any problems?

**Comment by mattn** [comment]
I'm trying to complete candidates with [spark framework](http://sparkjava.com/).
```java
get("/", (req, res) -> {
  req.<complete>
});
```
but not.

**Comment by artur-shaik** [comment]
I think because static imports still not supported.

**Comment by mattn** [comment]
```java
        try {
        	for (String s : target.split(",")) {
	            ClassReader reader = new Reflection(s);
	            reader.setTypeArguments(targetParser.getTypeArguments());
	            SourceClass clazz = reader.read(s);
	            if (clazz != null) {
	                String ss = new OutputClassInfo().get(clazz);
	                return ss;
	            }
        	}
        } catch (Throwable e) {
        }
    }
```
I'm thinking this should work for reflecting spark.SparkBase class. But I'm not sure how to pass the completion for the `req` parameter.

**Comment by artur-shaik** [comment]
The problem for now is that we don't know what is `get`, and what parameters it has.
