### ISSUE TITLE
TypeError: environment can only contain strings on Windows hosts

### ISSUE THREAD

**Issue by ElArtista** [artur-shaik/vim-javacomplete2#233]
```
Error detected while processing function javacomplete#Start[1]..javacomplete#server#Start:
line   30:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\TheArtist\.vim\bundle\vim-javacomplete2\autoload\javavibridge.py", line 55, in setupServer
    self.popen = SafePopen(javabin + ' ' + args + ' -D ' + str(SERVER[1]), shell=shell, env=environ, stdout = output, stderr = output, startupinfo = info)
  File "C:\Users\TheArtist\.vim\bundle\vim-javacomplete2\autoload\javavibridge.py", line 26, in SafePopen
    return subprocess.Popen( *args, **kwargs )
  File "F:\Programs\Python\Lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "F:\Programs\Python\Lib\subprocess.py", line 958, in _execute_child
    startupinfo)
TypeError: environment can only contain strings
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\TheArtist\.vim\bundle\vim-javacomplete2\autoload\javavibridge.py", line 55, in setupServer
    self.popen = SafePopen(javabin + ' ' + args + ' -D ' + str(SERVER[1]), shell=shell, env=environ, stdout = output, stderr = output, startupinfo = info)
  File "C:\Users\TheArtist\.vim\bundle\vim-javacomplete2\autoload\javavibridge.py", line 26, in SafePopen
    return subprocess.Popen( *args, **kwargs )
  File "F:\Programs\Python\Lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "F:\Programs\Python\Lib\subprocess.py", line 958, in _execute_child
    startupinfo)
TypeError: environment can only contain strings
```

I upgraded the plugin after some months, and now i get the above. I am working on a Windows machine.

**Comment by artur-shaik** [comment]
Hm, that's strange. Can you show you environ variable?
You can add this:
```python
        print(environ)
```
on line 51 of `autoload/javavibridge.py` file, run vim, and copy output here. Output should be visible if you run `:messages`.

**Comment by ElArtista** [comment]
(Huge environment incoming)

> ```
> {'TMP': 'C:\\Users\\THEART~1\\AppData\\Local\\Temp', u'NO_PROXY': u'127.0.0.1,localhost', 'CYGWIN': 'mintty', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'SYSTEMROOT': 'C:\\WINDOWS', 'CONEMUHWND': '0x002E020A', 'CONEMUDRIVE': 'C:', 'JAVA_HOME': 'C:\\Program Files\\Java\\jdk8', 'CONEMUBUILD': '151224', 'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe', 'FPS_BROWSER_APP_PROFILE_STRING': 'Internet Explorer', 'VENDOR_ROOT': 'C:\\Program Files (x86)\\CowShell\\Vendor', 'VS140COMNTOOLS': 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools\\', 'HOMEDRIVE': 'C:', 'GTK_BASEPATH': 'C:\\Program Files (x86)\\GtkSharp\\2.12\\', 'SYSTEMDRIVE': 'C:', 'GRADLE_USER_HOME': 'F:\\Programs\\Repos\\.gradle', 'VIM': 'F:\\Programs\\Vim', 'PROCESSOR_LEVEL': '6', 'CMDTOOLS': 'F:\\Programs\\CmdTools\\7z\\bin;F:\\Programs\\CmdTools\\aria2c\\bin;F:\\Programs\\CmdTools\\astyle\\bin;F:\\Programs\\CmdTools\\bash\\bin;F:\\Programs\\CmdTools\\bison\\bin;F:\\Programs\\CmdTools\\busybox\\bin;F:\\Programs\\CmdTools\\bzip2\\bin;F:\\Programs\\CmdTools\\cmake\\bin;F:\\Programs\\CmdTools\\coreutils\\bin;F:\\Programs\\CmdTools\\cpio\\bin;F:\\Programs\\CmdTools\\ctags\\bin;F:\\Programs\\CmdTools\\curl\\bin;F:\\Programs\\CmdTools\\darcs\\bin;F:\\Programs\\CmdTools\\dd\\bin;F:\\Programs\\CmdTools\\diffutils\\bin;F:\\Programs\\CmdTools\\dos2unix\\bin;F:\\Programs\\CmdTools\\doxygen\\bin;F:\\Programs\\CmdTools\\dumpbin\\bin;F:\\Programs\\CmdTools\\ffmpeg\\bin;F:\\Programs\\CmdTools\\figlet\\bin;F:\\Programs\\CmdTools\\file\\bin;F:\\Programs\\CmdTools\\findutils\\bin;F:\\Programs\\CmdTools\\flac\\bin;F:\\Programs\\CmdTools\\indent\\bin;F:\\Programs\\CmdTools\\gawk\\bin;F:\\Programs\\CmdTools\\gdb\\bin;F:\\Programs\\CmdTools\\grep\\bin;F:\\Programs\\CmdTools\\gzip\\bin;F:\\Programs\\CmdTools\\jad\\bin;F:\\Programs\\CmdTools\\lame\\bin;F:\\Programs\\CmdTools\\less\\bin;F:\\Programs\\CmdTools\\libutils\\bin;F:\\Programs\\CmdTools\\m4\\bin;F:\\Programs\\CmdTools\\make\\bin;F:\\Programs\\CmdTools\\md5deep\\bin;F:\\Programs\\CmdTools\\mpc\\bin;F:\\Programs\\CmdTools\\mysql\\bin;F:\\Programs\\CmdTools\\nasm\\bin;F:\\Programs\\CmdTools\\nc\\bin;F:\\Programs\\CmdTools\\ntp\\bin;F:\\Programs\\CmdTools\\oggenc2\\bin;F:\\Programs\\CmdTools\\openssh\\bin;F:\\Programs\\CmdTools\\pandoc\\bin;F:\\Programs\\CmdTools\\patch\\bin;F:\\Programs\\CmdTools\\pico2wave\\bin;F:\\Programs\\CmdTools\\png2ico\\bin;F:\\Programs\\CmdTools\\potrace\\bin;F:\\Programs\\CmdTools\\rsync\\bin;F:\\Programs\\CmdTools\\sed\\bin;F:\\Programs\\CmdTools\\shntool\\bin;F:\\Programs\\CmdTools\\sox\\bin;F:\\Programs\\CmdTools\\sqlite\\bin;F:\\Programs\\CmdTools\\svn\\bin;F:\\Programs\\CmdTools\\tar\\bin;F:\\Programs\\CmdTools\\tinyscheme\\bin;F:\\Programs\\CmdTools\\uncrustify\\bin;F:\\Programs\\CmdTools\\unrar\\bin;F:\\Programs\\CmdTools\\unzip\\bin;F:\\Programs\\CmdTools\\vbindiff\\bin;F:\\Programs\\CmdTools\\vim\\bin;F:\\Programs\\CmdTools\\waf\\bin;F:\\Programs\\CmdTools\\wget\\bin;F:\\Programs\\CmdTools\\windump\\bin;F:\\Programs\\CmdTools\\zip\\bin;F:\\Programs\\CmdTools\\rtmpdump\\bin;', 'ANSICON': '126x1000 (126x42)', 'OS': 'Windows_NT', 'CONEMUANSILOG': '', 'CONEMUBACKHWND': '0x00071470', 'CONEMUPID': '872', 'CONEMUWORKDRIVE': 'C:', 'ANSICON_DEF': '7', 'TEMP': 'C:\\Users\\THEART~1\\AppData\\Local\\Temp', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'CONEMUPROMPT2': '$_$E[90m$G', 'CONEMUPROMPT3': '$E[m$S$E[0m', 'CONEMUPROMPT0': '$E[32m$E]9;8;"USERNAME"$E\\@$E]9;8;"COMPUTERNAME"$E\\$S', 'CONEMUPROMPT1': '$E[32m$E]9;8;"USERNAME"$E\\@$E]9;8;"COMPUTERNAME"$E\\$S$E[92m$P$E[90m', 'COWSHELL_BOOT': '"C:\\Program Files (x86)\\CowShell\\Vendor\\ConEmu\\ConEmu.exe" /single /Icon "C:\\Program Files (x86)\\CowShell\\Resources\\terminal.ico" /Title CowShell /LoadCfgFile "C:\\Program Files (x86)\\CowShell\\Config\\ConEmu.xml"', 'CONEMUARGS': '/single /Icon "C:\\Program Files (x86)\\CowShell\\Resources\\terminal.ico" /Title CowShell /LoadCfgFile "C:\\Program Files (x86)\\CowShell\\Config\\ConEmu.xml"', 'FPS_BROWSER_USER_PROFILE_STRING': 'Default', 'HOMEPATH': '\\Users\\TheArtist', 'M2_HOME': 'F:\\Programs\\Maven', 'CONEMUSERVERPID': '6100', 'RESOURCES_ROOT': 'C:\\Program Files (x86)\\CowShell\\Resources', 'COWSHELL_ROOT': 'C:\\Program Files (x86)\\CowShell\\', 'LOGONSERVER': '\\\\TA-PC', 'PF32': 'C:\\Program Files (x86)', 'USERBOOTSCRIPT': 'C:\\Users\\TheArtist\\AppData\\Roaming\\CowShell\\init.bat', 'CLASSPATH': 'C:\\\\Users\\\\TheArtist\\\\.vim\\\\bundle\\\\vim-javacomplete2\\\\libs\\\\javavi\\\\target\\\\classes;C:\\\\Users\\\\TheArtist\\\\.vim\\\\bundle\\\\vim-javacomplete2\\\\libs\\\\javaparser.jar;;C:\\\\Users\\\\TheArtist\\\\Workdir\\\\InvisionApp\\\\build\\\\intermediates\\\\exploded-aar\\\\com.android.support\\\\cardview-v7\\\\23.1.1\\\\jars\\\\classes.jar;C:\\\\Users\\\\TheArtist\\\\Workdir\\\\InvisionApp\\\\build\\\\intermediates\\\\classes\\\\debug;F:\\\\Programs\\\\Android\\\\android-sdk\\\\extras\\\\android\\\\m2repository\\\\org\\\\jacoco\\\\org.jacoco.agent\\\\0.7.4.201502262128\\\\org.jacoco.agent-0.7.4.201502262128.jar;F:\\\\Programs\\\\Android\\\\android-sdk\\\\extras\\\\android\\\\m2repository\\\\com\\\\android\\\\support\\\\support-annotations\\\\23.1.1\\\\support-annotations-23.1.1.jar;F:\\\\Programs\\\\Android\\\\android-sdk\\\\extras\\\\android\\\\m2repository\\\\org\\\\jacoco\\\\org.jacoco.ant\\\\0.7.4.201502262128\\\\org.jacoco.ant-0.7.4.201502262128.jar;C:\\\\Users\\\\TheArtist\\\\Workdir\\\\InvisionApp\\\\build\\\\intermediates\\\\exploded-aar\\\\com.android.support\\\\support-v4\\\\23.1.1\\\\jars\\\\classes.jar;F:\\\\Programs\\\\Android\\\\android-sdk\\\\platforms\\\\android-23\\\\android.jar;C:\\\\Users\\\\TheArtist\\\\Workdir\\\\InvisionApp\\\\build\\\\intermediates\\\\exploded-aar\\\\com.android.support\\\\recyclerview-v7\\\\23.1.1\\\\jars\\\\classes.jar;C:\\\\Users\\\\TheArtist\\\\Workdir\\\\InvisionApp\\\\build\\\\intermediates\\\\exploded-aar\\\\com.android.support\\\\appcompat-v7\\\\23.1.1\\\\jars\\\\classes.jar;C:\\\\Users\\\\TheArtist\\\\Workdir\\\\InvisionApp\\\\lib\\\\xstream-1.4.7.jar;C:\\\\Users\\\\TheArtist\\\\Workdir\\\\InvisionApp\\\\build\\\\intermediates\\\\exploded-aar\\\\com.android.support\\\\design\\\\23.1.1\\\\jars\\\\classes.jar;C:\\\\Program Files\\\\Java\\\\jdk8\\\\lib', 'SESSIONNAME': 'Console', 'ASL.LOG': 'Destination=file', 'APPDATA': 'C:\\Users\\TheArtist\\AppData\\Roaming', 'CONEMU_CONFIG': 'C:\\Program Files (x86)\\CowShell\\Config\\ConEmu.xml', 'MYVIMRC': 'C:\\Users\\TheArtist\\_vimrc', 'COMPUTERNAME': 'TA-PC', 'USERDOMAIN': 'TA-PC', 'COWSHELL_ICON': 'C:\\Program Files (x86)\\CowShell\\Resources\\terminal.ico', 'CONEMU_EXE': 'C:\\Program Files (x86)\\CowShell\\Vendor\\ConEmu\\ConEmu.exe', 'COMMONPROGRAMFILES': 'C:\\Program Files (x86)\\Common Files', 'HOME': 'C:\\Users\\TheArtist', 'CTH': 'F:\\Programs\\CmdTools', 'PROCESSOR_ARCHITECTURE': 'x86', 'CONEMUDIR': 'C:\\Program Files (x86)\\CowShell\\Vendor\\ConEmu', 'ALLUSERSPROFILE': 'C:\\ProgramData', 'USERDOMAIN_ROAMINGPROFILE': 'TA-PC', 'PROGRAMW6432': 'C:\\Program Files', 'USERNAME': 'TheArtist', 'PROMPT': 'C\x08L\x08I\x08N\x08K\x08 \x08$E[32m$E]9;8;"USERNAME"$E\\@$E]9;8;"COMPUTERNAME"$E\\$S$E[92m$P$E[90m$_$E[90m$G$E[m$S$E[0m', 'VIMRUNTIME': 'F:\\Programs\\Vim', 'NVTOOLSEXT_PATH': 'C:\\Program Files\\NVIDIA Corporation\\NvToolsExt\\', 'ANDROID_HOME': 'F:\\Programs\\Android\\android-sdk', 'WINDIR': 'C:\\WINDOWS', 'NUMBER_OF_PROCESSORS': '4', 'PROCESSOR_ARCHITEW6432': 'AMD64', 'CONEMUWORKDIR': 'C:\\Program Files (x86)\\CowShell', 'PUBLIC': 'C:\\Users\\Public', 'USERPROFILE': 'C:\\Users\\TheArtist', 'PSMODULEPATH': 'C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules\\', 'CONEMUANSI': 'ON', 'PF64': 'C:\\Program Files', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 58 Stepping 9, GenuineIntel', 'PROGRAMFILES': 'C:\\Program Files (x86)', 'PROCESSOR_REVISION': '3a09', 'PATH': 'C:\\Program Files (x86)\\CowShell\\Vendor\\ConEmu;C:\\Program Files (x86)\\CowShell\\Vendor\\ConEmu\\ConEmu;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files (x86)\\Windows Kits\\8.1\\Windows Performance Toolkit\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Common Files\\Autodesk Shared\\;C:\\Program Files (x86)\\GtkSharp\\2.12\\bin;C:\\Program Files\\Git LFS;C:\\Program Files\\Git\\cmd;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Git\\cmd;F:\\Programs\\Vim;F:\\Programs\\LLVM\\bin;F:\\Programs\\Gcc\\bin;F:\\Programs\\Haskell\\bin;F:\\Programs\\Haskell\\lib\\extralibs\\bin;F:\\Programs\\Repos\\cabal\\bin;F:\\Programs\\Python;F:\\Programs\\Python\\Scripts;F:\\Programs\\Rust\\bin;C:\\Users\\TheArtist\\.cargo\\bin;F:\\Programs\\Ruby\\bin;F:\\Programs\\Perl\\bin;F:\\Programs\\Lua\\bin;F:\\Programs\\Scripts;F:\\Programs\\CmdTools\\7z\\bin;F:\\Programs\\CmdTools\\aria2c\\bin;F:\\Programs\\CmdTools\\astyle\\bin;F:\\Programs\\CmdTools\\bash\\bin;F:\\Programs\\CmdTools\\bison\\bin;F:\\Programs\\CmdTools\\busybox\\bin;F:\\Programs\\CmdTools\\bzip2\\bin;F:\\Programs\\CmdTools\\cmake\\bin;F:\\Programs\\CmdTools\\coreutils\\bin;F:\\Programs\\CmdTools\\cpio\\bin;F:\\Programs\\CmdTools\\ctags\\bin;F:\\Programs\\CmdTools\\curl\\bin;F:\\Programs\\CmdTools\\darcs\\bin;F:\\Programs\\CmdTools\\dd\\bin;F:\\Programs\\CmdTools\\diffutils\\bin;F:\\Programs\\CmdTools\\dos2unix\\bin;F:\\Programs\\CmdTools\\doxygen\\bin;F:\\Programs\\CmdTools\\dumpbin\\bin;F:\\Programs\\CmdTools\\ffmpeg\\bin;F:\\Programs\\CmdTools\\figlet\\bin;F:\\Programs\\CmdTools\\file\\bin;F:\\Programs\\CmdTools\\findutils\\bin;F:\\Programs\\CmdTools\\flac\\bin;F:\\Programs\\CmdTools\\indent\\bin;F:\\Programs\\CmdTools\\gawk\\bin;F:\\Programs\\CmdTools\\gdb\\bin;F:\\Programs\\CmdTools\\grep\\bin;F:\\Programs\\CmdTools\\gzip\\bin;F:\\Programs\\CmdTools\\jad\\bin;F:\\Programs\\CmdTools\\lame\\bin;F:\\Programs\\CmdTools\\less\\bin;F:\\Programs\\CmdTools\\libutils\\bin;F:\\Programs\\CmdTools\\m4\\bin;F:\\Programs\\CmdTools\\make\\bin;F:\\Programs\\CmdTools\\md5deep\\bin;F:\\Programs\\CmdTools\\mpc\\bin;F:\\Programs\\CmdTools\\mysql\\bin;F:\\Programs\\CmdTools\\nasm\\bin;F:\\Programs\\CmdTools\\nc\\bin;F:\\Programs\\CmdTools\\ntp\\bin;F:\\Programs\\CmdTools\\oggenc2\\bin;F:\\Programs\\CmdTools\\openssh\\bin;F:\\Programs\\CmdTools\\pandoc\\bin;F:\\Programs\\CmdTools\\patch\\bin;F:\\Programs\\CmdTools\\pico2wave\\bin;F:\\Programs\\CmdTools\\png2ico\\bin;F:\\Programs\\CmdTools\\potrace\\bin;F:\\Programs\\CmdTools\\rsync\\bin;F:\\Programs\\CmdTools\\sed\\bin;F:\\Programs\\CmdTools\\shntool\\bin;F:\\Programs\\CmdTools\\sox\\bin;F:\\Programs\\CmdTools\\sqlite\\bin;F:\\Programs\\CmdTools\\svn\\bin;F:\\Programs\\CmdTools\\tar\\bin;F:\\Programs\\CmdTools\\tinyscheme\\bin;F:\\Programs\\CmdTools\\uncrustify\\bin;F:\\Programs\\CmdTools\\unrar\\bin;F:\\Programs\\CmdTools\\unzip\\bin;F:\\Programs\\CmdTools\\vbindiff\\bin;F:\\Programs\\CmdTools\\vim\\bin;F:\\Programs\\CmdTools\\waf\\bin;F:\\Programs\\CmdTools\\wget\\bin;F:\\Programs\\CmdTools\\windump\\bin;F:\\Programs\\CmdTools\\zip\\bin;F:\\Programs\\CmdTools\\rtmpdump\\bin;;C:\\Program Files\\Java\\jdk8\\bin;F:\\Programs\\Gradle\\bin;F:\\Programs\\Android\\android-sdk\\platform-tools;F:\\Programs\\Android\\android-sdk\\tools;F:\\Programs\\Love2D\\bin;F:\\Programs\\Ant\\bin;F:\\Programs\\LiquidSoap;F:\\Programs\\ApiTrace\\x64\\bin;C:\\Program Files (x86)\\CowShell\\Vendor\\AutoJump\\bin;F:\\Programs\\Vim', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'CONEMU_PATH': 'C:\\Program Files (x86)\\CowShell\\Vendor\\ConEmu', 'CONEMUHOOKS': 'Enabled', 'LOCALAPPDATA': 'C:\\Users\\TheArtist\\AppData\\Local', 'PROGRAMDATA': 'C:\\ProgramData', 'ESC': '\x1b', 'CLINK_PATH': 'C:\\Program Files (x86)\\CowShell\\Vendor\\Clink', 'CONFIG_ROOT': 'C:\\Program Files (x86)\\CowShell\\Config', 'ADSK_3DSMAX_X64_2016': 'F:\\Programs\\Autodesk\\3ds Max 2016\\', 'FP_NO_HOST_CHECK': 'NO', 'CONEMUBASEDIR': 'C:\\Program Files (x86)\\CowShell\\Vendor\\ConEmu\\ConEmu', 'GRADLE_HOME': 'F:\\Programs\\Gradle', 'DXSDK_DIR': 'C:\\Program Files (x86)\\Microsoft DirectX SDK (June 2010)\\', 'CLINK_ARGS': ' --profile "C:\\Users\\TheArtist\\AppData\\Roaming\\clink_profile"', 'CONEMUDRAWHWND': '0x00161466', 'CONEMUCONFIG': '', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files'}
> ```

**Comment by artur-shaik** [comment]
Ok, seems nothing special. Can you try to rollback to earler version, to find out what changes break it? As I see everything related to environment hasn't changed since last summer.

**Comment by ElArtista** [comment]
Well, i tried to checkout to a previous build i was using, namely this:
```
commit 5035b409c3d8dd9e338b1f7ab4f061e19d17bd27
Merge: e773f7e a2ddac8
Author: Artur Shaik <ashaihullin@gmail.com>
Date:   Fri Feb 5 17:58:41 2016 +0600

    Merge pull request #191 from msfm/master

    Replace getcurpos with getpos to support older Vim
```

Also i should note i have made this patch to work around an issue back then (that it may apply till today), this:
```
diff --git a/autoload/javacomplete/classpath/gradle.vim b/autoload/javacomplete/classpath/gradle.vim
index a354ec8..86a95e5 100644
--- a/autoload/javacomplete/classpath/gradle.vim
+++ b/autoload/javacomplete/classpath/gradle.vim
@@ -60,7 +60,7 @@ function! s:GenerateClassPath(path, gradle) abort
   if !executable(gradle)
     let gradle = 'gradle'
   endif
-  call writefile(["allprojects{apply from: '". g:JavaComplete_Home. g:FILE_SEP. "classpath.gradle'}"], s:temporaryGradleFile)
+  call writefile(["allprojects{apply from: '". substitute(g:JavaComplete_Home, "\\", "/", "g") . '/' . "classpath.gradle'}"], s:temporaryGradleFile)
   let cmd = [gradle, '-I', s:temporaryGradleFile, 'classpath']
   call javacomplete#util#RunSystem(cmd, 'gradle classpath build process', 'javacomplete#classpath#gradle#BuildClasspathHandler')
 endfunction
```

Well checking out the previous version i was using and applying my patch, still didn't make it work!
Any insights on this?

**Comment by ElArtista** [comment]
Well, Roy from the IT Crowd series said it all ("Did you tried turning it off and on again?"). I just rebooted my machine and it worked.. I suppose that somebody wrote an utf8 environment variable that javacomplete2 could not handle...

**Comment by artur-shaik** [comment]
Ok, glad it works. You can close issue if it will not repeate. Seems like hard to reproduce issue.
