### ISSUE TITLE
New instance of javacomplete launched for each new java file

### ISSUE THREAD

**Issue by dannywillems** [artur-shaik/vim-javacomplete2#234]
## Actual behavior (Required!)
When we edit a file, the server is launched, but it is not stopped when we closed the file and exit vim.
Here, I open 4 files, with different names, and 4 instance are launched.

## Expected behavior (Required!)
Server instance killed when exit vim

## The steps to reproduce actual behavior (Required!)
 1. Open multiple java files and use htop

## Environment (Required!)
 * OS: Linux 4.4.5
 * Neovim version: Last production version. (EDIT: development version!)

## Screenshot (Optional)
![selection_001](https://cloud.githubusercontent.com/assets/6018454/14588718/1e2a8a3e-04d0-11e6-96f9-32373bb53fe8.png)

**Comment by wsdjeg** [comment]
#217 same issue?

**Comment by adelarsq** [comment]
Many times this behavior was described. The better way I think is set a default value for `g:JavaComplete_ServerAutoShutdownTime` on the plugin, so we can avoid that.
@artur-shaik @wsdjeg What you guys think?

**Comment by dannywillems** [comment]
@wsdjeg @adelarsq This variable kills the server after x seconds, not when vim exits.

**Comment by artur-shaik** [comment]
@dannywillems can you call `:JCserverTerminate` after server started up, and check is server still running or not.

Just can not to catch where this issue happens.

**Comment by dannywillems** [comment]
@artur-shaik Yes, the server still running.

**Comment by artur-shaik** [comment]
@dannywillems, can you please, switch to this branch https://github.com/artur-shaik/vim-javacomplete2/tree/issue_234 and try the same again

**Comment by dannywillems** [comment]
I've got this error message when I first open a java file. Server still running after exit vim. (I didn't change the initial configuration, just cloned)

![selection_006](https://cloud.githubusercontent.com/assets/6018454/14760555/64079be8-0947-11e6-80b2-a245bb685062.png)

**Comment by wsdjeg** [comment]
@dannywillems 
you can try with this file
test.vim
```vim
set rtp+=/path/to/javacomplete2
autocmd FileType java setlocal omnifunc=javacomplete#Complete
```
and open vim by `vim -u test.vim`
then run command `:e Foo.java`,and `:JCserverTerminate`

and see if the java server still running

**Comment by artur-shaik** [comment]
@dannywillems strange, cannot reproduce this issues. You can try, as @wsdjeg suggest, with minimal configuration. And will be nice if you could debug this issue...

**Comment by wsdjeg** [comment]
@dannywillems just notice you are using neovim,can you give me the output of this script?I think maybe there is something wrong with you neovim's python config.
https://github.com/tweekmonster/nvim-python-doctor

also you can try with vim,I think it should works well

**Comment by dannywillems** [comment]
@wsdjeg: Here is the output
```
## Neovim Python Diagnostic

- Neovim Version: NVIM v0.1.4-195-g3d7a6e4

## Python versions visible to Neovim

### 'python' info from /usr/local/bin/nvim

WARN: 'g:python_host_prog' is not set
WARN: Fallback to '/usr/bin/python'
**Python Version**: `Python 2.7.6`
**Neovim Package Version**: `neovim (0.1.7)`

### 'python3' info from /usr/local/bin/nvim

WARN: 'g:python3_host_prog' is not set
WARN: Fallback to '/usr/bin/python3'
**Python Version**: `Python 3.4.3`
ERR: `/usr/bin/python3: No module named pip`

## Python versions visible in the current shell

- **python** version: `Python 2.7.6`
  - **neovim** version: `neovim (0.1.7)`
- **python3** version: `Python 3.4.3`
  - **neovim** version: `Not installed`
```

I use the neovim development version, not the last production (sorry, I edited my first comment).

**Comment by dannywillems** [comment]
@wsdjeg I have the same issue with vim. ```java kg.ash.javavi.Javavi ...``` still running.

**Comment by wsdjeg** [comment]
as the script output shown,no issues about your config.
do you have this in your vimrc?
```vim
" python host for neovim
let g:python_host_prog = '/usr/bin/python2'
let g:python3_host_prog = '/usr/bin/python3'
```
@artur-shaik I think maybe #217 also do not be solved,but we do not know where the issue happend.

**Comment by dannywillems** [comment]
@wsdjeg I added it but the issue still present.

**Comment by wsdjeg** [comment]
stange,but I can not catch this bug now,so sorry

**Comment by artur-shaik** [comment]
@wsdjeg yeah, that was just a workaround. Will leave this issue open and hope that somebody can reproduce it.

**Comment by dannywillems** [comment]
Still no solution ? Very disturbing and boring to kill manually.

**Comment by artur-shaik** [comment]
@dannywillems can you test `issue_234` branch one time more?

**Comment by artur-shaik** [comment]
You don't need now to switch to another branch, changes are in master now. Please try again.

**Comment by dannywillems** [comment]
The issue still present. Am I the only one who has this issue ?

**Comment by artur-shaik** [comment]
@pvrs12 has this issue too. He made PR to fix it, seems like it works for him: https://github.com/artur-shaik/vim-javacomplete2/pull/240

**Comment by dannywillems** [comment]
Here maybe another issue:
- I open a java file. The server starts and when I type ´´´import java.``` I have some autocomplete (I use YouCompleteMe).
- I kill the server with JCserverTerminate -> The server is killed.
- I type another ```import java.``` and the server restart and I have some autocomplete.

Is it normal?

**Comment by artur-shaik** [comment]
Yeah, script autostart server if it is not running on completion trigger.

**Comment by artur-shaik** [comment]
I guess if `I kill the server with JCserverTerminate -> The server is killed.` so issue is solved for you?

**Comment by dannywillems** [comment]
I must do it manually. It's not very convenient.

**Comment by wsdjeg** [comment]
@dannywillems are you using neovim? have you tried in vim?

**Comment by wsdjeg** [comment]
@artur-shaik I think this issue has be fixed,as I know @dannywillems is using YCM,and when he type into `import java.` the omnifunc will be auto started by YCM.so the server will auto restart.
and I think this issue is caused by 
```vim
 let g:ycm_semantic_triggers =  {
                        \   'c' : ['->', '.'],
                        \   'objc' : ['->', '.'],
                        \   'ocaml' : ['.', '#'],
                        \   'cpp,objcpp' : ['->', '.', '::'],
                        \   'perl' : ['->'],
                        \   'php' : ['->', '::'],
                        \   'cs,javascript,d,python,perl6,scala,vb,elixir,go' : ['.'],
                        \   'java,jsp' : ['.'],
                        \   'vim' : ['re![_a-zA-Z]+[_\w]*\.'],
                        \   'ruby' : ['.', '::'],
                        \   'lua' : ['.', ':'],
                        \   'erlang' : [':'],
                        \ }
```

you need remove ` \   'java,jsp' : ['.'],`

**Comment by artur-shaik** [comment]
@wsdjeg as I understand server still work after vim exit.

**Comment by dannywillems** [comment]
@artur-shaik @wsdjeg Yes, the server still working after exiting vim.

**Comment by dannywillems** [comment]
@wsdjeg Yes, same issue with vim. I think I will try without any other plugins and see if there is a conflict with another one. I don't have time now but I will try in some days. I will give you a feedback.

**Comment by artur-shaik** [comment]
Actually that's strange, if `JCserverTerminate` works for, so must be do and on exit, too. Maybe you need bind `JCserverTerminate` manually, to run it on vim exit. This is how it runs by script:
```
autocmd VimLeave * call javacomplete#server#Terminate()
```
By the way, as writted in vim help, you can check previous exit code of vim, by run `:echo v:dying` and see if it equals to 0 or 1, thus if it's bigger so `VimLeave` not triggered on exit.

**Comment by artur-shaik** [comment]
Any news?

**Comment by dannywillems** [comment]
@artur-shaik Don't have time to try something new for the moment, sorry. I use it with neovim but kill manually each javavi instance manually.
