### ISSUE TITLE
Startup version warning

### ISSUE THREAD

**Issue by TheTravelingSpaceman** [artur-shaik/vim-javacomplete2#235]
## Actual behavior (Required!)
Produces warning: 

> JavaComplete2 : TextChangedI feature needs vim version >= 7.4.143

 on start up even though my vim version is version 7.4.52 as quoted by vim start up screen

## Expected behavior (Required!)
No error/warning

## The steps to reproduce actual behavior (Required!)
 1. Open java source file using vim
 2. Observe error
 3. Profit?

## Environment (Required!)
 * OS: Linux Mint 17.2 Rafaela (Cinnamon 64-bit) 
 * Vim version: version 7.4.52 
 * Neovim version: ???

## The output of :redir and :message (Optional)
JavaComplete2 : TextChangedI feature needs vim version >= 7.4.143

**Comment by wsdjeg** [comment]
7.4.52means 7.4.052,it is small than 7.4.143,please update your vim

**Comment by TheTravelingSpaceman** [comment]
Thanks, works now. I hope you see where the confusion crept in.
