### ISSUE TITLE
Javacomplete functions

### ISSUE THREAD

**Issue by artek2001** [artur-shaik/vim-javacomplete2#236]
Hello guys. Sorry for my bad English. My question is: when there is a function in a class (for example a function that has a name "find" and uses String) and I want to call it in my java file. But when I type a variable and put a dot, press C-x then C-o but I dont see this function. How to fix that? Thanks.

**Comment by artur-shaik** [comment]
Can you do this steps, that mentioned in issue template:
```
## Q&A
* Yes, I tried minimal .vimrc configuraion.
* Yes, I have enabled logs with `JCdebugEnableLogs` and can put here content of `JCdebugGetLogContent` command, if you need.
* Even, if you wish, I can set `g:JavaComplete_JavaviDebug` to `1`, than set `g:JavaComplete_JavaviLogfileDirectory`, and put here server logs, too.
```

**Comment by artek2001** [comment]
I want to use my method, but I can see only java default methods. Here's a link------>http://imgur.com/FvjuqRj
1)My logs after using C-x-o



 50.961181 [context] context: CONTEXT_AFTER_DOT
 50.961250 [context] dot expression: testString.
 50.961356 [complete] complete after dot. expr: testString.
 50.964657 [collector] get declared class name for: "testString"
 51.095555 [complete] F3. "testString.|"  typename: "TestString"
 51.095602 [collector] get class info. class: TestString
 51.187654 [server] communicate: -E "TestString" [collector#FetchInfoFromServer]
 51.333369 [server] 
 51.333721 [server] communicate: -E "java.lang.TestString" [collector#FetchInfoFromServer]
 51.443397 [server] 
 51.444036 [server] communicate: -E "java.lang.Object" [collector#FetchInfoFromServer]
 51.574784 [server] {'java.lang.Object':{'tag':'CLASSDEF','flags':'1','name':'java.lang.Object','classpath':'1','pos':[-1,-1],'endpos':[-1,-1],'fqn':'java.lang.Object','implements':[],'nested':[],'ctors':[{'m':'1','d':'public java.lang.Object()'},],'fields':[],'methods':[{'n':'finalize','c':'void','m':'100','r':'void','d':'protected void java.lang.Object.finalize() throws java.lang.Throwable'},{'n':'toString','c':'java.lang.String','m':'1','r':'java.lang.String','d':'public java.lang.String java.lang.Object.toString()'},{'n':'registerNatives','c':'void','m':'100001010','r':'void','d':'private static native void java.lang.Object.registerNatives()'},{'n':'clone','m':'100000100','r':'java.lang.Object','d':'protected native java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException'},{'n':'notify','c':'void','m':'100010001','r':'void','d':'public final native void java.lang.Object.notify()'},{'n':'wait','c':'void','m':'10001','r':'void','d':'public final void java.lang.Object.wait() throws java.lang.InterruptedException'},{'n':'wait','c':'void','m':'10001','r':'void','p':['long','int',],'d':'public final void java.lang.Object.wait(long,int) throws java.lang.InterruptedException'},{'n':'wait','c':'void','m':'100010001','r':'void','p':['long',],'d':'public final native void java.lang.Object.wait(long) throws java.lang.InterruptedException'},{'n':'getClass','c':'java.lang.Class<?>','m':'100010001','r':'java.lang.Class<?>','d':'public final native java.lang.Class<?> java.lang.Object.getClass()'},{'n':'hashCode','c':'int','m':'100000001','r':'int','d':'public native int java.lang.Object.hashCode()'},{'n':'equals','c':'boolean','m':'1','r':'boolean','p':['java.lang.Object',],'d':'public boolean java.lang.Object.equals(java.lang.Object)'},{'n':'notifyAll','c':'void','m':'100010001','r':'void','d':'public final native void java.lang.Object.notifyAll()'},],},}
 51.576078 [complete] get member list. outputkind: 0
 51.576178 [complete] search member. name: , kind: 0, outputkind: 0
 51.586094 [complete] finish completion  0.632536s

**Comment by artur-shaik** [comment]
Yeah, now I see. Seems like nested classes in the parent class not supported yet.

**Comment by artek2001** [comment]
Are you planning to fix it soon?

**Comment by artur-shaik** [comment]
Yes, I will look it little bit later.

**Comment by artek2001** [comment]
Thanks a lot
