### ISSUE TITLE
Duplicate class name from different packages

### ISSUE THREAD

**Issue by bruce3557** [artur-shaik/vim-javacomplete2#238]
## Actual behavior (Required!)
When I try to autocomplete a new variable, ex: DataFrame
There are many classes of ```DataFrame``` from different packages, ex: ```org.apache.spark.sql``` or ```org.eclipse.jetty.spdy.frames```
<img width="641" alt="screen shot 2016-04-27 at 3 41 42 am" src="https://cloud.githubusercontent.com/assets/4061342/14831918/43538430-0c2a-11e6-8161-ac4c872a2266.png">

## Expected behavior (Required!)
I expected we should have all the classes of the same name.

## The steps to reproduce actual behavior (Required!)
 1. Open a java file
 2. type ```DataFrame``` and press ```ctrl + x + o```

## Environment (Required!)
 * OS: OS X Yosemite
 * Vim version: 7.4
 * Neovim version: none

**Comment by artur-shaik** [comment]
You mean package name should be the same? Generally this package does mean nothing, we just take first we have in database to fill that space, and sometimes this is usefull. But it doesn't matter later, and I don't think that there are any sense to sort those package names.

**Comment by wsdjeg** [comment]
I thinks no need show all package name,if there are more than one package,the auto import will be done after complete class name .and you can select the package you need.

**Comment by bruce3557** [comment]
Oh.. I misunderstand the implementation of this function (actually I thought if I choose one auto-completion and it will auto-import the related package I choose). Thanks for your replies!
