### ISSUE TITLE
complete constructor after new ...?

### ISSUE THREAD

**Issue by richox** [artur-shaik/vim-javacomplete2#244]
## Actual behavior (Required!)
new Strin|
completes class names in classpath:
    String
    StringBuffer
    StringBuilder
    ...

## Expected behavior (Required!)
new Strin|
completes constructors:
    String  f  String()
    String  f  String(byte[])
    String  f  String(byte[], Charset)
    ...

## The steps to reproduce actual behavior (Required!)
 1. ...
 2. ...
 3. ...

## Environment (Required!)
 * OS:
 * Vim version:
 * Neovim version:

## Q&A
* Yes, I tried minimal .vimrc configuraion.
* Yes, I have enabled logs with `JCdebugEnableLogs` and can put here content of `JCdebugGetLogContent` command, if you need.
* Even, if you wish, I can set `g:JavaComplete_JavaviDebug` to `1`, than set `g:JavaComplete_JavaviLogfileDirectory`, and put here server logs, too.

**Comment by wsdjeg** [comment]
I don's think so, for example;
if I want to use `new StringBuilder()`, how could I complete after `new Str`?

**Comment by artur-shaik** [comment]
What you think it should do, only show what constructors exists or do any substitution on parameters?

I think, at least, we can show constructors list if we have full class name and it is already imported.

**Comment by artur-shaik** [comment]
Any info?

**Comment by richox** [comment]
my requirement is: when I want to create an object with `new ...()` I cannot get any infomation of constructor parameters. I think it would be helpful if completion after `new XXX` will show __all constructors of classes prefixed with XXX__ but not only classnames prefixed XXX.

**Comment by artur-shaik** [comment]
May be it would be better to show constructors after `new String(|` ?

**Comment by richox** [comment]
@artur-shaik good idea:)
