### ISSUE TITLE
Remove unused removes static imports

### ISSUE THREAD

**Issue by asm0dey** [artur-shaik/vim-javacomplete2#249]
## Actual behavior

F6 removes all static imports (even used ones)

## Expected behavior

Used static imports are not removed

## The steps to reproduce actual behavior

 1. Press F6 in class with static imports

## Environment
 * OS: Ubuntu 16.04 Xenial 
 * Vim version: vim-nox 7.4

**Comment by wsdjeg** [comment]
we have no func for remove all static imports(even if been used), BTW, I think it is not useful func. but we have the func for Remove Unused Imports.
if you need this func I think you can add this to your vimrc. this should no be needed by all user, so we can not add that into javacomplete2.
```vim
autocmd FileType java nnoremap <silent><buffer> <F6> :<c-u>%s/^static\s\+.*;$\n//g<cr>
```

**Comment by asm0dey** [comment]
You got me wrong: I don't need function to remove static imports, I need function Imports-RemoveUnused to not remove static imports :). If it's difficult to implement then the reasonable default should be not to remove static imports at all.

**Comment by wsdjeg** [comment]
@asm0dey got it, it is a bug!!

that func should not remove used imports if it is static.

**Comment by wsdjeg** [comment]
BTW, can you show me a litter example java project? I want to fix it.

**Comment by asm0dey** [comment]
Of course. https://github.com/asm0dey/ratpack-moneytransfer/
In Main class and in test there are static imports.

**Comment by wsdjeg** [comment]
@artur-shaik
I got it, it is the issue with javavi lib.
in https://github.com/asm0dey/ratpack-moneytransfer/blob/master/src/main/java/com/github/asm0dey/moneytransfer/Main.java
`javacomplete#server#Communicate('-unused-imports -content', base64Content, 'RemoveUnusedImports')` return `['java.text.MessageFormat$format','ratpack.jackson.Jackson$json',]`

**Comment by wsdjeg** [comment]
@artur-shaik
I got it, it is the issue with javavi lib.
in https://github.com/asm0dey/ratpack-moneytransfer/blob/master/src/main/java/com/github/asm0dey/moneytransfer/Main.java
`javacomplete#server#Communicate('-unused-imports -content', base64Content, 'RemoveUnusedImports')` return `['java.text.MessageFormat$format','ratpack.jackson.Jackson$json',]`

**Comment by wsdjeg** [comment]
@artur-shaik
I got it, it is the issue with javavi lib.
in https://github.com/asm0dey/ratpack-moneytransfer/blob/master/src/main/java/com/github/asm0dey/moneytransfer/Main.java
`javacomplete#server#Communicate('-unused-imports -content', base64Content, 'RemoveUnusedImports')` return `['java.text.MessageFormat$format','ratpack.jackson.Jackson$json',]`

**Comment by artur-shaik** [comment]
Yeah, can confirm. Will try to fix it.

**Comment by artur-shaik** [comment]
Please, can you check again?

**Comment by asm0dey** [comment]
Should I just run `:PluginInstall`?

**Comment by wsdjeg** [comment]
`import static java.text.MessageFormat.format;` this import still be removed.

**Comment by artur-shaik** [comment]
You should run `:JCserverCompile`, before try.

On 06-18 (03:08), Paul wrote:
>    Should I just run :PluginInstall?
> 
>    —
>    You are receiving this because you were mentioned.
>    Reply to this email directly, [1]view it on GitHub, or [2]mute the thread.
> 
>    Reverse link: [3]unknown
> 
> References
> 
>    Visible links
>    1. https://github.com/artur-shaik/vim-javacomplete2/issues/249#issuecomment-226933748
>    2. https://github.com/notifications/unsubscribe/AEozu1f_5TDCCgvkCb-mdjv9d-F4e00Jks5qM8OBgaJpZM4I437K
>    3. https://github.com/artur-shaik/vim-javacomplete2/issues/249#issuecomment-226933748

-- 
Best regards,
Artur Shaikhullin

**Comment by wsdjeg** [comment]
in that Main.java file in the example project shown above. there are two static imports which are used.
```
import static java.text.MessageFormat.format;
import static ratpack.jackson.Jackson.json;
```
after run `:JCserverCompile`, I run `:JCimportsRemoveUnused`, the first one is removed. but the second one is not.

**Comment by artur-shaik** [comment]
@wsdjeg , hm, yes. You are right... Will look it.

**Comment by asm0dey** [comment]
Guys, test class may be interesting for you too, because there are wildcard (.*) imports.

**Comment by artur-shaik** [comment]
@asm0dey, as I remember, wildcard always stays untouched by JC2.

**Comment by artur-shaik** [comment]
@wsdjeg can you try again

**Comment by wsdjeg** [comment]
@artur-shaik now it works well. I have tested it.

**Comment by artur-shaik** [comment]
Nice, thank you...

On 06-18 (23:46), Wang Shidong wrote:
>    [1]@artur-shaik now it works well. I have tested it.
> 
>    —
>    You are receiving this because you were mentioned.
>    Reply to this email directly, [2]view it on GitHub, or [3]mute the thread.
> 
>    Reverse link: [4]unknown
> 
> References
> 
>    Visible links
>    1. https://github.com/artur-shaik
>    2. https://github.com/artur-shaik/vim-javacomplete2/issues/249#issuecomment-226982520
>    3. https://github.com/notifications/unsubscribe/AEozuwRJW3MLM1EdDGsQ47mgOgUKkNhwks5qNOW8gaJpZM4I437K
>    4. https://github.com/artur-shaik/vim-javacomplete2/issues/249#issuecomment-226982520

-- 
Best regards,
Artur Shaikhullin

**Comment by artur-shaik** [comment]
@asm0dey you can reopen this issue, if you still have problems.

**Comment by asm0dey** [comment]
@artur-shaik How can I test the fix? `:PluginInstall` doesn't update anything :(

**Comment by wsdjeg** [comment]
@asm0dey you should use `:PluginUpdate` and `:JCserverCompile`

**Comment by asm0dey** [comment]
It works :)
Thank you very much for such a quick fix!

**Comment by artur-shaik** [comment]
Glad to hear it!

On 06-23 (03:25), Paul wrote:
>    It works :)
>    Thank you very much for such a quick fix!
> 
>    —
>    You are receiving this because you were mentioned.
>    Reply to this email directly, [1]view it on GitHub, or [2]mute the thread.
> 
>    Reverse link: [3]unknown
> 
> References
> 
>    Visible links
>    1. https://github.com/artur-shaik/vim-javacomplete2/issues/249#issuecomment-228010066
>    2. https://github.com/notifications/unsubscribe/AEozu_klpAGprJ8m0MLpqczdXm2c16ndks5qOl8mgaJpZM4I437K
>    3. https://github.com/artur-shaik/vim-javacomplete2/issues/249#issuecomment-228010066

-- 
Best regards,
Artur Shaikhullin
