### ISSUE TITLE
JavaComplete2 : TextChangedI feature needs vim version >= 7.4.143

### ISSUE THREAD

**Issue by crazy-canux** [artur-shaik/vim-javacomplete2#250]
## Actual behavior (Required!)
when i write new java file show me:

JavaComplete2 : TextChangedI feature needs vim version >= 7.4.143
Press ENTER or type command to continue

## Expected behavior (Required!)
write java code with vim without errors or warnings.

## The steps to reproduce actual behavior (Required!)
 1. use vundle to install this plugin
 2. write "autocmd FileType java,jsp setlocal omnifunc=javacomplete#Complete" in .vimrc
 3. use vim to open new file "test.java"

## Environment (Required!)
 * OS:   ubuntu14.04
 * Vim version: VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:47)
Included patches: 1-52
 * Neovim version:

## Q&A
* Yes, I tried minimal .vimrc configuraion.
* Yes, I have enabled logs with `JCdebugEnableLogs` and can put here content of `JCdebugGetLogContent` command, if you need.
* Even, if you wish, I can set `g:JavaComplete_JavaviDebug` to `1`, than set `g:JavaComplete_JavaviLogfileDirectory`, and put here server logs, too.

**Comment by wsdjeg** [comment]
your vim is too old, please install vim from 
https://github.com/vim/vim-win32-installer
it is daily build version of vim

and javacomplete2 need vim has TextChangedI feature, that means your vim version must > 7.4.143

**Comment by crazy-canux** [comment]
Ok， thanks.

But, where can I get this  >7.4.143 ?
I am using ubuntu14.04, not windows.
I didn't find it    https://github.com/vim/vim/tree/v7.0232

**Comment by wsdjeg** [comment]
if you are using linux, I think it is easy buildding vim from source.
see my config for vim buildding;
https://github.com/wsdjeg/DotFiles/blob/master/build_vim.sh

and the build FAQ for ubuntu
https://github.com/wsdjeg/DotFiles/blob/master/stack/linux.md
Q:How to build vim from source?

**Comment by crazy-canux** [comment]
Well, I see.
Just one question.
How to enable all functions?

**Comment by crazy-canux** [comment]
configure: WARNING: unrecognized options: --enable-sniff

**Comment by crazy-canux** [comment]
Fixed. Thanks.
