### ISSUE TITLE
Deoplete source is slow

### ISSUE THREAD

**Issue by DonnieWest** [artur-shaik/vim-javacomplete2#256]
## Actual behavior (Required!)
When deoplete source is used, completions come back slower than when we use the omni completion directly

## Expected behavior (Required!)
Deoplete source should be on par or even faster than when omni completion is used

## The steps to reproduce actual behavior (Required!)
 1. Setup Deoplete as listed in the wiki
 2. Deoplete completes quickly
 3. Remove `let g:deoplete#ignore_sources._ = ['javacomplete2']` which enables the deoplete source included in javacomplete2
 4. Deoplete completes slowly

I also think that it is very odd that the javacomplete2 wiki for tells you to disable the source that we have in javacomplete2. I've only recently begun to use Deoplete but I'm more than willing to help find a solution to this problem

Also, thanks to @wsdjeg for showing me the light with Deoplete :+1: 

## Environment (Required!)
 * OS: Archlinux
 * Vim version: 
 * Neovim version: 1.4

## Q&A
* Yes, I tried minimal .vimrc configuration.
* Yes, I have enabled logs with `JCdebugEnableLogs` and can put here content of `JCdebugGetLogContent` command, if you need.
* Even, if you wish, I can set `g:JavaComplete_JavaviDebug` to `1`, than set `g:JavaComplete_JavaviLogfileDirectory`, and put here server logs, too.

**Comment by artur-shaik** [comment]
@wsdjeg , any thougths?

**Comment by wsdjeg** [comment]
I can not reproduce this issue, I also use neovim in archlinux, BTW, I in `javacomplete2.py` instead of `omni.py` source. there is many differences between javacomplete2 source and omni source, javacomplete2 source is asyc, and will not block your cursor before the popupmenu was opened. There is a g:var for how long deoplete wait for user type into chars before popupmenu opend.

**Comment by wsdjeg** [comment]
here is my config
https://github.com/wsdjeg/DotFiles/blob/master/config/nvim/config/plugins/deoplete.vim
By default ` g:settings.enable_javacomplete2_py == 1`

**Comment by DonnieWest** [comment]
@wsdjeg with those settings, the problem has completely gone away! I'd love it if they were added to the wiki :)

If desired, I can do it. For now I'll close this out. Thanks for the help!

**Comment by artur-shaik** [comment]
@DonnieWest, yeah, it would be great.

**Comment by lkyhfx** [comment]
@wsdjeg ,the link is broken, can you update the link?

**Comment by wsdjeg** [comment]
sorry， The vim config is split as SpaceVim now，https://github.com/SpaceVim/SpaceVim
