### ISSUE TITLE
Open suggestions automatically after indicator

### ISSUE THREAD

**Issue by CodingJonas** [artur-shaik/vim-javacomplete2#260]
Currently I always have to activate javacomplete2 with a key sequence in order to open the suggestions and choose one of them.
As the plugin recognizes indicators, how can I make it open the suggestions automatically?

 * OS: Ubuntu 16.04
 * Vim version: 7.4
I use GVim

**Comment by DonnieWest** [comment]
Since you're on Gvim, I would recommend using a third party tool such as [Neocomplete](https://github.com/Shougo/neocomplete.vim) or [YouCompleteMe](https://github.com/Valloric/YouCompleteMe), automatically opening the suggestions is probably out of the scope of this plugin :)

**Comment by artur-shaik** [comment]
Yeah, not really related to jc2.
Here is my config for YouCompleteMe:
```
 Plug 'Valloric/YouCompleteMe' "{{{2
 " let g:ycm_server_log_level = 'debug'
 let g:ycm_semantic_triggers =  {
     \   'c' : ['->', '.'],
     \   'objc' : ['->', '.'],
     \   'ocaml' : ['.', '#'],
     \   'cpp,objcpp' : ['->', '.', '::'],
     \   'perl' : ['->'],
     \   'php' : ['->', '::'],
     \   'cs,javascript,d,python,perl6,scala,vb,elixir,go' : ['.'],
     \   'java,jsp' : ['.', '::'],
     \   'vim' : ['re![_a-zA-Z]+[_\w]*\.'],
     \   'ruby' : ['.', '::'],
     \   'lua' : ['.', ':'],
     \   'erlang' : [':'],
     \ }

 let g:ycm_global_ycm_extra_conf = '~/.ycm_extra_conf.py'
 let g:ycm_confirm_extra_conf = 0
 let g:ycm_collect_identifiers_from_tags_files = 1
 let g:ycm_autoclose_preview_window_after_completion = 1
```
