### ISSUE TITLE
Error compiling server, followed by "Pattern not found" for imported classes

### ISSUE THREAD

**Issue by adamski** [artur-shaik/vim-javacomplete2#262]
## Actual behavior (Required!)
call `:JCserverCompile`
Get the following output
```
Error detected while processing function javacomplete#server#CompilationJobHandler:
line    9:
Note: Some input files use unchecked or unsafe operations.
```
Completion does not work for imported classes. Output is  `Pattern not found`

## Expected behavior (Required!)

call `:JCserverCompile`
No errors!
Completion works for imported classes.

## Environment (Required!)
 * OS: OSX 10.11.4
 * Neovim version: 0.1.5
 * JDK 1.8

**Comment by artur-shaik** [comment]
Hm, can you try compile it manually? With maven, if it possible

**Comment by artur-shaik** [comment]
Reopen on demand.
