### ISSUE TITLE
Can't get class complection from the log4j  jar package, import package complection can work well.

### ISSUE THREAD

**Issue by duanqiaobb** [artur-shaik/vim-javacomplete2#266]
I have equiped the lib path use the   JavaComplete_LibsPath configuration option: (as this)

` let g:JavaComplete_LibsPath="/mnt/D/Developer/WorkPlace/Personal-Workplace-Temp/Java/AntTest/lib/:"  `

And I also put my jar package file in my lib directory.My directory structure like this:

```shell
├── build
│   ├── classes
│   │   ├── com
│   │   │   └── foo
│   │   │       └── Bar.class
│   │   └── oata
│   │       ├── HelloWorld2.class
│   │       └── HelloWorld.class
│   └── jar
│       └── HelloWorld2.jar
├── build0_backup.xml
├── build1_backup.xml
├── build.xml
├── lib
│   └── log4j-1.2.17.jar
├── myMainfest
└── src
    ├── com
    │   └── foo
    │       └── Bar.java
    └── oata
        ├── HelloWorld2.java
        └── HelloWorld.java
   ```

I was editing the HelloWorld2 class , the class content is :

 ```java
package oata;

import org.apache.log4j.BasicConfigurator;
import org.apache.log4j.Logger;
import com.foo.Bar;

public class HelloWorld2 {
    
    static Logger logger = Logger.getLogger(HelloWorld2.class);
    
    public static void main(String[] args){
        //set up a simple configuration that logs on the console.
        BasicConfigurator.configure();
        logger.info("hello world");
        Bar bar  = new Bar();
        bar.doIt();
    }
}
```

It seems that javacomple2 plugin could realize this jar package's existence .Because I  could get the correct complection when I typed import clause. For example , When I typed the  **import org.apache.log4j.** , there would be a complection  hint for me with "Logger" after the peroid.

But it is odd that I can't get any complection information  after the "."  except all the qualified namespace when I typed "BasicConfigurator" or "logger". 

My OS Environment (Required!)
 * OS:  **Ubuntu 16.04**
 * Vim version: **VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 16 2016 10:50:38)** 

#### What's more, as the requirement, I had enabled the debug mode and got the debug information as follows , after the "JCcacheClear" and "rm -rf ~/.cache/javacomple2/" operations.

**try to get the complection after BasicConfigurator**

```vimscript
1208.539992 [complete] complete after dot. expr: BasicConfigurator.
1208.540623 [collector] get declared class name for: "BasicConfigurator"
1208.574357 [complete] search member. name: BasicConfigurator, kind: 2, outputkind: 0
1208.575024 [complete] F3. "BasicConfigurator.|"  typename: ""
1208.575054 [complete] F4. "TypeName.|"
1208.575106 [collector] get class info. class: BasicConfigurator
1208.585438 [server] communicate: -E "org.apache.log4j.BasicConfigurator" [collector#FetchInfoFromServer]
1208.715478 [server] 
1208.716034 [complete] F5. "package.|"
1208.716120 [complete] get members. fqn: BasicConfigurator
1208.716860 [server] communicate: -p "BasicConfigurator" [collector#FetchInfoFromServer]
1208.851280 [server] {'BasicConfigurator':{'tag':'PACKAGE','subpackages':['org.apache.log4j',],'classes':[]},}
1208.851951 [complete] package info in directories. package: BasicConfigurator
1208.852438 [complete] get source dirs. filepath: /mnt/D/Developer/WorkPlace/Personal-Workplace-Temp/Java/AntTest/src/oata/HelloWorld2.java
1208.866899 [complete] finish completion  0.331331s
```

**try to get the complection after Logger**

```vimscript
1553.766811 [context] context: CONTEXT_AFTER_DOT
1553.766857 [context] dot expression: logger.
1553.766910 [complete] complete after dot. expr: logger.
1553.767211 [collector] get declared class name for: "logger"
1553.788496 [complete] F3. "logger.|"  typename: "Logger"
1553.788536 [collector] get class info. class: Logger
1553.798788 [server] communicate: -E "org.apache.log4j.Logger" [collector#FetchInfoFromServer]
1553.924228 [server] 
```

I don't know why.......

**My complete screenshot**
![jar-complement-issue](https://github.com/duanqiaobb/vim-javacomplete2/raw/master/bugs/jar-complements-issue/jar-complements-issue.png)

**Comment by artur-shaik** [comment]
Don't you use maven or gradle?

**Comment by wsdjeg** [comment]
@duanqiaobb please open a java file, and try completion, if it does not work, than show me the value of `g:JavaComplete_LibsPath`, you can use `:let @+=g:JavaComplete_LibsPath`, then copy to here.

**Comment by duanqiaobb** [comment]
@artur-shaik After using maven, this problem dispeared.But It really makes my vim running slowly.

**Comment by duanqiaobb** [comment]
@wsdjeg  the value g:JavaComplete_LibsPath I got from my vim is  as follows:
```vimscript
     g:JavaComplete_LibsPath  /mnt/D/Developer/WorkPlace/Personal-Workplace-Temp/Java/vimscriptSample/lib::.                                                                                       
```
I just get it by typing `let g:JavaComplete_LibsPath` in the command mode .
However I just get nothing echoed by using  `:let @+=g:JavaComplete_LibsPath`

**Comment by wsdjeg** [comment]
can you change the to `let g:JavaComplete_LibsPath="/mnt/D/Developer/WorkPlace/Personal-Workplace-Temp/Java/AntTest/lib/"

**Comment by duanqiaobb** [comment]
No any helps, after change that , It only hints that `Pattern not found `.

**Comment by artur-shaik** [comment]
Duplicate #267
