### ISSUE TITLE
javavi cannot compilet / socket cannot be open - manually solved issue?

### ISSUE THREAD

**Issue by alnavv** [artur-shaik/vim-javacomplete2#273]
## Actual behavior (Required!)

javavi cannot compile + socket cannot be open (for completion)
## Expected behavior (Required!)

code completion
## The steps to reproduce actual behavior (Required!)
1. Install latest version of the plugin  
2. usinng map  **<Plug>jI** for triggering completion
3. ...
## Environment (Required!)
- OS: debian jessie
- Vim version: 7.4
- Neovim version: 0.1.5
# Solution

Following one of the  threads exposing similar problem, https://github.com/artur-shaik/vim-javacomplete2/issues/165, came up wiht manual compilation:

cd /$HOME/.config/nvim/plugged/vim-javacomplete/libs/javavi; mvn compile

afterwards the plugin works as expected.

Note: I may enable logs (as described in Q&A), minimun vimrc conf, and try to reproduce again if you need so ...
## Q&A
- Yes, I tried minimal .vimrc configuraion.
- Yes, I have enabled logs with `JCdebugEnableLogs` and can put here content of `JCdebugGetLogContent` command, if you need.
- Even, if you wish, I can set `g:JavaComplete_JavaviDebug` to `1`, than set `g:JavaComplete_JavaviLogfileDirectory`, and put here server logs, too.

**Comment by artur-shaik** [comment]
Hi, you can set `let g:JavaComplete_ShowExternalCommandsOutput = 1` to see maven output on automatic compilation. But before, make `mvn clean` in `javavi` folder.

**Comment by alnavv** [comment]
Hi, sorry for a bit of delay (busy times).

I installed everything from scratch, using the option your mentioned (also mvn clean ...), so:
-> now it works again. I received the message "socket cannot be opened" once, but it worked (javavi compiled).
-> <Plug>jI triggers imports correctly, but also shows the message: "import already exists". It doest not really exist, and although it triggers the "imports" correctly  also shows that wrong message.

Also:
-> In a (relatively) big project Maven/Gradle the plugin is not working at all for importing classes/functions in dependencies  located outside of the git repo where the project resides.
Regarding this last issue, as soon as I will gain more knowledge about Gradle/Maven (I am a C++ dev), i will let you know the exact problem.

**Comment by artur-shaik** [comment]
You see, when `socket cannot be opened` happens, plugin try to start server, if it doesn't find server, it run compilation. So, actually, it is not an issue.

`jI` means to find all imports, so when it find some already imported, it writes `import already exists`. So this is not an issue, as well. If you want find import on class under cursor, you should use `ji`.

May be it would be better to make this messages suppressed in future.

**Comment by artur-shaik** [comment]
Will close for now, feel free to open if required.
