### ISSUE TITLE
Class creation command

### ISSUE THREAD

**Issue by artur-shaik** [artur-shaik/vim-javacomplete2#274]
One frustrating thing with this plugin, that I need create classes by hand, that's really slow down me. Here some work and ideas on it.

Commands, already implemented (not pushed, yet):

Suppose we in class with package 'org.foo.bar'

`NewClass` - to open/create class relative to current, with fqn 'org.foo.bar.NewClass'
`baz.NewClass` - to open/create class relative to current, with fqn 'org.foo.bar.baz.NewClass'
`/org.baz.NewClass` - to open/create class with fqn 'org.baz.NewClass'
`/foo.bas.NewClass` - to open/create class with fqn 'org.foo.bas.NewClass'
`/com.bar.NewClass` - to open/create class with fqn 'com.bar.NewClass'

Some ideas:

Some funky stuff can be done here. Something like:

`NewClass extends List` - create class with auto import and abstract classes

or may be:

`NewClass(String foo, Integer bar)` - create class with private fields and accessors.

maybe we can add:

`NewClass(String foo, Integer bar):constructor(foo, bar):equals:hashCode:toString` - generate constructor, and standart methods.

even more ideas:

`test:NewClassTest` - same package but in test subfolder or `androidTest:NewClassTest` and etc.

Any thoughts?

**Comment by DonnieWest** [comment]
All of that sounds pretty fantastic. I too have found class creation rather slow in my daily workflow. I do request though:

1. Generate class code within an empty file w/ package
2. Generate inner classes

Both might be slightly crazy though. With the empty file you have to infer the package from the path. Inner classes have their own problems.

**Comment by artur-shaik** [comment]
Yeah, nice proposals. For now, not really know, how to find package name from empty file. But definetly, we can find right way. As a last resort, we can try to guess, or give optional values to choose, for user.

**Comment by DonnieWest** [comment]
Yeah, it'd be difficult for generic java projects. I'd probably default to the current directory path without standard directories like src and java being counted

for example

`app/src/java/com/myapp/api` becomes `com.myapp.api`

But even that has a crazy number of edge cases. Another idea would be to allow the user to pass in the main package name and cache that somehow. That would be nice for the user to ensure that things are working appropriately but also for third party plugins (like my VimStudio) that can derive the package name through separate means.

Thanks though for opening up the discussion and for continuing to maintain vim-javacomplete2!

**Comment by artur-shaik** [comment]
Yes, we can guess the package basing on standards. If there are not standart dirs, so we can ask user, I think.

Btw, thanks for participating )

**Comment by albinscode** [comment]
Hi, 
Yes, this can be interesting to create a class from scratch. And if you have already done part of it, it's always interesting :)
On my side I've got a snippet approach (using snipmate) to generate the class skeleton but of course the package is not guessed...
So I'll have a look to this new feature with interest!
Thanks again!

**Comment by artur-shaik** [comment]
@albinscode , I'll do some work on it in [class-creation](https://github.com/artur-shaik/vim-javacomplete2/tree/class-creation) branch, but it could be buggy.
