### ISSUE TITLE
Get some errors when start vim or neovim with java file.

### ISSUE THREAD

**Issue by wsdjeg** [artur-shaik/vim-javacomplete2#277]
error message:
```

Messages maintainer: Bram Moolenaar <Bram@vim.org>
Error detected while processing function javacomplete#Start[1]..javacomplete#server#Start:
line   40:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/wsdjeg/.cache/vimfiles/repos/github.com/artur-shaik/vim-javacomplete2/autoload/javavibridge.py", line 56, in setupServer
    "a")
IOError: [Errno 2] No such file or directory: '/tmp/javavi_log/javavi_stdout.log'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/wsdjeg/.cache/vimfiles/repos/github.com/artur-shaik/vim-javacomplete2/autoload/javavibridge.py", line 56, in setupServer
    "a")
IOError: [Errno 2] No such file or directory: '/tmp/javavi_log/javavi_stdout.log'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/wsdjeg/.cache/vimfiles/repos/github.com/artur-shaik/vim-javacomplete2/autoload/javavibridge.py", line 56, in setupServer
    "a")
IOError: [Errno 2] No such file or directory: '/tmp/javavi_log/javavi_stdout.log'
```

**Comment by artur-shaik** [comment]
Thanks

**Comment by gkapfham** [comment]
Hello @artur-shaik! Thank you so much for developing this plugin. I used it on a regular basis when I am programming in Java. Like @wsdjeg, I too recently experience the aforementioned issue. Now after I have updated the plugin, I always see the following error message when I try to save a file:

```
could not open socket, try again                                    
could not open socket, try again
```

I can confirm that I see exactly the same error message on both vim and nvim. Currently, I am running nvim and vim in tmux. I have also done several different debugging steps, like removing and reinstalling the plugin, only to receive exactly the same error message when I try to save a file. Finally, it seems as though the plugin is no longer working correctly; features that I used in the past still do not work now.

I can post additional details as needed. If you have time, could you please comment on whether on not these errors are related to the fix mention in this thread? Again, thanks so much for your help!

**Comment by artur-shaik** [comment]
Hi @gkapfham , can you try to run `JCserverCompile`.  But before it, please, make `let g:JavaComplete_ShowExternalCommandsOutput = 1`. So we can see if server compilation is ok.

**Comment by gkapfham** [comment]
Hello @artur-shaik. Thanks again for developing this plugin. I can confirm that when I run the `JCServerCompile` and then attempt to use the plugin that everything works as I intended. So, it seems that this issue is indeed fully resolved. Thanks again for fixing the code that caused the problem.

**Comment by DonnieWest** [comment]
@artur-shaik it seems like lots of our issues are the result of the application needing to be compiled when the java code changes. It might be a good idea to version the server and check if the version of the server is the same as when it was last compiled. If it's not, recompile.

Another plugin that does this is [fzf.vim](https://github.com/junegunn/fzf.vim)

**Comment by wsdjeg** [comment]
good idea!

**Comment by artur-shaik** [comment]
@DonnieWest good point. I thought about it some time ago, and effectively forgot to implement it.
