### ISSUE TITLE
Complete of import does not work

### ISSUE THREAD

**Issue by skubyooru** [artur-shaik/vim-javacomplete2#283]
Hi! My English is poor) I use the google-translate.

I use vim8.0, linux.  My pom.xml:
`...
 11     <dependencies> 
...
 17         <dependency>
 18             <groupId>commons-digester</groupId>
 19             <artifactId>commons-digester</artifactId>
 20             <version>2.0</version>
 21         </dependency>
...
 22     </dependencies>
...`
jar exist in ~/.m2/repository. But complete of import not work:
http://storage7.static.itmages.ru/i/16/1117/h_1479362939_2623733_c52de645ac.jpg

But complete of object work:
http://storage4.static.itmages.ru/i/16/1117/h_1479362830_1917880_f55a6d2cf3.jpg

I did "let g:JavaComplete_LibsPath", but it does not help.

**Comment by artur-shaik** [comment]
Hm, try to do `JCclasspathGenerate` and wait some time.

**Comment by skubyooru** [comment]
It works! Thank you!
