### ISSUE TITLE
no-argument method completion does not add closing parentice but probably should

### ISSUE THREAD

**Issue by struktured** [artur-shaik/vim-javacomplete2#289]
## Actual behavior (Required!)
```Java
Object o = "hi";
int code = o.ha
 // omnifunc invocation now triggered
// I select "hashCode()"

int code o.hashCode(

```
## Expected behavior (Required!)
```Java
Object o = "hi";
int code = o.ha
 // omnifunc invocation now triggered
// I select "hashCode()"

int code o.hashCode()
```
## The steps to reproduce actual behavior (Required!)
 See above code

## Environment (Required!)
 * OS: Linux
 * Vim version: n/a
 * Neovim version: 0.1.6

## Q&A
* Yes, I tried minimal .vimrc configuraion.
* Yes, I have enabled logs with `JCdebugEnableLogs` and can put here content of `JCdebugGetLogContent` command, if you need.
* Even, if you wish, I can set `g:JavaComplete_JavaviDebug` to `1`, than set `g:JavaComplete_JavaviLogfileDirectory`, and put here server logs, too.

**Comment by DonnieWest** [comment]
I'm not sure this is within the scope of Javacomplete2 - an excellent plugin that does what you want though is [auto-pairs](https://github.com/jiangmiao/auto-pairs) :)

**Comment by struktured** [comment]
I get you but I would argue it's not really the desired behavior for this plugin either. I don't think anyone wants it to complete the way it does now for functions with no arguments. I will check out auto-pairs, regardless, though. Thanks @DonnieWest .

**Comment by DonnieWest** [comment]
@struktured Ah, I see. Yeah, it does make sense to automatically add the ending parenthesis when autocompleting functions without arguments. Sorry for jumping the gun there

**Comment by wsdjeg** [comment]
@artur-shaik I do not think it is the bug of javacomplete. 

@struktured you can use neosnippet.vim, it will auto close pairs if the method has no args, also it will expand the args if the method has args. BTW you can use tab jump between the args.

**Comment by wsdjeg** [comment]
see here for config.

https://github.com/Shougo/neosnippet.vim/issues/359

**Comment by DonnieWest** [comment]
@wsdjeg see my comment. I thought the same thing, but, if a method doesn't have any arguments the autocompletion should autoclose the parenthesis. I don't think another plugin is necessary for this :)

**Comment by wsdjeg** [comment]
got it. just neeb change item.word to something like toString(). if the method has no args.

**Comment by artur-shaik** [comment]
@wsdjeg yeah, I just want to check implementation, and if it easy enough, we can close brace on no args methods.
