### ISSUE TITLE
No Javavi library classes found

### ISSUE THREAD

**Issue by holens** [artur-shaik/vim-javacomplete2#296]
when I open vim, There is a error.
No Javavi library classes found, it means that we couldn't compile it. Do you have JDK8+ installed?

I'm sure that my centos system has java8.

 * OS: Centos 7
 * Vim version: 8.0

Where there is wrong?

**Comment by artur-shaik** [comment]
#220 #165

**Comment by holens** [comment]
thank you for your help. this issue has been resolved according to #165

**Comment by artur-shaik** [comment]
Nice, can we close it?
