### ISSUE TITLE
Can't work with NeoVim

### ISSUE THREAD

**Issue by eschao** [artur-shaik/vim-javacomplete2#297]
## Actual behavior (Required!)
Installed it with VimPlug in Neovim, following the doc to configured it in vim profile, but when I opened a Java file, the error vim reported is:

```"src/com/client/RandomClient.java" 64L, 2373C
Error detected while processing FileType Auto commands for "java":
E117: Unknown function: javacomplete#Start
```
My configuration for java2complete:

```
autocmd FileType java setlocal omnifunc=javacomplete#Complete
let g:JavaComplete_LibsPath = '~/Software/android-sdk/platforms:/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home'
let g:JavaComplete_SourcesPath = '~/Software/android-sdk/sources'
let g:JavaComplete_ShowExternalCommandsOutput = 1
```

I googled about this error but nothing found, Could you please tell me how to fix it? I

## Environment (Required!)
 * OS: macOS
 * Vim version: 7.4.898
 * Neovim version: 0.1.7

**Comment by wsdjeg** [comment]
can not reproduced. can you show the minivimrc.

**Comment by eschao** [comment]
@wsdjeg You mean my vimrc file? thanks!

**Comment by wsdjeg** [comment]
I mean how do you install this plugin, and what is the result of `:echo globpath(&rtp,'autoload/javacomplete.vim')` in nvim

**Comment by wsdjeg** [comment]
and `:exe 'e '. globpath(&rtp,'autoload/javacomplete.vim')` in nvim should open javacomplete.vim , and you will see `javacomplete#Start` func in it.

**Comment by artur-shaik** [comment]
@eschao seems like wrong configuration with VimPlug, it didn't load plugin script. So @wsdjeg is right, show us your vimrc.

**Comment by eschao** [comment]
I can use it in vim. Forget Neovim. I will close it
