### ISSUE TITLE
When I switch the user, There is something wrong when recompile the vim-javacomplete2 

### ISSUE THREAD

**Issue by holens** [artur-shaik/vim-javacomplete2#298]
There are two users in my centos system.
     *worker
     *production
I use the user of worker to execute mvn compile is ok at first time. 
I want to complement java Code when I use the user of  production, but when I  execute mvn compile ,there is some  failure.

**Comment by holens** [comment]
.vimrc config:

**Comment by holens** [comment]
.vimrc config:

call vundle#begin()
Plugin 'artur-shaik/vim-javacomplete2'
call vundle#end()
autocmd Filetype java setlocal omnifunc=javacomplete#Complete
let g:JavaComplete_JavaCompiler="/usr/lib/jvm/java-1.8.0-openjdk/bin"

**Comment by holens** [comment]
the error as follow:

**Comment by holens** [comment]
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for kg.ash.javavi:javavi:jar:1.0-SNAPSHOT
[WARNING] 'dependencies.dependency.systemPath' for kg.ash.javavi.apache.logging.log4j:log4j-api:jar should not point at files within the project directory, ${basedir}/../javavi_log4j-api.jar will be unresolvable by dependent projects @ line 28, column 25
[WARNING] 'dependencies.dependency.systemPath' for kg.ash.javavi.apache.logging.log4j:log4j-core:jar should not point at files within the project directory, ${basedir}/../javavi_log4j-core.jar will be unresolvable by dependent projects @ line 35, column 25
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building javavi 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ javavi ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ javavi ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 57 source files to /home/hadoop/.vim/bundle/vim-javacomplete2/libs/javavi/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.515s
[INFO] Finished at: Tue Dec 27 14:07:24 CST 2016
[INFO] Final Memory: 6M/16M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project javavi: Fatal error compiling: 无效的目标发行版: 1.8 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by wsdjeg** [comment]
@holens this should be issue of maven instead of javacomplete2, can you run `mvn compile` in production user?

**Comment by holens** [comment]
@wsdjeg  it's ok in worker user, but as the same config in production  user is error.

**Comment by wsdjeg** [comment]
@holens as I saied above it should be issue of maven project, what is the `mvn version` and `javac version` in each user?

**Comment by holens** [comment]
@wsdjeg oh,thanks .javac version is 1.7
