### ISSUE TITLE
I want to automatically popup references with press key "."

### ISSUE THREAD

**Issue by Markers** [artur-shaik/vim-javacomplete2#305]
Hello~

first, Very thank you for this tools.

Sorry, but I am not good at English, so please understand me.

I'll jot it down shortly.

i found it #46 issue.

so i knew it. x-c x-o after "." key

but i want to automatically popup references with press key "."

Can you tell me how I can do what I want?

**Comment by artur-shaik** [comment]
Hi, consider to use YouCompleteMe or neocomplete... or anything else to automatically trigger completion.
