### ISSUE TITLE
(Windows 10) During plugin load it throws error

### ISSUE THREAD

**Issue by asknet** [artur-shaik/vim-javacomplete2#306]
## Actual behavior (Required!)

Error detected while processing function javacomplete#Start[1]..javacomplete#server#Start:
line   44:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Parrot\.vim\bundle\javacomplete2\autoload\javavibridge.py", line 55, in setupServer
    os.mkdir(logdir)
FileNotFoundError: [WinError 3] The system cannot find the path specified: '\\tmp\\javavi_log'

## Expected behavior (Required!)
Plugin load should be completed successful in windows

## The steps to reproduce actual behavior (Required!)
 1. ... Just normal plugin install on windows should give this error, because \\tmp folder doesn't exist in windows. 
 2. ...
 3. ...

## Environment (Required!)
 * OS: Windows 10
 * Vim version: 8.0.134
 * Neovim version:

## Q&A
* Yes, I tried minimal .vimrc configuraion.
* Yes, I have enabled logs with `JCdebugEnableLogs` and can put here content of `JCdebugGetLogContent` command, if you need.
* Even, if you wish, I can set `g:JavaComplete_JavaviDebug` to `1`, than set `g:JavaComplete_JavaviLogfileDirectory`, and put here server logs, too.

**Comment by artur-shaik** [comment]
Should be fixed on develop branch
