### ISSUE TITLE
(Windows 10) Plugin load error, invalid arguments for function addd

### ISSUE THREAD

**Issue by asknet** [artur-shaik/vim-javacomplete2#307]
## Actual behavior (Required!)
After doing workaround for Issue#306(by setting let g:JavaComplete_JavaviLogDirectory), I get the below error

Error detected while processing function javacomplete#Start[1]..javacomplete#server#Start:
line   19:
E116: Invalid arguments for function add

## Expected behavior (Required!)
Plugin load should be successfull

## The steps to reproduce actual behavior (Required!)
 1. ...
 2. ...
 3. ...

## Environment (Required!)
 * OS: Windows 10
 * Vim version: 8.0.314
 * Neovim version:

## Q&A
* Yes, I tried minimal .vimrc configuraion.
* Yes, I have enabled logs with `JCdebugEnableLogs` and can put here content of `JCdebugGetLogContent` command, if you need.
* Even, if you wish, I can set `g:JavaComplete_JavaviDebug` to `1`, than set `g:JavaComplete_JavaviLogfileDirectory`, and put here server logs, too.

**Comment by artur-shaik** [comment]
Should be fixed on develop branch
