### ISSUE TITLE
it can't work?so confuse

### ISSUE THREAD

**Issue by SilgerZuo** [artur-shaik/vim-javacomplete2#308]
## Actual behavior (Required!)
when installed with vundle and open .java file firsttime,show the error:
function <SNR>61_JobVimOnErrorHandler[3]..javacomplete#server#CompilationJobHandler runtime error
,and when input java code,vim-javacomplete2 doesn't work;

## Expected behavior (Required!)
i expect vim-javacomplete2 work ,however, it dosen't
## The steps to reproduce actual behavior (Required!)
 1. ... add "Pluginartur-shaik/vim-javacomplete2" to the .vimrc
 2. ...add "autocmd FileType java setlocal omnifunc=javacomplete#Complete" to my .vimrc file
 3. ... run the ":PluginInstall"
 4. ... then .when i open my helloworld.java;,it shows the error "function <SNR>61_JobVimOnErrorHandler[3]..javacomplete#server#CompilationJobHandler runtime "

## Environment (Required!)
 * OS:ubuntu16.04
 * Vim version:7.4
 * Neovim version:not installed

## Q&A
* Yes, I tried minimal .vimrc configuraion.
* Yes, I have enabled logs with `JCdebugEnableLogs` and can put here content of `JCdebugGetLogContent` command, if you need.
* Even, if you wish, I can set `g:JavaComplete_JavaviDebug` to `1`, than set `g:JavaComplete_JavaviLogfileDirectory`, and put here server logs, too.

**Comment by artur-shaik** [comment]
Hm, can you post screenshot of that runtime error?
