### ISSUE TITLE
Getting lots of non useful messages

### ISSUE THREAD

**Issue by oblitum** [artur-shaik/vim-javacomplete2#31]
Just installed it, quite nice! I'm trying it coupled with vim-android and YCM.

One thing that's annoying me a bit is that it's generating non-useful messages like `creating socket` and `Cannot open file "/Users/francisco/.vim/plugged/vim-javacomplete2/libs/javavi/target/classes/*.java"`, even though the completion is being functional these messages keep getting showing up. What about providing a silence mode or removing them?

**Comment by artur-shaik** [comment]
Agreed. Will work on it.

**Comment by artur-shaik** [comment]
Please, can you pull last commits and try again. Is there anything unnecessary?

**Comment by oblitum** [comment]
Thanks! I'll check asap when I get back home late night.

**Comment by oblitum** [comment]
Thanks!
