### ISSUE TITLE
vim-javacomplete2 not working on Ubuntu 16.04 x64 ?

### ISSUE THREAD

**Issue by zhaochenyou** [artur-shaik/vim-javacomplete2#311]
## Actual behavior (Required!)
I use vundle to manage vim plugins, vim version 7.4.
after install javacomplete2 successfully, I use:
mvn -f "/home/zhaochenyou/.vim/bundle/vim-javacomplete2/libs/javavi/pom.xml" compile
and it's success.
But still no completion.

## Expected behavior (Required!)
auto completion

## The steps to reproduce actual behavior (Required!)
 1. install javacomplete2 with vundle
 2. open a Test.java and write something like "System.out.println("Hello World")", see if it's working.

## Environment (Required!)
 * OS: Ubuntu 16.04 x64
 * Vim version: 7.4
 * jdk version: OpenJDK 8

## Q&A
I set `g:JavaComplete_JavaviDebug` to `1`, and set `g:JavaComplete_JavaviLogfileDirectory` to `~/`, but I didn't find server logs.

**Comment by artur-shaik** [comment]
You can call `JCdebugEnableLogs` after you open java file. Then execute completion, than call `JCdebugGetLogsContent`. Show the content, please.

**Comment by wsdjeg** [comment]
@zhaochenyou 
I think you should complete in a class, not in an empty file
try with `vim  Foo.java`, and write in 
```java
class Foo{
       public static void test(){
             System.           // complete should works well here.
       }
}
```
```

**Comment by zhaochenyou** [comment]
it still not working...

**Comment by artur-shaik** [comment]
Have you read my comment?

**Comment by adelarsq** [comment]
Same problem here on Windows 10. To solve I had to compile manually the ```javavi``` lib.

**Comment by zhaochenyou** [comment]
@adelarsq please teach me, how to manually compile the library.

**Comment by artur-shaik** [comment]
```
cd ~/.vim/bundles/vim-javacomplete2/libs/javavi
mvn compile
```

**Comment by garydwatson** [comment]
Thanks, compiling the javaavi files by hand worked for me, much appreciated :)
