### ISSUE TITLE
Gradle classpath is truncated

### ISSUE THREAD

**Issue by DonnieWest** [artur-shaik/vim-javacomplete2#312]
## Actual behavior (Required!)

When generating a new classpath using Gradle, if the output is sufficiently large the classpath is truncated

Example of gradle output
http://pastebin.com/BXxbTbfA

Example of classpath after
http://pastebin.com/s5ZfUQHU

## Expected behavior (Required!)

Classpath shouldn't be truncated 

## The steps to reproduce actual behavior (Required!)
 1. Open Gradle project with lots of dependencies
 2. Run `:JCclasspathGenerate`
 3. Check classpath or cache file

## Environment (Required!)
 * OS: Archlinux
 * Vim version:
 * Neovim version: NVIM v0.2.0-779-g58b5e1438

## Q&A
* Yes, I tried minimal .vimrc configuraion.
* Yes, I have enabled logs with `JCdebugEnableLogs` and can put here content of `JCdebugGetLogContent` command, if you need.
* Even, if you wish, I can set `g:JavaComplete_JavaviDebug` to `1`, than set `g:JavaComplete_JavaviLogfileDirectory`, and put here server logs, too.

## Notes

https://github.com/artur-shaik/vim-javacomplete2/blob/master/autoload/javacomplete/classpath/gradle.vim#L19

Logging the `s:gradleOutput` just before this line shows that the classpath line is split for some reason

**Comment by artur-shaik** [comment]
@wsdjeg, as I remember, you did something with this problem, right? Can you participate?

**Comment by wsdjeg** [comment]
it is bug of neovim, but should be fixed, I will look into it.

**Comment by wsdjeg** [comment]
old issue opened here https://github.com/neovim/neovim/issues/4266

**Comment by wsdjeg** [comment]
https://github.com/artur-shaik/vim-javacomplete2/blob/master/autoload/javacomplete/classpath/maven.vim#L56-L61

here is how I fix maven output parse, I will try to do it with gradle.

**Comment by artur-shaik** [comment]
@DonnieWest, can you test with @wsdjeg PR, please?
