### ISSUE TITLE
a little shame to ask, how to trigger completion?

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [artur-shaik/vim-javacomplete2#317]
## Actual behavior (Required!)
not able to trigger completion menu popup. So, how to trigger it? is it auto popup after i enter dot?
JCimportsAddMissing command works, so i think I have installed it right.

## Expected behavior (Required!)
as the gif shows, pop completion menu after dot

## The steps to reproduce actual behavior (Required!)
 1. install the plugin.
 2. config only one line `autocmd FileType java setlocal omnifunc=javacomplete#Complete
`
 3. open a java file, all background work is processing ok. but no popup menu.

## Environment (Required!)
 * OS:MacOS
 * Vim version:
 * Neovim version:0.1.7

## Q&A
* Yes, I tried minimal .vimrc configuraion.
* Yes, I have enabled logs with `JCdebugEnableLogs` and can put here content of `JCdebugGetLogContent` command, if you need.
* Even, if you wish, I can set `g:JavaComplete_JavaviDebug` to `1`, than set `g:JavaComplete_JavaviLogfileDirectory`, and put here server logs, too.

**Comment by FinallyFinancialFreedom** [comment]
C-X C-O will trigger the completion. Can you put this on the git page?
Now i trigger it, but it will fill a default candidate string, i must delete it and then type character to narrow down the candidates. This behaviour is different from the gif.

**Comment by wsdjeg** [comment]
set completeopt-=noselect

:h completeopt

**Comment by FinallyFinancialFreedom** [comment]
thank you. I set `set completeopt=menu,noinsert`
