### ISSUE TITLE
'apiElements' directly is not allowed in gradle3.4. Maybe the gradle has changed

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [artur-shaik/vim-javacomplete2#319]
## Actual behavior (Required!)
gradle project Resolving configuration 'apiElements' directly is not allowed

## Expected behavior (Required!)
works ok

## The steps to reproduce actual behavior (Required!)
 1. use gradle 3.4.1
 2. ...
 3. ...

## Environment (Required!)
 * OS:macos
 * Vim version:
 * Neovim version:0.1.7

## Q&A
* Yes, I tried minimal .vimrc configuraion.
* Yes, I have enabled logs with `JCdebugEnableLogs` and can put here content of `JCdebugGetLogContent` command, if you need.
* Even, if you wish, I can set `g:JavaComplete_JavaviDebug` to `1`, than set `g:JavaComplete_JavaviLogfileDirectory`, and put here server logs, too.

**Comment by DonnieWest** [comment]
I'm not really sure what you're reporting. Can I get a sample app that replicates the issue and the error that it outputs?

**Comment by FinallyFinancialFreedom** [comment]
OK, the zip file is a small gradle project, my gradle version is 3.4.1, and i got "Resolving configuration 'apiElements' directly is not allowed" error when i open App.java file. I'm sure the  gradle has changed something in 3.4.1 so the error occured, but i can not resolved it.
[case.zip](https://github.com/artur-shaik/vim-javacomplete2/files/888785/case.zip)

**Comment by Dissonant-Tech** [comment]
@FinallyFinancialFreedom I got hit with this issue as well. 

As a workaround you can:
1. Set `let g:JavaComplete_GradleExecutable = './gradlew'` in your `.vimrc`
2. Edit your `gradle/wrapper/gradle-wrapper.properties` file and change the gradle version to 3.3

**Comment by DonnieWest** [comment]
Thanks for the feedback and troubleshooting. Looks like this is the result of Gradle making certain configurations unresolvable in 3.4 and I think I know the fix. Hopefully I'll get around to it tonight 

Sorry for the delay

**Comment by DonnieWest** [comment]
@FinallyFinancialFreedom @Dissonant-Tech y'all mind looking over #323 and seeing if that fixes it?

**Comment by FinallyFinancialFreedom** [comment]
@DonnieWest @Dissonant-Tech ,i have tried the new classpath.gradle, it works for me, thank you.
