### ISSUE TITLE
could not open socket, try again

### ISSUE THREAD

**Issue by mvalkon** [artur-shaik/vim-javacomplete2#328]
## Actual behavior (Required!)
Autocompletion is failing. When attempting to autocomplete, an error message `could not open socket, try again` is displayed

## Expected behavior (Required!)
Autocompletion should work

## The steps to reproduce actual behavior (Required!)
 1. open a java file, or create a new one
 2. type `System.` or `import java.`
 3. See an error message

## Environment (Required!)
 * OS: os x
 * Vim version: - 
 * Neovim version: 0.2.0

## Q&A
Here are some logs I collected by:
1. `JCdebugEnableLogs`
2. `JCserverTerminate`
3. `JCserverStart`
4. Type `System.` or `import java.`
5. `JCdebugGetLogContent`

```
 52.609244 [server] start server javac 1.8.0_131
error: Class names, 'kg.ash.javavi.Javavi', are only accepted if annotation processing is explicitly requested
1 error

 52.609913 [server] executing python file: /Users/mvalkonen/.config/nvim/plugged/vim-javacomplete2/autoload/javavibridge.py
 52.784676 [server]   0.168483s to exec "/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/javac -XshowSettings" by Get java settings
 52.784924 [server] server classpath: -cp /Users/mvalkonen/.config/nvim/plugged/vim-javacomplete2/libs/javavi/target/classes:/Users/mvalkonen/.config/nvim/plugged/vim-javacomplete2/libs/javaparser.jar:/Users/mvalkonen/.config/nvim/plugged/vim-javacomplete2/libs/javavi_log4j-api.jar:/Users/mvalkonen/.config/nvim/plugged/vim-javacomplete2/libs/javavi_log4j-core.jar:.:/lib
 52.784957 [server] server arguments:-Ddaemon.port=53422 -Dlog4j.configurationFile=/Users/mvalkonen/.config/nvim/plugged/vim-javacomplete2/libs/javavi/target/classes/log4j2.xml kg.ash.javavi.Javavi -sources /private/tmp/merchant-invoice-delivery/src: -base /Users/mvalkonen/.cache/javacomplete2/ -compiler /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/javac
 61.324363 [context] context: CONTEXT_IMPORT
 61.324395 [context] dot expression: java.
 61.324498 [complete] get members. fqn: java
 61.740195 [server] start server javac 1.8.0_131
```
For some reason setting `let g:JavaComplete_JavaviDebug = 1` and `let g:JavaComplete_JavaviLogfileDirectory='/tmp/jc2'` and subsequently restarting the server does not yield logs in `/tmp/jc2`.

**Comment by artur-shaik** [comment]
Can you check if server was compiled? You can check it in `~/.vim/bundles/vim-javacomplete2/libs/javavi/target/`.

**Comment by mvalkon** [comment]
@artur-shaik The directory is not empty at least. I have compiled the server earlier with `mvn compile`.

**Comment by artur-shaik** [comment]
Look like it cannot run java machine. What if you run `java -cp javavi/target/classes:javavi_log4j-api.jar:javavi_log4j-core.jar:javaparser.jar kg.ash.javavi.Javavi -version` from `libs` directory?

**Comment by mvalkon** [comment]
That seems to work:

```
 libs → java -cp javavi/target/classes:javavi_log4j-api.jar:javavi_log4j-core.jar:javaparser.jar kg.ash.javavi.Javavi -version
2.3.7.3%
```

**Comment by artur-shaik** [comment]
It would be great if you can debug this issue on your OSX, but I really can't say what can be the problem. Seems that server cannot be started. And this line: `error: Class names, 'kg.ash.javavi.Javavi', are only accepted if annotation processing is explicitly requested` is something like the reason of that.

You can put some debug code in `function! javacomplete#server#Start()' method of `server.vim`. If you 
have some specific question, please ask.

**Comment by adelarsq** [comment]
Same problem for me on Windows:

```
2288.118654 [server] executing python file: C:\Users\adelar.queiroz\.vim\plugged\vim-javacomplete2\autoload\javavibridge.py
2288.142146 [server] server classpath: -cp 0;C:\\Users\\adelar.queiroz\\.vim\\plugged\\vim-javacomplete2\\libs\\javaparser.jar;C:\\Users\\adelar.queiroz\\.vim\\plugged\\vim-javacomplete2\\libs\\javavi_log4j-api.jar;C:\\Users\\adelar.queiroz\\.vim\\plugged\\vim-javacomplete2\\libs\\javavi_log4j-core.jar;.;C:\\dev\\java\\jdk8_x64\\lib
2288.142190 [server] server arguments:-Ddaemon.port=58356 -Dlog4j.configurationFile=C:\Users\adelar.queiroz\.vim\plugged\vim-javacomplete2\libs\javavi\target\classes\log4j2.xml kg.ash.javavi.Javavi -sources  -t 300 -base C:\Users\adelar.queiroz\.vim\cache\javacomplete2\ -compiler javac
2294.554043 [context] context: CONTEXT_AFTER_DOT
2294.554116 [context] dot expression: System.
2294.554238 [complete] complete after dot. expr: System.
2294.554829 [collector] get declared class name for: "System"
2294.915549 [complete] search member. name: System, kind: 2, outputkind: 0
2294.916639 [complete] F3. "System.|"  typename: ""
2294.916708 [complete] F4. "TypeName.|"
2294.916773 [collector] get class info. class: System
2295.645666 [server] start server Erro: Não foi possível localizar nem carregar a classe principal kg.ash.javavi.Javavi
```
For some reason javavi-1.0-SNAPSHOT.jar file is missing from the classpath. Also the file `vim-javacomplete2\libs\javavi\target\classes\log4j2.xml` don't exists.

**Comment by artur-shaik** [comment]
@adelarsq hm, as I remember javavi not compiles to  jar. In classpath shoulb path to `target/classes`.

**Comment by adelarsq** [comment]
@artur-shaik for some reason `JCserverCompile` isn't working, but using `mvn compile` on the javavi directory works.

**Comment by dawei101** [comment]
```
Error detected while processing function <SNR>23_JobVimOnErrorHandler[3]..javacomplete#server#CompilationJobHandler:
line   10:
POM file "~/.vim/bundle/vim-javacomplete2/libs/javavi//pom.xml" specified with the -f/--file command line argument does not exist
```

this is what I got, seems javavi//pom.xml with two slashes cause this bug

**Comment by artur-shaik** [comment]
@dawei101 what if you run this command from cmdline by hand, using double slash path. It works fine for me.

**Comment by dawei101** [comment]
@artur-shaik 
It is okay with double slash, and after run below command manually, it worked then
```
 mvn -f "~/.vim/bundle/vim-javacomplete2/libs/javavi//pom.xml" **** 
```
Anyway, I am sure there's tricky bugs in these lines around.

**Comment by wolloda** [comment]
I have the same problem on Win10.
Compiling javavi using mvn compile goes okay (with some warnings), but whenever I open a .java file, CMD window flashes, removing my /target/classes/ folder.
That results in `could not open socket, try again` error

**Comment by cononota** [comment]
@wolloda You can check whether the version of `C:\Windows\System32\java.exe` is  JDK8.

My English is poor.

When more than one JDK were installed on the windows, `javavibridge.py` maybe use the wrong version of the JDK that cause the `could not open socket, try again` error.

This is the log of `javavibridge.py`
```
C:\Users\KANG>java -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
C:\Users\KANG>head -5 %TEMP%\javavi_log\javavi_stdout.log
Registry key 'Software\JavaSoft\Java Runtime Environment\CurrentVersion'
has value '1.8', but '1.6' is required.
Error: could not find java.dll
Error: could not find Java SE Runtime Environment.
CacheAction.perform(AddClassToCacheAction.java:20)
C:\Users\KANG>
```

This is the log of `subprocess.Popen()`
```
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> popen_without_shell = subprocess.Popen("java -version")
>>> Registry key 'Software\JavaSoft\Java Runtime Environment\CurrentVersion'
has value '1.8', but '1.6' is required.
Error: could not find java.dll
Error: could not find Java SE Runtime Environment.
>>> popen_without_shell.terminate()
>>> popen_with_shell = subprocess.Popen("java -version", shell = True)
>>> java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
>>> popen_with_shell.terminate()
>>>
```
On windows, `subprocess.Popen()` use the `CreateProcess()`

> If the file name does not contain a directory path, the system searches for the executable file in the following sequence:
> 1. The directory from which the application loaded.
> 2. The current directory for the parent process.
> 3. The 32-bit Windows system directory. Use the GetSystemDirectory function to get the path of this directory.
> 4. The 16-bit Windows system directory. There is no function that obtains the path of this directory, but it is searched. The name of this directory is System.
> 5. The Windows directory. Use the GetWindowsDirectory function to get the path of this directory.
> 6. The directories that are listed in the PATH environment variable. Note that this function does not search the per-application path specified by the App Paths registry key. To include this per-application path in the search sequence, use the ShellExecute function.

`subprocess.Popen()` without "shell = True" use the `%SYSTEMROOT%\System32\java.exe`(**JDK6 on my computer**) , not the `%JAVA_HOME\bin\java.exe`(**JDK8**)
```
C:\Users\KANG>"%SYSTEMROOT%"\System32\java.exe -version
Registry key 'Software\JavaSoft\Java Runtime Environment\CurrentVersion'
has value '1.8', but '1.6' is required.
Error: could not find java.dll
Error: could not find Java SE Runtime Environment.
C:\Users\KANG>
```

**Comment by bananenmannfrau** [comment]
Try running `:CheckHealth` in neovim and make sure that ruby and python support is working.

This solved it for me.

**Comment by wsdjeg** [comment]
what is the issue? I can not understand it, this issue only happend in mac? does it happened in windows? win7 or win 10?

**Comment by avastmick** [comment]
No, I get the same error on Arch Linux. 

With `SpaceVim`, the plugin does not compile automatically, I had to search for the plugin location and run `mvn compile`, then I get this error. I wonder, if it a path issue with SpaceVim... The only other variable I have is that I use [`asdf`](https://github.com/asdf-vm/asdf) to manage `Java` versions, but I have no other problems with it.

**Comment by artur-shaik** [comment]
I guess it related to #383. If it didn't help, you can reopen issue.
