### ISSUE TITLE
Error when opening a java file

### ISSUE THREAD

**Issue by bootzin** [artur-shaik/vim-javacomplete2#334]
## Actual behavior (Required!)
```
Error detected while processing function javacomplete#Start[1]..javacomplete#server#Start[36]..javacomplete#util#GetBase:
line 3:
E739: Cannot create directory: /javacomplete2
```
The file does open when the message is dismissed and the commands seem to work normally (Although I'm not getting popups for autocompletion)
I get the same error when running `:JCserverCompile` from inside the file I opened

## Expected behavior (Required!)
Open file normally

## The steps to reproduce actual behavior (Required!)
 1. I actually simply opened a java file, I have permission to access the directories
 2. For the second method I tried running `JCserverCompile` from inside a java file 

## Environment (Required!)
 * OS:Kali Linux
 * Vim version:8.0

## Q&A
* No, I've not tried minimal .vimrc configuraion.
* Yes, I have enabled logs with `JCdebugEnableLogs` and can put here content of `JCdebugGetLogContent` command, if you need.
* Even, if you wish, I can set `g:JavaComplete_JavaviDebug` to `1`, than set `g:JavaComplete_JavaviLogfileDirectory`, and put here server logs, too.

**Comment by artur-shaik** [comment]
Hi. Seems like you don't have write permissions for `~/.cache` directory.

**Comment by bootzin** [comment]
I just tested it and I have both read and write permissions on all files there

**Comment by artur-shaik** [comment]
Can you run `:echo g:JavaComplete_BaseDir` and show result.

**Comment by bootzin** [comment]
It displays nothing at all

**Comment by artur-shaik** [comment]
Hm. That's strange. You can try to add this line in your vimrc:
```
let g:JavaComplete_BaseDir = expand('~'. g:FILE_SEP. '.cache')
```

Then try again.

**Comment by bootzin** [comment]
It says g:FILE_SEP is undefined

**Comment by bootzin** [comment]
I have just tried typing 
`let g:JavaComplete_BaseDir = '~/.cache'`
and it seems to have worked!
I'm not getting the error, at least, and running `:echo g:JavaComplete_BaseDir` returns `~/.cache` so I think it worked (:

**Comment by artur-shaik** [comment]
Yeah, that's strange. `g:JavaComplete_BaseDir` should be setted by default. Would be nice if you can find why it is overrided. It initializes at `vim-javacomplete2/plugin/javacomplete.vim`.
