### ISSUE TITLE
Completion not working - maven project with local .classpath

### ISSUE THREAD

**Issue by noenthu** [artur-shaik/vim-javacomplete2#340]
## Actual behavior (Required!)
Please pardon my lack of experience with Java 
On an existing project - managed using maven

The autocomplete feature is not triggering unless I remove/rename the .classpath

with .classpath present
:echo g:JavaComplete_LibsPath
.:/home/noenthu/workspace/project/target/classes:/home/noenthu/workspace/project/target/test-classes:/home/noenthu/workspace/project/target/classes

after removing/renaming the .classpath
:echo g:JavaComplete_LibsPath
./home/noenthu/.m2/repository..................................

## Expected behavior (Required!)
Completion should work leveraging the classpath that is generated by Maven and ignore that set in .classpath

## The steps to reproduce actual behavior (Required!)
 1. create a mvn project through cli
 2. add a few dependencies in pom.xml
 3. mvn clean && mvn package
 4. Autocomplete works fine if editing the files 
 5. Open the project in Eclipse (this generated a .classpath)
 6. Completion no longer works

## Environment (Required!)
 * OS: Arch Linux
 * Vim version: vim 8.0.1092-1
 * Neovim version:

## Q&A
* Yes, I tried minimal .vimrc configuraion.
* Yes, I have enabled logs with `JCdebugEnableLogs` and can put here content of `JCdebugGetLogContent` command, if you need.
* Even, if you wish, I can set `g:JavaComplete_JavaviDebug` to `1`, than set `g:JavaComplete_JavaviLogfileDirectory`, and put here server logs, too.

**Comment by artur-shaik** [comment]
There is variable `g:JavaComplete_ClasspathGenerationOrder`. You can change order like this:
```
let g:JavaComplete_ClasspathGenerationOrder = ['Maven', 'Eclipse', 'Gradle']
```

This should fix you issue.

**Comment by noenthu** [comment]
Let me test it out. I'll get back shortly.

**Comment by artur-shaik** [comment]
@noenthu not so shortly :smile:

**Comment by artur-shaik** [comment]
Feel free to reopen.

**Comment by noenthu** [comment]
Sorry for not getting back. Confirming that the order change fixed my issue!
