### ISSUE TITLE
@Deprecated label

### ISSUE THREAD

**Issue by skubyooru** [artur-shaik/vim-javacomplete2#341]
@Deprecated supported?

**Comment by artur-shaik** [comment]
I think no. How exactly you are expecting it should be supported?

**Comment by skubyooru** [comment]
for example, highlight @Deprecated method in the menu.

**Comment by wsdjeg** [comment]
no, Vim'S poppupmenu only has two highlight group, selected and none selected.

**Comment by skubyooru** [comment]
label before the method in the menu?
