### ISSUE TITLE
How to add generated sources to the source path

### ISSUE THREAD

**Issue by marcelo140** [artur-shaik/vim-javacomplete2#342]
Hi, I'm building a java project with `gradle` where I use `protocol buffers`. The thing with `protocol buffers` is that some code must be generated from `.proto` files into `.java` files that are then saved in a different directory than other sources: `build/generated/source/proto/main/java`.

I tried to add this directory to the `JavaComplete_SourcesPath` without success. Can someone point me to the right direction so that the generated files are also recognized as sources?

**Comment by artur-shaik** [comment]
Can you, please, create minimal project that we can reproduce this issue and fix it?

**Comment by marcelo140** [comment]
Here it is: https://github.com/marcelo140/jc-gradle-demo

**Comment by artur-shaik** [comment]
You can try to set your `build/generated` path in your vimrc, than run `JCclasspathGenerate` and your generated sources should be included.
