### ISSUE TITLE
Complete list can't auto refresh

### ISSUE THREAD

**Issue by coder-bts** [artur-shaik/vim-javacomplete2#345]
## Actual behavior (Required!)
Auto pop-up complete list after typed "."(dot), can't auto refresh when I type in. Until I tap "Backspace"

## Expected behavior (Required!)
The pop-up complete list should auto refreshed.
Eg: I type in "System.out.", it pops up a list, I continue to type pr -- "System.out.pr", the list does not refresh.

## Environment (Required!)
 * OS: Deepin Linux 15.2.1
 * Vim version: Vim80

## Screenshot (Optional)

![deepin-screen-recorder_deepin-terminal_20171012101716](https://user-images.githubusercontent.com/24204079/31565291-3940e622-b034-11e7-8c38-6f89cc6b91dd.gif)

**Comment by artur-shaik** [comment]
Do you have the same, on minimal vim setup and running completion on <C-x><C-o>?
