### ISSUE TITLE
Suggestion: Allow to disable automatic startup of server

### ISSUE THREAD

**Issue by seishinryohosha** [artur-shaik/vim-javacomplete2#346]
## Actual behavior (Required!)
Server starts at startup not matter what
## Expected behavior (Required!)
Make it optional. 
## The steps to reproduce actual behavior (Required!)
 1. Start a java file with vim.

## Environment (Required!)
 * OS: Arch Linux
 * Vim version: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct  7 2017 13:50:55)

**Comment by wsdjeg** [comment]
I will try to add this feature, maybe use ftplugin will be better.

**Comment by seishinryohosha** [comment]
Thank you!

Sure, it has been just a suggestion.

**Comment by artur-shaik** [comment]
@wsdjeg have you any progress on it?

**Comment by wsdjeg** [comment]
@artur-shaik it is done in #349

**Comment by artur-shaik** [comment]
Done in #349
