### ISSUE TITLE
Mac Installed it using Vbundle, but it Doesn't work

### ISSUE THREAD

**Issue by MRzNone** [artur-shaik/vim-javacomplete2#347]
## Actual behavior (Required!)
Nothing happens after I install it.

## Expected behavior (Required!)
I wat to use the features of auto completion

## The steps to reproduce actual behavior (Required!)
 1. vim [any java file]

## Environment (Required!)
 * OS: OSX Sierra 10.12.6
 * Vim version: 7.4
 * Vbundle Version: 0.10.2

## Q&A
This is my .vimrc:::
`set nocompatible              " be iMproved, required
filetype off                  " required <<========== We can turn it on later

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" " alternatively, pass a path where Vundle should install plugins
" "call vundle#begin('~/some/path/here')

" " let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

"plugin java auto-completion
Plugin 'artur-shaik/vim-javacomplete2'
" " <============================================>
" " Specify the plugins you want to install here.
" " We'll come on that later
" " <============================================>
" " All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" " To ignore plugin indent changes, instead use:
" "filetype plugin on

" " Brief help
" " :PluginList       - lists configured plugins
" " :PluginInstall    - installs plugins; append `!` to update or just
" :PluginUpdate
" " :PluginSearch foo - searches for foo; append `!` to refresh local cache
" " :PluginClean      - confirms removal of unused plugins; append `!` to
	" auto-approve removal
" "
" " see :h vundle for more details or wiki for FAQ
" " Put your non-Plugin stuff after this line
" " Put the rest of your .vimrc file here

" This wraps lines at 80 characters 
set textwidth=80 

" Sets tabs to be 2 characters instead of the default which is 8. 
set tabstop=2 

" Number of spaces to use for each step of (auto)indent. 
set shiftwidth=2 

" Tells vim to use spaces instead of tabs 
set expandtab 

" Tells vim to use c-style indenting 
set cindent
 
"enabling line number display
set number

"turn on syntax highlight
syntax on

autocmd FileType java setlocal omnifunc=javacomplete#Complete
`
I put autocompletion in ~/.vim/bundle/Vundle.vim

**Comment by justbaker** [comment]
@MRzNone I had this same issue, and fixed with `let g:JavaComplete_Home = $HOME . '/.vim/bundle/vim-javacomplete2'`.  Perhaps set the path for `g:JavaComplete_Home` to the local vim-javacomplete2 directory?

**Comment by artur-shaik** [comment]
How do you trigger auto completion?

**Comment by wsdjeg** [comment]
@MRzNone Javacomplete is not a plugin for auto completion, it just provide an omni function for java and jsp file, you can use `<c-x><c-o>` to get the completion menu, if you need autocompletion feature, I think you should install https://github.com/Shougo/deoplete.nvim
