### ISSUE TITLE
Can't call javacomplete2 properly from deoplete.nvim

### ISSUE THREAD

**Issue by J-Liu** [artur-shaik/vim-javacomplete2#348]
## Actual behavior (Required!)
type `<C+x> <C+o>` or `.` get a error like this
<img width="566" alt="screen shot 2017-11-02 at 2 22 47 pm" src="https://user-images.githubusercontent.com/1065112/32312642-cbac0d02-bfd9-11e7-8f04-2ec0913055eb.png">

## Expected behavior (Required!)
list something to complete.

## The steps to reproduce actual behavior (Required!)
 1. my init.vim file
```
set nocompatible
let s:dein_path=expand('~/.vim/dein')
set runtimepath+=~/.vim/dein/repos/github.com/Shougo/dein.vim
if dein#load_state(s:dein_path)
  call dein#begin(s:dein_path)
  call dein#add('Shougo/dein.vim')
  call dein#add('Shougo/deoplete.nvim')
  call dein#add('roxma/nvim-yarp')
  call dein#add('roxma/vim-hug-neovim-rpc')
  call dein#add('artur-shaik/vim-javacomplete2')
  call dein#end()
  call dein#save_state()
endif
if dein#check_install()
  call dein#install()
endif
filetype plugin indent on
syntax enable

let g:deoplete#enable_yarp=1
let g:deoplete#enable_at_startup=1

autocmd FileType java setlocal omnifunc=javacomplete#Complete
```
 2. packages I installed by home-brew 
```
brew ls
aria2		gettext		libvterm	python		unibilium
bash-completion	jemalloc	msgpack		python3		xz
gdbm		libtermkey	neovim		readline
geckodriver	libuv	
```
 3. My pip packages
```
pip2 list
futures (3.1.1)
greenlet (0.4.12)
msgpack-python (0.4.8)
neovim (0.1.13)
pip (9.0.1)
setuptools (36.5.0)
six (1.11.0)
trollius (2.1)
wheel (0.30.0)
```
```
pip3 list
Django (1.11.6)
greenlet (0.4.12)
jedi (0.11.0)
msgpack-python (0.4.8)
neovim (0.1.13)
parso (0.1.0)
pip (9.0.1)
pytz (2017.2)
selenium (3.6.0)
setuptools (36.6.0)
wheel (0.30.0)
```

## Environment (Required!)
 * OS: macOS 10.13.1
 * Neovim version: 0.2.0
 * Vimr version: 0.19.1 (229)

**Comment by artur-shaik** [comment]
@Shougo can you to participate?

**Comment by Shougo** [comment]
@J-Liu If you get the errors by `<C-X><C-O>`, it is not related to deoplete.
It just vim-javacomplete2 error.

**Comment by artur-shaik** [comment]
@J-Liu leave just `vim-javacomplete2` plugin in your config and call completion on `<C-x><C-o>`, please.

**Comment by J-Liu** [comment]
Sorry, it was my fault, I used JDK 9.0.1 instead of 8.x.
`vim-javacomplete2` by `deoplete.nvim` is perfectly working now.

`deoplete-jedi` is not that good so I used `completor.vim` replaced.

Thank you @artur-shaik @Shougo all for you all are so kindly.
