### ISSUE TITLE
generate methods after @Override

### ISSUE THREAD

**Issue by richox** [artur-shaik/vim-javacomplete2#35]
completion after @Override helps users to easily override methods from super class, for example:

    class MyList extends List {
        @Override
        |<C-x><C-o>
    }
will show menu like:
  |- ...
  |- void add(Object arg1) {
  |- Object get(int arg1) {
  |- Object set(int arg1, Object arg2) {
  |- ...

**Comment by artur-shaik** [comment]
Yeah, nice idea. We need something like this and much more :smile: . Will add it in todo list.

**Comment by wsdjeg** [comment]
![2015-11-11 21-40-50](https://cloud.githubusercontent.com/assets/13142418/11092297/34b85bbc-88bd-11e5-830f-ad35d4233cba.png)
it great work ,awesome

**Comment by mattn** [comment]
@artur-shaik after completion and type ENTER, seems to be needless empty line?

![](https://i.gyazo.com/9e0a3d47b988322789c1cc4fbdb4db74.png)

**Comment by artur-shaik** [comment]
@mattn added some extra condition to prevent that.

**Comment by wsdjeg** [comment]
when after completion,enter works well for me,maybe it is due to my maps
```vim
inoremap <silent> <buffer> <CR> <C-r>=MyEnterfunc()<Cr>
function MyEnterfunc()
    if pumvisible()
        return "\<esc>a"
    elseif getline('.')[col('.') - 2]=="{"&&getline('.')[col('.')-1]=="}"
        return "\<Enter>\<esc>ko"
    else
        return "\<Enter>"
    endif
endf
```

**Comment by wsdjeg** [comment]
hi @artur-shaik can you make the completion like 
`protected java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException {}`

**Comment by artur-shaik** [comment]
@wsdjeg it might be so, if you press `Space` it will add close bracket at the same line, and if you press `Enter` it will add new line and bracket. What do you think?

**Comment by wsdjeg** [comment]
great, it but it will affected by mapping
if i remove my my inoremap for `Enter`and`Space`,it works very well

**Comment by wsdjeg** [comment]
and here is result of enter and space ,it seems space also add o new line and will add a space at the end of the method

space

![space](https://cloud.githubusercontent.com/assets/13142418/11164092/0a8d4cfa-8b22-11e5-800e-0c5f5f9bf6b3.png)

enter

![exter](https://cloud.githubusercontent.com/assets/13142418/11164095/1756418a-8b22-11e5-8a4a-6b786e6c7738.png)

**Comment by wsdjeg** [comment]
hi @artur-shaik after change my MyEnterFunc(). the plugin works well ,and there is no problem with typping `Enter`after completion,but  `space` seems not word
here is my MyEnterFunc()
```vim
function MyEnterfunc()
    if pumvisible()
        return "\<c-y>"
    elseif getline('.')[col('.') - 2]=="{"&&getline('.')[col('.')-1]=="}"
        return "\<Enter>\<esc>ko"
    else
        return "\<Enter>"
    endif
endf
```
