### ISSUE TITLE
Exit with status code (3) when trying to open java file

### ISSUE THREAD

**Issue by nnquy** [artur-shaik/vim-javacomplete2#353]
## Actual behavior (Required!)
`NeoVim` Open java file, exit with status code (3)

## Expected behavior (Required!)
Open Java file successfully

## The steps to reproduce actual behavior (Required!)
 1. Open a `java` file with VIM
 2. Show error `NeoVim exit with status code (3)`
 3. In the log see this error: `2017/11/15 10:31:28 ERROR 19052 libuv_process_spawn:69: uv_spawn failed: no such file or directory`

> Note: Can only open a `java` file after removing this plugin
> This plugin had been installed using `Vundle`

## Environment (Required!)
 * OS: Windows 7 Enterprise
 * Vim version:
 * Neovim version:
```
λ nvim --version
NVIM v0.2.2-1173-gc46d6f8da
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/msys64/mingw64/bin/gcc.exe -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -D__USE_MINGW_ANSI_STDIO -D_WIN32_WINNT=0x0600 -Wvla -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/msys64/mingw64/include -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv -jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info
```
 * Neovim `init.vim`:
```
g:JavaComplete_JavaviDebug = 1
let g:JavaComplete_Home = 'C:/Users/d874546/.vim/bundle/vim-javacomplete2'

autocmd FileType java setlocal omnifunc=javacomplete#Complete

nmap <F4> <Plug>(JavaComplete-Imports-AddSmart)

imap <F4> <Plug>(JavaComplete-Imports-AddSmart)

nmap <F5> <Plug>(JavaComplete-Imports-Add)

imap <F5> <Plug>(JavaComplete-Imports-Add)

nmap <F6> <Plug>(JavaComplete-Imports-AddMissing)

imap <F6> <Plug>(JavaComplete-Imports-AddMissing)

nmap <F7> <Plug>(JavaComplete-Imports-RemoveUnused)

imap <F7> <Plug>(JavaComplete-Imports-RemoveUnused)
```

## Q&A
* Yes, I tried minimal .vimrc configuraion.
* Yes, I have enabled logs with `JCdebugEnableLogs` and can put here content of `JCdebugGetLogContent` command, if you need.
* Even, if you wish, I can set `g:JavaComplete_JavaviDebug` to `1`, than set `g:JavaComplete_JavaviLogfileDirectory`, and put here server logs, too.

**Comment by artur-shaik** [comment]
Hello.
Just pulled last neovim revision, it works for me fine. Cannot reproduce the problem. Would be cool if you can debug this issue by yourself.

**Comment by artur-shaik** [comment]
Please, reopen if you have more information.
