### ISSUE TITLE
Java still running on background

### ISSUE THREAD

**Issue by mai1015** [artur-shaik/vim-javacomplete2#354]
## Actual behavior (Required!)
Opening java file, autocomplete does not work. It does not work when I try to run the JCserverStart. Then, I use auto import then the server started. Autocomplete works. However, when I exit vim, Java still running at background, I ran multiple times vim, and I got multiple java server running. It took all my memory.

## Expected behavior (Required!)
Opening java file, autocomplete should work. Java server should exit when vim exit.

## Environment (Required!)
 * OS: Debian
 * Vim version: 8.0

## Q&A
* Yes, I have enabled logs with `JCdebugEnableLogs` and can put here content of `JCdebugGetLogContent` command, if you need.
* Even, if you wish, I can set `g:JavaComplete_JavaviDebug` to `1`, than set `g:JavaComplete_JavaviLogfileDirectory`, and put here server logs, too.

**Comment by artur-shaik** [comment]
Can you post log content?

**Comment by wsdjeg** [comment]
@artur-shaik Just a Tips. some plugin use no-nested autocmd to quit windows, for example nerdtree/ vimfiler. This will cause `VimLeavePro` will not be triggered. I think this is why the progress is still running. 

@mai1015 Please post your mini vimrc, I will test it.

**Comment by artur-shaik** [comment]
@wsdjeg can you reproduce it? For example with `nerdtree`.

**Comment by artur-shaik** [comment]
Reopen if still relevant
