### ISSUE TITLE
Complete Methods that need to be implemented.

### ISSUE THREAD

**Issue by andiderp** [artur-shaik/vim-javacomplete2#36]
It would be useful if you could add the method signature + empty body of the methods that are abstract(superclass) or come from an interface that the current class implements if the current class is not abstract.

**Comment by artur-shaik** [comment]
Definetly will be useful. In todo.

**Comment by artur-shaik** [comment]
Made some implementation of this. Need testing.

**Comment by wsdjeg** [comment]
+1

**Comment by wsdjeg** [comment]
really love this feature; thanks for your work;

**Comment by artur-shaik** [comment]
That great. You are welcome :relieved:
