### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by DanielSolomon** [artur-shaik/vim-javacomplete2#360]
## Actual behaviour (Required!)
When opening java file, vim renders weirdly and error messages appear in the bottom:

- error detected while processing function <SNR>15_JobVimOnCallbackHandler[3]..javacomplete#server#CheckServerAccordance
- E121: Undefined variable: s:serverVersionOutput
- E116: Invalid arguments for function extend

## Expected behavior (Required!)
No errors, no renders.

## The steps to reproduce actual behavior (Required!)
 1. Installation was done by Vundle.
 2. The following is my .vimrc:
" Vundle
set nocompatible
filetype off 
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'           " Vundle
Plugin 'Valloric/YouCompleteMe'         " You comeplete me (python)
"Plugin 'artur-shaik/vim-javacomplete2'  " java
call vundle#end()
filetype plugin indent on  

" java autocompletion
"autocmd FileType java setlocal omnifunc=javacomplete#Complete
"nmap <F4> <Plug>(JavaComplete-Imports-AddSmart)
"imap <F4> <Plug>(JavaComplete-Imports-AddSmart)
"nmap <F5> <Plug>(JavaComplete-Imports-Add)
"imap <F5> <Plug>(JavaComplete-Imports-Add)
"nmap <F6> <Plug>(JavaComplete-Imports-AddMissing)
"imap <F6> <Plug>(JavaComplete-Imports-AddMissing)
"nmap <F7> <Plug>(JavaComplete-Imports-RemoveUnused)
"imap <F7> <Plug>(JavaComplete-Imports-RemoveUnused)

All javacomplete lines are commented out now, since it doesn't work.
 3. PluginInstall
 4. vim a.java

## Environment (Required!)
 * OS: Ubuntu 16.04
 * Vim version: 7.4
 * Neovim version: 

## Q&A
* Yes, I tried minimal .vimrc configuration.
* Yes, I have enabled logs with `JCdebugEnableLogs` and can put here content of `JCdebugGetLogContent` command, if you need.
* Even, if you wish, I can set `g:JavaComplete_JavaviDebug` to `1`, than set `g:JavaComplete_JavaviLogfileDirectory`, and put here server logs, too.

**Comment by artur-shaik** [comment]
Can you try to update vim version to 8 and try again?

**Comment by DanielSolomon** [comment]
Well after upgrading vim, it just worked. Thanks a lot!

**Comment by laxman20** [comment]
So does this plugin not work for vim7?

**Comment by artur-shaik** [comment]
Yep
![screenshot_20180223_150509](https://user-images.githubusercontent.com/4862907/36586215-26519f22-18ab-11e8-84fd-05147bc134bb.png)
