### ISSUE TITLE
Error when opening a java file

### ISSUE THREAD

**Issue by lywschxd** [artur-shaik/vim-javacomplete2#361]
## Actual behavior (Required!)
Open a java file

## Expected behavior (Required!)
Open a java file

## The steps to reproduce actual behavior (Required!)
 1. use vundle install javacomplete2
 2. open a java file

## Environment (Required!)
 * OS: Ubuntu 16.04
 * Vim version: 7.4
 * Neovim version:

## Q&A
* Yes, I tried minimal .vimrc configuraion.
* Yes, I have enabled logs with `JCdebugEnableLogs` and can put here content of `JCdebugGetLogContent` command, if you need.
* Even, if you wish, I can set `g:JavaComplete_JavaviDebug` to `1`, than set `g:JavaComplete_JavaviLogfileDirectory`, and put here server logs, too.

## Screenshot (Optional)
![image](https://user-images.githubusercontent.com/3980884/34650341-b2b9e58a-f3fa-11e7-8b7a-e480e3f97636.png)

**Comment by wsdjeg** [comment]
what is your javac version? and if you are using maven, what is the mvn version?

**Comment by lywschxd** [comment]
```bash
#javac -version
javac 1.7.0_95

#java -version
ava version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-3)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
```
And, I don't use maven.

**Comment by wsdjeg** [comment]
you need to use jdk 1.8+

**Comment by lywschxd** [comment]
Does vim-javacomplete2 support java8 only?

**Comment by artur-shaik** [comment]
> Does vim-javacomplete2 support java8 only?

Yes
