### ISSUE TITLE
Pattern not found on all completions of fields

### ISSUE THREAD

**Issue by tkdberger** [artur-shaik/vim-javacomplete2#364]
## Actual behavior
`field.` starts Omnicompletion but returns a `Pattern not found` message for all fields I've tested (using source from [this repo.](https://github.com/BHSSFRC/3494_2018_repo/tree/develop))

## Expected behavior
Omnicompletion of the field (with its accessible methods, fields, etc)

## The steps to reproduce actual behavior
 1. Open java file (I'm using [Robot.java](https://github.com/BHSSFRC/3494_2018_repo/blob/develop/src/main/java/org/usfirst/frc/team3494/robot/Robot.java))
 2. Try omnicomplete (I typed out `limelight.`)
 3. Watch omicompletion error occur

## Environment
 * OS: Arch Linux
 * Neovim version: 0.2.2-1 (from `pacman`)
 * init.vim: https://hastebin.com/orazohujad.sql

**Comment by artur-shaik** [comment]
Hi. Do you see grandle initialization in status line, when you first time open `Robot.java`?
And what is `limelight`? I don't see such fields there.

**Comment by tkdberger** [comment]
[Here's the limelight field.](https://github.com/BHSSFRC/3494_2018_repo/blob/develop/src/main/java/org/usfirst/frc/team3494/robot/Robot.java#L42)

I didn't see any Gradle lines appear on the status line even if I made the window as large as possible.

**Comment by artur-shaik** [comment]
Sorry, forgot to switch branch.
So, I cannot reproduce you problem. Can you try to run command: `JCclasspathGenerate`?

**Comment by tkdberger** [comment]
[It appears to be working now!](https://imgur.com/31WcDOz)

Should I put that command in my `init.vim`?

**Comment by artur-shaik** [comment]
That should be run automatically on plugin load. That's strange that it didn't executed for you.

[Here is](https://github.com/artur-shaik/vim-javacomplete2/blob/1d8402b8c4c1cb4207e86f390711bbe9d6693d2d/autoload/javacomplete.vim#L305). You can try to debug it in your environment, if you have some time.
