### ISSUE TITLE
Doesn't autocomplete Classnames when creating objects

### ISSUE THREAD

**Issue by ym1234** [artur-shaik/vim-javacomplete2#365]
When creating an object `ArrayList<String> arraylist = new ArrayList<>();` java-autocomplete doesn't autocomplete ArrayList<String> or ArrayList<>();

## Actual behavior (Required!)
1. Doesn't autocomplete

## Expected behavior (Required!)
1. It should autocomplete (like in the demo gif)

## The steps to reproduce actual behavior (Required!)
I use the default keybindings with deoplete 
Deoplete config: 
```
let g:deoplete#enable_ignore_case = 1
let g:deoplete#enable_refresh_always = 0
let g:deoplete#omni#input_patterns = get(g:,'deoplete#omni#input_patterns',{})
let g:deoplete#omni#input_patterns.java = [
    \'[^. \t0-9]\.\w*',
    \'[^. \t0-9]\->\w*',
    \'[^. \t0-9]\::\w*',
    \]
let g:deoplete#ignore_sources = get(g:, 'deoplete#ignore_sources', {})
let g:deoplete#ignore_sources._ = ['javacomplete2']
let g:deoplete#auto_complete_delay = let g:deoplete#auto_refresh_delay = 10
```
## Environment (Required!)
 * OS: Arch Linux
 * Vim version:
 * Neovim version: 0.2.2

I don't think the problem is with your plugin, its with the matching in deoplete (specifically the values of input_patterns.java) and I don't know what to match

**Comment by ym1234** [comment]
Sorry, if I'm being unclear. What I mean is that it doesn't show the omnibox, if I write `ArrayList` or any Class Name.

**Comment by ym1234** [comment]
(and sorry for the issue spam)

**Comment by wsdjeg** [comment]
@ym1234 you should test this plugin without autocomplete engin.  or press `<c-x><c-o>` in insert mode.

**Comment by ym1234** [comment]
Pressing <C-x><C-o> Solves the problem, Thank you!
Is there is a way i con configure Deoplete to open with classnames?
