### ISSUE TITLE
The plugin should report failure when it cannot import/autocomplete due to syntax errors.

### ISSUE THREAD

**Issue by ym1234** [artur-shaik/vim-javacomplete2#367]
If I open a file with incorrect syntax, and try to import missing imports, the plugin silently fails instead of reporting the error/warning/notice.

## Actual behavior (Required!)
Silently fails.

## Expected behavior (Required!)
Report an error/warning/notice.

## The steps to reproduce actual behavior (Required!)
 1. Open an file with syntax error.
 2. Try to import missing imports.
 
## Environment (Required!)
 * OS: Arch Linux
 * Vim version:
 * Neovim version: 0.2.2

## Q&A
* Yes, I tried minimal .vimrc configuraion.
* Yes, I have enabled logs with `JCdebugEnableLogs` and can put here content of `JCdebugGetLogContent` command, if you need.
* Even, if you wish, I can set `g:JavaComplete_JavaviDebug` to `1`, than set `g:JavaComplete_JavaviLogfileDirectory`, and put here server logs, too.

**Comment by artur-shaik** [comment]
Year, I agree. We should inform about this.

**Comment by livingBEEF** [comment]
It would be nice if it could populate `location-list` too. The `ale` plugin can already do that, but
 - the compilation has to be done twice - once for `ale` and once for `javacomplete2`
 - `ale`'s support for gradle seems buggier

**Comment by wsdjeg** [comment]
why localtion list is need, what info do you want to shown in it, and what should it done when you press Enter or run `:lnext`?

**Comment by livingBEEF** [comment]
My idea was something like error hinting that IDEs usually do, so it would populate location list with encountered errors (possibly also highlight the errors, if it's not too difficult). Another question is, whether it should leave it to the users how they use the location-list, or whether it should add its own line markings and such, but either would be fine with me.

**Comment by wsdjeg** [comment]
@livingBEEF Javacomplete is omni plugin for java, I do not think it should provides lint featurem you can use neomake which should support maven and grandle project. and the neomake's java lint is maintained by me.
