### ISSUE TITLE
Idea: Auto Implement Interface methods

### ISSUE THREAD

**Issue by bert003** [artur-shaik/vim-javacomplete2#368]
## Actual behavior (Required!)
1. Design a Java interface
2. Implement the interface in another class
3. Currently there is no way (I think) to auto implement methods that need to be overridden

## Expected behavior (Required!)
3. Automatic generation (ex: \<leader\>jI) to implement methods that need to be overridden

**Comment by giovyloca** [comment]
Good news! There is already a command for that: `:JCgenerateAbstractMethods`

From the README 
```nmap <leader>jM <Plug>(JavaComplete-Generate-AbstractMethods)```
