### ISSUE TITLE
Vim help about imap

### ISSUE THREAD

**Issue by yangzhanlong** [artur-shaik/vim-javacomplete2#369]
https://github.com/artur-shaik/vim-javacomplete2/issues/46
i want to use dot replace Ctrl-x Ctrl-o
when i write dot , how can i list the complete to select

**Comment by yangzhanlong** [comment]
and how i can autocomplete missing import when i forget the JCimportsAddMissing  command

**Comment by wsdjeg** [comment]
This is not issue about javacomplete，you should readme Vim help about imap.

**Comment by artur-shaik** [comment]
#305
