### ISSUE TITLE
Autocomplete fails possibly due to failure to JCserverCompile

### ISSUE THREAD

**Issue by tmsimont** [artur-shaik/vim-javacomplete2#373]
## Actual behavior (Required!)
No autocomplete in maven project.

when running `JCserverCompile` I initially see this:

`POM file "/home/tmsimont/.vim/bundle/vim-javacomplete2/libs/javavi//pom.xml" specified with the -f/--file command line argument does not exist`

After a while I do see `Javavi compilation finished`, but still get nothing on autocompletion.

I also went to `~/.vim/bundle/vim-javacomplete2/libs/javavi` and ran `maven compile` without any issue. The project there compiles.

## Expected behavior (Required!)
Some autocomplete for Java?

## The steps to reproduce actual behavior (Required!)
 1. ... Open a java file in a maven project
 2. ... Try `JCserverCompile`
 3. ... See error, sometimes also see "Javavi compilation finished" mesage
 4. ... Get nothing out of the plugin

## Environment (Required!)
 * OS: OS name: "linux", version: "4.15.7-1-arch", arch: "amd64", family: "unix" 
 * Vim version: version 8.0.1542
 * Neovim version:

```
Apache Maven 3.5.2 (NON-CANONICAL_2017-10-25T13:09:52+03:00_root; 2017-10-25T04:09:52-06:00)
Maven home: /opt/maven
Java version: 1.8.0_162, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk/jre
Default locale: en_US, platform encoding: UTF-8
```

## Q&A
* Yes, I tried minimal .vimrc configuraion.
* Yes, I have enabled logs with `JCdebugEnableLogs` see below
* Even, if you wish, I can set `g:JavaComplete_JavaviDebug` to `1`, than set `g:JavaComplete_JavaviLogfileDirectory`, and put here server logs, too.

I tried the variables above (debug and then logfile dir) and nothing appears in the specified Javavi logfile directory.

I should note that the JCserverShowPID shows a real pid... not sure what the server is doing if there are errors starting up.

`JCdebugGetLogContent` output is as follows:
```
2  81.312935 [server] executing python file: /home/tmsimont/.vim/bundle/vim-javacomplete2/autoload/javavibridge.py
  3  81.319343 [server] server classpath: -cp /home/tmsimont/.vim/bundle/vim-javacomplete2/libs/javavi/target/classes:/home/tmsimont/.vim/bundle/vim-javacompl    ete2/libs/javaparser.jar:/home/tmsimont/.vim/bundle/vim-javacomplete2/libs/javavi_log4j-api.jar:/home/tmsimont/.vim/bundle/vim-javacomplete2/libs/javavi_l    og4j-core.jar:.:/home/tmsimont/.m2/repository/com/budhash/cliche/cliche-shell/0.9.3/cliche-shell-0.9.3.jar:/home/tmsimont/.m2/repository/org/apache/xmlgra    phics/xmlgraphics-commons/2.2/xmlgraphics-commons-2.2.jar:/home/tmsimont/.m2/repository/org/apache/xmlgraphics/batik-svggen/1.9.1/batik-svggen-1.9.1.jar:/    home/tmsimont/.m2/repository/xalan/serializer/2.7.2/serializer-2.7.2.jar:/home/tmsimont/.m2/repository/commons-logging/commons-logging/1.0.4/commons-loggi    ng-1.0.4.jar:/home/tmsimont/.m2/repository/commons-io/commons-io/1.3.1/commons-io-1.3.1.jar:/home/tmsimont/.m2/repository/com/myproject/svg/my-svg    /1.0/my-svg-1.0.jar:/home/tmsimont/.m2/repository/org/apache/xmlgraphics/batik-dom/1.9.1/batik-dom-1.9.1.jar:/home/tmsimont/.m2/repository/org/apache/    xmlgraphics/batik-css/1.9.1/batik-css-1.9.1.jar:/home/tmsimont/.m2/repository/org/apache/xmlgraphics/batik-ext/1.9.1/batik-ext-1.9.1.jar:/home/tmsimont/.m    2/repository/xml-apis/xml-apis/1.3.04/xml-apis-1.3.04.jar:/home/tmsimont/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar:/home/tmsimont/.m2/repository/xa    lan/xalan/2.7.2/xalan-2.7.2.jar:/home/tmsimont/.m2/repository/org/apache/xmlgraphics/batik-constants/1.9.1/batik-constants-1.9.1.jar:/home/tmsimont/.m2/re    pository/org/apache/xmlgraphics/batik-awt-util/1.9.1/batik-awt-util-1.9.1.jar:/home/tmsimont/.m2/repository/xml-apis/xml-apis-ext/1.3.04/xml-apis-ext-1.3.    04.jar:/home/tmsimont/.m2/repository/org/apache/xmlgraphics/batik-xml/1.9.1/batik-xml-1.9.1.jar:/home/tmsimont/.m2/repository/org/apache/xmlgraphics/batik    -util/1.9.1/batik-util-1.9.1.jar:/home/tmsimont/.m2/repository/org/apache/xmlgraphics/batik-i18n/1.9.1/batik-i18n-1.9.1.jar:/home/tmsimont/code/myproject/my-cli/target/classes:/home/tmsimont/code/myproject/my-cli/target/test-classes:/usr/lib/jvm/java-8-openjdk/jre/lib
  4  81.319380 [server] server arguments:-Ddaemon.port=57015 -Dlog4j.configurationFile=/home/tmsimont/.vim/bundle/vim-javacomplete2/libs/javavi/target/classes    /log4j2.xml kg.ash.javavi.Javavi -sources /home/tmsimont/code/myproject/my-cli/src: -base /home/tmsimont/.cache/javacomplete2/ -compiler javac -project pom_xml
```

**Comment by artur-shaik** [comment]
I don't see any request for completion in logs. Does it trigger automatically when you press dot?
And you wrote that you have Oracle java, but showed path to openjdk. But anyway it shouldn't be problem.

**Comment by tmsimont** [comment]
Hmm good point. Actually nothing at all happens when I type dot. So the problem is likely that the dot doesn't trigger what it should.

I have this in my .vimrc:
```
autocmd FileType java setlocal omnifunc=javacomplete#Complete
```

Is there something else I should have or set to get the dot to trigger autocomplete?

Also that bit about Oracle comes from maven. I'm not sure why it says that but `java -version` returns 
```
openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-b12)
OpenJDK 64-Bit Server VM (build 25.162-b12, mixed mode)
```

**Comment by DonnieWest** [comment]
Yeah, you  should definitely use something that will provide that autocompletion on your behalf. A really good plugin for this is [deoplete](https://github.com/Shougo/deoplete.nvim)

**Comment by tmsimont** [comment]
Thanks that does the trick! Deoplete was a little tricky to install on Arch with vim8 but I got it up and running and it seems to be working well!
