### ISSUE TITLE
error when open a java file

### ISSUE THREAD

**Issue by dong8chao3** [artur-shaik/vim-javacomplete2#374]
## Actual behavior (Required!)
error when open a java file

"javavi complete finished" appears continuously
a java process always run with high cpu usage
## Expected behavior (Required!)
open a java with no error

## The steps to reproduce actual behavior (Required!)
 1. open a java file

## Environment (Required!)
 * OS:ubuntu 16.04 x64
 * Vim version: 7.4

## Q&A
* Yes, I tried minimal .vimrc configuraion.

## The output of :redir and :message (Optional)
E121: 未定义的变量: s:serverVersionOutput
E116: Invalid arguments for function extend

**Comment by artur-shaik** [comment]
Can you try `Vim 8`. And check write permissions in vim-javacomplete2 folder.
