### ISSUE TITLE
error when building maven classpath

### ISSUE THREAD

**Issue by dong8chao3** [artur-shaik/vim-javacomplete2#375]
## Actual behavior (Required!)
error when building maven classpath

## Expected behavior (Required!)
fix the error

## The steps to reproduce actual behavior (Required!)
 1. build maven classpath

## Environment (Required!)
 * OS: ubuntu16.04 x64
 * Vim version: 7.4

## Q&A
* Yes, I tried minimal .vimrc configuraion.

## Screenshot (Optional)
Maven classpath built successfully
处理 function <SNR>44_JobVimOnCallbackHandler[3]..javacomplete#classpath#maven#BuildClasspathHandler 时发生错误:
第   31 行:
E121: 未定义的变量: s:mavenSettingsOutput
E116: Invalid arguments for function extend

**Comment by artur-shaik** [comment]
Can you try `Vim 8`?
