### ISSUE TITLE
Autoimport adds empty lines between imports

### ISSUE THREAD

**Issue by g4s8** [artur-shaik/vim-javacomplete2#376]
## Actual behavior
Autoformat can add empty lines between imports if imports are from different packages

## Expected behavior
Autoformat adds imports in alphabetical order or it can be configured in `.vimrc`

## The steps to reproduce actual behavior
 1. Add class from `java.` package, e.g. `java.util.Date`, use autoimport
 2. Add class from local package, e.g. `com.test.Foo`, use autoimport

## Environment
 * OS: `Linux 4.9.76-gentoo-r1`
 * Vim version: `8.0`
 * Neovim version: `0.2.2`

## Screenshot
![scrot-2018-04-03-14 36 29](https://user-images.githubusercontent.com/1524988/38247047-8398817c-374c-11e8-80d0-ebd4830c68de.png)

**Comment by joshleeb** [comment]
The lines are between different import groups and are based on the specified import order. 

From the docs:

```
Specifies the order of import groups, when use `packageName` sorting type:

   		let g:JavaComplete_ImportOrder = ['java.', 'javax.', 'com.', 'org.', 'net.'] 
        An import group is a list of individual import statements that all start with the same beginning of package name surrounded by blank lines above and below the group.
```

## Grouping Everything (No line inbetween groups)

If you want to group all import groups together, try adding `let g:JavaComplete_ImportOrder = ['*']` to your vimrc. 

## Slightly Fancier Ordering

If you want to configure a fancier input order, the entries in the `g:JavaComplete_ImportOrder` are prefixes so, for example if you want to keep `java.*` and `javax.*` imports in the same grouping you could have an import list that looks something like: `['java', 'com.', 'org.', 'net.']`.

## IntelliJ Ordering

This is more for reference than anything else but it is also possible to get the same (or close) import order as IntelliJ with:

```
let g:JavaComplete_ImportSortType = 'packageName'
let g:JavaComplete_ImportOrder = ['com.company.', '*', 'java']
let g:JavaComplete_StaticImportsAtTop = 1
```

**Comment by g4s8** [comment]
@joshleeb thanks!
