### ISSUE TITLE
Get Variable Type

### ISSUE THREAD

**Issue by joshleeb** [artur-shaik/vim-javacomplete2#377]
Less of an issue, more of a question.

Does `vim-javacomplete2` currently support getting the type of a variable under the cursor? And if not is this something that can be done with `javaparser`?

Thanks 😄

**Comment by wsdjeg** [comment]
How does other editors support this feature？ A gif Demo will be better.

**Comment by joshleeb** [comment]
@wsdjeg Take a look at [this gif](https://github.com/autozimu/LanguageClient-neovim/issues/35#issuecomment-288731665) from `LanguageClient-neovim`. Specifically this is for Rust but I think it would be really useful to have a similar feature for Java.

**Comment by wsdjeg** [comment]
Ok, I will look into it.
