### ISSUE TITLE
Upgrade JavaParser

### ISSUE THREAD

**Issue by joshleeb** [artur-shaik/vim-javacomplete2#378]
Currently `libs/javavi/pom.xml` sticks the `javaparser-core` version to `2.5.1`. At the time of writing this, the [latest version](https://github.com/javaparser/javaparser/releases) is `3.5.20`. 

IMHO, it's worth upgrading to get some of the bug fixes, Java10 support, an upgraded JavaDoc parser, and other goodies that have changed since `2.5.1`. 

I made an attempt at upgrading to `3.5.14` a few months ago and, also from looking through the [changelog](https://github.com/javaparser/javaparser/blob/master/changelog.md) there are quite a few breaking changes so this could require a fair bit of effort.

**Comment by joshleeb** [comment]
Ref. [joshleeb/vim-java:update-javaparser-3.5.20](https://github.com/joshleeb/vim-java/tree/update-javaparser-3.5.20)

Currently at a state where Rake and Maven tests are passing. Planning on doing some refactoring and possibly adding more tests before submitting a PR.

**Comment by artur-shaik** [comment]
Yeah, we should update it now or later. Just cannot to find some free time. PR welcome.

**Comment by joshleeb** [comment]
@artur-shaik WDYT about, in the same PR, doing a bit of clean up such as removing unused vars/methods and fixing little styling nits?

**Comment by artur-shaik** [comment]
@joshleeb yeah, why not.

**Comment by joshleeb** [comment]
Great :) I'll aim to have a PR up in a few days
