### ISSUE TITLE
Needs python to run!

### ISSUE THREAD

**Issue by andiderp** [artur-shaik/vim-javacomplete2#38]
I have vim compiled with the option --with-python. Now you check the available version with has("python2") but this does not return true, even my version vim was compiled with is 2.7.10. I tried it with has("python") and that yields true.

**Comment by artur-shaik** [comment]
@Townk, may be you can participate?

**Comment by justinmk** [comment]
`has("python2")` is not a thing in Vim. 

- `has("python")` is the correct way to check for Python 2 support.
- `has("python3")` is the correct way to check for Python 3 support.

So this line should be fixed: https://github.com/artur-shaik/vim-javacomplete2/blob/2f11a7becc10e68134a35130a0d8a158c11d56eb/autoload/javacomplete.vim#L11

**Comment by artur-shaik** [comment]
@justinmk , thanks.
@andiderp , please can you try again?

**Comment by andiderp** [comment]
It works fine.

**Comment by Townk** [comment]
Double apologies guys for this. First for the lack of response on the past week and second for the stupid python2 check. I used that to guarantee I would load python 2.x by accident and I completely forgot to changed it. Thanks for fixing it.
