### ISSUE TITLE
Getting error when opening a java file and auto-completion isn't working 

### ISSUE THREAD

**Issue by ybettan** [artur-shaik/vim-javacomplete2#383]
## Actual behavior (Required!)
Error when opening a java file and auto-completion isn't working

## Expected behavior (Required!)
Opening a java file without error and make auto-completion work.

## The steps to reproduce actual behavior (Required!)
 1. install vim-javacompletion2 using vim-plug 
 2. updating vimrc file according to the README file
 3. open a java file

## Environment (Required!)
 * OS: Fedora 27
 * Vim version: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 13 2018 08:57:55)  
 * Neovim version: don't have neovim
 * vimrc file: https://github.com/ybettan/MyLinuxConfig/blob/master/dotfiles/vimrc
 * java -version: 
openjdk version "1.8.0_171"                                                                                                      
OpenJDK Runtime Environment (build 1.8.0_171-b10)                                                                                  
OpenJDK 64-Bit Server VM (build 25.171-b10, mixed mode) 
 * javac -version: javac 1.8.0_171 

## Screenshot (Optional)
![image](https://user-images.githubusercontent.com/29724509/39428341-b3d2ca02-4c8f-11e8-94a8-d8cfeb26c0d1.png)

**Comment by ybettan** [comment]
![image](https://user-images.githubusercontent.com/29724509/39429821-cd6b4a16-4c94-11e8-80ae-e0b5c0be7bd5.png)

**Comment by Clebersonc** [comment]
I have the same problem

**Comment by roleyzhang** [comment]
I have this issue as well

**Comment by ybettan** [comment]
Do you have any solution for this case?

Thanks

**Comment by JESii** [comment]
Same issue here; any solution coming?
```
MacOS 10.13.4 High Sierra
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
Maven home: /usr/local/Cellar/maven/3.5.3/libexec
Java version: 1.8.0_171, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.4", arch: "x86_64", family: "mac"
```

**Comment by JESii** [comment]
In addition, when javaacomplete2 is installed, and I use the `:Gblame` command from the `fugitive` plugin, as soon as I close a `Gblame` window I get a vim segfault. Once I remove javacomplete2, `Gblame` works just fine.

**Comment by wsdjeg** [comment]
It seems a jc2 use wrong pom file path, It should be `javavi/pom.xml` instead of `javavi//pom.xml`

**Comment by JESii** [comment]
Might be worth a try; I noticed that but doubled slashes work just fine in BASH -- i.e., `less .//pom.xml` does exactly the same thing as `less ./pom.xml`.

**Comment by BriceGagnageRenault** [comment]
same thing here, calling manually _mvn -f <pom.xml path> compile_ in a shell does work though. I don't have the error on the second run, but autocompletion still doesn't work and the :messages window is empty.

**Comment by artur-shaik** [comment]
Still looking for somebody who can debug this issue on reproducible machine.

**Comment by wsdjeg** [comment]
@JESii  `less ".//pom.xml"` should cause same error.

**Comment by artur-shaik** [comment]
Can somebody try this branch https://github.com/wsdjeg/vim-javacomplete2/tree/pom_path

**Comment by BriceGagnageRenault** [comment]
POM file "/home/brice/.local/share/nvim/plugged/vim-javacomplete2/libs/javavi/pom.xml" specified with the -f/--file command line argument does not exist

It seems that the double slash has disappeared, but the error is still there.

**Comment by wsdjeg** [comment]
@BriceGagnageRenault what is the result of this command in terminal:

```
file "/home/brice/.local/share/nvim/plugged/vim-javacomplete2/libs/javavi/pom.xml" 
```

**Comment by BriceGagnageRenault** [comment]
/home/brice/.local/share/nvim/plugged/vim-javacomplete2/libs/javavi/pom.xml: exported SGML document, UTF-8 Unicode text

The file exists and can be found under bash (even with the double slash)

**Comment by BriceGagnageRenault** [comment]
Ok so I managed to make this error disappear:

1. Maven doesn't seem to like double quotes around the path given by -f. I removed them.
2. Maven output is (for me at least) colorized by default, which introduces ansi characters in the output, and messes up with the regexes in the plugin ("[INFO" becomes "[31mINFO"). Using "mvn -B" enforces a raw input.
3. I added `let g:JavaComplete_UsePython3 = 1` in my .vimrc since my vim has been compiled only with python3 support (I don't know if it changed anything though)

```diff
diff --git a/autoload/javacomplete/classpath/maven.vim b/autoload/javacomplete/classpath/maven.vim
index 877965b..2070c86 100644
--- a/autoload/javacomplete/classpath/maven.vim
+++ b/autoload/javacomplete/classpath/maven.vim
@@ -27,7 +27,7 @@ function! javacomplete#classpath#maven#Generate(force) abort
     let s:mavenPath = path
     let s:mavenPom = g:JavaComplete_PomPath
     let s:mavenSettingsOutput = []
-    let mvnCmd = ['mvn', '--file', g:JavaComplete_PomPath, 'help:effective-pom', 'dependency:build-classpath', '-DincludeScope=test']
+    let mvnCmd = ['mvn', '-B', '--file', g:JavaComplete_PomPath, 'help:effective-pom', 'dependency:build-classpath', '-DincludeScope=test']
     call javacomplete#server#BlockStart()
     call javacomplete#util#RunSystem(mvnCmd, 'maven classpath build process', 'javacomplete#classpath#maven#BuildClasspathHandler')
     return ""
diff --git a/autoload/javacomplete/server.vim b/autoload/javacomplete/server.vim
index 0bc1409..afa819d 100644
--- a/autoload/javacomplete/server.vim
+++ b/autoload/javacomplete/server.vim
@@ -190,7 +190,7 @@ function! javacomplete#server#Compile()

   let s:compilationIsRunning = 1
   if executable('mvn')
-    let command = ['mvn', '-f', '"'. javaviDir. 'pom.xml"', 'compile']
+    let command = ['mvn', '-B', '-f', javaviDir. 'pom.xml', 'compile']
   else
     call mkdir(javaviDir. join(['target', 'classes'], g:FILE_SEP), "p")
     let deps = s:GetJavaviDeps()
```

No more errors on debug logs (both JCserverLog and JCdebugGetLogContent), still I don't have completion working unfortunately. I can use the JCgenerate/import functions though. Any ideas ?

**Comment by artur-shaik** [comment]
Nice job, can you create PR?

About your issue, can you try `JCcacheClear` and then `JCclasspathGenerate`. And may be restart vim after that and try again.

**Comment by BriceGagnageRenault** [comment]
Thanks, ok for the PR.

I still have no completion. I use the example project from the Maven website:
`mvn archetype:generate -DgroupId=com.mycompany.app -DartifactId=my-app -DarchetypeArtifactId=maven-archetype-quickstart -DinteractiveMode=false`

I'm trying to have "System.out." something, but nothing happens.

**Comment by artur-shaik** [comment]
Hm, that's strange. Can you check if server is running? You can do `JCserverShowPort`. 
If it show port, than server is running. 
You then can check server is working right. You can telnet on this port `telnet localhost port`, then write `-E System.out` press `Enter`.

**Comment by BriceGagnageRenault** [comment]
I enabled the javavi debug log file, I get some errors I didn't see in buffers opened by :JC... commands.

I get plenty of:
0802 18:03:24.723 D [Thread-1] error lookup java.util$Collection<E> [readers.Reflection]
java.lang.ClassNotFoundException: java.util$Collection<E>
.....

I'll look into it.

**Comment by artur-shaik** [comment]
@ybettan can you try last version?

**Comment by BriceGagnageRenault** [comment]
About the other issue I got, I get classpath errors when I do a :JCclasspathGenerate.
It seems that the class path used to compile javavi is corrupted:

/home/brice/wkp/my-app/target/test-classes:/home/brice/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib:/home/brice/wkp/my-app/target/classes:.:/home/brice/.local/share/nvim/plugged/vim-javacomplete2/libs/javavi_log4j-api.jar:/home/brice/.local/share/nvim/plugged/vim-javacomplete2/libs/javavi/target/classes:/home/brice/.m2/repository/junit/junit/4.12/junit-4.12.jar:/home/brice/.local/share/nvim/plugged/vim-javacomplete2/libs/javaparser-core-3.5.20.jar:/home/brice/.local/share/nvim/plugged/vim-javacomplete2/libs/javavi_log4j-core.jar:**/home/brice/wkp/my-app/target/test-classes./home/brice/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar**

It seems that the last path has been wrongly concatenated from a previous one. I'm trying to understand how this is generated but it's a bit complicated. Do you have any idea ?

**Comment by BriceGagnageRenault** [comment]
Good news, I found out that Ctrl+N works to open the autocompletion window ! Although it seems a bit lost on the auocompletion itself.... The menu proposes every symbol known in the file, but nothing from elwhere. Any idea ?

**Comment by artur-shaik** [comment]
> @BriceGagnageRenault Good news, I found out that Ctrl+N works to open the autocompletion window ! Although it seems a bit lost on the auocompletion itself.... The menu proposes every symbol known in the file, but nothing from elwhere. Any idea ?

Hey, do you have something like YouCompleteMe or Deoplete? Or what if you press `<C-x><C-o>` after the dot.
