### ISSUE TITLE
Unable to infer generic type

### ISSUE THREAD

**Issue by Jose-Luis** [artur-shaik/vim-javacomplete2#384]
## Actual behavior (Required!)
When I try to complete on 'funtionMap', the 'get' method of the Map find 'Object' instead of 'Function<Integer, Integer>' 
```
import java.util.HashMap;
import java.util.Map;
import java.util.function.Function;

public class NewClass {

    private Map<String,Function<Integer, Integer>> functionMap; 
 
    public void testMethod() {
        this.functionMap = new HashMap<>();
        this.functionMap.get
    }
}
```

## Expected behavior (Required!)
The type of the object completed coincide with the var type

## The steps to reproduce actual behavior (Required!)
 1. Copy the code above
 2. Try to complete functionMap

## Environment (Required!)
 * OS: Linux 4.14.35-1
 * Vim version:
 * Neovim version: 0.2.2

## Q&A
* Yes, I tried minimal .vimrc configuraion.
* Yes, I have enabled logs with `JCdebugEnableLogs` and can put here content of `JCdebugGetLogContent` command, if you need.
* Even, if you wish, I can set `g:JavaComplete_JavaviDebug` to `1`, than set `g:JavaComplete_JavaviLogfileDirectory`, and put here server logs, too.

**Comment by artur-shaik** [comment]
As I remember it was limitation of the javaparser. But I definitely should check it again.
