### ISSUE TITLE
auto popup completion for jdk classes name

### ISSUE THREAD

**Issue by jackiilong** [artur-shaik/vim-javacomplete2#389]
## Actual behavior (Required!)
When input HashM <tab> cannot list the possbile completion of java.util.HashMap 

## Expected behavior (Required!)
when input HashM <tab> can list out java.util.HashMap option in the popup menu

## The steps to reproduce actual behavior (Required!)
 1. ...vi 1.java 
2. type in HashM <tab> , java.util.HashMap not pop out in the list
 

## Environment (Required!)
 * OS: ubuntu 
 * Vim version: latest
 * Neovim version: no

**Comment by jackiilong** [comment]
I know the vscode editor can implement this function .

**Comment by wsdjeg** [comment]
please use deoplete or ycm, BTW you can press c-x C-o to open popup menu.

**Comment by jackiilong** [comment]
@wsdjeg:   Can  ycm  do completion for java ?

**Comment by jackiilong** [comment]
can this plugin   popup the completion menu when type in a dot character?

**Comment by jackiilong** [comment]
@wsdjeg :Do you mean I should integrate ycm or deoplete together with vim-javacomplete2 ?
or  maybe  you   mean I should use ycm or deoplete instead of vim-javacomplete2 ?

**Comment by wsdjeg** [comment]
please read #331 and #305
