### ISSUE TITLE
Classname not found in any scope for android.jar methods

### ISSUE THREAD

**Issue by lem0nez** [artur-shaik/vim-javacomplete2#390]
## Actual behavior (Required!)
When I try to complete any method from android.jar file, in class, which extends any from android.jar (other libraries I'm not tested), I'm getting message: `JavaComplete: classname 'methodName' not found in any scope` (but method avaible in popup menu). And, when I try to complete parameters for this method, I'm getting errors (see below `:message`).
If typing method using any object (using operator dot), then all OK.

## Expected behavior (Required!)
Methods from Android framework should complete correctly, without errors, if not used `this.` or any object.

## The steps to reproduce actual behavior (Required!)
 1. Open java file with class, which extends any from Android library.
 2. Typing any android.jar method, not using for it `this.` or object.
 3. Select it from popup menu (first error).
 4. Try to complete parameters of this method by pressing `<C-X><C-O>` (second error).

## Environment (Required!)
 * OS: Kali Linux Rolling, arm7l, chroot
 * Vim version: 8.0 (2016 Sep 12, compiled Apr 27 2018 02:08:08)
 * Neovim version: —

## Q&A
* Yes, I tried minimal .vimrc configuraion.
* Yes, I have enabled logs with `JCdebugEnableLogs` and can put here content of `JCdebugGetLogContent` command, if you need.
* Even, if you wish, I can set `g:JavaComplete_JavaviDebug` to `1`, than set `g:JavaComplete_JavaviLogfileDirectory`, and put here server logs, too.

## The output of :redir and :message (Optional)
`:message` [pastebin](https://pastebin.com/x77kqbXv) 

Sorry for my bad English.

**Comment by artur-shaik** [comment]
Is this issue still relevant for you? Can you try with latest version.

**Comment by lem0nez** [comment]
@artur-shaik, not relevant anymore after updating. Thank you!
