### ISSUE TITLE
Suggestion: Search apache-ants build.xml files for classpath to include.  

### ISSUE THREAD

**Issue by Jens0512** [artur-shaik/vim-javacomplete2#391]
Won't go into much details, just want to hear if anyone thinks it is a good idea first.

**Comment by artur-shaik** [comment]
PR welcome

**Comment by artur-shaik** [comment]
Ok, added some stuff related to this feature.
Get classpath from ant is pretty tricky. Now, I add additional targets to `build.xml` that print classpath collected in xml.
Tricky part is that classpath can be collected in many ways.
Now I check the `project.classpath` path reference and `javac.classpath` parameter (that used in one of my old ant project, created in NetBeans).

This stuff should be tested on several projects to find out how ant collects classpath in other projects.

And it can be tested in `ant` branch.

For now, it works with ui blocking. Will finish it later.
