### ISSUE TITLE
Can this be installed on gvim in win10?

### ISSUE THREAD

**Issue by lvxingtu** [artur-shaik/vim-javacomplete2#392]
Can this be installed on gvim in win10?

**Comment by artur-shaik** [comment]
You can try. Somebody use it with windows.

**Comment by SKrPl** [comment]
@lvxingtu I think you can. I am using this plugin (with deoplete.nvim) on neovim in Windows 10.
![image](https://user-images.githubusercontent.com/12163892/45676039-76d03580-bb4e-11e8-8028-56f7882eec6c.png)

**Comment by lvxingtu** [comment]
@SKrPl Thank you. Is it automatic or need shortcut keys ?

**Comment by SKrPl** [comment]
@lvxingtu It is automatic, please refer to [deoplete.nvim](https://github.com/Shougo/deoplete.nvim).
