### ISSUE TITLE
I must be misunderstanding "Add to .vimrc:"

### ISSUE THREAD

**Issue by FaustXVII** [artur-shaik/vim-javacomplete2#396]
## Actual behavior (Required!)
Error detected while processing /home/pi/.vimrc:
line   58:
E492: Not an editor command: Plugin 'artur-shaik/vim-javacomplete2'
line   59:
E492: Not an editor command: NeoBundle 'artur-shaik/vim-javacomplete2'
line   60:
E492: Not an editor command: Plug 'artur-shaik/vim-javacomplete2'
Press ENTER or type command to continue

## Expected behavior (Required!)
I expected to see no errors on start-up.

## The steps to reproduce actual behavior (Required!)
 1. I made the directory: `~/.vim/bundle`
 2. Cloned the project: `git clone https://github.com/artur-shaik/vim-javacomplete2.git`
 3. Created the file `.vimrc` and pasted the line `Plugin 'artur-shaik/vim-javacomplete2'` into it.
 4. Opened a file with vim.
 5. Error message showed up.

## Environment (Required!)
 * OS: Raspbian GNU/Linux 8 (jessie)
 * Vim version: version 7.4.576
 * Neovim version: -

## Q&A
* Yes, I tried minimal .vimrc configuraion.
* no, I have enabled logs with `JCdebugEnableLogs` and can put here content of `JCdebugGetLogContent` command, if you need.
Never got this far.

## Screenshot (Optional)
https://imgur.com/a/03Rqcqn

**Comment by artur-shaik** [comment]
Do you have any plugin managers installed?

**Comment by FaustXVII** [comment]
I just realized that: `pathogen`, `Vundle`, `NeoBundle `and `vim-plug `where plugin-managers.
My issue got solved after reading the Vim-plug manual, thanks.
