### ISSUE TITLE
Javavi won't compile with maven

### ISSUE THREAD

**Issue by hsanson** [artur-shaik/vim-javacomplete2#4]
The default command used to compile javavi when maven is available does not work:

    !mvn -f "/home/ryujin/.vim/bundle/vim-javacomplete2/libs/javavi/" compile

I had to compile manually using:

    mvn -f "/home/ryujin/.vim/bundle/vim-javacomplete2/libs/javavi/pom.xml" compile

**Comment by artur-shaik** [comment]
Looks like it depends on maven version, because I can compile it with your first command.

I think I will add pom.xml, to satisfy all cases.
