### ISSUE TITLE
This only can complete or import class from JDK?how can i add my classes;

### ISSUE THREAD

**Issue by wsdjeg** [artur-shaik/vim-javacomplete2#40]
here is my .vimrc.
Plugin 'artur-shaik/vim-javacomplete2'
autocmd FileType java set omnifunc=javacomplete#Complete
nmap <F4> :call javacomplete#AddImport()<cr>
imap <F4> <Esc>:call javacomplete#AddImport()<cr>
""let g:JavaComplete_SourcesPath='/home/wsdjeg/wsdjeg.github.io/code'
""let g:JavaComplete_LibsPath='/home/wsdjeg/wsdjeg.github.io/code'
here is my file:
/home/wsdjeg/wsdjeg.github.io/code/src/com/wsdjeg/day01/Person.java(package com.wsdjeg.day01;)
/home/wsdjeg/wsdjeg.github.io/code/bin/com/wsdjeg/day01/Person.class
if i writer a new file named Man.java(home/wsdjeg/wsdjeg.github.io/code/bin/com/wsdjeg/day01/Man.java)
in the new file how can complete the Person's method

**Comment by wsdjeg** [comment]
how can i add /home/wsdjeg/wsdjeg.gitgub.com/code/bin into the classpath
and  how can i add home/wsdjeg/wsdjeg.gitgub.com/code/lib into the classpath

**Comment by artur-shaik** [comment]
Can you say, what is your working directory. What you get if you run :!pwd from vim?

**Comment by wsdjeg** [comment]
cd ~/wsdjeg.github.io/code
vim src/com/wsdjeg/day01/Person.java
after edite :wq
then javac -d ./bin src/com/wsdjeg/day01/Person
then java -cp ./bin com.wsdjeg.day01.Person

**Comment by wsdjeg** [comment]
all my code is in my github/wsdjeg.github.io

**Comment by wsdjeg** [comment]
the same issus
https://github.com/vgod/vimrc/issues/3

**Comment by wsdjeg** [comment]
the :!pwd show the path to my java fies
such as /home/wsdjeg/wsdjeg.github.io/code/src/com/wsdjeg/day21

**Comment by artur-shaik** [comment]
Looks like this link refer to old version of javacomplete.

In your example you have commented JavaComplete_SourcesPath, does it commented in your vimrc? If you want have completion of your code, you need to specify this parameter. Or run vim from your `wsdjeg.github.io` directory, `src` dir will append automatically.

**Comment by wsdjeg** [comment]
i have run vim from wsdjeg.github.io
use these command
cd /home/wsdjeg/wsdjeg.github.io
then vim code/src/com/wsdjeg/day01/person.java
but in the vim when i input :!pwd,it also return 
 /home/wsdjeg/wsdjeg.github.io/code/src/com/wsdjeg/day01

**Comment by wsdjeg** [comment]
can the process java  close auto,when i close the vim .the java process need 600~900M cpu .and many time not only one java

**Comment by artur-shaik** [comment]
Strange, for me vim doesn't change directory.

What about g:JavaComplete_SourcesPath? Have you set it?

Java should be shut down on exit, it is also strange if it doesn't on
your system.

**Comment by wsdjeg** [comment]
i have not set g:JavaComplete_SourcesPath and g:JavaComplete_lib .but i have set the~/.bashrc:CLASSPTH=.:${Javahome}/lib:${jrehome}/lib:home/wsdjeg/wsdjeg.github.io/lib
so it can import all the classes inthis lib ,but how can i complete cle  >>> class damoclass extends List like the damo.gif in you README.MD

**Comment by artur-shaik** [comment]
Please, try to use g:JavaComplete_SourcesPath or g:JavaComplete_LibsPath, and you should be able to complete your classes.
And `CLASSPTH` is wrong.

**Comment by wsdjeg** [comment]
i will try tonight ,thank you !

**Comment by wsdjeg** [comment]
#### thank you  i have got it!

<img src="https://github.com/wsdjeg/wsdjeg.github.io/blob/master/Java/java1.png?raw=true">
