### ISSUE TITLE
Can't auto complete

### ISSUE THREAD

**Issue by 6a209** [artur-shaik/vim-javacomplete2#41]
i see your gif [](https://raw.githubusercontent.com/artur-shaik/vim-javacomplete2/master/doc/generics_demo.gif)  it can auto complete , but i can't, i want complete need press ctrl+x ctrl+o

**Comment by mattn** [comment]
I'm thinking it's not an issue of javacomplete2. it should be a task of YCM or neocomplete or etc.

**Comment by artur-shaik** [comment]
@6a209 I'm not sure I understand your issue. Please, can you read another issues, may be you will find your case.

**Comment by MaxAnggy** [comment]
Hi, I have the same issue, can't autocomplete with Ctr+x Ctrl+o , this is mi vimrc, and use vundle to manage my plugins

" Java plugin
Plugin 'artur-shaik/vim-javacomplete2'+

if has("autocmd")
autocmd Filetype java setlocal omnifunc=javacomplete#Complete
endif

" NerdTree
Plugin 'scrooloose/nerdtree.git'

call vundle#end()            " required
filetype plugin indent on    " required

set mouse=a
set number
set history=30


If I'm doing something wrong please tell me, I'm new with vim

**Comment by wsdjeg** [comment]
I understand!
you can imap . . c-x c-o c-p
also you can imap A B C and so on
