### ISSUE TITLE
javacomplete#newclass#CreateClass parsing error

### ISSUE THREAD

**Issue by MichaelCombs28** [artur-shaik/vim-javacomplete2#413]
## Actual behavior (Required!)
```vimscript
enter new class name: Hello

Error detected while processing function javacomplete#newclass#CreateClass[11]..<SNR>26_ParseInput:
line    1:
E121: Undefined variable: g:RE_TYPE
E116: Invalid arguments for function matchlist(a:userinput, '^\([A-Za-z0-9_]*:\)\=\(\[.\{-}\]:\)\=\(\%(\/\|\/\.\|\)'. g:RE_TYPE. '\)\(\s\+extends\s\+'. g:RE_TYPE. '\)\=\(\s\+implements\s\+'. g:RE_TYPE. '\)\=\((.\{-})\|\)\(:.*\)\=$')
E15: Invalid expression: matchlist(a:userinput, '^\([A-Za-z0-9_]*:\)\=\(\[.\{-}\]:\)\=\(\%(\/\|\/\.\|\)'. g:RE_TYPE. '\)\(\s\+extends\s\+'. g:RE_TYPE. '\)\=\(\s\+implements\s\+'. g:RE_TYPE. '\)\=\((.\{-})\|\)\(:.*\)\=$')
line    2:
E121: Undefined variable: submatch
E116: Invalid arguments for function empty(submatch)
E15: Invalid expression: !empty(submatch)
^@
Error detected while processing function javacomplete#newclass#CreateClass:
line   15:
Error: could not parse input line
```

## Expected behavior (Required!)
A new class file.

## The steps to reproduce actual behavior (Required!)
 1. Call JCclassNew command
 2. Enter any string that should create a new class

## Environment (Required!)
 * OS: Ubuntu 18.04, Mac OSX High Sierra (tested on both)
 * Vim version: 8.0 (both) Included patches: 1-503, 505-680, 682-1283 (for Mac)

**Comment by artur-shaik** [comment]
I guess you have some conditions that give this issue. Can you create test project for me to reproduce it?

**Comment by artur-shaik** [comment]
So, this mean that jc2 plugin is not yet loaded, I guess. No sure if we can do something here. Or, what if you let jc2 load for every file type in you bundle manager?

**Comment by MichaelCombs28** [comment]
I'm a bit new to vimscript, I would assume some commands could be exposed to the global scope without the need to load the entire plugin. Potentially commands such as create class but if opened in a non java buffer would require users to enter the package string. 

I honestly think this is more a non issue and more of a feature request, please feel free to close this issue.

**Comment by artur-shaik** [comment]
Class generation heavy depends on relative relation to other java files. If you trying to start new project you should open empty `java` file in vim, and run `JCclassInFile`. Than, you can relatively create classes with `JCclassNew`.

You can reopen this issue later, after some use of `jc2`, when you can shape you feature request better.
