### ISSUE TITLE
file "classpath.py" do not exist output.    # if kind == 'src' and 'output' in a.keys():-------->    #if kind == 'src' and 'path' in a.keys():

### ISSUE THREAD

**Issue by chaiguolong** [artur-shaik/vim-javacomplete2#415]
## The steps to reproduce actual behavior (Required!)
 1. ...
 2. ...
 3. ...

## Environment (Required!)
 * OS:
 * Vim version:
 * Neovim version:

## Q&A
* Yes, I tried minimal .vimrc configuraion.
* Yes, I have enabled logs with `JCdebugEnableLogs` and can put here content of `JCdebugGetLogContent` command, if you need.
* Even, if you wish, I can set `g:JavaComplete_JavaviLogLevel` to `'debug'`, then set `g:JavaComplete_JavaviLogDirectory`, and put here server logs, too.

**Comment by artur-shaik** [comment]
Fill issue tempate, fix header, than reopen.
