### ISSUE TITLE
Code navigation features

### ISSUE THREAD

**Issue by fwy** [artur-shaik/vim-javacomplete2#417]
I have been using vim-javacomplete2 for some time, although not for large-project Java development.  My preferences for this plugin would be more basic code navigation features, as opposed to advanced refactoring or debugging capabilities.  I am already using exuberant tags along with the vim-easytags plugin, but this does not provide smart code navigation for Java.  I would think the Java parser used in javacomplete2 could support these features in a much better way.

In particular, the following features would be especially helpful.

- Jump from a class/method/variable reference to its definition, taking into account method overloading (where there are multiple definitions for the same method with different signatures) and inner classes.
- Display all the references for a given class/method/variable definition in the quicklist or location list, and use it to navigate to those locations.
- Rename a method or variable across the project code base ('lightweight' refactoring).

If these feature are already available somewhere in javacomplete2 and I missed them, please let me know.

**Comment by artur-shaik** [comment]
No, there aren't such features, but sounds useful.

**Comment by wsdjeg** [comment]
@artur-shaik @fwy This feature can be done with gtags. No need to implement this feature again.

**Comment by artur-shaik** [comment]
@fwy, can you try `gtags` and say if it satisfies your requirements?

**Comment by fwy** [comment]
@artur-shaik I will try over the next few weeks.  I am not at all familiar with gtags, but saw mention that it has not been implemented for Windows.  Nevertheless, I will try to use it in either Linux or Windows and let you know.

**Comment by wsdjeg** [comment]
I use gtags in Windows 7. please search gun global as the key word.


---

Shidong Wang

-------- 原始邮件 --------
主题：Re: [artur-shaik/vim-javacomplete2] Code navigation features (#417)
发件人：Fred Yeadon
收件人：artur-shaik/vim-javacomplete2
抄送：Wang Shidong ,Comment


@artur-shaik<https://github.com/artur-shaik> I will try over the next few weeks. I am not at all familiar with gtags, but saw mention that it has not been implemented for Windows. Nevertheless, I will try to use it in either Linux or Windows and let you know.

―

**Comment by fwy** [comment]
@artur-shaik @wsdjeg  I have just tried gtags with vim, and it appears to satisfy the first 2 of the 3 requirements I mentioned (navigation but not renaming).  On Windows there were some problems with the backslash path separator, but they were not difficult to work around with vim mappings.

I haven't tried gtags enough to assess its Java parsing capability, in particular support for Java 8+ constructs.  GNU Global project development continues but does not seem very active, so I suspect that the Java support may not be very current.  I will post any key issues that I find.

Thanks for your quick replies to my original post.

**Comment by artur-shaik** [comment]
@fwy you see, the third requirement you mentioned, can be related to #18 issue. It won't be realized earlier than I will proceed with those. So, you can close this issue, if others are suit you.

**Comment by fwy** [comment]
Closing this issue. I am seeing some problems with gtags Java parsing-navigation but may post those separately.
