### ISSUE TITLE
context param name completed

### ISSUE THREAD

**Issue by Me1onRind** [artur-shaik/vim-javacomplete2#418]
Javacomplete2 look like can't complete context param name, such as
``` java
public void foo() {
    String str = "hi";
    st
}
```
It's can't complete 'str'.
I think if it can complete  context param name will make the wonderful plugin more perfect. I don't know will it need many workload. Just a little suggestion.

**Comment by Me1onRind** [comment]
by the way, I find   java.util.Collections has same problem https://github.com/artur-shaik/vim-javacomplete2/issues/93

**Comment by artur-shaik** [comment]
Consider switch to [jc.nvim](https://github.com/artur-shaik/jc.nvim)
