### ISSUE TITLE
as your damo,how can it complete extends?

### ISSUE THREAD

**Issue by wsdjeg** [artur-shaik/vim-javacomplete2#42]
i have see the damo,!
you can complete cle ==> public class ClassDame extends List{
}

how could i config it!

**Comment by artur-shaik** [comment]
I think you should add
```
import java.util.List
```
before you can have completes.

**Comment by wsdjeg** [comment]
i hava insert package com.wsdjeg;
import java.util.List;
cle =>but it doesn't work
do you install another plugin,such as snipMate

**Comment by artur-shaik** [comment]
Oh sorry, I didn't understand your issue.
Yes, I use https://github.com/SirVer/ultisnips for that and https://github.com/honza/vim-snippets.

**Comment by wsdjeg** [comment]
so you are using these two plugin ;
how about garbas/vim-snipmate Shougo/neosnippet drmingdrmer/xptmplate?
which one is right for java?

**Comment by wsdjeg** [comment]
so you are using these two plugin ;
how about garbas/vim-snipmate Shougo/neosnippet drmingdrmer/xptmplate?
which one is right for java?

**Comment by artur-shaik** [comment]
You need only `ultisnip` and `vim-snippets`.
`vim-snippets` has snippets for java.

**Comment by wsdjeg** [comment]
OK，thank you
