### ISSUE TITLE
Running :JCgenerateAbstractMethods gives an error

### ISSUE THREAD

**Issue by Tyler-Roche** [artur-shaik/vim-javacomplete2#420]
## Actual behavior (Required!)
When I run :JCgenerateAbstractMethods, vim returns

Error detected while processing function javacomplete#generators#AbstractDeclaration[9]..javacomplete#collector#DoGetClassInfo:
line   35:
E731: using Dictionary as a String
E15: Invalid expression: fqn. '$'. a:class
line   90:
E121: Undefined variable: extends
E116: Invalid arguments for function s:CollectFQNs
E15: Invalid expression: s:CollectFQNs(typename, packagename, filekey, extends)
line   91:
E121: Undefined variable: fqns
E15: Invalid expression: fqns
Error detected while processing function javacomplete#generators#AbstractDeclaration[10]..javacomplete#complete#complete#SearchMember:
line    3:
E716: Key not present in Dictionary: name)
E116: Invalid arguments for function javacomplete#util#GetClassPackage
E15: Invalid expression: javacomplete#complete#complete#GetPackageName() == javacomplete#util#GetClassPackage(a:ci.name)
Press ENTER or type command to continue

## Expected behavior (Required!)
I expect that the methods needed should be generated, for example, a java lsp tells me the following error 'javac: BigChest is not abstract and does not override abstract method createNewTileEntity(World,int) in ITileEntityProvider (E)'

## The steps to reproduce actual behavior (Required!)
 1. ... Have a class that does not have all the methods required
 2. ... Run :JCgenerateAbstractMethods
 3. ... Get the above error

## Environment (Required!)
 * OS: Mac Mojave 10.14.3
 * Vim version: 8.1, Compiled with:
+acl               +extra_search      +mouse_netterm     +tag_old_static
+arabic            +farsi             +mouse_sgr         -tag_any_white
+autocmd           +file_in_path      -mouse_sysmouse    -tcl
+autochdir         +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          -toolbar
+cindent           +insert_expand     +path_extra        +user_commands
-clientserver      +job               +perl              +vartabs
+clipboard         +jumplist          +persistent_undo   +vertsplit
+cmdline_compl     +keymap            +postscript        +virtualedit
+cmdline_hist      +lambda            +printer           +visual
+cmdline_info      +langmap           +profile           +visualextra
+comments          +libcall           -python            +viminfo
+conceal           +linebreak         +python3           +vreplace
+cryptv            +lispindent        +quickfix          +wildignore
+cscope            +listcmds          +reltime           +wildmenu
+cursorbind        +localmap          +rightleft         +windows
+cursorshape       +lua               +ruby              +writebackup
+dialog_con        +menu              +scrollbind        -X11
+diff              +mksession         +signs             -xfontset
+digraphs          +modify_fname      +smartindent       -xim
-dnd               +mouse             +startuptime       -xpm
-ebcdic            -mouseshape        +statusline        -xsmp
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_clipboard
+eval              -mouse_gpm         +syntax            -xterm_save
+ex_extra          -mouse_jsbterm     +tag_binary

 * Neovim version: NVIM v0.4.0-603-gd81b510ec

## Q&A
* Yes, I tried minimal .vimrc configuraion.

## Screenshot (Optional)
![Screenshot 2019-04-18 at 13 51 18](https://user-images.githubusercontent.com/44542003/56362270-569a4f00-61e1-11e9-933f-07d6b78abf4e.png)

**Comment by artur-shaik** [comment]
Hello. Thanks for report. Can you create minimal project with this packages, so I can reproduce issue and catch this bug?
