### ISSUE TITLE
how to can have Python support? sorry ,my English is stupid.

### ISSUE THREAD

**Issue by zxm66** [artur-shaik/vim-javacomplete2#429]
## The steps to reproduce actual behavior (Required!)
 1. ...
 2. ...
 3. ...

## Environment (Required!)
 * OS:
 * Vim version:
 * Neovim version:

## Q&A
* Yes, I tried minimal .vimrc configuraion.
* Yes, I have enabled logs with `JCdebugEnableLogs` and can put here content of `JCdebugGetLogContent` command, if you need.
* Even, if you wish, I can set `g:JavaComplete_JavaviLogLevel` to `'debug'`, then set `g:JavaComplete_JavaviLogDirectory`, and put here server logs, too.

**Comment by artur-shaik** [comment]
You need to install or build vim or neovim with python support. Search the web.

You can run `vim --version` and find there `+python` entry.
