### ISSUE TITLE
complete class error!

### ISSUE THREAD

**Issue by wsdjeg** [artur-shaik/vim-javacomplete2#43]
package  com.wsdjeg.dao;
  2 
  3 import java.util.ArrayList;
  4 import java.util.List;
  5 public class Perple{
  6     public void du(){
  7     List<?> list = new ArrayList<>();
  8     list.====>
            can not complete                                                                                                                       
  9     }
 10 }

name: "package" of token type PACKAGE                                                                                                        
  3 == type ==
  4 == type definition body ==
  5 s:classOrInterfaceBodyDeclaration
  6 field init NEW
  7 [syntax error](7,32): illegal.start.of.type
  8 [syntax error](8,3): IDENTIFIER expected
  9 [syntax error](9,3): not.stmt

**Comment by artur-shaik** [comment]
Sorry for delay. Should be fixed. Thanks.

**Comment by wsdjeg** [comment]
thank you ! it's ok now
