### ISSUE TITLE
Add support for lombok annotation processing in a maven project

### ISSUE THREAD

**Issue by 0x01Brain** [artur-shaik/vim-javacomplete2#437]
## Actual behavior
Currently adding lombok not working as I already tried setting lombok in java environment globally by setting environment variable:

`JAVA_TOOL_OPTIONS=-javaagent:/home/levon/.m2/repository/org/projectlombok/lombok/1.18.12/lombok-1.18.12.jar -Xbootclasspath/a:/home/levon/.m2/repository/org/projectlombok/lombok/1.18.12/lombok-1.18.12.jarJAVA_TOOL_OPTIONS=-javaagent:/home/levon/.m2/repository/org/projectlombok/lombok/1.18.12/lombok-1.18.12.jar -Xbootclasspath/a:/home/levon/.m2/repository/org/projectlombok/lombok/1.18.12/lombok-1.18.12.jar
`

After compilation and running debugger I get this exception thrown:

`Exception occurred: java.lang.ClassNotFoundException (uncaught)"thread=main", java.lang.ClassLoader.loadClass(), line=431 bci=121 [1] java.lang.ClassLoader.loadClass (ClassLoader.java:431) [2] sun.misc.Launcher$AppClassLoader.loadClass (Launcher.java:352) [3] java.lang.ClassLoader.loadClass (ClassLoader.java:352) [4] com.zyzt.testapplication.MyApplication.main (MyApplication.java:22)
`
## Environment
 * Vim version: **VIM - Vi IMproved 8.2**
 * Neovim version: **NVIM v0.4.3**

**Comment by artur-shaik** [comment]
There was an issue #79 . Seems like some configuration needed for lombok to work.

**Comment by 0x01Brain** [comment]
@artur-shaik can you please explain more, I saw the issue related what configuration is needed?

**Comment by artur-shaik** [comment]
If you have compiled your sources on next run lombok's methods should appear. Check if your `target/classes` are in `g:JavaComplete_LibsPath`.
