### ISSUE TITLE
AutoCompletion does not show up on Ubuntu, installed with pathogen

### ISSUE THREAD

**Issue by zhxh1** [artur-shaik/vim-javacomplete2#439]
## Actual behavior (Required!)

After installing the plugin with pathogen (by directly cloning the project), I opened a new java file, and wrote several lines. But no code completion has been done.

## Expected behavior (Required!)

The code completion works as shown in the README.

## The steps to reproduce actual behavior (Required!)
 1. Install [ultimate vimrc](https://github.com/amix/vimrc), which use pathogen as package management
 2. Clone `vim-javacomplete2` into `~/.vim_runtime/my_plugins`
 3. Open a new file with `vim demo.java`
 4. Type `import java.` and wait for code completion to happen

## Environment (Required!)
 * OS: Ubuntu 20.04
 * Vim version: 8.1
 * Java version: 1.8.0_252
 * maven version: 3.6.3

## Other context

As mentioned in this [issue](https://github.com/artur-shaik/vim-javacomplete2/issues/338), I go to `libs/javavi` and run `mvn compile test`. And see "BUILD SUCCESS" with no error.

**Comment by artur-shaik** [comment]
What if you press `<C-x><C-o>` after `import java.` ?

**Comment by zhxh1** [comment]
@artur-shaik Thanks for your quick reply!

Do you mean press `<C-x><C-o>` in normal mode? I have seen this shortcut somewhere eles. But after `<C-x>`, a new buffer is created. It seems that the shortcut has been overrided somewhere. But I have `grep`ed everything in my vim configuration folder, nothing seems to relate to this behaviour:

<html>
<pre><font color="#75507B">.vim_runtime/my_plugins/vim-lsp/test/lsp/ui/vim/completion.vimspec</font><font color="#06989A">:</font>    execute &quot;normal! &apos;gg$ha id\<font color="#CC0000"><b>&lt;C-x&gt;</b></font>\&lt;C-o&gt;\&lt;C-n&gt;\&lt;Tab&gt;&apos;&quot;
<font color="#75507B">.vim_runtime/my_plugins/vim-lsp/test/lsp/ui/vim/completion.vimspec</font><font color="#06989A">:</font>    execute &quot;normal! &apos;:gg2j$ha\<font color="#CC0000"><b>&lt;C-x&gt;</b></font>\&lt;C-o&gt;\&lt;C-n&gt;\&lt;Tab&gt;&apos;&quot;
<font color="#75507B">.vim_runtime/my_plugins/vim-lsp/autoload/lsp/ui/vim/completion.vim</font><font color="#06989A">:</font>&quot; 1. `call getbuf|`<font color="#CC0000"><b>&lt;C-x&gt;</b></font>&lt;C-o&gt;
<font color="#75507B">.vim_runtime/my_plugins/jedi-vim/autoload/jedi.vim</font><font color="#06989A">:</font>    return &quot;\<font color="#CC0000"><b>&lt;C-x&gt;</b></font>\&lt;C-o&gt;\&lt;C-r&gt;=jedi#complete_opened(&quot;.a:autocomplete.&quot;)\&lt;CR&gt;&quot;
<font color="#75507B">.vim_runtime/README.md</font><font color="#06989A">:</font>    let g:multi_cursor_skip_key            = &apos;<font color="#CC0000"><b>&lt;C-x&gt;</b></font>&apos;
<font color="#75507B">.vim_runtime/sources_non_forked/vim-multiple-cursors/spec/multiple_cursors_spec.rb</font><font color="#06989A">:</font>    type &apos;&lt;C-n&gt;&lt;C-n&gt;<font color="#CC0000"><b>&lt;C-x&gt;</b></font>cworld&lt;Esc&gt;&apos;
<font color="#75507B">.vim_runtime/sources_non_forked/vim-multiple-cursors/README.md</font><font color="#06989A">:</font>    * skip:         `<font color="#CC0000"><b>&lt;C-x&gt;</b></font>` skip the next match
<font color="#75507B">.vim_runtime/sources_non_forked/vim-multiple-cursors/README.md</font><font color="#06989A">:</font>let g:multi_cursor_skip_key            = &apos;<font color="#CC0000"><b>&lt;C-x&gt;</b></font>&apos;
<font color="#75507B">.vim_runtime/sources_non_forked/vim-multiple-cursors/plugin/multiple_cursors.vim</font><font color="#06989A">:</font>      \ &apos;skip_key&apos;:            &apos;<font color="#CC0000"><b>&lt;C-x&gt;</b></font>&apos;,
<font color="#75507B">.vim_runtime/sources_non_forked/vim-multiple-cursors/doc/multiple_cursors.txt</font><font color="#06989A">:</font>        + skip:   `<font color="#CC0000"><b>&lt;C-x&gt;</b></font>` skip the next match
<font color="#75507B">.vim_runtime/sources_non_forked/vim-multiple-cursors/doc/multiple_cursors.txt</font><font color="#06989A">:</font>    let g:multi_cursor_skip_key            = &apos;<font color="#CC0000"><b>&lt;C-x&gt;</b></font>&apos;
<font color="#75507B">.vim_runtime/sources_non_forked/ale/doc/ale.txt</font><font color="#06989A">:</font>the omnicomplete menu with <font color="#CC0000"><b>&lt;C-x&gt;</b></font>&lt;C-o&gt;. In some versions of Vim, the value set
<font color="#75507B">.vim_runtime/sources_non_forked/ale/autoload/ale/completion.vim</font><font color="#06989A">:</font>inoremap &lt;silent&gt; &lt;Plug&gt;(ale_show_completion_menu) <font color="#CC0000"><b>&lt;C-x&gt;</b></font>&lt;C-o&gt;
<font color="#75507B">.vim_runtime/sources_non_forked/vim-ruby/ChangeLog</font><font color="#06989A">:</font>	1..2.<font color="#CC0000"><b>&lt;C-x&gt;</b></font>&lt;C-o&gt;. fixed the symbol completion bug, where you
<font color="#75507B">.vim_runtime/sources_non_forked/vim-ruby/ChangeLog</font><font color="#06989A">:</font>	Ranges. added handlers for string completion: &quot;test&quot;.<font color="#CC0000"><b>&lt;C-x&gt;</b></font>&lt;C-o&gt;
<font color="#75507B">.vim_runtime/sources_non_forked/vim-ruby/ChangeLog</font><font color="#06989A">:</font>	f.chomp! <font color="#CC0000"><b>&lt;C-x&gt;</b></font>&lt;C-o&gt; returning chomp! again, where it should provide
<font color="#75507B">.vim_runtime/sources_non_forked/vim-ruby/ChangeLog</font><font color="#06989A">:</font>	the global list. It also fixes f.foo( a.B, b.<font color="#CC0000"><b>&lt;C-x&gt;</b></font>&lt;C-o&gt; returning a&apos;s
<font color="#75507B">.vim_runtime/vimrcs/plugins_config.vim</font><font color="#06989A">:</font>let g:multi_cursor_skip_key            = &apos;<font color="#CC0000"><b>&lt;C-x&gt;</b></font>&apos;</pre>
</html>

**Comment by artur-shaik** [comment]
Yes, of course, see this #305
