### ISSUE TITLE
can not start server, not work

### ISSUE THREAD

**Issue by SifungLei** [artur-shaik/vim-javacomplete2#448]
## The steps to reproduce actual behavior (Required!)
when I open java file with vim, something wrong:
Error detected while processing function <SNR>46_JobVimOnCloseHandler[4]..javacomplete#classpath#maven#BuildClasspathHandler:
line   15:
Failed to build maven classpath

sorry,my English is poor.

## Environment (Required!)
 * OS: linux centos 7.8
 * Vim version:8.2
 * Neovim version:

## Q&A
* Yes, I tried minimal .vimrc configuraion.
* Yes, I have enabled logs with `JCdebugEnableLogs` and can put here content of `JCdebugGetLogContent` command, if you need.
* Even, if you wish, I can set `g:JavaComplete_JavaviLogLevel` to `'debug'`, then set `g:JavaComplete_JavaviLogDirectory`, and put here server logs, too.

**Comment by artur-shaik** [comment]
can you use instructions from this issue: #404 ?

**Comment by SifungLei** [comment]
ok,thanks.
