### ISSUE TITLE
Invalid Windows pathname when creating new class

### ISSUE THREAD

**Issue by fwy** [artur-shaik/vim-javacomplete2#449]
## Actual behavior (Required!)
On a Windows 10 workstation, when I run the JCclassInFile or JCclassNew commands, javacomplete2 generates the wrong pathname for the new class because of the leading drive letter in Windows pathnames.  A vim buffer is then created with an incorrect pathname and various vim errors are displayed.  The error details are different in vim and neovim.

Example: I have a project in a directory C:\Users\fwy\test-project\ with a valid pom.xml file.  (I am using Maven.)  I have set this directory as my current vim directory. Inside this project is the subdirectory src\main\java\.  

In vim, the following messages are displayed if I run JCclassnew within the src\main\java directory, entering the new class name 'MyClass'.

Error detected while processing javacomplete#newclass#CreateClass[19]..<SNR>209_CreateClass:
Line 7:
E739: Cannot create directory: \C:\Users
"C:\C:\Users\fwy\test-project\src\main\java\MyClass.java [New DIRECTORY]

In addition, a buffer containing the generated source code is created with the pathname '\C:\Users\fwy\test-project\src\main\\MyClass.java'.  A new empty directory 'C' is also created directly under the C drive.

In neovim, I don't see the error messages, but the same buffer and directory are created.

I found a small fix.  In the functions javacomplete#newclass#CreateInFile() and javacomplete#newclass#CreateClass(), 
I replaced this line of code:

call filter(currentPath, 'empty(v:val) == 0')

... with this one, dropping any path segment that ends in a colon character.

call filter(currentPath, 'empty(v:val) == 0 && v:val[-1:] != ":"')

I am not experienced in vim scripting, so this solution may not be the right fix.  However, let me know if you would like a pull request for it.

## Expected behavior (Required!)

The class file with a source code skeleton is created with no errors, correct buffer path, and no extra directories in the filesystem.

## The steps to reproduce actual behavior (Required!)
<See above>

## Environment (Required!)
 * OS: Windows 10
 * Vim version: 8.2
 * Neovim version: 0.4.4

## Q&A
* Yes, I tried minimal .vimrc configuraion.
* Yes, I have enabled logs with `JCdebugEnableLogs` and can put here content of `JCdebugGetLogContent` command, if you need.
* Even, if you wish, I can set `g:JavaComplete_JavaviLogLevel` to `'debug'`, then set `g:JavaComplete_JavaviLogDirectory`, and put here server logs, too.

**Comment by artur-shaik** [comment]
Hello.

Yes, please, make PR and we will try to fix it together.
