### ISSUE TITLE
Map.Entry class can not complete!

### ISSUE THREAD

**Issue by wsdjeg** [artur-shaik/vim-javacomplete2#45]
Map.Entry can not complete method!
Map. ===> Map.class 
Map.Entry.===> no result

**Comment by artur-shaik** [comment]
Yeah, nested classes still not implemented. It requires some time.

**Comment by wsdjeg** [comment]
there's no hurry about that, Your project has done very well.

**Comment by wsdjeg** [comment]
https://github.com/Valloric/ycmd/issues/45#issuecomment-138011085

**Comment by artur-shaik** [comment]
I added basic support for nested classes, please, can you try?

**Comment by wsdjeg** [comment]
ok  let me have a look

**Comment by wsdjeg** [comment]
![2015-09-17 19-31-34](https://cloud.githubusercontent.com/assets/13142418/9931968/bfc15770-5d72-11e5-9762-f86d80050e7a.png)
![2015-09-17 19-30-39](https://cloud.githubusercontent.com/assets/13142418/9931970/bfe341fa-5d72-11e5-8ffb-a364a38b08d7.png)
![2015-09-17 19-30-24](https://cloud.githubusercontent.com/assets/13142418/9931969/bfe33034-5d72-11e5-873f-6b294c02bf65.png)
![2015-09-17 19-28-02](https://cloud.githubusercontent.com/assets/13142418/9931971/bfe54f40-5d72-11e5-9675-2c1aa84b00f9.png)

**Comment by artur-shaik** [comment]
The static import not yet supported.
Second and third errors now should be fixed.

**Comment by wsdjeg** [comment]
![2015-09-17 19-39-50](https://cloud.githubusercontent.com/assets/13142418/9932120/e331d184-5d73-11e5-913a-563f43135123.png)
great it works well

**Comment by wsdjeg** [comment]
#116
