### ISSUE TITLE
Keystrokes for generating class-specific methods

### ISSUE THREAD

**Issue by reymalahay** [artur-shaik/vim-javacomplete2#452]
Hi all,

Seasons Greetings and Happy New Year!

Is there a set of keystrokes to generate class-specific methods?

So this is the scenario:
I am in a class called MySecretClass and i wish to define a method that is specific to that class only. Let's call the method mySecretMethod().

So let's say i am in line 50, and i write a method invocation for mySecretMethod(), but i must still define mySecretMethod(). What are the keystrokes to do that? Or would you recommend that I take advantage of the `vim-javacomplete2` templates?

Please advise.

Thanks in advance,
rey malahay

**Comment by artur-shaik** [comment]
Hello and Happy New Year!

As I understand you want to generate method with name that is under cursor now? If yes, so I think there is no such ability now. But may be this is something that can be implemented later.

**Comment by reymalahay** [comment]
@artur-shaik that's correct. no worries. thanks all the same.


> Hello and Happy New Year!
> 
> As I understand you want to generate method with name that is under cursor now? If yes, so I think there is no such ability now. But may be this is something that can be implemented later.
