### ISSUE TITLE
Importing a class of same package

### ISSUE THREAD

**Issue by carlsonsantana** [artur-shaik/vim-javacomplete2#455]
## Actual behavior
When autocomplete a class of same package and press space, dot or parentheses key the plugin is creating a import statement. Also is possible reproduce this problem when execute the command `JCimportAddSmart` when the class is selected.

## Expected behavior
Only create import statement for classes of different packages.

## The steps to reproduce actual behavior
 1. Create a class `ExempleClass1` on package `org.example`;
 2. Create a class `ExempleClass2` on package `org.example`;
 3. Write the `ExempleClass2` using the autocomplete on `ExempleClass1` and press space.

## Environment
 * OS: Linux
 * Vim version: 8.2

## Q&A
* Yes, I tried minimal .vimrc configuraion.
* Yes, I have enabled logs with `JCdebugEnableLogs` and can put here content of `JCdebugGetLogContent` command, if you need.
* Even, if you wish, I can set `g:JavaComplete_JavaviLogLevel` to `'debug'`, then set `g:JavaComplete_JavaviLogDirectory`, and put here server logs, too.

**Comment by artur-shaik** [comment]
Yep, can confirm. Thanks.
