### ISSUE TITLE
JavaComplete2 Installation

### ISSUE THREAD

**Issue by mlthati** [artur-shaik/vim-javacomplete2#456]
Dear Sir
I am not able to add Javacomplete2 plugin to my vim. Please help me. I enclosed the .vimrc file along with

-Madhubabu
[vimrc.txt](https://github.com/artur-shaik/vim-javacomplete2/files/6139284/vimrc.txt)

**Comment by artur-shaik** [comment]
You need, at least this line in your vimrc: `Plugin 'artur-shaik/vim-javacomplete2'`. Also you need completion manager like YouCompleteMe or deoplete.

May be you should try to use https://github.com/SpaceVim/SpaceVim/ first. Or try to find tutorial for completion functionallity in vim.
