### ISSUE TITLE
vim-javacomplete2 not working on Mac

### ISSUE THREAD

**Issue by rgdgr8** [artur-shaik/vim-javacomplete2#458]
## The have installed javacomplete2 using vim-plug and I have my vim using +python3.  
The plugin status is OK but still javacomplete2 is not autocompleting anything. 
 I expected it to auto-complete keywords and built in class name like package, public, private, List, etc.

## The steps to reproduce actual behavior:
 1. Install vim-plug(if not already installed)
 2. Install vim which supports +python3(if not already installed)
 3. Install vim-javacomplete2 using vim-plug

## Environment:
 * OS: MacOS
 * Vim version: 8.2 (Homebrew installed vim)

**Comment by Gibson0918** [comment]
Hi, can I ask how did you resolve this issue?

**Comment by rgdgr8** [comment]
> Hi, can I ask how did you resolve this issue?

https://github.com/artur-shaik/vim-javacomplete2/issues/439#issuecomment-656987860

**Comment by Gibson0918** [comment]
Thanks!
