### ISSUE TITLE
Java showing error when using spring and maven

### ISSUE THREAD

**Issue by vuvgaG** [artur-shaik/vim-javacomplete2#459]
## Actual behavior (Required!)

![image](https://user-images.githubusercontent.com/75189112/124352131-6ea9ed80-dbf6-11eb-88b4-ce9e9e31a428.png)

## Expected behavior (Required!)
I don't expect an error.

## The steps to reproduce actual behavior (Required!)
Open a initial spin boot application

## Environment (Required!)
 * OS: Mac OS 11.4
 * Neovim version: 5.0

## Q&A
```
0703 09:13:53.909 I [main] starting javavi server on port: 65235 [Javavi]
0703 09:13:53.910 D [main] argument: -sources [Javavi]
0703 09:13:53.910 D [main] argument: -t [Javavi]
0703 09:13:53.911 D [main] argument: 300 [Javavi]
0703 09:13:53.911 D [main] argument: -base [Javavi]
0703 09:13:53.911 D [main] argument: -compiler [Javavi]
0703 09:13:53.911 D [main] argument: -project [Javavi]
0703 09:13:53.911 D [main] argument: -D [Javavi]
0703 09:13:53.911 D [main] new  action: "ExecuteDaemonAction" [Javavi]
0703 09:13:53.912 D [main] starting daemon mode [actions.ExecuteDaemonAction]
0703 09:13:53.913 D [main] action time: 3ms [Javavi]
0703 09:13:53.915 I [Thread-3] start collecting cache [cache.Cache]
0703 09:13:53.915 I [Thread-3] loading cache class_packages from file /Users/vuvgag/.cache/javacomplete2//cache/class_packages__Users_vuvgag_DesktopTemp_spring-hello_pom_xml.dat [cache.CacheSerializator]
0703 09:13:56.633 D [Thread-0] argument: -E [Javavi]
0703 09:13:56.634 D [Thread-0] new  action: "GetClassInfoAction" [Javavi]
0703 09:13:56.634 D [Thread-0] executing search of "org" [searchers.ClassSearcher]
0703 09:13:56.635 I [Thread-0] visit source: org [searchers.SourceFileVisitor]
0703 09:13:56.639 D [Thread-0] action time: 6ms [Javavi]
0703 09:13:56.744 D [Thread-0] argument: -p [Javavi]
0703 09:13:56.745 D [Thread-0] new  action: "GetPackageInfoAction" [Javavi]
0703 09:13:56.746 D [Thread-0] action time: 2ms [Javavi]
0703 09:14:00.392 D [Thread-0] argument: -E [Javavi]
0703 09:14:00.392 D [Thread-0] new  action: "GetClassInfoAction" [Javavi]
0703 09:14:00.392 D [Thread-0] executing search of "org.springframework" [searchers.ClassSearcher]
0703 09:14:00.393 I [Thread-0] visit source: springframework [searchers.SourceFileVisitor]
0703 09:14:00.394 D [Thread-0] executing search of "org" [searchers.ClassSearcher]
0703 09:14:00.395 I [Thread-0] visit source: org [searchers.SourceFileVisitor]
0703 09:14:00.396 D [Thread-0] action time: 4ms [Javavi]
0703 09:14:00.499 D [Thread-0] argument: -p [Javavi]
0703 09:14:00.499 D [Thread-0] new  action: "GetPackageInfoAction" [Javavi]
0703 09:14:00.500 D [Thread-0] action time: 1ms [Javavi]
0703 09:14:00.631 D [Thread-0] argument: -collect-packages [Javavi]
0703 09:14:00.632 D [Thread-0] new  action: "CollectPackagesAction" [Javavi]
0703 09:14:00.633 D [Thread-0] action time: 1ms [Javavi]
0703 09:14:00.633 I [Thread-4] start collecting cache [cache.Cache]
0703 09:14:00.633 I [Thread-4] loading cache class_packages from file /Users/vuvgag/.cache/javacomplete2//cache/class_packages__Users_vuvgag_DesktopTemp_spring-hello_pom_xml.dat [cache.CacheSerializator]
0703 09:14:00.633 W [Thread-4] Couldn't load cache [cache.CacheSerializator]
0703 09:14:00.633 I [Thread-4] collecting empty cache [cache.Cache]
0703 09:14:00.642 D [Thread-4] search source files [searchers.SourcePackageSearcher]
0703 09:14:01.583 I [Thread-4] saving cache class_packages to file /Users/vuvgag/.cache/javacomplete2//cache/class_packages__Users_vuvgag_DesktopTemp_spring-hello_pom_xml.dat [cache.CacheSerializator]
```
```
 [kg.ash.javavi.Javavi] starting javavi server on port: 65235
 [kg.ash.javavi.Javavi] argument: -sources
 [kg.ash.javavi.Javavi] argument: -t
 [kg.ash.javavi.Javavi] argument: 300
 [kg.ash.javavi.Javavi] argument: -base
 [kg.ash.javavi.Javavi] argument: -compiler
 [kg.ash.javavi.Javavi] argument: -project
 [kg.ash.javavi.Javavi] argument: -D
 [kg.ash.javavi.Javavi] new  action: "ExecuteDaemonAction"
 [kg.ash.javavi.actions.ExecuteDaemonAction] starting daemon mode
 [kg.ash.javavi.Javavi] action time: 3ms
 [kg.ash.javavi.cache.Cache] start collecting cache
 [kg.ash.javavi.cache.CacheSerializator] loading cache class_packages from file /Users/vuvgag/.cache/javacomplete2//cache/class_packages__Users_vuvgag_DesktopTemp_spring-hello_pom_xml.dat
 [kg.ash.javavi.Javavi] argument: -E
 [kg.ash.javavi.Javavi] new  action: "GetClassInfoAction"
 [kg.ash.javavi.searchers.ClassSearcher] executing search of "org"
 [kg.ash.javavi.searchers.SourceFileVisitor] visit source: org
 [kg.ash.javavi.Javavi] action time: 6ms
 [kg.ash.javavi.Javavi] argument: -p
 [kg.ash.javavi.Javavi] new  action: "GetPackageInfoAction"
 [kg.ash.javavi.Javavi] action time: 2ms
 [kg.ash.javavi.Javavi] argument: -E
 [kg.ash.javavi.Javavi] new  action: "GetClassInfoAction"
 [kg.ash.javavi.searchers.ClassSearcher] executing search of "org.springframework"
 [kg.ash.javavi.searchers.SourceFileVisitor] visit source: springframework
 [kg.ash.javavi.searchers.ClassSearcher] executing search of "org"
 [kg.ash.javavi.searchers.SourceFileVisitor] visit source: org
 [kg.ash.javavi.Javavi] action time: 4ms
 [kg.ash.javavi.Javavi] argument: -p
 [kg.ash.javavi.Javavi] new  action: "GetPackageInfoAction"
 [kg.ash.javavi.Javavi] action time: 1ms
 [kg.ash.javavi.Javavi] argument: -collect-packages
 [kg.ash.javavi.Javavi] new  action: "CollectPackagesAction"
 [kg.ash.javavi.Javavi] action time: 1ms
 [kg.ash.javavi.cache.Cache] start collecting cache
 [kg.ash.javavi.cache.CacheSerializator] loading cache class_packages from file /Users/vuvgag/.cache/javacomplete2//cache/class_packages__Users_vuvgag_DesktopTemp_spring-hello_pom_xml.dat
 [kg.ash.javavi.cache.CacheSerializator] Couldn't load cache
 [kg.ash.javavi.cache.Cache] collecting empty cache
 [kg.ash.javavi.searchers.SourcePackageSearcher] search source files
 [kg.ash.javavi.cache.CacheSerializator] saving cache class_packages to file /Users/vuvgag/.cache/javacomplete2//cache/class_packages__Users_vuvgag_DesktopTemp_spring-hello_pom_xml.dat
````

**Comment by artur-shaik** [comment]
Does it happen when you just type `org`?

**Comment by vuvgaG-dukgu3-wysnox** [comment]
No. Not when i tried again. The error came after typing `import org.springframe.`

**Comment by vuvgaG-dukgu3-wysnox** [comment]
> Does it happen when you just type `org`?

No. Not when i tried again. The error came after typing `import org.springframe.`

**Comment by artur-shaik** [comment]
Copy and paste all of the error window in screenshot, please.

**Comment by vuvgaG-dukgu3-wysnox** [comment]
> Copy and paste all of the error window in screenshot, please.

How can I get this information

**Comment by artur-shaik** [comment]
Usually you can use `:messages` command. Can you try to clean this directory: `/Users/vuvgag/.cache/javacomplete2//cache/` and then try again.

**Comment by vuvgaG-dukgu3-wysnox** [comment]
that screenshot shows all the messages in :messages

**Comment by vuvgaG-dukgu3-wysnox** [comment]
here is a snip from youcomlete me debugs
0703 09:13:53.909 I [main] starting javavi server on port: 65235 [Javavi]
0703 09:13:53.910 D [main] argument: -sources [Javavi]
0703 09:13:53.910 D [main] argument: -t [Javavi]
0703 09:13:53.911 D [main] argument: 300 [Javavi]
0703 09:13:53.911 D [main] argument: -base [Javavi]
0703 09:13:53.911 D [main] argument: -compiler [Javavi]
0703 09:13:53.911 D [main] argument: -project [Javavi]
0703 09:13:53.911 D [main] argument: -D [Javavi]
0703 09:13:53.911 D [main] new  action: "ExecuteDaemonAction" [Javavi]
0703 09:13:53.912 D [main] starting daemon mode [actions.ExecuteDaemonAction]
0703 09:13:53.913 D [main] action time: 3ms [Javavi]
0703 09:13:53.915 I [Thread-3] start collecting cache [cache.Cache]
0703 09:13:53.915 I [Thread-3] loading cache class_packages from file /Users/vuvgag/.cache/javacomplete2//cache/class_packages__Users_vuvgag_DesktopTemp_spring-hello_pom_xml.dat [cache.CacheSerializator]
0703 09:13:56.633 D [Thread-0] argument: -E [Javavi]
0703 09:13:56.634 D [Thread-0] new  action: "GetClassInfoAction" [Javavi]
0703 09:13:56.634 D [Thread-0] executing search of "org" [searchers.ClassSearcher]
0703 09:13:56.635 I [Thread-0] visit source: org [searchers.SourceFileVisitor]
0703 09:13:56.639 D [Thread-0] action time: 6ms [Javavi]
0703 09:13:56.744 D [Thread-0] argument: -p [Javavi]
0703 09:13:56.745 D [Thread-0] new  action: "GetPackageInfoAction" [Javavi]
0703 09:13:56.746 D [Thread-0] action time: 2ms [Javavi]
0703 09:14:00.392 D [Thread-0] argument: -E [Javavi]
0703 09:14:00.392 D [Thread-0] new  action: "GetClassInfoAction" [Javavi]
0703 09:14:00.392 D [Thread-0] executing search of "org.springframework" [searchers.ClassSearcher]
0703 09:14:00.393 I [Thread-0] visit source: springframework [searchers.SourceFileVisitor]
0703 09:14:00.394 D [Thread-0] executing search of "org" [searchers.ClassSearcher]
0703 09:14:00.395 I [Thread-0] visit source: org [searchers.SourceFileVisitor]
0703 09:14:00.396 D [Thread-0] action time: 4ms [Javavi]
0703 09:14:00.499 D [Thread-0] argument: -p [Javavi]
0703 09:14:00.499 D [Thread-0] new  action: "GetPackageInfoAction" [Javavi]
0703 09:14:00.500 D [Thread-0] action time: 1ms [Javavi]
0703 09:14:00.631 D [Thread-0] argument: -collect-packages [Javavi]
0703 09:14:00.632 D [Thread-0] new  action: "CollectPackagesAction" [Javavi]
0703 09:14:00.633 D [Thread-0] action time: 1ms [Javavi]
0703 09:14:00.633 I [Thread-4] start collecting cache [cache.Cache]
0703 09:14:00.633 I [Thread-4] loading cache class_packages from file /Users/vuvgag/.cache/javacomplete2//cache/class_packages__Users_vuvgag_DesktopTemp_spring-hello_pom_xml.dat [cache.CacheSerializator]
0703 09:14:00.633 W [Thread-4] Couldn't load cache [cache.CacheSerializator]
0703 09:14:00.633 I [Thread-4] collecting empty cache [cache.Cache]
0703 09:14:00.642 D [Thread-4] search source files [searchers.SourcePackageSearcher]
0703 09:14:01.583 I [Thread-4] saving cache class_packages to file /Users/vuvgag/.cache/javacomplete2//cache/class_packages__Users_vuvgag_DesktopTemp_spring-hello_pom_xml.dat [cache.CacheSerializator]

**Comment by vuvgaG-dukgu3-wysnox** [comment]
> Usually you can use `:messages` command. Can you try to clean this directory: `/Users/vuvgag/.cache/javacomplete2//cache/` and then try again.

After clearing the correct directory it still errors.

However the path to the cace directory was `/Users/vuvgag/.cache/javacomplete2/cache/`

Any chance this wrong path is the issue?

**Comment by artur-shaik** [comment]
I don't think so. It's, actually, right.

Can you try with minimal configuration? Only `vim-javacomplete2` package. You can trigger completion manually with `C-x C-o`.

**Comment by vuvgaG-dukgu3-wysnox** [comment]
> I don't think so. It's, actually, right.
> 
> Can you try with minimal configuration? Only `vim-javacomplete2` package. You can trigger completion manually with `C-x C-o`.

How can I trigger using C-x at the time the error shows i'm in insert mode. (pressing them keys just types C-x)

**Comment by artur-shaik** [comment]
I mean `Ctrl+x` then `Ctrl+o`.

**Comment by vuvgaG** [comment]
> I mean `Ctrl+x` then `Ctrl+o`.

No I get the same error

javacomplete error: {}

**Comment by vuvgaG** [comment]
Is java 8 a solid requirement or is java >8 workable.

```
openjdk 14.0.2 2020-07-14
```

**Comment by vuvgaG** [comment]
Same result with java 11. 

I've also tried with the no google formatter path. Formatting also doesn't work

**Comment by artur-shaik** [comment]
Can you prepare minimal project for me? So I can try to reproduce it.

**Comment by vuvgaG** [comment]
> Can you prepare minimal project for me? So I can try to reproduce it.

Not really. I'm using spacevim. I tried creating a minimal project using their docker command to start it. But I can't get it working.

I'm not sure If I can do that with novim. Plus it would be a different environment. I also don't know If I can swap my vim environment easily.

Is there any other debug information you would like?

**Comment by vuvgaG** [comment]
> Can you prepare minimal project for me? So I can try to reproduce it.

Importing works for files within the project. But not for files that are outside. Is this me making a Java woopsy?

**Comment by vuvgaG** [comment]
> Can you prepare minimal project for me? So I can try to reproduce it.

here is an example of minimal install https://github.com/vuvgaG/spaceivm-youcompleteme. however you need spacevim https://spacevim.org which also has some requirements.

I don't recommend installing this on your base computer.

I'll see if I can spin up a vm and get a minimal version working.

**Comment by vuvgaG** [comment]
Running with on ubuntu with only this plugin install via vim plug.

When invoking c-x c-o I get omifunct is not set error.

**Comment by vuvgaG** [comment]
Should g:JavaComplete_LibsPath? point to something like also point to my local maven repository ~/.m2/repository/?

**Comment by artur-shaik** [comment]
Here is my workflow with deoplete and vim-javacomplete2. I don't use spacevim.
![tmp-2021-07-08_15 40 47](https://user-images.githubusercontent.com/4862907/124900976-693c1100-e003-11eb-99a7-95b2bbb010ba.gif)

**Comment by vuvgaG** [comment]
How does it build the classpath. I don't see that prompt anywhere

**Comment by vuvgaG** [comment]
Do you support nvim?

**Comment by artur-shaik** [comment]
> How does it build the classpath. I don't see that prompt anywhere

Do you have `:JCstart` or `JCclasspathGenerate` command in vim?

> Do you support nvim?

Yes, of cause.

**Comment by vuvgaG** [comment]
Yes, both. I've tried running them both to the same end.

Based on how long it takes, space vim must build the class path on file write.

**Comment by vuvgaG** [comment]
https://github.com/SpaceVim/SpaceVim/blob/a74237108a78106757e445d335760cd8165bcef4/bundle/neomake/autoload/neomake/makers/ft/java.vim
https://github.com/SpaceVim/SpaceVim/blob/a74237108a78106757e445d335760cd8165bcef4/autoload/SpaceVim/layers/lang/java.vim
https://github.com/SpaceVim/SpaceVim/blob/a74237108a78106757e445d335760cd8165bcef4/bundle/ale/ale_linters/java/eclipselsp.vim

I'm going to have a rake around and see if I can come up with anything.

**Comment by vuvgaG** [comment]
![image](https://user-images.githubusercontent.com/75189112/124943183-32b2c600-e004-11eb-8d48-45150b03f625.png)


I got it working. I think it was an issue with my java installation. 

I have seen the identical error message since getting it working, but everything continues to work fine. So not sure what that error is or what's not working.
