### ISSUE TITLE
no autocomplete

### ISSUE THREAD

**Issue by MaxAnggy** [artur-shaik/vim-javacomplete2#46]
Hi I'm new with vim, and this is my issue with javacomplete2, no autocomplete

vim -version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:40:04)

:echo has("python")  -> return 1

java -version
java version "1.8.0_51"

Plugin manager : Vundle

and this is my .vimrc
---------------------------------------------------------------------------------------------------------
" Configuracion Vundle
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" Keep Plugin commands between vundle#begin/end.

" Java plugin
Plugin 'artur-shaik/vim-javacomplete2'

setlocal omnifunc=javacomplete#Complete

" NerdTree
Plugin 'scrooloose/nerdtree.git'

call vundle#end()            " required
filetype plugin indent on    " required

----------------------------------------------------------------------------------------------------
if I put setlocal or autocmd between vundle#begin/#end  or aftler vundle#end, it's the same

I try this steps:
1. open Vim and create a text with .java or open a .java document
2. call javacomplete-server (:call javacomplete#ServerStart() )
3. call import (:call javacomplete#AddImport() )
4. verify ( :call javacomplete#ShowPID() , :call javacomplete#ShowPort() )
5. Start typing and no autocomplete, even with Ctrl+n or Ctrl+p

Second way
1. open Vim
2. call javacomplete-server (:call javacomplete#ServerStart() )
3. call import (:call javacomplete#AddImport() )
4. verify ( :call javacomplete#ShowPID() , :call javacomplete#ShowPort() )
5. Create a .java document
6. Start typing and no autocomplete, even with Ctrl+n or Ctrl+p

--Sorry, Im very bad with english, hope understand my issue

**Comment by wsdjeg** [comment]
you need to try  click Ctrl+x and Ctrl+o

**Comment by artur-shaik** [comment]
Yeah, try press C-x C-o, after dot.

**Comment by MaxAnggy** [comment]
Thx a lot :D now pop-up autocomplete, but if I want to remap the keys? , change C-x C-o TO C-Space or automatically pop-up references? it is possible? and how?
Sorry if I'm very new :cry:

**Comment by wsdjeg** [comment]
inmap c-space c x c o c p
i think it is not necessary,

**Comment by wsdjeg** [comment]
i think you can close this  Issue

**Comment by artur-shaik** [comment]
Will give @MaxAnggy little bit more time, to answer.

**Comment by yangzhanlong** [comment]
how can i use dot replace  C-x C-o
