### ISSUE TITLE
Variables created using `var` are not completable.

### ISSUE THREAD

**Issue by InfoSec812** [artur-shaik/vim-javacomplete2#463]
## Actual behavior (Required!)
As shown in [THIS EXAMPLE](https://github.com/InfoSec812/vertx-matrix-params-example/blob/main/src/main/java/com/example/matrix_testing/MainVerticle.java#L21)

The variable `router` does not auto-complete correctly when initiating the omni-complete

## Expected behavior (Required!)
That I would be presented the correct options for the `Router` class type

## The steps to reproduce actual behavior (Required!)
 1. Clone [THIS REPO](https://github.com/InfoSec812/vertx-matrix-params-example/)
 2. Open the project using vim with this plugin enabled
 3. Go to line 22, type `router.` and initiate autocompletion

## Environment (Required!)
 * OS: Linux (Xubuntu 21.10)
 * Vim version: 
 ```
 VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 21 2021 08:39:53)
Included patches: 1-2434, 3402-3403, 3409, 3428
```
 * Neovim version:

## Q&A
* Yes, I tried minimal .vimrc configuraion.
* Yes, I have enabled logs with `JCdebugEnableLogs` and can put here content of `JCdebugGetLogContent` command, if you need.
```
271.740240 [context] context: CONTEXT_AFTER_DOT
271.740341 [context] dot expression: router.
271.740430 [complete] complete after dot. expr: router.
271.740618 [collector] get declared class name for: "router"
271.775161 [complete] F3. "router.|"  typename: "var"
271.775191 [collector] get class info. class: var
271.792788 [server] communicate: -E "com.example.matrix_testing.var" [collector#FetchInfoFromServer]
271.900418 [server] 
271.900668 [server] communicate: -E "java.lang.var" [collector#FetchInfoFromServer]
272.009019 [server] 
272.010143 [server] communicate: -E "io.vertx.core.AbstractVerticle$var" [collector#FetchInfoFromServer]
272.120748 [server] 
272.122307 [complete] get member list. outputkind: 0
272.122496 [complete] search member. name: , kind: 0, outputkind: 0
272.140664 [complete] finish completion  0.404853s
290.126112 [server] communicate: -clear-from-cache "com.example.matrix_testing.MainVerticle" [s:RemoveCurrentFromCache]
290.227628 [server] 
290.228478 [server] communicate: -async -recompile-class "com.example.matrix_testing.MainVerticle" [s:RemoveCurrentFromCache]
290.330706 [server] 
290.331762 [server] communicate: -async -add-source-to-cache "-source /home/dphillips/Documents/Zanclus/Workspace/vertx-matrix-params-example/src/main/java/com/example/matrix_testing/MainVerticle.java -class MainVerticle -package com.example.matrix_testing" [s:RemoveCurrentFromCache]
```
* Even, if you wish, I can set `g:JavaComplete_JavaviLogLevel` to `'debug'`, then set `g:JavaComplete_JavaviLogDirectory`, and put here server logs, too.

## Screenshot (Optional)

![image](https://user-images.githubusercontent.com/99691/140644023-2f415c22-40af-426a-a548-74bcca8ff2e0.png)

**Comment by artur-shaik** [comment]
Actually yes, not yet implemented.

**Comment by InfoSec812** [comment]
If you give me some hints, I might be able to submit a PR. I'll try to take a look later today.

**Comment by artur-shaik** [comment]
I guess it requires some hacks in `vim java parser` class, that I still wish to replace with `javaparser` library.

But may be there is enough information returned by parser.

**Comment by InfoSec812** [comment]
Thanks for the hint! I'll try to look into it.

DEVEN PHILLIPS

ARCHITECT, RED HAT CLOUD NATIVE RUNTIMES PRACTICE
[image: https://www.redhat.com/] <https://www.redhat.com/>

**Comment by artur-shaik** [comment]
Consider switch to [jc.nvim](https://github.com/artur-shaik/jc.nvim)
