### ISSUE TITLE
maven project cant import class from dependencies

### ISSUE THREAD

**Issue by ShenFeng312** [artur-shaik/vim-javacomplete2#465]
## Actual behavior (Required!)

show
home/shenfeng/work/myvimdemo   src/main/java/com/example/myvimdemo/MyvimdemoApplication.java                                                                                  6,4           全部
JavaComplete: classname 'SpringBootApplication' not found in any scope.

## Expected behavior (Required!)
success to import SpringBootApplication
## The steps to reproduce actual behavior (Required!)
1.use IDEA create a springboot project 
2.use vim open the project  root path
3 open MyvimdemoApplication and use F4

## Environment (Required!)
 * OS:unubtu 20.4
 * Vim version:IM - Vi IMproved 8.1 (2018 May 18, compiled Feb 01 2022 09:16:32)
 * Neovim version:

## Q&A
* Yes, I tried minimal .vimrc configuraion.
* Yes, I have enabled logs with `JCdebugEnableLogs` and can put here content of `JCdebugGetLogContent` command, if you need.
* Even, if you wish, I can set `g:JavaComplete_JavaviLogLevel` to `'debug'`, then set `g:JavaComplete_JavaviLogDirectory`, and put here server logs, too.

**Comment by ShenFeng312** [comment]
![image](https://user-images.githubusercontent.com/49786112/179454755-ed165f33-0376-4139-95fb-a67b582860d5.png)

**Comment by ShenFeng312** [comment]
my vim config 
![image](https://user-images.githubusercontent.com/49786112/179454840-b7cb301e-2a7a-448f-ac17-1c4901800cd6.png)

**Comment by ShenFeng312** [comment]
`:echo g:JavaComplete_PomPath`


result  ` `  empty

`:echo g:JavaComplete_LibsPath`
result `.`

**Comment by ShenFeng312** [comment]
and how can i use it with out C-X C-O

**Comment by artur-shaik** [comment]
Please consider using [jc.nvim](https://github.com/artur-shaik/jc.nvim)
