### ISSUE TITLE
complete not Comprehensive!

### ISSUE THREAD

**Issue by wsdjeg** [artur-shaik/vim-javacomplete2#47]
```java
public class Test{
    public void test(){
         this. ====>only one method test(),can not complete getClass() and so on!
    }
}
```

**Comment by artur-shaik** [comment]
8ba4d5dc0383c12bd4e2e6948d6dd8fd6f4c7bba commit should add this completions.

**Comment by wsdjeg** [comment]
Great

This problem has been solved.

Thank you very much.

**Comment by wsdjeg** [comment]
another issue appears.
only 7methen, maybe it because of generics!
https://github.com/wsdjeg/wsdjeg.github.io/blob/master/java/invoicingsystem/WEB-INF/src/com/wsdjeg/impl/UserDAOImpl.java
![2015-08-28 01 01 09](https://cloud.githubusercontent.com/assets/13142418/9527250/77403140-4d20-11e5-9ba5-e83cc68ebf24.png)

**Comment by wsdjeg** [comment]
no method after bd.

![2015-08-28 01 19 30](https://cloud.githubusercontent.com/assets/13142418/9527645/e5877b02-4d22-11e5-8184-85eb192ca305.png)

**Comment by artur-shaik** [comment]
I think issue is that generics for source files still not implemented. Going to do it later.

**Comment by wsdjeg** [comment]
if i delete <Product> alfte BaseDAO it work well

**Comment by wsdjeg** [comment]
i hava compile all the files necessary, but it still not work after bd. or pdi.  which is in the above picture
