### ISSUE TITLE
how to close the javavi auto?

### ISSUE THREAD

**Issue by wsdjeg** [artur-shaik/vim-javacomplete2#48]
when i : w q ,the javavi still worded ! and  alfter i have edit many file,there are too mant java process in my computer ,and the system becomes very slow!

**Comment by wsdjeg** [comment]
![2015-08-19 23 42 57](https://cloud.githubusercontent.com/assets/13142418/9361010/0e6a4e62-46cc-11e5-9f0e-275b1bf28d9a.png)

**Comment by artur-shaik** [comment]
Strange issue. It should autoclose itself. May be I will add some timeout parameter to server to shutdown it when there is no request some time.

**Comment by wsdjeg** [comment]
i use vim not gvim;when i use :wq go to the terminal;then go to vim next time,c-x c-o opens another javaai service

**Comment by wsdjeg** [comment]
Benefit from   https://github.com/stirp/.vim
i think i can add these into vimrc
autocmd FileType java set omnifunc=javacomplete#Complete
autocmd FileType java setlocal omnifunc=javacomplete#Complete
autocmd FileType java call javacomplete#StartServer()
"""autocmd FileType java nnoremap <C-S-O> call javacomplete#AddImport()<cr>
autocmd FileType java nmap :wq call javacomplete#TerminateServer()<cr>:wq
autocmd FileType java nmap :q call javacomplete#TerminateServer()<cr>:q

**Comment by artur-shaik** [comment]
With 2e4659297d8f1346f117e8dfe1c6edec8f74ac2c I added parameter, that let you set auto shutdown timeout. You can try to set it. By defaullt timeout is off.

**Comment by wsdjeg** [comment]
thank you ,it works well
