### ISSUE TITLE
an compelete error!

### ISSUE THREAD

**Issue by wsdjeg** [artur-shaik/vim-javacomplete2#50]
DoGetClassInfo: TestJCimpl
 35 RunReflection: -E "com.wsdjeg.test.impl.TestJCimpl" [FetchClassInfo in Batch]
 36 DoGetClassInfo: TestJCimpl
 37 RunReflection: -E "com.wsdjeg.test.impl.TestJCimpl" [FetchClassInfo in Batch]
 38 finish completion 13.626196s
 39 GetDeclaredClassName for "t"
 40 F3. "t.|"  typename: "TestDAOImpl"
 41 DoGetClassInfo: TestDAOImpl
 42 RunReflection: -E "com.wsdjeg.test.impl.TestDAOImpl" [FetchClassInfo in Batch]
 43 RunReflection: -E "java.lang.TestDAOImpl" [FetchClassInfo in Batch]
 44 RunReflection: -E "java.lang.Object" [FetchClassInfo in Batch]
 45 finish completion 17.845121s
 46 GetDeclaredClassName for "t"
 47 F3. "t.|"  typename: "TestDAOImpl"
 48 DoGetClassInfo: TestDAOImpl
 49 RunReflection: -E "com.wsdjeg.test.impl.TestDAOImpl" [FetchClassInfo in Batch]                                                               
 50 RunReflection: -E "java.lang.TestDAOImpl" [FetchClassInfo in Batch]
 51 finish completion  2.328846s

![2015-08-21 21 02 03](https://cloud.githubusercontent.com/assets/13142418/9408826/67deb0be-4848-11e5-8461-cc3c90df8711.png)
![Uploading 2015-08-21 21:02:03屏幕截图.png…]()
![Uploading 2015-08-21 21:02:03屏幕截图.png…]()

**Comment by artur-shaik** [comment]
Hello, sorry for no response, I'm on vacation now. Will look it next week.

**Comment by wsdjeg** [comment]
ok thank you !
i have pay three hours read the VJDE introduction documents, I hava find many useful function in it;
I hope the JavaComplete2 add thess function.

**Comment by artur-shaik** [comment]
Try with last commit, please. Don't forget to recompile Javavi lib.

**Comment by wsdjeg** [comment]
thank you !

**Comment by wsdjeg** [comment]
thank you !
