### ISSUE TITLE
New completions do not show when editing g:JavaComplete_LibsPath

### ISSUE THREAD

**Issue by DonnieWest** [artur-shaik/vim-javacomplete2#52]
Unfortunately, it seems that completions will not include new additions to the g:JavaComplete_LibsPath variable /after/ you have already started the javacomplete2 server

To recreate:

1. Open a project in vim and open a .java file
2. import java.util. --> C+x C+o
3. run command in vim: let g:JavaComplete_LibsPath = <path to new jar>
4. import <new jar classpath> --> C+x C+o
5. Completions for new jar will not show

**Comment by wsdjeg** [comment]
please try add this to vimrc
let g:JavaComplete_LibsPath = '/home/path/to/lib'

**Comment by wsdjeg** [comment]
import com.    --> C+x C+o

**Comment by DonnieWest** [comment]
Not a solution for me - I want to be able to edit the classpath during a Vim session and get the new completions. Building a plugin that sits on top of javacomplete2

**Comment by DonnieWest** [comment]
I was just thinking about this - tried to restart the javacomplete server and it didn't help. Maybe a command to reset completions would be the best solution? Like javacomplete#ClearCache()?

**Comment by artur-shaik** [comment]
Ok, I added `javacomplete#ClearCache()` function. You can try to use it. But you steel need to restart server to add your new libs to classpath.

**Comment by DonnieWest** [comment]
Works amazingly! Thank you!
