### ISSUE TITLE
an compelete error with jsp file!

### ISSUE THREAD

**Issue by wsdjeg** [artur-shaik/vim-javacomplete2#54]
![2015-08-30 08-26-01](https://cloud.githubusercontent.com/assets/13142418/9565153/1936d6da-4ef1-11e5-9f7c-44c2812a207b.png)

**Comment by wsdjeg** [comment]
```vim
autocmd! FileType jsp set omnifunc=javacomplete#Complete
```
need i add this to my vimrc
i have add ,but it does not work

**Comment by artur-shaik** [comment]
See comment here: 552f6cacdc2722e5a4ad04746d975cb516310bac

**Comment by wsdjeg** [comment]
i do not know why?
case one===>
autocmd Filetype java set onimifunc=javacomplete#Complete
autocmd Filetype jsp set onimifunc=javacomplete#Complete
filetype plugin indent on
java file onimfunc is javacompelte
jsp file is htmlcomplete
but
case two ===>
filetype plugin indent on
autocmd Filetype java set onimifunc=javacomplete#Complete
autocmd Filetype jsp set onimifunc=javacomplete#Complete

all of java jsp file onimifunc is javacomplette

**Comment by wsdjeg** [comment]
it works will with requset onimifunc and :JCimportAdd and :JCimportAddI, so i think i should close the issue
