### ISSUE TITLE
can this plugin autocompile java file?

### ISSUE THREAD

**Issue by wsdjeg** [artur-shaik/vim-javacomplete2#55]
some config in my `.vimrc` 
```vim
Plugin 'artur-shaik/vim-javacomplete2'
Plugin 'airblade/vim-rooter'
let g:rooter_patterns = ['Rakefile', 'web.xml']
let g:JavaComplete_LibsPath = 'classes/:lib/:/home/wsdjeg/tools/apache-tomcat-8.0.24/lib'
```
in the WEB-INF dir contains  classes/   lib/   src/ and    web.xml
the plugin `rooter` helps me set the pwd WEB-INF/
all the necessary jar is  included in lib/
java file is included in the src/
class file is included in the classes/
I want to compile the file when save it!
Maybe this function would be the best solution? 
Like add this to vimrc
```vim
let g:javacomplete_compile_on_save = 1  "default is 0
let g:javacomplete_compile_outputdir = 'classes'
```

**Comment by artur-shaik** [comment]
For now, I think better to try to add autocommand to execute compilation on write buffer.

**Comment by wsdjeg** [comment]
I think so too , i have pull the latest version of this plugin ,and the auto import is very good .
