### ISSUE TITLE
auto import miss class?

### ISSUE THREAD

**Issue by wsdjeg** [artur-shaik/vim-javacomplete2#56]
```java
Date d = new Date();  //import java.sql.Date; not java.util.Date
```

**Comment by artur-shaik** [comment]
Now it insert first found import. When we will save most used option, we
will insert it. So, until that, will hope for more unique class names.

**Comment by wsdjeg** [comment]
i think the most used option is for the method complete,and the import should tip me to choose.

**Comment by wsdjeg** [comment]
as the com.wsdjeg.User, can not be inport ,when i insert User it auto insert org.apache.catalina.User

**Comment by artur-shaik** [comment]
I tried that first, of course. But I don't know why, vim doesn't show
options when I echo it in auto command. So, for now only this works,
and I will consider it, to make it better, on later changes.

**Comment by artur-shaik** [comment]
And for better expirience, you can map `AddImport` in insert mode. It
should work even if cursor is after classname.

`:inoremap <F4> <esc>:call javacomplete#AddImport()<CR>a`

**Comment by wsdjeg** [comment]
i think 
insert mode auto javacomplete#AddImport()<cr>gi
nomal there is no need aoto inport ,can click <F4>

**Comment by wsdjeg** [comment]
![2015-09-02 21-20-30](https://cloud.githubusercontent.com/assets/13142418/9632232/7efd5d80-51b8-11e5-8ccc-f5e1e1fa6cbe.png)
![Uploading 2015-09-02 21-20-30屏幕截图.png…]()

**Comment by wsdjeg** [comment]
### Some thoughts about automatic import

1. auto import after `<cr>`

```java
Date date = new Date//here click c-x c-o show all the class,such as java.util.Date and java.sql.Date;
//when I choose one of them, auto import after selecteet relativenumber;
```

**Comment by wsdjeg** [comment]
Really good kind,thank you for your work!!
