### ISSUE TITLE
JCimportAddI is not the command!

### ISSUE THREAD

**Issue by wsdjeg** [artur-shaik/vim-javacomplete2#59]
class A{
public void method(){
Map m = new HashMap();
}
}
get this error
E492 JCimportAddI is not the command error!

**Comment by artur-shaik** [comment]
Does other commands work?

**Comment by wsdjeg** [comment]
other work well such as addall remove unuse JCimportAdd,only JCimportAddI dosent work

**Comment by artur-shaik** [comment]
Are you sure there are no mistypes?
You can look at `plugin/javacomplete.vim`, and see those commands, try
to run it manually or something else.

**Comment by wsdjeg** [comment]
ahaa ,i add the command before you change the readme.md, now i have change the command,and it works well!
