### ISSUE TITLE
can not complete method of classs which extend ClassA<ClassB> implements IntefaceC

### ISSUE THREAD

**Issue by wsdjeg** [artur-shaik/vim-javacomplete2#61]
another issue appears.
only 7methen, maybe it because of generics!
https://github.com/wsdjeg/wsdjeg.github.io/blob/master/java/invoicingsystem/WEB-INF/src/com/wsdjeg/impl/UserDAOImpl.java
![2015-08-28 01 01 09](https://cloud.githubusercontent.com/assets/13142418/9527250/77403140-4d20-11e5-9ba5-e83cc68ebf24.png)

**Comment by wsdjeg** [comment]
https://github.com/artur-shaik/vim-javacomplete2/issues/47

**Comment by wsdjeg** [comment]
https://github.com/artur-shaik/vim-javacomplete2/issues/120

**Comment by artur-shaik** [comment]
Does it still reproducable? Can you prepare small example?

**Comment by wsdjeg** [comment]
great work, it works very well,let me show you two pic
![2015-11-05 19-12-58](https://cloud.githubusercontent.com/assets/13142418/10966866/6fb89a4a-83f1-11e5-8426-7dcbd28ec884.png)
![2015-11-05 19-13-12](https://cloud.githubusercontent.com/assets/13142418/10966865/6f9ad942-83f1-11e5-9370-39a803a534cf.png)
