### ISSUE TITLE
Failed to work with OpenJDK8 on Arch Linux

### ISSUE THREAD

**Issue by htfy96** [artur-shaik/vim-javacomplete2#62]
Hi,
I installed this plugin with Vundle and set the correct `autocmd`. However when I opened a .java source, an error `No Javavi library classes found, it means that we couldn't compile it.` occurred.

Before this I had `openjdk-8-jdk` and `openjdk-8-jre` installed. When I tried to compile javavi manually with `mvn -f "/home/lz/.vim/bundle/vim-javacomplete2/libs" compile`, I got the following message:
```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/lz/.vim/bundle/vim-javacomplete2/libs/javavi/src/main/java/kg/ash/javavi/readers/source/ClassNamesFetcher.java:[30,26] Package com.sun.javafx.css does not exist
[INFO] 1 error
[INFO] -------------------------------------------------------------
```

After that I installed Oracle JDK8 and compiled it again, this time everything worked out well.

It seems like a compatibility issue. Any way to make it compatible with openjdk?

**Comment by wsdjeg** [comment]
any config error,iam using openjdk8,and it works well!
what's the result of 
javac or java -version

**Comment by htfy96** [comment]
[lz@lz ~]$ java -version
openjdk version "1.8.0_60"
OpenJDK Runtime Environment (build 1.8.0_60-b24)
OpenJDK 64-Bit Server VM (build 25.60-b23, mixed mode)

**Comment by wsdjeg** [comment]
javac

**Comment by htfy96** [comment]
Well, now this problem is solved: On Arch Linux package `java-openjfx` should be installed manually because `openjdk` on Arch does not contain `JavaFX` packages. Maybe you should add this to `README.md`.

**Comment by artur-shaik** [comment]
Sorry, of course we don't need those javafx package for this project, that was my fault. Last commit should fix this issue. Thanks.

**Comment by wsdjeg** [comment]
sorry i used ubuntu ,and has no that problem
