### ISSUE TITLE
never popout automatically

### ISSUE THREAD

**Issue by itcai** [artur-shaik/vim-javacomplete2#63]
Hi, I'm totally new to this. Overtime I need complete I have to press Cx Co, it never popout automatically. When I press dot key, nothing happened.
OS X 10.10.5
Vim 7.4(built-in MacVim)
JDK8
python 2.7.10
parts of vimrc:
Plugin 'VundleVim/Vundle.vim'
Plugin 'artur-shaik/vim-javacomplete2'
Plugin 'scrooloose/nerdtree'
Plugin 'bling/vim-airline'

setlocal omnifunc=javacomplete#Complete
autocmd FileType java setlocal omnifunc=javacomplete#Complete
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
map <C-n> :NERDTreeToggle<CR>
nnoremap <F4> :JCimportAdd<cr>
inoremap <F4> <esc>:JCimportAddI<cr>

If auto-popout can't be done, how can I change the Cx Co to any other?XD

**Comment by DonnieWest** [comment]
That functionality it outside the scope of this project, but, you can get it by using a couple other plugins

[Neocomplete](https://github.com/Shougo/neocomplete.vim) and [YouCompleteMe](https://github.com/Valloric/YouCompleteMe) are both fantastic examples. Be sure to check them out!

**Comment by itcai** [comment]
Oh, you mean it must work with other plugins? I will have a try. Thx.
FYI, it seems that there are some problems at line 3498 of autoload/javacomplete.vim.

**Comment by wsdjeg** [comment]
i only use this one plugin without any other ,and it works well.

**Comment by wsdjeg** [comment]
you can have a look at my vimrc in my dotfile

**Comment by itcai** [comment]
Can I use your vimrc ? It looks great. Is it for java develop or any other language?

**Comment by wsdjeg** [comment]
java you can use vimrc_vundle which is short than vimrc_neobundle ,all of them are in my dotfile or Netfuns/javavim

**Comment by itcai** [comment]
It works much better now! :+1: It shows up when I press down the dot key. I think it should work when I press any key cause I see you bind all of them. But only dot key works.

**Comment by itcai** [comment]
Ok, I found it works at some specific place, I think it's all depend on this plugin.
