### ISSUE TITLE
a bug about  JCimportsRemoveUnused command!

### ISSUE THREAD

**Issue by wsdjeg** [artur-shaik/vim-javacomplete2#64]
![2015-09-12 21-06-41](https://cloud.githubusercontent.com/assets/13142418/9831645/511eb2ba-5992-11e5-8184-3d70437a19b6.png)

in this file ,if i insert command JCimportsRemoveUnused, the plugin will remove org.hibernate.boot.registry.StandardServiceRegistryBuilder  and org.hibernate.metamodel.MetadataSources which is necessary!!

**Comment by artur-shaik** [comment]
Thanks for issue. Please can you try last commit.

**Comment by wsdjeg** [comment]
![2015-09-14 19-18-33](https://cloud.githubusercontent.com/assets/13142418/9848618/6bf1d93a-5b15-11e5-862b-33e3bb8b6154.png)
if I change "小米" to other english words will not get this error

**Comment by artur-shaik** [comment]
Yeah, but this is another issue.

**Comment by wsdjeg** [comment]
ok i open an new issues, and thank you for fix the previous bug!
