### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 1261: ordinal not in range(128)!

### ISSUE THREAD

**Issue by wsdjeg** [artur-shaik/vim-javacomplete2#65]
![2015-09-14 19-18-33](https://cloud.githubusercontent.com/assets/13142418/9848618/6bf1d93a-5b15-11e5-862b-33e3bb8b6154.png)
if I change "小米" to other english words will not get this error!
i think  it is if owing to the command can not deal with chinese!
i have add this to into my vimrc
```vim
set encoding=utf-8
set termencoding=utf-8
```

**Comment by artur-shaik** [comment]
Can you try once more with last commit.

**Comment by wsdjeg** [comment]
The problem has been solved! thank you for your work!
i have create an repositories named VJDE,maybe some useful function you can add to JAVACOMPLETE2!
https://github.com/VJDE
