### ISSUE TITLE
Merge branch 'vimscript_refactor' bug report!

### ISSUE THREAD

**Issue by wsdjeg** [artur-shaik/vim-javacomplete2#66]
![2015-09-14 23-17-24](https://cloud.githubusercontent.com/assets/13142418/9853588/e7f774d8-5b36-11e5-9f8a-ed9b09831e57.png)

when open vim get this error

**Comment by artur-shaik** [comment]
Sorry, can you try with last commit?

**Comment by wsdjeg** [comment]
also get error!
![2015-09-15 07-59-18](https://cloud.githubusercontent.com/assets/13142418/9864753/c24aeb04-5b7f-11e5-9633-f8440275166f.png)

**Comment by artur-shaik** [comment]
Ok, I think last commits should fix this.

**Comment by wsdjeg** [comment]
i will try tonight!thank you !

**Comment by wsdjeg** [comment]
still has error
![2015-09-15 18-43-26](https://cloud.githubusercontent.com/assets/13142418/9874614/bd9a302e-5bd9-11e5-818c-16448479e046.png)

**Comment by wsdjeg** [comment]
i am using ubuntu ,and install the jdk by apt-get ,by default link the java and javac to /usr/bin/java and /usr/bin/javac ,without setting CLASSPATH by default

**Comment by artur-shaik** [comment]
I think this commit sould be last one. :smile:

**Comment by wsdjeg** [comment]
:smile: great it works well now ! thank you very much!!!!!!!!!!!!!!!!
