### ISSUE TITLE
an issues about complete with vim-rooter!

### ISSUE THREAD

**Issue by wsdjeg** [artur-shaik/vim-javacomplete2#67]
i have install the plugin called vim-rooter,the plugin auto set my pwd to the dir contains .git.
so this plugin can not open the current file by src/*.java,
![2015-09-15 23-36-25](https://cloud.githubusercontent.com/assets/13142418/9881612/5335154e-5c03-11e5-9610-9d82ba27217d.png)
if i use the command `:cd src/com/wsdjeg/utils/` to change the pwd to the dir contains the current file,alse get another error! 
![2015-09-15 23-40-23](https://cloud.githubusercontent.com/assets/13142418/9881611/52c7be86-5c03-11e5-8c1c-545456f0b219.png)
here is my vimrc 
```vim
NeoBundle 'airblade/vim-rooter'
let g:rooter_patterns = ['Rakefile' , 'pom.xml' , 'web.xml' , '.git/']
NeoBundle 'artur-shaik/vim-javacomplete2'
", { 'rev' : '5db2dca' }
autocmd FileType java,jsp set omnifunc=javacomplete#Complete
nnoremap <F4> :JCimportAdd<cr>
inoremap <F4> <esc>:JCimportAddI<cr>
let g:JavaComplete_UseFQN = 1          "补全描述使用全类名 默认是0
"++++++> app1 补全配置
"let g:JavaComplete_LibsPath ='/home/wsdjeg/wsdjeg.github.io/java/app1/WEB-INF/classes:/home/wsdjeg/wsdjeg.github.io/lib/'
"++++++> Invoicing_System 补全配置
let g:JavaComplete_LibsPath = 'classes/:lib/:/home/wsdjeg/tools/apache-tomcat-8.0.24/lib'
let g:JavaComplete_ServerAutoShutdownTime = 300             "自动关闭javavi服务的等待时间间隔
let g:JavaComplete_MavenRepositoryDisable = 1
autocmd FileType java inoremap <F5> <esc>:w<CR>:!javac -cp classes/ -Djava.ext.dirs=lib/ -d classes/ % <CR>
autocmd FileType java nnoremap <F5> :!javac -cp classes/ -Djava.ext.dirs=lib/ -d classes/ % <CR>
autocmd FileType java nnoremap <F6> :!java -cp classes/ -Djava.ext.dirs=lib/ com.wsdjeg.util.TestMethod

**Comment by artur-shaik** [comment]
I cannot see, when exactly this error happen. After what actions?

**Comment by wsdjeg** [comment]
public void test=>c x  x o here cannot complete ,i think may be it is because of the plugin vim rooter

**Comment by artur-shaik** [comment]
And what result should be?
Can you translate those messages, that vim writes?

**Comment by wsdjeg** [comment]
can not open the file "src/*.java"

**Comment by wsdjeg** [comment]
the error appears after a methodName!

**Comment by artur-shaik** [comment]
May be you can prepare project and describe you algorithm of actions. Because I realy can't reproduce this errors.

**Comment by wsdjeg** [comment]
ok let me give you a repo
https://github.com/wsdjeg/JavaUtils
https://github.com/wsdjeg/DotFiles/blob/master/vimrc_neobundle
cd JavaUtils
vim src/com/wsdjeg/util/TestMethod.java
then complete after te
![2015-09-17 21-09-46](https://cloud.githubusercontent.com/assets/13142418/9933833/73d66d74-5d80-11e5-8830-73f60a3d57dd.png)
the error is can not open the file "src/*.java"
but after insert <CR>
also get the result
![2015-09-17 21-11-37](https://cloud.githubusercontent.com/assets/13142418/9933905/cd62ec32-5d80-11e5-9bf6-5a7f16b4a3d1.png)

**Comment by wsdjeg** [comment]
i think maybe something wrong here
![2015-09-17 21-04-01](https://cloud.githubusercontent.com/assets/13142418/9933987/38a11528-5d81-11e5-877a-a88270239846.png)

**Comment by artur-shaik** [comment]
Can you switch on `issue67` branch.
Then, after you open file, run command `JCdebugEnableLogs`.
Then run completion.
Then run command `JCdebugGetLogContent`.
And put content here.

**Comment by wsdjeg** [comment]
Communicate: -P "-" [s:DoGetInfoByReflection]
finish completion  2.261904s
finish completion  2.339044s
finish completion  1.787601s

**Comment by artur-shaik** [comment]
Have you switched to branch `issue67`? Looks like not, there are not enough text.

**Comment by wsdjeg** [comment]
![2015-09-17 22-45-36](https://cloud.githubusercontent.com/assets/13142418/9936299/d528fddc-5d8d-11e5-8ff2-6dbbf1e3b364.png)

**Comment by wsdjeg** [comment]
![2015-09-17 22-46-58](https://cloud.githubusercontent.com/assets/13142418/9936334/07ce5430-5d8e-11e5-804e-b2e57426d54f.png)

**Comment by artur-shaik** [comment]
`issue67` not `issues67`

**Comment by wsdjeg** [comment]
i have add three line to the file

**Comment by wsdjeg** [comment]
te
Communicate: -P "-" [s:DoGetInfoByReflection]
1
/home/wsdjeg/JavaUtils/src
/home/wsdjeg/JavaUtils/src/com/wsdjeg/util
finish completion  1.910030s

**Comment by wsdjeg** [comment]
i have fix this error by add an <space> between className add "{"

**Comment by wsdjeg** [comment]
![2015-09-17 23-23-53](https://cloud.githubusercontent.com/assets/13142418/9937401/2f0c3fee-5d93-11e5-885b-db166b6179c7.png)

**Comment by artur-shaik** [comment]
Ok, can you try last commit on `issue67`

**Comment by wsdjeg** [comment]
alse ceho can not open the file "src/*.java"
but without red error add can complete the method

**Comment by wsdjeg** [comment]
i think we can close this issue

**Comment by artur-shaik** [comment]
I guess last commit should take away this error.

**Comment by wsdjeg** [comment]
you are a stickler for perfection

**Comment by artur-shaik** [comment]
Haha, I wish so. :smile:

**Comment by wsdjeg** [comment]
all the errors have gone!! thank you very much
