### ISSUE TITLE
a function i wanted,not a error!

### ISSUE THREAD

**Issue by wsdjeg** [artur-shaik/vim-javacomplete2#70]
as you know i have added something into my vimrc to implements autocomplete!
then c x c o c p will show the results ,if only one result c p will close the result window!
any config can remove the differences between one result and others

**Comment by artur-shaik** [comment]
And what is the question? Sorry, I couldn't understand.

**Comment by wsdjeg** [comment]
<c-x><c-o>will open the list window and insert the first result ,i do not want it to insert the result ,so i imap A A<c-x><c-o><c-p> ,then the issue appears,if the result of the list is only one <c-x><c-o><c-p> will close the list window

**Comment by artur-shaik** [comment]
If I understand right, I can't affect on it. All menu list stuff related
to vim and handled by it.

**Comment by wsdjeg** [comment]
thank you ,i will search for more usefull info from google

**Comment by wsdjeg** [comment]
I have implemented this feature

**Comment by wsdjeg** [comment]
```vim
autocmd Filetype java inoremap <buffer>  Z  <C-r>=MyFunc('Z')<CR>
function! MyFunc(char)
    if(getline(".")=~?'^\s*\/\/')==0
        let line = getline('.')
        let col = col('.')
        if line[col - 2] == " "
            return a:char."\<c-x>\<c-o>\<c-p>"
        else
            return a:char
        endif
    else
        return a:char
    endif
endf
```

**Comment by wsdjeg** [comment]
set completeopt=longest,menu will remove this issue

**Comment by artur-shaik** [comment]
I think you have to leave it in your vimrc. Because `C-x``C-o` doesn't
work for me, and those who use YouCompleteMe.

**Comment by wsdjeg** [comment]
yes i have done!
YCM is a plugin that contains all the completion such as c-x c-o and c-x c-f and so on,is it?

**Comment by wsdjeg** [comment]
i understand , YCM is an engine adn JC2 is a complete tools

**Comment by artur-shaik** [comment]
Yeah, something like this. YCM decides when to call completion.

**Comment by wsdjeg** [comment]
it is too Complex for me , i don't know how to install with neobundle,and how to config it, now i think the origin complete engine is more suitable for me

**Comment by wsdjeg** [comment]
can you update your plugin with :NeoBundleUpdate
why i get the error
/home/wsdjeg/.vim/bundle/vim-javacomplete2
You are not currently on a branch. Please specify which
branch you want to merge with. See git-pull(1) for details.

git pull <remote> <branch>

https://github.com/Shougo/neobundle.vim/issues/424

**Comment by artur-shaik** [comment]
Just remove `vim-javacomplete2` directory from `~/.vim/bundle` and then
run NeoBundleInstall again. I think this will help.

**Comment by wsdjeg** [comment]
yes only by this way!

**Comment by wsdjeg** [comment]
i have install YCM ,and it is very very sllow ,so i remove it!!

**Comment by wsdjeg** [comment]
hi Artur Shaik
   i find how to deal with the problem that can not update!
   i use vumdle and neobundle together
