### ISSUE TITLE
JCimportsAddMissing command auto import String!maybe it is a bug!

### ISSUE THREAD

**Issue by wsdjeg** [artur-shaik/vim-javacomplete2#72]
![2015-09-20 10-42-35](https://cloud.githubusercontent.com/assets/13142418/9978970/8b4207ce-5f84-11e5-8e86-b0fc1cc79e2d.png)

**Comment by wsdjeg** [comment]
i think JCimportsAddMissing should not import Class which is declared in java.lang and whitout import statement!

**Comment by wsdjeg** [comment]
JCimportAdd and JCimportAddI should list all the class with same name ,JCimportsAddMissing should list all the class which is not in java.lang and has no import statement!

**Comment by artur-shaik** [comment]
No, it's not a bug. In your system there is to `String` classes, that's
why you are asking what class you need. If you choose first, it won't be
addded to your imports, beause it from `java.util`.

**Comment by wsdjeg** [comment]
i just need String str ="aaa"；
why does it import

**Comment by wsdjeg** [comment]
java.util. has no String

**Comment by artur-shaik** [comment]
Sorry, I mean `java.lang`.

You have another String in classpath, that's why.

On 09-19 (21:36), Wang Shidong wrote:
>    java.util. has no String
> 
>    —
>    Reply to this email directly or [1]view it on GitHub.
> 
>    Reverse link: [2]unknown
> 
> References
> 
>    Visible links
>    1. https://github.com/artur-shaik/vim-javacomplete2/issues/72#issuecomment-141748091
>    2. https://github.com/artur-shaik/vim-javacomplete2/issues/72#issuecomment-141748091

-- 
Best regards,
Artur Shaikhullin

**Comment by wsdjeg** [comment]
i think some Classes such as String Integer that need not to import ,should not be inserted into the file even if i have another Class in the ClassPath ,the Class with the same name can be import manully by JCimportAdd and JCimportAddI

**Comment by wsdjeg** [comment]
sorry if it is my misstake , the plugin has no problem ,thank you
