### ISSUE TITLE
java.util.Collections complete error!

### ISSUE THREAD

**Issue by wsdjeg** [artur-shaik/vim-javacomplete2#78]
can not complete static methods of java.util.Collections
![2015-09-30 21-24-13](https://cloud.githubusercontent.com/assets/13142418/10194387/efae298e-67ba-11e5-9431-dcb06e0f87db.png)

**Comment by artur-shaik** [comment]
You don't have `Collectors` import there.

**Comment by wsdjeg** [comment]
sorry it is my fault
