### ISSUE TITLE
lombok support?

### ISSUE THREAD

**Issue by mattn** [artur-shaik/vim-javacomplete2#79]
seems not support completion of method via lombok.

**Comment by artur-shaik** [comment]
Hm, I'm wonder, does eclipse do compilation before detect those methods?

**Comment by mattn** [comment]
eclipse need to configure for lombok in recently.

http://stackoverflow.com/a/3419385/720391

and eclipse should compile before completion maybe.

**Comment by wsdjeg** [comment]
eclipse compile file when it was saved

**Comment by artur-shaik** [comment]
Seems that.
@mattn so any progress with `target/classes` you added?

**Comment by mattn** [comment]
that's all. :)
