### ISSUE TITLE
can not complete request.==>

### ISSUE THREAD

**Issue by wsdjeg** [artur-shaik/vim-javacomplete2#80]
![2015-10-01 11-08-41](https://cloud.githubusercontent.com/assets/13142418/10212048/d67aab00-682c-11e5-9360-8ebb82f65691.png)

**Comment by wsdjeg** [comment]
mvn compile succese

**Comment by wsdjeg** [comment]
i think i know why!
the plugin miss servlet in pom
![2015-10-01 11-49-13](https://cloud.githubusercontent.com/assets/13142418/10212481/8c12d938-6832-11e5-9ba6-ed3f95b6f8f5.png)
![2015-10-01 11-49-00](https://cloud.githubusercontent.com/assets/13142418/10212485/9bfef16a-6832-11e5-9b2c-c2bf75c15779.png)

**Comment by wsdjeg** [comment]
i have fix it by delete ~/.javacomplete/classpath/pom.xml
and let the plugin reload the pom.xml in my project ,and the issure is gone

**Comment by wsdjeg** [comment]
https://github.com/artur-shaik/vim-javacomplete2/issues/76
thats why i suggest use ProjectName_pom.xml instade of pom.xml
alse could add something to this pom.show to show whether the pom.xml has been changed,if it has been changed ,let the plugin reload the project's pom.xml

**Comment by artur-shaik** [comment]
Script checks for modification date, and if file have been changed than file replaced.
Do you set pom path by hand, or it auto detected?

**Comment by wsdjeg** [comment]
no,i just use vim root and ,the JC2 load my WEBAPP/pom.xml and translate it into ~/.javacomplete/classpath/pom.xml,i think it should translate into ~/.javacomplete/classpath/WEBAPP_pom.xml!
so that let me change to another webapp quickly,and will not miss Class!

now ,the JC2 translate APP1's pom.xml to ~/.javacomplete/classpath/pom.xml,if i change to  APP2's, will not translate APP2's pom.xml,just use ~/.javacomplete/classpath/pom.xml,then will miss Class, just like the picture above!

**Comment by wsdjeg** [comment]
fixed
