### ISSUE TITLE
Allow to set the JVM Launcher to compile/start JAVAPI daemon

### ISSUE THREAD

**Issue by hsanson** [artur-shaik/vim-javacomplete2#81]
Lots of projects still require JDK7 to compile/run (e.g. all android projects) so upgrading to JDK8 is not an option.

Since going back to JDK7 is not an option maybe add a global variable g:javapi_jvm_launcher or similar that allows to set the path for the java command. This way I can set this single variable to use the JDK8 version and leave my system with JDK7.

**Comment by artur-shaik** [comment]
Sounds reasonable. I added two options, you can try:

`g:JavaComplete_JvmLauncher`

`g:JavaComplete_JavaCompiler`

**Comment by hsanson** [comment]
Compiling works with maven. I cannot get it to compile without maven due to missing dependencies so is not related.

Still working on getting the auto complete to work. I get an error that cannot connect to socket or something like that. The error disappears to fast to see.

**Comment by hsanson** [comment]
Closing this issue as the java version is correctly being used by setting these variables.
