### ISSUE TITLE
Autocompletion fails with "could not open socket, try again"

### ISSUE THREAD

**Issue by hsanson** [artur-shaik/vim-javacomplete2#82]
Using latest master I cannot get auto complete to work. Pressing Ctrl-X Ctrl-O shows "could not open socket, try again".

I can start the JCserver and I can see the process is running:

    /home/ryujin/Apps/jdk1.8.0_45/bin/java kg.ash.javavi.Javavi -sources /home/ryujin/Projects/Join/android-client/Join/src/main/java/:/home/ryujin/Projects/Join/android-client/Join/src/main/res/:0: -D 33833

Running JCserverPID and JCserverPort return the correct values but still I get the socket error when trying to autocomplete.

**Comment by artur-shaik** [comment]
Hm, may be you can rollback to older versions to find out when it becomed broken for you?

**Comment by wsdjeg** [comment]
yes you can try with neobundle lock the commit !

**Comment by hsanson** [comment]
Works perfectly on my work laptop but not on my home desktop. Certainly something on my configuration so closing.
