### ISSUE TITLE
complete getFoo() when candidate of getFoo is only one.

### ISSUE THREAD

**Issue by mattn** [artur-shaik/vim-javacomplete2#86]
javacomplete2 provide candidate `getFoo(` not `getFoo()`.

**Comment by wsdjeg** [comment]
do you mean ,if a method has no Overloading method,should  complete "()";
but if the methed need args,and the the Cursor is out of the "()==>",and we need to type `<right>`,it will be slow than just getFoo(

**Comment by mattn** [comment]
I just prefer to type below.

before
```java
target.
```

type
```
<c-x><c-o>.<c-x><c-o>
```

after
```java
target.getFoo().getBar()
```

currently, we need to type
type
```
<c-x><c-o>).<c-x><c-o>)
```

**Comment by artur-shaik** [comment]
Sounds reasonable. But I think it should work in this way only for methods without parameters.
Will look at this closer.

**Comment by wsdjeg** [comment]
yes ,also why donot use YCM catch JC2's onimifuc ,then you just need type . ).)

**Comment by mattn** [comment]
okay, i see.

**Comment by wsdjeg** [comment]
@mattn @artur-shaik https://github.com/Shougo/deoplete.nvim
this plugin has the func
like complete after @Override
this. auto show funcs,then chooce any one ,if the one you choose end with '(' ')'will be complete after you type any char

**Comment by wsdjeg** [comment]
also neocomplete has this func
