### ISSUE TITLE
can you help me with my MathUtil?

### ISSUE THREAD

**Issue by wsdjeg** [artur-shaik/vim-javacomplete2#92]
https://github.com/wsdjeg/JavaWeb/blob/master/src/main/java/com/wsdjeg/util/MathUtils.java
I have wrote a class deal with a List,and to find the Composition which Summation is a appoint int!

now the class works vert well,but only can deal with List.size() <= 30 or numbers of result <= 10000

**Comment by wsdjeg** [comment]
at the beginning i use a List place all of the result ,but the then only can deal with list.size() <=20 int

so i change to use String

**Comment by mattn** [comment]
Sorry Is this an issue depend on javacomplete2 ?

**Comment by wsdjeg** [comment]
no i am sorry

**Comment by wsdjeg** [comment]
i just know asking question tools StackOverflow., i will use it ,so i will close it
