### ISSUE TITLE
java.util.Arrays cannot complete static method!

### ISSUE THREAD

**Issue by wsdjeg** [artur-shaik/vim-javacomplete2#93]
![2015-10-05 14-09-49](https://cloud.githubusercontent.com/assets/13142418/10273975/e10a1c22-6b6a-11e5-98a3-8d3fcc01435d.png)
but commit 7aaba87 works well
![2015-10-05 14-11-54](https://cloud.githubusercontent.com/assets/13142418/10273993/1fab2692-6b6b-11e5-9bc6-988e0a81c134.png)

**Comment by mattn** [comment]
I can do on latest commit.

![](http://go-gyazo.appspot.com/7a92fd413cb4e401.png)

**Comment by artur-shaik** [comment]
Yeah, I know this bug, it is cache related. I think will kill it soon.
