### ISSUE TITLE
can't complete with only leading `@`

### ISSUE THREAD

**Issue by mattn** [artur-shaik/vim-javacomplete2#94]
```
package main;

import lombok.Data;

@A
public class Bar {
	private String message;
	private String description;
	private int age;
	private String living;
	private int sex;
	private String name;
}
```
This works fine but
```
package main;

import lombok.Data;

@
public class Bar {
	private String message;
	private String description;
	private int age;
	private String living;
	private int sex;
	private String name;
}
```
This return `Pattern not found`.

**Comment by wsdjeg** [comment]
here is my vimrc set it can works together with YCM
https://github.com/wsdjeg/DotFiles/commit/2442a4a8482976dd63040522af53210fcb8207b6

**Comment by wsdjeg** [comment]
and if i type @A 
all the anocation whit starting "A" will be listed

**Comment by mattn** [comment]
No, It's plugin's bug.

**Comment by mattn** [comment]
@artur-shaik annotation will be completed when leading `@` with one letter.

https://github.com/artur-shaik/vim-javacomplete2/blob/master/autoload/javacomplete/complete.vim#L104

is this your expected?

And I notice it should be `g:RE_ANNOTATION`.

https://github.com/artur-shaik/vim-javacomplete2/blob/4d4167d31850a8341b8fddf2f0aead9b4fd24ba8/autoload/javacomplete.vim#L74

**Comment by artur-shaik** [comment]
Yeah, this is expected behavior. But I'm looking forward to add feature to load all annotations on `@`.

**Comment by artur-shaik** [comment]
Added this in 2d1f0b22a196d5677e7469daf9716e2510d22f0a.
Looks like it is not really usefull when you have too much annotations.

**Comment by mattn** [comment]
thanks!
