### ISSUE TITLE
i think maybe it is function of YCM,will this be added to JC2?

### ISSUE THREAD

**Issue by wsdjeg** [artur-shaik/vim-javacomplete2#97]
when the string i insert into is Not exactly match
![2015-10-05 16-13-28](https://cloud.githubusercontent.com/assets/13142418/10275708/345f2258-6b7c-11e5-85bf-f3fad41fb709.png)
but when use JC2'func
![1](https://cloud.githubusercontent.com/assets/13142418/10275732/66800f18-6b7c-11e5-8c42-5173882bf0a8.png)
when i type into a
![2015-10-05 16-13-16](https://cloud.githubusercontent.com/assets/13142418/10275746/80a09a48-6b7c-11e5-8a2a-4a95a80d261b.png)
nothing show me

**Comment by mattn** [comment]
Sorry, what is your expected? Something should be displayed at least even though no-match?

**Comment by wsdjeg** [comment]
can you have look at first picture ,which is function of YCM let ny match to notify and notifyAll ,
ny just like *n*y*

**Comment by wsdjeg** [comment]
i think it is func of YCM and JC2 has no need to change
