### ISSUE TITLE
after use JCimportadd or JCimportaddI the Cursor change to the begin of the class

### ISSUE THREAD

**Issue by wsdjeg** [artur-shaik/vim-javacomplete2#99]
![2015-10-05 19-29-07](https://cloud.githubusercontent.com/assets/13142418/10279326/5f597092-6b97-11e5-9f71-3647b2eb1724.png)

**Comment by wsdjeg** [comment]
it does not work after import the Cursor go to the end of the class

**Comment by wsdjeg** [comment]
it appears when have blank lines between package and class name

**Comment by artur-shaik** [comment]
Please, try again.

**Comment by wsdjeg** [comment]
![111](https://cloud.githubusercontent.com/assets/13142418/10279704/642a92e2-6b9a-11e5-9771-b439b0342cf4.png)

![222](https://cloud.githubusercontent.com/assets/13142418/10279701/6332db38-6b9a-11e5-83af-d5d82d783c1c.png)

![333](https://cloud.githubusercontent.com/assets/13142418/10279702/63a39314-6b9a-11e5-947e-7e1e634ea9c8.png)

**Comment by wsdjeg** [comment]
thank you very mach it works well you have push 45 commits this week ,thank you and @mattn
